/** Append-only snapshot synchronization. Providers never overwrite an existing cloud file.
 * Concurrent heads stop automatic sync; conflict resolution always requires an explicit user action.
 * This is session-bound replication, not a service worker or background cloud daemon.
 */
import { exportBackup, verifyBackup, sha256 } from '../storage/index.js';
export function canonicalJSON(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return'['+value.map(canonicalJSON).join(',')+']';return'{'+Object.keys(value).sort().filter(k=>value[k]!==undefined).map(k=>JSON.stringify(k)+':'+canonicalJSON(value[k])).join(',')+'}';}
export async function workspaceFingerprint(state){const value=structuredClone(state);delete value.revision;delete value.projection;value.audit=(value.audit||[]).filter(a=>a.type!=='workspace.restore');return sha256(new TextEncoder().encode(canonicalJSON(value)));}
export function syncHeads(commits){const parents=new Set(commits.flatMap(c=>c.parents));return commits.filter(c=>!parents.has(c.commitId));}
export class SnapshotSync extends EventTarget {
 constructor({engine,provider,channel,mode='two-way',intervalMs=30000,writerId=crypto.randomUUID(),checkpoint=null,onCheckpoint=()=>{}}){super();if(!/^[a-z0-9_-]{3,48}$/.test(channel))throw new Error('Use a 3–48 character lowercase channel name.');if(!['two-way','backup'].includes(mode))throw new Error('Invalid sync mode.');if(engine.repository.kind==='server'&&mode==='two-way')throw new Error('Server workspaces support outgoing backup only. Do not overwrite a team database from browser synchronization.');Object.assign(this,{engine,provider,channel,mode,writerId,onCheckpoint});if(!Number.isFinite(intervalMs)||intervalMs<1000)throw new Error('Sync interval must be at least 1,000 milliseconds.');this.intervalMs=intervalMs;this.generation=0;this.base=checkpoint?.base||null;this.baseFingerprint=checkpoint?.fingerprint||null;this.known=new Map();this.status='paused';this.errors=0;this.running=false;this.busy=null;this.timer=null;this.conflict=null;this.lastSync=null;this.message='Not started';}
 emit(status,message){this.status=status;this.message=message;this.dispatchEvent(new CustomEvent('status',{detail:{status,message,lastSync:this.lastSync,conflict:this.conflict}}));}
 saveCheckpoint(){this.onCheckpoint({base:this.base,fingerprint:this.baseFingerprint,channel:this.channel,writerId:this.writerId});}
 start(){if(this.running)return;this.running=true;this.emit('connecting','Checking immutable remote history');void this.tick();}
 stop(){this.running=false;this.generation++;clearTimeout(this.timer);this.emit('paused','Synchronization paused');}
 async remote(){const files=await this.provider.list();if(files.length>=2000)throw new Error('Provider listing reached its safety cap. Rotate to a new channel before history can become incomplete.');const matches=files.filter(f=>f.name.startsWith(`civora-sync-${this.channel}-`));if(matches.length>500)throw new Error('Channel reached its 500-snapshot safety cap. Archive it and start a new channel.');for(const file of matches){const stamp=JSON.stringify([file.name,file.size,file.date]);if(this.known.get(file.id)?.stamp===stamp)continue;const backup=await this.provider.load(file.id),s=backup.sync;if(!s||s.protocol!=='civora-sync/1'||s.channel!==this.channel||typeof s.commitId!=='string'||!/^[a-f0-9-]{36}$/.test(s.commitId)||!Array.isArray(s.parents)||s.parents.length>500||s.parents.some(p=>typeof p!=='string'||!/^[a-f0-9-]{36}$/.test(p)||p===s.commitId)||new Set(s.parents).size!==s.parents.length)throw new Error('Invalid remote sync manifest.');await verifyBackup(backup);const fingerprint=await workspaceFingerprint(backup.workspace);if(fingerprint!==s.fingerprint)throw new Error('Remote sync fingerprint does not match its workspace.');this.known.set(file.id,{...s,fileId:file.id,stamp});}const present=new Set(matches.map(f=>f.id)),commits=[...this.known.values()].filter(c=>present.has(c.fileId));const ids=new Set(commits.map(c=>c.commitId));if(ids.size!==commits.length)throw new Error('Duplicate remote commit IDs.');for(const c of commits)if(c.parents.some(id=>!ids.has(id)))throw new Error('Remote history is incomplete; a parent snapshot is missing.');const byId=new Map(commits.map(c=>[c.commitId,c])),active=new Set(),done=new Set();function visit(id){if(active.has(id))throw new Error('Remote sync history is cyclic.');if(done.has(id))return;active.add(id);for(const parent of byId.get(id).parents)visit(parent);active.delete(id);done.add(id);}commits.forEach(c=>visit(c.commitId));if(this.base&&!byId.has(this.base))throw new Error('Previously synchronized base is missing from remote history.');this.remoteCommits=byId;return syncHeads(commits);}
 guard(generation){if(generation!==this.generation)throw new Error('Synchronization paused before applying changes.');}
 async push(state,parents,generation=this.generation){const backup=await exportBackup(this.engine.repository,state),fingerprint=await workspaceFingerprint(state);backup.sync={protocol:'civora-sync/1',channel:this.channel,commitId:crypto.randomUUID(),parents:[...parents],writerId:this.writerId,fingerprint};this.guard(generation);const saved=await this.provider.save(backup);this.guard(generation);this.known.set(saved.id,{...backup.sync,fileId:saved.id});this.base=backup.sync.commitId;this.baseFingerprint=fingerprint;this.saveCheckpoint();this.lastSync=new Date().toISOString();return backup.sync;}
 async pull(head,expectedRevision,generation=this.generation){const backup=await this.provider.load(head.fileId),verified=await verifyBackup(backup);if(backup.sync?.commitId!==head.commitId||await workspaceFingerprint(verified.state)!==head.fingerprint)throw new Error('Remote content changed while preparing synchronization.');this.guard(generation);await this.engine.repository.replace(verified.state,verified.files,expectedRevision);await this.engine.refresh();this.base=head.commitId;this.baseFingerprint=await workspaceFingerprint(this.engine.state);this.saveCheckpoint();this.lastSync=new Date().toISOString();}
 async perform(generation=this.generation){const state=structuredClone(this.engine.state);if(state.projection?.filtered)throw new Error('Only a full, administrator-visible workspace may be synchronized.');const local=await workspaceFingerprint(state),heads=await this.remote();this.guard(generation);if(heads.length>1){this.conflict={heads,localFingerprint:local};this.emit('conflict','Concurrent cloud versions detected. Nothing was overwritten.');return;}
 const head=heads[0];if(!head){if(this.base)throw new Error('Previously synchronized cloud history disappeared. Automatic publication is stopped.');await this.push(state,[],generation);this.emit('synced','Initial snapshot published');return;}
 if(local===head.fingerprint){this.base=head.commitId;this.baseFingerprint=local;this.saveCheckpoint();this.lastSync=new Date().toISOString();this.emit('synced','Local and remote content match');return;}
 if(this.base===head.commitId){await this.push(state,[head.commitId],generation);this.emit('synced','Local changes published');return;}
 if(this.base&&local===this.baseFingerprint&&this.mode==='two-way'){const ancestors=new Set(),walk=id=>{if(ancestors.has(id))return;ancestors.add(id);this.remoteCommits.get(id)?.parents.forEach(walk);};walk(head.commitId);if(!ancestors.has(this.base))throw new Error('Remote head does not descend from the synchronized base.');await this.pull(head,state.revision,generation);this.emit('synced','Remote changes applied after checksum verification');return;}
 this.conflict={heads,localFingerprint:local};this.emit('conflict',this.mode==='backup'?'Remote history changed. Review before creating a new branch.':'Local and remote content differ. Choose which version to retain.');
 }
 async tick(){if(this.busy)return this.busy;clearTimeout(this.timer);const generation=this.generation;this.busy=(async()=>{try{this.emit('syncing','Checking local changes and cloud history');await this.perform(generation);this.guard(generation);this.errors=0;}catch(e){if(generation!==this.generation)return;this.errors++;this.emit(/expir|connect.*provider|401|authoriz/i.test(e.message)?'reauthorize':'error',e.message);}finally{this.busy=null;if(this.running&&!['conflict','reauthorize'].includes(this.status)){this.timer=setTimeout(()=>void this.tick(),Math.min(300000,this.intervalMs*2**Math.min(this.errors,4)));}}})();return this.busy;}
 async resolve(choice,commitId){if(this.busy)await this.busy;clearTimeout(this.timer);const generation=this.generation,heads=await this.remote(),snapshot=structuredClone(this.engine.state);this.guard(generation);if(choice==='remote'){if(this.mode!=='two-way')throw new Error('Incoming synchronization is disabled in backup-only mode.');const head=heads.find(h=>h.commitId===commitId);if(!head)throw new Error('The selected remote head is no longer current.');await this.pull(head,snapshot.revision,generation);if(heads.length>1)await this.push(this.engine.state,heads.map(h=>h.commitId),generation);}else if(choice==='local'){await this.push(snapshot,heads.map(h=>h.commitId),generation);}else throw new Error('Choose local or a named remote version.');this.conflict=null;this.emit('synced','Conflict resolved by explicit user choice; original snapshots retained');if(this.running){clearTimeout(this.timer);this.timer=setTimeout(()=>void this.tick(),this.intervalMs);}}
}
