/** Dependency-free, stored (uncompressed) ZIP writer with UTF-8 names and CRC-32. */
const crcTable = Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
export function crc32(bytes){let crc=0xffffffff;for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return(crc^0xffffffff)>>>0;}
export function safeArchivePath(name){const parts=String(name).replaceAll('\\','/').split('/');if(parts.some(p=>!p||p==='.'||p==='..'||/[\x00-\x1f]/.test(p)))throw new Error('Unsafe archive path.');return parts.join('/');}
export async function createZip(entries){
  if(entries.length>65535)throw new Error('Too many files for this ZIP writer.');const local=[],central=[];let offset=0;const encoder=new TextEncoder(), now=new Date(), dosDate=((Math.max(1980,now.getFullYear())-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate(),dosTime=(now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1), names=new Set();
  for(const entry of entries){const path=safeArchivePath(entry.name);if(names.has(path))throw new Error('Duplicate ZIP entry.');names.add(path);const name=encoder.encode(path);const bytes=entry.data instanceof Blob?new Uint8Array(await entry.data.arrayBuffer()):typeof entry.data==='string'?encoder.encode(entry.data):new Uint8Array(entry.data);if(bytes.length>0xffffffff||offset+bytes.length+name.length+30>0xffffffff)throw new Error('ZIP64 is not supported.');const crc=crc32(bytes),header=new Uint8Array(30+name.length),v=new DataView(header.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(10,dosTime,true);v.setUint16(12,dosDate,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,name.length,true);header.set(name,30);local.push(header,bytes);const record=new Uint8Array(46+name.length),c=new DataView(record.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0x800,true);c.setUint16(12,dosTime,true);c.setUint16(14,dosDate,true);c.setUint32(16,crc,true);c.setUint32(20,bytes.length,true);c.setUint32(24,bytes.length,true);c.setUint16(28,name.length,true);c.setUint32(42,offset,true);record.set(name,46);central.push(record);offset+=header.length+bytes.length;}
  const centralLength=central.reduce((n,b)=>n+b.length,0),end=new Uint8Array(22),view=new DataView(end.buffer);view.setUint32(0,0x06054b50,true);view.setUint16(8,entries.length,true);view.setUint16(10,entries.length,true);view.setUint32(12,centralLength,true);view.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'});
}
