import { PointerSession } from '../interactions/index.js';
import { boundsOf, validateModel } from '../engineering/index.js';
import { escapeHTML as e } from '../controls/index.js';
/** Standalone, dependency-free triangular mesh inspector. WebGL with a bounded Canvas fallback. */
export function mountModelViewer(host, model, {onSelect = () => {}} = {}) {
  validateModel(model);
  let disposed=false, yaw=-.72,pitch=.58,zoom=1,pan=[0,0],selected='',hidden=new Set(),isolate=false,section=1,measure=false,measurePoints=[],frame=0,panMode=false;
  const all=model.objects.flatMap(o=>o.vertices),bounds=boundsOf(all),center=bounds.min.map((v,i)=>(v+bounds.max[i])/2),radius=Math.max(Math.hypot(...bounds.max.map((v,i)=>v-bounds.min[i]))/2,.001);
  host.innerHTML=`<div class="model-inspector" data-model-panel="model"><div class="model-mobile-tabs" role="group" aria-label="Model panels"><button data-model-panel="model" aria-pressed="true">Model</button><button data-model-panel="elements" aria-pressed="false">Elements &amp; properties</button></div><aside class="model-tree"><div class="model-tree-title">MODEL EXPLORER <span>${model.objects.length}</span></div><input class="model-search" placeholder="Find an element…" aria-label="Find model element"><div class="model-object-list"></div><div class="model-properties"><strong>Element properties</strong><p>Select geometry or an element.</p></div></aside><div class="model-stage"><canvas tabindex="0" aria-label="3D model. One finger or drag to orbit. Two fingers pan and zoom. Use Pan, Fit and zoom buttons as alternatives. Tap to inspect; measurement selects two vertices."></canvas><div class="model-stage-tools"><button data-view="iso">Isometric</button><button data-view="top">Top</button><button data-view="front">Front</button><button data-view="fit">Fit</button><button data-view="pan" aria-pressed="false">Pan</button><button data-view="out" aria-label="Zoom model out">−</button><button data-view="in" aria-label="Zoom model in">+</button><button data-view="left" aria-label="Rotate model left">←</button><button data-view="right" aria-label="Rotate model right">→</button><button data-view="up" aria-label="Rotate model up">↑</button><button data-view="down" aria-label="Rotate model down">↓</button><button data-view="isolate">Isolate selection</button><button data-view="measure">Measure</button><button data-view="capture">Capture</button></div><div class="model-section"><span>Section Z</span><input type="range" min="0" max="100" value="100" aria-label="Section cut along Z"><output>100%</output></div><div class="model-hud"><span class="model-renderer"></span><span class="model-measure">Orbit with one finger · Pan/zoom with two · Buttons also available</span></div></div></div>`;
  const canvas=host.querySelector('canvas'),tree=host.querySelector('.model-object-list'),properties=host.querySelector('.model-properties'),hud=host.querySelector('.model-measure');
  const gl=canvas.getContext('webgl',{antialias:true,alpha:false,preserveDrawingBuffer:true});
  // A canvas cannot switch context kinds once initialized. WebGL initialization failure uses a new canvas.
  let ctx=null,program=null,buffer=null,normalBuffer=null,positionLoc,normalLoc,matrixLoc,colorLoc,clipLoc;
  if(gl){const compile=(kind,source)=>{const shader=gl.createShader(kind);gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS))throw new Error('Model shader compilation failed.');return shader;};const vertex=compile(gl.VERTEX_SHADER,`attribute vec3 position; attribute vec3 normal; uniform mat4 matrix; varying vec3 n; varying float z; void main(){n=normal; z=position.z;gl_Position=matrix*vec4(position,1.0);}`),fragment=compile(gl.FRAGMENT_SHADER,`precision highp float; varying vec3 n; varying float z; uniform vec3 color; uniform float cut; void main(){if(z>cut)discard;float light=.35+.65*abs(dot(normalize(n),normalize(vec3(.4,-.5,.85))));gl_FragColor=vec4(color*light,1.0);}`);program=gl.createProgram();gl.attachShader(program,vertex);gl.attachShader(program,fragment);gl.linkProgram(program);gl.deleteShader(vertex);gl.deleteShader(fragment);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Model shader link failed.');positionLoc=gl.getAttribLocation(program,'position');normalLoc=gl.getAttribLocation(program,'normal');matrixLoc=gl.getUniformLocation(program,'matrix');colorLoc=gl.getUniformLocation(program,'color');clipLoc=gl.getUniformLocation(program,'cut');buffer=gl.createBuffer();normalBuffer=gl.createBuffer();gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);}
  else ctx=canvas.getContext('2d');
  const geometry=model.objects.map((o,index)=>{const vertices=[],normals=[];for(const ids of o.triangles){const p=ids.map(i=>o.vertices[i]),u=p[1].map((v,i)=>v-p[0][i]),v=p[2].map((v,i)=>v-p[0][i]),n=[u[1]*v[2]-u[2]*v[1],u[2]*v[0]-u[0]*v[2],u[0]*v[1]-u[1]*v[0]];for(const pt of p){vertices.push(...pt.map((v,i)=>(v-center[i])/radius));normals.push(...n);}}return{o,index,vertices:new Float32Array(vertices),normals:new Float32Array(normals)};});
  if(gl)for(const g of geometry){g.positionBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,g.positionBuffer);gl.bufferData(gl.ARRAY_BUFFER,g.vertices,gl.STATIC_DRAW);g.normalBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,g.normalBuffer);gl.bufferData(gl.ARRAY_BUFFER,g.normals,gl.STATIC_DRAW);}
  host.querySelector('.model-renderer').textContent=gl?'WebGL · triangle geometry':'Canvas · limited to 20,000 triangles';
  const colors=[[.41,.76,.71],[.47,.64,.86],[.86,.70,.42],[.77,.57,.70],[.60,.72,.83],[.77,.80,.69]];
  function list(q=''){tree.innerHTML=model.objects.filter(o=>(o.name+' '+o.type+' '+o.id).toLowerCase().includes(q.toLowerCase())).map(o=>`<div class="model-object ${o.id===selected?'selected':''}"><input type="checkbox" data-visible="${e(o.id)}" ${hidden.has(o.id)?'':'checked'} aria-label="Show ${e(o.name)}"><button data-select="${e(o.id)}"><span>${e(o.name||o.id)}</span><small>${e(o.type||'Mesh')} · ${o.triangles.length} triangles</small></button></div>`).join('');}
  function choose(id){selected=id;const o=model.objects.find(o=>o.id===id);list(host.querySelector('.model-search').value);properties.innerHTML=o?`<strong>${e(o.name||o.id)}</strong><dl><dt>Type</dt><dd>${e(o.type||'Mesh')}</dd><dt>Identifier</dt><dd>${e(o.id)}</dd><dt>Triangles</dt><dd>${o.triangles.length}</dd>${Object.entries(o.properties||{}).slice(0,100).map(([k,v])=>`<dt>${e(k)}</dt><dd>${e(typeof v==='object'?JSON.stringify(v):v)}</dd>`).join('')}</dl>`:'<strong>Element properties</strong><p>Select geometry or an element.</p>';onSelect(o);schedule();}
  function viewMatrix(){const cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),aspect=canvas.width/canvas.height,k=zoom*.9*Math.min(1,aspect);return new Float32Array([cy*k/aspect,sy*sp*k,sy*cp*.2,0,-sy*k/aspect,cy*sp*k,cy*cp*.2,0,0,cp*k,-sp*.2,0,pan[0],pan[1],0,1]);}
  function project(pt){const m=viewMatrix(),p=pt.map((v,i)=>(v-center[i])/radius);return[(m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12]+1)*canvas.width/2,(1-(m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13]))*canvas.height/2,m[2]*p[0]+m[6]*p[1]+m[10]*p[2]];}
  function visible(o){return!hidden.has(o.id)&&(!isolate||!selected||selected===o.id);}
  function draw(){frame=0;if(disposed)return;const box=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(box.width*ratio)),h=Math.max(1,Math.floor(box.height*ratio));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const cut=bounds.min[2]+(bounds.max[2]-bounds.min[2])*section;
    if(gl){gl.viewport(0,0,w,h);gl.clearColor(.063,.105,.15,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.uniformMatrix4fv(matrixLoc,false,viewMatrix());gl.uniform1f(clipLoc,section===1?1e8:(cut-center[2])/radius);for(const g of geometry){if(!visible(g.o))continue;gl.bindBuffer(gl.ARRAY_BUFFER,g.positionBuffer);gl.enableVertexAttribArray(positionLoc);gl.vertexAttribPointer(positionLoc,3,gl.FLOAT,false,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,g.normalBuffer);gl.enableVertexAttribArray(normalLoc);gl.vertexAttribPointer(normalLoc,3,gl.FLOAT,false,0,0);gl.uniform3fv(colorLoc,g.o.id===selected?[1,.82,.27]:colors[g.index%colors.length]);gl.drawArrays(gl.TRIANGLES,0,g.vertices.length/3);}}
    else if(ctx){ctx.fillStyle='#101b26';ctx.fillRect(0,0,w,h);let triangles=[];for(const g of geometry){if(!visible(g.o))continue;for(const ids of g.o.triangles){const world=ids.map(i=>g.o.vertices[i]);if(world.some(p=>p[2]>cut)&&section!==1)continue;const p=world.map(project);triangles.push({p,z:p.reduce((s,p)=>s+p[2],0),color:g.o.id===selected?'#ffd149':['#72bdb4','#759cc9','#c9ad71'][g.index%3]});if(triangles.length>=20000)break;}if(triangles.length>=20000)break;}triangles.sort((a,b)=>b.z-a.z);for(const t of triangles){ctx.beginPath();t.p.forEach((p,i)=>i?ctx.lineTo(...p.slice(0,2)):ctx.moveTo(...p.slice(0,2)));ctx.closePath();ctx.fillStyle=t.color;ctx.fill();ctx.strokeStyle='#223c4b';ctx.lineWidth=.5;ctx.stroke();}}
  }
  function schedule(){if(!disposed&&!frame)frame=requestAnimationFrame(draw);}
  function pick(event){const r=canvas.getBoundingClientRect(),x=(event.clientX-r.left)*canvas.width/r.width,y=(event.clientY-r.top)*canvas.height/r.height,cut=bounds.min[2]+(bounds.max[2]-bounds.min[2])*section;let best=null;
    for(const g of geometry){if(!visible(g.o))continue;for(const ids of g.o.triangles){const world=ids.map(i=>g.o.vertices[i]),p=world.map(project),[a,b,c]=p,den=(b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1]);if(Math.abs(den)<1e-9)continue;const u=((b[1]-c[1])*(x-c[0])+(c[0]-b[0])*(y-c[1]))/den,v=((c[1]-a[1])*(x-c[0])+(a[0]-c[0])*(y-c[1]))/den,w=1-u-v;if(Math.min(u,v,w)<0)continue;const depth=u*a[2]+v*b[2]+w*c[2],point=[0,1,2].map(k=>u*world[0][k]+v*world[1][k]+w*world[2][k]);if(section!==1&&point[2]>cut)continue;if(!best||depth<best.depth){const nearest=p.map((p,i)=>({i,d:(p[0]-x)**2+(p[1]-y)**2})).sort((a,b)=>a.d-b.d)[0].i;best={id:g.o.id,depth,vertex:world[nearest]};}}}
    if(best){choose(best.id);if(measure){if(measurePoints.length===2)measurePoints=[];measurePoints.push(best.vertex);hud.textContent=measurePoints.length===2?`Vertex distance: ${Math.hypot(...measurePoints[1].map((v,i)=>v-measurePoints[0][i])).toPrecision(7)} ${model.units||'model units'}`:'First vertex selected. Click a second vertex.';}}else if(!measure)choose('');
  }
  const pointers=new PointerSession(),inputEvents=new AbortController(),inputOpts={signal:inputEvents.signal};let shiftPan=false;
  const clampZoom=value=>Math.max(.05,Math.min(50,value));
  canvas.addEventListener('pointerdown',event=>{if(!pointers.down(event))return;event.preventDefault();shiftPan=event.shiftKey||event.button===1;try{canvas.setPointerCapture(event.pointerId);}catch{}},inputOpts);
  canvas.addEventListener('pointermove',event=>{const a=pointers.move(event);if(!a)return;event.preventDefault();if(a.kind==='pinch'){zoom=clampZoom(zoom*a.factor);pan[0]+=(a.to.x-a.from.x)/Math.max(1,canvas.clientWidth)*2;pan[1]-=(a.to.y-a.from.y)/Math.max(1,canvas.clientHeight)*2;}else if(panMode||shiftPan){pan[0]+=a.dx/Math.max(1,canvas.clientWidth)*2;pan[1]-=a.dy/Math.max(1,canvas.clientHeight)*2;}else{yaw+=a.dx*.009;pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,pitch+a.dy*.009));}schedule();},inputOpts);
  canvas.addEventListener('pointerup',event=>{const a=pointers.up(event);if(a?.kind==='end'&&a.tap)pick(event);try{canvas.releasePointerCapture(event.pointerId);}catch{}},inputOpts);
  canvas.addEventListener('pointercancel',()=>pointers.cancel(),inputOpts);canvas.addEventListener('lostpointercapture',event=>{if(pointers.pointers.has(event.pointerId))pointers.cancel();},inputOpts);
  canvas.addEventListener('wheel',event=>{event.preventDefault();zoom=clampZoom(zoom*Math.exp(-Math.max(-1000,Math.min(1000,event.deltaY))*.001));schedule();},{passive:false,signal:inputEvents.signal});
  canvas.addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0','Home'].includes(event.key)){event.preventDefault();if(panMode||event.shiftKey){if(event.key==='ArrowLeft')pan[0]-=.1;if(event.key==='ArrowRight')pan[0]+=.1;if(event.key==='ArrowUp')pan[1]+=.1;if(event.key==='ArrowDown')pan[1]-=.1;}else{if(event.key==='ArrowLeft')yaw-=.1;if(event.key==='ArrowRight')yaw+=.1;if(event.key==='ArrowUp')pitch=Math.min(1.57,pitch+.1);if(event.key==='ArrowDown')pitch=Math.max(-1.57,pitch-.1);}if(['+','='].includes(event.key))zoom=clampZoom(zoom*1.1);if(event.key==='-')zoom=clampZoom(zoom/1.1);if(['0','Home'].includes(event.key)){zoom=1;pan=[0,0];}schedule();}},inputOpts);
  host.querySelector('.model-mobile-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-model-panel]');if(!button)return;host.querySelector('.model-inspector').dataset.modelPanel=button.dataset.modelPanel;for(const b of host.querySelectorAll('.model-mobile-tabs button'))b.setAttribute('aria-pressed',String(b===button));schedule();});
  host.querySelector('.model-search').addEventListener('input',event=>list(event.target.value));tree.addEventListener('click',event=>{const b=event.target.closest('[data-select]');if(b)choose(b.dataset.select);});tree.addEventListener('change',event=>{const id=event.target.dataset.visible;if(id){event.target.checked?hidden.delete(id):hidden.add(id);schedule();}});
  host.querySelector('input[type=range]').addEventListener('input',event=>{section=Number(event.target.value)/100;host.querySelector('output').textContent=`${event.target.value}%`;schedule();});
  host.querySelector('.model-stage-tools').addEventListener('click',event=>{const b=event.target.closest('[data-view]');if(!b)return;switch(b.dataset.view){case'iso':yaw=-.72;pitch=.58;break;case'top':yaw=0;pitch=Math.PI/2;break;case'front':yaw=0;pitch=0;break;case'fit':zoom=1;pan=[0,0];break;case'pan':panMode=!panMode;b.classList.toggle('active',panMode);b.setAttribute('aria-pressed',String(panMode));for(const direction of ['left','right','up','down'])host.querySelector(`[data-view=${direction}]`).setAttribute('aria-label',`${panMode?'Pan':'Rotate'} model ${direction}`);break;case'in':zoom=clampZoom(zoom*1.25);break;case'out':zoom=clampZoom(zoom*.8);break;case'left':if(panMode)pan[0]-=.15;else yaw-=.15;break;case'right':if(panMode)pan[0]+=.15;else yaw+=.15;break;case'up':if(panMode)pan[1]+=.15;else pitch=Math.min(Math.PI/2,pitch+.15);break;case'down':if(panMode)pan[1]-=.15;else pitch=Math.max(-Math.PI/2,pitch-.15);break;case'isolate':isolate=!isolate;b.classList.toggle('active',isolate);break;case'measure':measure=!measure;measurePoints=[];b.classList.toggle('active',measure);hud.textContent=measure?'Click geometry twice to measure between nearest picked vertices.':'Orbit with one finger · Pan/zoom with two · Buttons also available';break;case'capture':draw();canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='civora-model.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});break;}schedule();});
  const observer=new ResizeObserver(schedule);observer.observe(canvas);list();schedule();
  return{select:choose,showOnly(ids){hidden=new Set(model.objects.filter(o=>!ids.includes(o.id)).map(o=>o.id));list();schedule();},destroy(){disposed=true;inputEvents.abort();pointers.cancel();cancelAnimationFrame(frame);observer.disconnect();if(gl){for(const g of geometry){gl.deleteBuffer(g.positionBuffer);gl.deleteBuffer(g.normalBuffer);}gl.deleteBuffer(buffer);gl.deleteBuffer(normalBuffer);gl.deleteProgram(program);gl.getExtension('WEBGL_lose_context')?.loseContext();}host.replaceChildren();}};
}
