"""Explicit transport-fixture checks. NOT a real browser/server authentication test.
Uses the actual app UI with a deliberately substituted fetch for capability/preview
responses, including delayed responses. Actual HTTP/SQLite tests are separate.
No fixture screenshots are presented as authenticated server captures.
"""
import hashlib,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results';results=[];errors=[]
def ok(name):results.append({'name':name,'passed':True});print('PASS',name,flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox']);page=browser.new_page();page.set_default_timeout(8000)
 try:
  page.expose_function('__testDigest',lambda data:list(hashlib.sha256(bytes(data)).digest()))
  page.evaluate('''()=>{Object.defineProperty(crypto,'subtle',{value:{digest:async(_,data)=>Uint8Array.from(await __testDigest(Array.from(new Uint8Array(data instanceof ArrayBuffer?data:data.buffer)))).buffer}});crypto.randomUUID=()=>{let b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};history.replaceState=()=>{};}''')
  page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'dist/civora.html').read_text(),wait_until='load');page.wait_for_function('!!window.Civora');page.locator('#toast-host .toast').evaluate_all('(items)=>items.forEach(i=>i.click())')
  doc=page.evaluate("Civora.engine.state.documents.find(d=>d.state==='Work in progress'&&!d.checkedOutBy&&!d.deletedAt).id")
  page.evaluate('''()=>{const fetchOriginal=window.fetch;window.__transport={enabled:false,error:false,calls:[],pending:[]};window.fetch=async(url,options)=>{const t=window.__transport;if(String(url).startsWith('/fixture-api/')){t.calls.push({url,options});if(String(url).endsWith('/capabilities')){if(t.error)throw new Error('Fixture network unavailable');return new Response(JSON.stringify({automation:{enabled:t.enabled,intervalMs:30000,lastError:null}}),{headers:{'Content-Type':'application/json'}});}if(String(url).endsWith('/workflow/preview'))return new Promise(resolve=>t.pending.push({resolve,body:JSON.parse(options.body)}));throw new Error('Unexpected fixture endpoint '+url);}return fetchOriginal(url,options);};Civora.engine.repository.kind='server';Civora.engine.repository.base='/fixture-api';Civora.navigate('automation');}''')
  page.wait_for_function("document.querySelector('.automation-banner').innerText.includes('scheduler · disabled')")
  assert page.evaluate("__transport.calls[0].url")=='/fixture-api/capabilities';ok('Capability fixture uses the repository base and disabled scheduler is not shown as running')
  page.evaluate('__transport.enabled=true');page.locator('[data-action=auto-scheduler-refresh]').click();page.wait_for_function("document.querySelector('.automation-banner').innerText.includes('scheduler · enabled')");ok('Explicit status refresh displays the newly returned enabled server configuration')
  page.locator('[data-action=auto-preview]').click();d=page.locator('dialog[open]').last;d.locator('[name=documentId]').select_option(doc);d.locator('[name=to]').select_option('Shared');d.locator('[name=reason]').fill('Original input');d.locator('[data-run-preview]').click();page.wait_for_function('__transport.pending.length===1');d.locator('[name=reason]').fill('Changed while pending')
  page.evaluate('''()=>{const p=__transport.pending.shift(),doc=Civora.engine.state.documents.find(d=>d.id===p.body.id);p.resolve(new Response(JSON.stringify({allowed:true,sourceRevision:Civora.engine.state.revision,documentId:doc.id,from:doc.state,to:'Shared',metadata:doc.metadata,tags:doc.tags}),{headers:{'Content-Type':'application/json'}}));}''');page.wait_for_timeout(100);assert d.locator('[type=submit]').is_disabled();assert 'All transition gates passed' not in d.inner_text();ok('A delayed server preview cannot reenable Apply after its exact form inputs changed')
  d.locator('[data-run-preview]').click();page.wait_for_function('__transport.pending.length===1');page.evaluate('''()=>{const p=__transport.pending.shift(),doc=Civora.engine.state.documents.find(d=>d.id===p.body.id);p.resolve(new Response(JSON.stringify({allowed:true,sourceRevision:Civora.engine.state.revision,documentId:doc.id,from:doc.state,to:'Shared',metadata:doc.metadata,tags:doc.tags}),{headers:{'Content-Type':'application/json'}}));}''');page.wait_for_timeout(100);assert not d.locator('[type=submit]').is_disabled()
  page.evaluate("async(id)=>Civora.engine.run('document.update',{id,title:'Concurrent edit after preview'})",doc);revision=page.evaluate('Civora.engine.state.revision');d.locator('[type=submit]').click();page.wait_for_timeout(100);assert 'workspace changed' in d.locator('.form-error').inner_text().lower();assert page.evaluate('Civora.engine.state.revision')==revision;ok('A successful preview becomes noncommittable after a genuine command advances its source revision')
  page.evaluate("document.querySelectorAll('dialog[open]').forEach(d=>d.close());__transport.error=true");page.locator('[data-action=auto-scheduler-refresh]').click();page.wait_for_function("document.querySelector('.automation-banner').innerText.includes('Scheduler status unavailable')");assert 'No running-state assumption' in page.locator('.automation-banner').inner_text();ok('Failed status transport shows an explicit unknown/error state instead of fabricated healthy service')
  assert not errors,errors
 finally:
  OUT.mkdir(exist_ok=True);(OUT/'automation-transport-ui.json').write_text(json.dumps({'mode':'explicit fetch transport fixture on actual app UI; not authenticated browser/server qualification','results':results,'pageErrors':errors},indent=2));browser.close()
