import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './support.mjs';
import {validateWorkspace,currentVersion} from '../packages/core/index.js';
import {prepareFile} from '../packages/storage/index.js';
import {projectWorkspace} from '../packages/access/index.js';
import {resolveDocumentSet,visibleDocumentSets,setMembers,setVersion,snapshotDocumentSet,validateDocumentSets} from '../packages/document-sets/index.js';
import {exportDocumentSetArchive} from '../packages/document-sets/archive.js';
const create=(f,patch={})=>f.run('set.create',{projectId:f.project,name:'Coordination package',documentIds:[f.doc],...patch});
const find=(f,id)=>f.state.sets.find(s=>s.id===id);
const resolve=(f,id,options={},actor='u-admin')=>resolveDocumentSet(f.state,actor,id,options);
const update=(f,id,patch={},actor='u-admin')=>f.run('set.update',{id,expectedVersion:setVersion(find(f,id)),...patch},actor);
const lock=(f,id,patch={},actor='u-admin')=>f.run('set.lock',{id,expectedVersion:setVersion(find(f,id)),reason:'Issued coordination package',...patch},actor);
const repo=f=>({async blob(id){return f.files.get(id);}});
const zip=(f,id,options={})=>exportDocumentSetArchive(()=>f.state,'u-admin',id,repo(f),options);
async function checkin(f,id=f.doc,body='Changed source bytes',actor='u-admin'){
 const file=await prepareFile(new Blob([body],{type:'text/plain'}));f.files.set(file.descriptor.hash,file.blob);f.run('document.checkout',{id},actor);f.run('document.checkin',{id,file:file.descriptor,revision:'P02',comment:'New revision'},actor);
}
// Independent decoder for the STORE-only ZIP local records; no application ZIP reader used.
async function decode(blob){const b=Buffer.from(await blob.arrayBuffer()),out=new Map();let p=0;while(b.readUInt32LE(p)===0x04034b50){assert.equal(b.readUInt16LE(p+8),0);const length=b.readUInt32LE(p+18),n=b.readUInt16LE(p+26),x=b.readUInt16LE(p+28),name=b.subarray(p+30,p+30+n).toString();out.set(name,b.subarray(p+30+n+x,p+30+n+x+length));p+=30+n+x+length;}assert.equal(b.readUInt32LE(p),0x02014b50);return out;}

test('Legacy documentIds sets remain readable as ordered live memberships',async()=>{const f=await fixture();f.state.sets.push({id:'legacy',projectId:f.project,name:'Legacy',documentIds:[f.doc],createdAt:new Date().toISOString(),createdBy:'u-admin'});validateWorkspace(f.state);assert.equal(resolve(f,'legacy').version,1);assert.equal(resolve(f,'legacy').records[0].binding,'latest');assert.equal(setMembers(find(f,'legacy'))[0].versionId,null);update(f,'legacy',{description:'Upgraded'});assert.equal(find(f,'legacy').version,2);assert.equal(find(f,'legacy').members.length,1);});
test('Set creation stores versioned definitions without copying or changing source documents',async()=>{const f=await fixture(),before=structuredClone(f.state.documents),count=f.files.size,id=create(f);assert.equal(setVersion(find(f,id)),1);assert.deepEqual(f.state.documents,before);assert.equal(f.files.size,count);assert.equal(find(f,id).members[0].versionId,null);validateWorkspace(f.state);});
test('Membership order and explicit bindings survive definition edits',async()=>{const f=await fixture(),other=await f.add('other.txt'),id=create(f);const v=currentVersion(f.state.documents.find(d=>d.id===f.doc));update(f,id,{members:[{documentId:other,versionId:null},{documentId:f.doc,versionId:v.id}]});assert.deepEqual(resolve(f,id).records.map(r=>r.documentId),[other,f.doc]);assert.equal(resolve(f,id).records[1].binding,'fixed');assert.equal(find(f,id).version,2);});
test('Latest follows check-in while fixed members remain pinned to their selected original bytes',async()=>{const f=await fixture(),v=currentVersion(f.state.documents.find(d=>d.id===f.doc)),live=create(f),fixed=create(f,{name:'Fixed',members:[{documentId:f.doc,versionId:v.id}]});await checkin(f);assert.notEqual(resolve(f,live).records[0].versionId,v.id);assert.equal(resolve(f,fixed).records[0].versionId,v.id);assert.equal(resolve(f,fixed).newerCount,1);});
for(const [label,patch] of [
 ['duplicate members',f=>({members:[{documentId:f.doc,versionId:null},{documentId:f.doc,versionId:null}]})],
 ['unknown revision',f=>({members:[{documentId:f.doc,versionId:'unknown'}]})],
 ['cross-project document',f=>({documentIds:[f.hidden]})],
 ['undefined binding',f=>({members:[{documentId:f.doc}]})],
 ['unknown document',f=>({documentIds:['not-a-document']})],
 ['blank name',()=>({name:'  '})],['oversized name',()=>({name:'x'.repeat(201)})],['oversized description',()=>({description:'x'.repeat(2001)})],
 ['too many members',f=>({members:Array.from({length:1001},()=>({documentId:f.doc,versionId:null}))})],['wrong member container',()=>({members:{}})],['wrong documentIds container',()=>({documentIds:'abc'})]
])test('Set commands reject '+label+' atomically',async()=>{const f=await fixture(),before=structuredClone(f.state);assert.throws(()=>create(f,patch(f)));assert.deepEqual(f.state,before);});
test('Names are project-unique without case sensitivity',async()=>{const f=await fixture();create(f);assert.throws(()=>create(f,{name:'COORDINATION PACKAGE'}),/exists/);});
test('Set mutations require a matching definition version, including delete and unlock',async()=>{const f=await fixture(),id=create(f);const before=structuredClone(f.state);for(const type of ['set.update','set.lock','set.unlock','set.delete'])for(const expectedVersion of [undefined,0,2,'1'])assert.throws(()=>f.run(type,{id,expectedVersion,reason:'Try'}),/version|changed/i);assert.deepEqual(f.state,before);});
test('All members and the project must be readable; a set never grants access',async()=>{const f=await fixture(),other=await f.add('restricted.txt'),id=create(f,{documentIds:[f.doc,other]});f.grant('project',f.project,'user:'+f.viewer,['read']);assert.equal(visibleDocumentSets(f.state,f.viewer).length,1);f.grant('document',other,'user:'+f.viewer,[],['read']);assert.equal(visibleDocumentSets(f.state,f.viewer).length,0);assert.throws(()=>resolve(f,id,{},f.viewer),/unavailable/);assert.equal(projectWorkspace(f.state,f.viewer).sets.length,0);});
test('Permissions agree in authoritative and projected states, and reject another projected identity',async()=>{const f=await fixture(),id=create(f);f.grant('project',f.project,'user:'+f.viewer,['read']);const p=projectWorkspace(f.state,f.viewer);assert.deepEqual(resolveDocumentSet(p,f.viewer,id),resolve(f,id,{},f.viewer));assert.throws(()=>resolveDocumentSet(p,f.author,id),/another account/);assert.throws(()=>resolve(f,id,{permission:'download'},f.viewer),/Permission/);});
test('Authors require project write and member reads; management is additionally required to lock',async()=>{const f=await fixture(),id=create(f);f.grant('project',f.project,'user:'+f.author,['read','write']);update(f,id,{description:'Author edit'},f.author);assert.throws(()=>lock(f,id,{},f.author),/Access|manager|permission/i);f.grant('document',f.doc,'user:'+f.author,[],['read']);assert.throws(()=>update(f,id,{description:'Cannot see member'},f.author));});
test('Viewer roles cannot mutate a set even if an administrator grants broad policy entries',async()=>{const f=await fixture(),id=create(f);f.grant('project',f.project,'user:'+f.viewer);assert.throws(()=>update(f,id,{},f.viewer),/role|permission|Access/i);});
test('Manager lock freezes revisions, names, numbers and paths; changes become newer indicators',async()=>{const f=await fixture(),id=create(f),before=resolve(f,id).records[0];lock(f,id);assert.equal(find(f,id).version,2);assert.equal(find(f,id).locked,true);assert.equal(resolve(f,id).records[0].binding,'fixed');await checkin(f);f.run('document.update',{id:f.doc,name:'renamed.txt',title:'New title'});f.run('folder.update',{id:f.folder,name:'Changed folder'});const frozen=resolve(f,id).records[0];assert.equal(frozen.name,before.name);assert.equal(frozen.path,before.path);assert.equal(frozen.title,before.title);assert.equal(frozen.hash,before.hash);assert.equal(frozen.newerRevision,true);validateWorkspace(f.state);});
test('Lock is reasoned, nonempty, and rejects any checked-out member without partial edits',async()=>{const f=await fixture(),empty=create(f,{name:'Empty',documentIds:[]}),id=create(f);assert.throws(()=>lock(f,empty),/empty/);assert.throws(()=>lock(f,id,{reason:' '}),/required/);f.run('document.checkout',{id:f.doc});const before=structuredClone(f.state);assert.throws(()=>lock(f,id),/Check in|release/);assert.deepEqual(f.state,before);});
test('Locked definitions and originals cannot be deleted through normal commands',async()=>{const f=await fixture(),id=create(f);lock(f,id);for(const type of ['set.update','set.delete'])assert.throws(()=>f.run(type,{id,expectedVersion:2}),/locked/i);assert.throws(()=>f.run('document.delete',{id:f.doc}),/locked|Unlock/i);});
test('Explicit unlock retains fixed bindings and audit evidence; removing a set keeps original files',async()=>{const f=await fixture(),id=create(f);lock(f,id);const bindings=structuredClone(find(f,id).members);f.run('set.unlock',{id,expectedVersion:2,reason:'Revised delivery scope'});assert.equal(find(f,id).locked,false);assert.equal(find(f,id).frozenDocuments,undefined);assert.deepEqual(find(f,id).members,bindings);assert.match(f.state.audit.at(-1).summary,/Revised delivery scope/);f.run('set.delete',{id,expectedVersion:3});assert.equal(f.state.sets.length,0);assert.ok(f.state.documents.some(d=>d.id===f.doc));});
test('Recycled members remain visible as unavailable but cannot be exported or locked',async()=>{const f=await fixture(),id=create(f);f.run('document.delete',{id:f.doc});assert.throws(()=>resolve(f,id),/recycled/);assert.equal(resolve(f,id,{allowRecycled:true}).records[0].recycled,true);await assert.rejects(()=>zip(f,id),/recycled/);assert.throws(()=>lock(f,id),/recycled/);});
test('Transmittal from a fixed set freezes selected revisions and source-definition evidence',async()=>{const f=await fixture(),id=create(f),v=resolve(f,id).records[0];lock(f,id);await checkin(f);const delivery=f.run('transmittal.create',{projectId:f.project,setId:id,expectedSetVersion:2,title:'Package',recipients:'recipient@test.example',purpose:'For information'}),out=f.state.transmittals.find(t=>t.id===delivery);assert.equal(out.documents[0].versionId,v.versionId);assert.equal(out.sourceSetId,id);assert.equal(out.sourceSetVersion,2);validateWorkspace(f.state);});
test('Review snapshot refuses historical fixed members and stale definition preconditions',async()=>{const f=await fixture(),id=create(f);lock(f,id);assert.equal(snapshotDocumentSet(f.state,'u-admin',{projectId:f.project,setId:id,expectedSetVersion:2},{currentOnly:true}).length,1);assert.throws(()=>snapshotDocumentSet(f.state,'u-admin',{projectId:f.project,setId:id}),/precondition/);await checkin(f);assert.throws(()=>snapshotDocumentSet(f.state,'u-admin',{projectId:f.project,setId:id,expectedSetVersion:2},{currentOnly:true}),/current revisions/);});
for(const [label,mutate] of [
 ['membership mismatch',s=>s.documentIds=[]],['duplicate membership',s=>{s.members.push({...s.members[0]});s.documentIds.push(s.documentIds[0]);}],['invalid definition version',s=>s.version=0],['missing frozen descriptor',s=>s.frozenDocuments=[]],['incorrect frozen hash',s=>s.frozenDocuments[0].hash='a'.repeat(64)],['incorrect frozen order',s=>s.frozenDocuments[0].documentId='unknown'],['unlocked frozen evidence',s=>s.locked=false],['missing reason',s=>s.lockReason=''],['invalid lock authority',s=>s.lockedBy='unknown']
])test('Workspace validation rejects '+label,async()=>{const f=await fixture(),id=create(f);lock(f,id);mutate(find(f,id));assert.throws(()=>validateDocumentSets(f.state));});
test('Verified archive preserves member order and exact pinned bytes, with independently decoded ZIP',async()=>{const f=await fixture(),other=await f.add('second.txt'),id=create(f,{documentIds:[other,f.doc]});lock(f,id);await checkin(f);const out=await zip(f,id),files=await decode(out.zip),manifest=JSON.parse(files.get('manifest.json'));assert.equal(manifest.setVersion,2);assert.deepEqual(manifest.documents.map(d=>d.documentId),[other,f.doc]);assert.equal(files.get(manifest.documents[1].archivePath).toString(),'Original a.txt');assert.equal(out.manifest.locked,true);});
test('Archive rejects missing bytes, corrupt content, excessive size and an empty set',async()=>{const f=await fixture(),id=create(f);await assert.rejects(()=>zip(f,id,{maxBytes:1}),/limit/);await assert.rejects(()=>zip(f,id,{maxBytes:Infinity}),/limit/);const empty=create(f,{name:'Empty',documentIds:[]});await assert.rejects(()=>zip(f,empty),/no documents/);await assert.rejects(()=>exportDocumentSetArchive(()=>f.state,'u-admin',id,{blob:async()=>new Blob(['bad'])}),/checksum/);f.files.clear();await assert.rejects(()=>zip(f,id),/checksum/);});
test('Archive rechecks access after asynchronous reads and before emitting a package',async()=>{const f=await fixture(),id=create(f);f.grant('project',f.project,'user:'+f.viewer,['read','download']);await assert.rejects(()=>exportDocumentSetArchive(()=>f.state,f.viewer,id,{async blob(id){f.grant('project',f.project,'user:'+f.viewer,['read'],['download']);return f.files.get(id);}}),/Permission/);});
test('Archive rejects source-definition edits, live revision changes and account workspace switches during reads',async()=>{const f=await fixture(),id=create(f);await assert.rejects(()=>exportDocumentSetArchive(()=>f.state,'u-admin',id,{async blob(hash){update(f,id,{description:'Changed while reading'});return f.files.get(hash);}}),/changed/);await assert.rejects(()=>exportDocumentSetArchive(()=>f.state,'u-admin',id,{async blob(hash){await checkin(f);return f.files.get(hash);}}),/live member changed/);await assert.rejects(()=>exportDocumentSetArchive(()=>f.state,'u-admin',id,{async blob(hash){f.state.id='different-workspace';return f.files.get(hash);}}),/Workspace changed/);});
test('Archive checks progress-triggered cancellation even after the final file',async()=>{const f=await fixture(),id=create(f),controller=new AbortController();await assert.rejects(()=>zip(f,id,{signal:controller.signal,onProgress(){controller.abort();}}),{name:'AbortError'});});
test('Fixed archives remain valid after unrelated work and newer source check-in during export',async()=>{const f=await fixture(),id=create(f);lock(f,id);const out=await exportDocumentSetArchive(()=>f.state,'u-admin',id,{async blob(hash){await checkin(f);return f.files.get(hash);}});assert.equal(out.manifest.documents[0].revision,'P01');});

test('Legacy one-thousand-member sets retain their previously supported capacity on upgrade',async()=>{const f=await fixture(),source=f.state.documents.find(d=>d.id===f.doc),ids=[];for(let i=0;i<1000;i++){const d=structuredClone(source);d.id='legacy-document-'+i;d.number='LEG-'+i;d.versions=d.versions.map((v,j)=>({...v,id:'legacy-version-'+i+'-'+j}));f.state.documents.push(d);ids.push(d.id);}f.state.sets.push({id:'large-legacy',projectId:f.project,name:'Legacy maximum',documentIds:ids,createdBy:'u-admin',createdAt:new Date().toISOString()});f.state=structuredClone(f.state);validateDocumentSets(f.state);assert.equal(resolve(f,'large-legacy').records.length,1000);update(f,'large-legacy',{description:'Capacity preserved'});assert.equal(find(f,'large-legacy').members.length,1000);validateWorkspace(f.state);});
