import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
import {createHash} from 'node:crypto';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function unusedPort(){const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));return port;}
test('Document sets over authenticated HTTP, exact-byte ZIP and persistent SQLite',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'civora-sets-')),origin=`http://127.0.0.1:${await unusedPort()}`,password='explorer-test-unique-local-password';let child,logs='',admin='',authorCookie='',viewerCookie='',state,project,folder,target,doc,other,secret,author,viewer,shared,pin,viewId,setId,frozenVersion,delivery;
 const request=async(path,{method='GET',body,cookie=admin,requestOrigin=origin}={})=>{const response=await fetch(origin+path,{method,headers:{Cookie:cookie,...(method!=='GET'?{Origin:requestOrigin,'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:response.status,headers:response.headers,data:(response.headers.get('content-type')||'').includes('application/json')?await response.json():(response.headers.get('content-type')||'').includes('application/zip')?Buffer.from(await response.arrayBuffer()):await response.text()};};
 const refresh=async()=>{const out=await request('/api/workspace');assert.equal(out.status,200);state=out.data.state;return state;};
 const command=async(type,payload,{cookie=admin,expectedRevision=state.revision,file}={})=>request('/api/commands',{method:'POST',cookie,body:{expectedRevision,command:{type,payload},...(file?{file}:{})}});
 const run=async(type,payload,options)=>{const out=await command(type,payload,options);assert.equal(out.status,200,`${type}: ${JSON.stringify(out.data)}`);await refresh();return out.data.result;};
 async function add(name,folderId=folder){const bytes=Buffer.from('Original exact bytes: '+name+'\n'),hash=createHash('sha256').update(bytes).digest('hex');return run('document.create',{projectId:project,folderId,name,file:{hash,blobId:hash,size:bytes.length,mime:'text/plain'}},{file:{data:bytes.toString('base64'),mime:'text/plain'}});}
 async function start(){child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:new URL(origin).port,HOST:'127.0.0.1',CIVORA_PUBLIC_ORIGIN:origin,CIVORA_DATA_DIR:dir,CIVORA_ADMIN_PASSWORD:password,CIVORA_DB:'sqlite',CIVORA_AUTO_RENDITIONS:'0',CIVORA_SEED_DEMO:'0',CIVORA_AUTOMATION:'0'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);for(let i=0;i<200;i++){try{if((await request('/api/health')).status===200)return;}catch{}if(child.exitCode!==null)throw new Error(logs);await delay(30);}throw new Error(logs);}
 async function stop(){if(child?.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await done;}}
 async function login(email){const out=await request('/api/login',{method:'POST',cookie:'',body:{email,password}});assert.equal(out.status,200);return out.headers.get('set-cookie').split(';')[0];}
 const resolve=(cookie=admin,extra={})=>request('/api/sets/resolve',{method:'POST',cookie,body:{id:setId,expectedVersion:state.sets.find(s=>s.id===setId)?.version,expectedRevision:state.revision,...extra}});
 const archive=(cookie=admin,extra={})=>request('/api/sets/export',{method:'POST',cookie,body:{id:setId,expectedVersion:state.sets.find(s=>s.id===setId)?.version,expectedRevision:state.revision,...extra}});
 const decode=b=>{let offset=0;const files=new Map();while(b.readUInt32LE(offset)===0x04034b50){assert.equal(b.readUInt16LE(offset+8),0);const n=b.readUInt16LE(offset+26),x=b.readUInt16LE(offset+28),size=b.readUInt32LE(offset+18),name=b.subarray(offset+30,offset+30+n).toString();files.set(name,b.subarray(offset+30+n+x,offset+30+n+x+size));offset+=30+n+x+size;}assert.equal(b.readUInt32LE(offset),0x02014b50);return files;};
 try{await start();admin=await login('admin@civora.local');await refresh();
  await t.test('Set endpoints require authentication and same-origin requests',async()=>{for(const path of ['/api/sets/resolve','/api/sets/export']){assert.equal((await request(path,{method:'POST',cookie:'',body:{}})).status,401);assert.equal((await request(path,{method:'POST',requestOrigin:'https://hostile.invalid',body:{}})).status,403);}project=await run('project.create',{name:'Set integration',code:'SET'});folder=await run('folder.create',{projectId:project,name:'Design'});doc=await add('Drawing2.txt');other=await add('Drawing10.txt');secret=await add('restricted.txt');setId=await run('set.create',{projectId:project,name:'Issued coordination',documentIds:[doc,other]});author=await run('user.create',{name:'Scoped Author',email:'author@sets.test',role:'author'});viewer=await run('user.create',{name:'Scoped Viewer',email:'viewer@sets.test',role:'viewer'});await run('access.set',{scope:'project',resourceId:project,inherit:true,entries:[{principal:'user:'+author,allow:['read','download','write'],deny:[]},{principal:'user:'+viewer,allow:['read'],deny:[]}]});for(const userId of [author,viewer])assert.equal((await request('/api/admin/password',{method:'POST',body:{userId,password}})).status,200);authorCookie=await login('author@sets.test');viewerCookie=await login('viewer@sets.test');});
  await t.test('Set resolution returns authoritative membership order but does not grant download',async()=>{const out=await resolve(viewerCookie);assert.equal(out.status,200);assert.deepEqual(out.data.records.map(d=>d.documentId),[doc,other]);assert.equal(out.data.records[0].binding,'latest');assert.equal((await archive(viewerCookie)).status,403);assert.equal((await resolve(viewerCookie,{permission:'download'})).status,403);});
  await t.test('Malformed member inputs return client errors without mutation or server faults',async()=>{const before=structuredClone(state);for(const members of [{},'bad',[null],[{versionId:null}]]){const out=await command('set.update',{id:setId,expectedVersion:1,members},{cookie:authorCookie});assert.equal(out.status,400,JSON.stringify(out.data));}await refresh();assert.deepEqual(state,before);});
  await t.test('Set edit authorization and stale definition revisions are enforced independently',async()=>{assert.equal((await command('set.update',{id:setId,expectedVersion:1,name:'viewer edit'},{cookie:viewerCookie})).status,403);await run('set.update',{id:setId,expectedVersion:1,description:'Edited by author'},{cookie:authorCookie});assert.equal((await command('set.update',{id:setId,expectedVersion:1,description:'Stale'},{cookie:authorCookie})).status,409);assert.equal((await archive(admin,{expectedVersion:1})).status,409);assert.equal((await archive(admin,{expectedVersion:null})).status,400);assert.equal((await resolve(admin,{expectedRevision:0})).status,409);});
  await t.test('Manager lock freezes exact selected versions without copying original bytes',async()=>{assert.equal((await command('set.lock',{id:setId,expectedVersion:2,reason:'Not authorized'},{cookie:authorCookie})).status,403);frozenVersion=state.documents.find(d=>d.id===doc).versions.at(-1);await run('set.lock',{id:setId,expectedVersion:2,reason:'Coordination issue'});assert.equal(state.sets.find(s=>s.id===setId).locked,true);assert.equal((await command('document.delete',{id:doc})).status,409);await run('document.checkout',{id:doc},{cookie:authorCookie});const bytes=Buffer.from('NEWER SOURCE CONTENT'),hash=createHash('sha256').update(bytes).digest('hex');await run('document.checkin',{id:doc,revision:'P02',comment:'Later edit',file:{hash,blobId:hash,size:bytes.length,mime:'text/plain'}},{cookie:authorCookie,file:{data:bytes.toString('base64'),mime:'text/plain'}});const out=await resolve();assert.equal(out.data.newerCount,1);assert.equal(out.data.records[0].versionId,frozenVersion.id);});
  await t.test('Downloaded ZIP is independently decoded and contains older issued originals, not newer files',async()=>{const out=await archive(authorCookie);assert.equal(out.status,200,JSON.stringify(out.data));assert.equal(out.headers.get('cache-control'),'no-store');assert.match(out.headers.get('content-disposition'),/attachment/);const files=decode(out.data),manifest=JSON.parse(files.get('manifest.json'));assert.equal(manifest.setVersion,3);assert.equal(manifest.locked,true);assert.equal(manifest.documents[0].versionId,frozenVersion.id);assert.equal(files.get(manifest.documents[0].archivePath).toString(),'Original exact bytes: Drawing2.txt\n'.replace('\\n','\n'));assert.equal(createHash('sha256').update(files.get(manifest.documents[0].archivePath)).digest('hex'),frozenVersion.hash);});
  await t.test('Transmittal generation uses server-resolved set snapshots with exact version evidence',async()=>{delivery=await run('transmittal.create',{projectId:project,title:'Set delivery',setId,expectedSetVersion:3,recipients:'recipient@example.test',purpose:'For information'});const t=state.transmittals.find(x=>x.id===delivery);assert.equal(t.documents[0].versionId,frozenVersion.id);assert.equal(t.sourceSetId,setId);assert.equal(t.sourceSetVersion,3);});
  await t.test('Revoking any member read hides the whole set, including API and package endpoints',async()=>{await run('access.set',{scope:'document',resourceId:other,inherit:true,entries:[{principal:'user:'+author,allow:[],deny:['read']},{principal:'user:'+viewer,allow:[],deny:['read']}]});assert.equal((await resolve(authorCookie)).status,404);assert.equal((await archive(authorCookie)).status,404);const view=(await request('/api/workspace',{cookie:authorCookie})).data.state;assert.equal(view.sets.length,0);assert.ok(!view.documents.some(d=>d.id===other));});
  await t.test('Real restart retains frozen set identity, binding order and verified ZIP bytes',async()=>{const revision=state.revision;await stop();await start();admin=await login('admin@civora.local');await refresh();assert.equal(state.revision,revision);const out=await archive();assert.equal(out.status,200);const files=decode(out.data),manifest=JSON.parse(files.get('manifest.json'));assert.equal(manifest.documents[0].versionId,frozenVersion.id);assert.equal(manifest.setVersion,3);});
  await t.test('Explicit audited unlock permits definition deletion, preserving the issued package and source',async()=>{await run('set.unlock',{id:setId,expectedVersion:3,reason:'Superseded package'});assert.equal(state.sets[0].members[0].versionId,frozenVersion.id);await run('set.delete',{id:setId,expectedVersion:4});assert.equal(state.sets.length,0);assert.equal(state.transmittals.find(t=>t.id===delivery).documents[0].versionId,frozenVersion.id);assert.ok(state.documents.some(d=>d.id===doc));});
 }finally{await stop();await rm(dir,{recursive:true,force:true});}
});
