"""Explorer 0.8 appearance and keyboard regressions on the real application.
Opaque-origin MemoryRepository. __preferences is an explicit localStorage fixture
for serialization/account-isolation checks, NOT real browser persistence.
"""
import hashlib,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results';OUT.mkdir(exist_ok=True)
results=[];errors=[]
def ok(name):results.append({'name':name,'passed':True});print('PASS',name,flush=True)
def d(page):return page.locator('dialog[open]').last
def dismiss(page):page.locator('#toast-host .toast').evaluate_all('(xs)=>xs.forEach(x=>x.click())')
def close(page):page.evaluate("document.querySelectorAll('dialog[open]').forEach(d=>d.close())");page.wait_for_timeout(50)
def action(page,name,extra=''):page.locator(f'[data-action="{name}"]{extra}:visible').first.click();page.wait_for_timeout(80)
def submit(page):d(page).locator('[type=submit]').click();page.wait_for_timeout(130)
def install(page):
 page.expose_function('__testDigest',lambda data:list(hashlib.sha256(bytes(data)).digest()))
 page.evaluate('''()=>{Object.defineProperty(crypto,'subtle',{value:{digest:async(_,data)=>Uint8Array.from(await __testDigest(Array.from(data instanceof ArrayBuffer?new Uint8Array(data):new Uint8Array(data.buffer,data.byteOffset,data.byteLength)))).buffer}});crypto.randomUUID=()=>{let b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};history.replaceState=()=>{};window.__preferences=new Map();Object.defineProperty(window,'localStorage',{value:{getItem:k=>__preferences.get(k)||null,setItem:(k,v)=>__preferences.set(k,v)}});}''')
 page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'dist/civora.html').read_text(),wait_until='load');page.wait_for_function('!!window.Civora');dismiss(page)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox']);page=browser.new_page(viewport={'width':1600,'height':1000},device_scale_factor=1);page.set_default_timeout(8000)
 try:
  install(page);assert page.locator('.ex-menubar [data-menu]').all_text_contents()==['Datasource','Folder','Document','View','Tools','Window','Help'];assert page.locator('.ex-standard-toolbar').is_visible();assert not page.locator('#sidebar').is_visible();assert page.locator('.ex-ribbon').count()==0
  assert page.locator('.ex-standard-toolbar').bounding_box()['height']<=44;ok('Desktop defaults to familiar menu groups and compact standard tools without the dashboard rail')
  assert page.locator('[data-ex-column=title]').count()==1;assert page.locator('[data-ex-row]').count()==15;assert page.locator('[data-ex-row]').first.bounding_box()['height']<=32
  assert page.locator('.ex-file-cell small').first.is_hidden();assert page.locator('.ex-datasource-root').inner_text()=='Civora Explorer Datasources';assert 'Temporary memory' in page.locator('.ex-statusbar').inner_text();ok('Detailed register has separate descriptions, single-line files, real datasource hierarchy and truthful storage status')
  row=page.locator('[data-ex-row]').first;y=row.bounding_box()['y'];row.click();page.wait_for_timeout(70);assert abs(page.locator('[data-ex-row]').first.bounding_box()['y']-y)<1
  dismiss(page);page.screenshot(path=str(OUT/'design-explorer.png'),full_page=True)
  action(page,'clear-selection');page.locator('[data-ex-row]').first.dblclick();page.wait_for_timeout(100);assert page.locator('dialog[open]').count()==1;close(page);ok('Selection does not shift document rows and double-click opens the full inspector reliably')
  # Real current metadata, not a static properties mockup.
  target=page.evaluate('Civora.engine.state.documents.find(d=>d.projectId===Civora.ui.projectId&&Object.values(d.metadata).includes(false))?.id')
  if not target:
   target=page.evaluate('Civora.engine.state.documents.find(d=>d.projectId===Civora.ui.projectId&&!d.checkedOutBy).id')
   page.evaluate('async(id)=>{const doc=Civora.engine.state.documents.find(d=>d.id===id);await Civora.engine.run("document.update",{id,metadata:{...doc.metadata,handover_ready:false}})}',target)
  page.evaluate('(id)=>Civora.explorer.go(Civora.ui.projectId,"",{documentId:id})',target);action(page,'ex-inspector-tab','[data-tab=attributes]')
  expected=page.evaluate('Civora.engine.state.projects.find(p=>p.id===Civora.ui.projectId).fields.length');assert page.locator('dialog[open]').count()==0
  assert page.locator('.ex-attributes-panel tbody tr').count()==expected
  fields=page.locator('.ex-attributes-panel').inner_text();assert 'Metadata environment' in fields;assert 'false' in fields
  page.screenshot(path=str(OUT/'design-attributes.png'),full_page=True);ok('Attributes tab renders current typed metadata and preserves false boolean values')
  action(page,'ex-inspector-tab','[data-tab=folder]');source=page.evaluate('(id)=>Civora.engine.state.documents.find(d=>d.id===id).folderId',target)
  expected_name=page.evaluate('(id)=>Civora.engine.state.folders.find(f=>f.id===id)?.name',source)
  assert expected_name in page.locator('.ex-placeholder-properties').inner_text();action(page,'ex-tree',f'[data-id="{source}"][data-scope=folder]');assert page.evaluate('Civora.ui.folderId')==source;ok('Folder properties report the selected document source and navigate through real folder commands')
  page.evaluate('Civora.explorer.go(Civora.ui.projectId)');project=page.evaluate('Civora.ui.projectId');node=page.locator(f'#ex-node-{project}');node.focus();page.keyboard.press('ArrowLeft');page.wait_for_timeout(60);assert page.locator(f'#ex-node-{project}').get_attribute('aria-expanded')=='false';assert page.evaluate('document.activeElement.id')=='ex-node-'+project
  page.keyboard.press('ArrowRight');page.wait_for_timeout(60);assert page.locator(f'#ex-node-{project}').get_attribute('aria-expanded')=='true';assert page.evaluate('document.activeElement.id')=='ex-node-'+project
  page.keyboard.press('ArrowRight');assert page.evaluate('document.activeElement.dataset.scope')=='folder';page.keyboard.press('ArrowLeft');assert page.evaluate('document.activeElement.id')=='ex-node-'+project;ok('Tree collapse is retained for the current project and keyboard expand/parent navigation retains focus')
  action(page,'ex-collection','[data-id=sets]');assert page.locator('.ex-collection-content [data-action=set-open]').count()==0;action(page,'ex-collection','[data-id=sets]');assert page.locator('.ex-collection-content [data-action=set-open]').count()>0;ok('Tree collections have working persisted disclosure controls rather than decorative section labels')
  page.locator('.ex-menubar [data-menu=Datasource]').focus();page.keyboard.press('ArrowRight');assert page.evaluate('document.activeElement.dataset.menu')=='Folder';page.keyboard.press('ArrowDown');assert page.locator('.ex-context').is_visible();page.keyboard.press('Escape');assert page.evaluate('document.activeElement.dataset.menu')=='Folder';ok('Menubar supports directional navigation, keyboard opening and focus restoration')
  page.locator('[data-ex-row]').first.click();action(page,'ex-inspector-tab','[data-tab=properties]');page.locator('.ex-inspector-tabs [data-tab=properties]').focus();page.keyboard.press('ArrowRight');assert page.locator('.ex-inspector-tabs [data-tab=folder]').get_attribute('aria-selected')=='true';assert page.evaluate('document.activeElement.dataset.tab')=='folder';page.keyboard.press('F6');assert page.evaluate('document.activeElement.id')=='document-search';page.keyboard.press('F6');assert page.evaluate('document.activeElement.id')=='ex-tree-search';page.keyboard.press('Alt+d');assert d(page).locator('[name=link]').count()==1;close(page);ok('Preview tabs and F6 cycle work by keyboard; Alt+D exposes permission-checked address navigation')
  revision=page.evaluate('Civora.engine.state.revision');original=page.evaluate('Civora.explorer.layout');action(page,'ex-appearance');d(page).locator('[data-appearance-preset=ribbon]').click();page.screenshot(path=str(OUT/'design-appearance.png'),full_page=True);close(page);assert page.evaluate('Civora.explorer.layout')==original;assert page.evaluate('Civora.engine.state.revision')==revision;ok('Appearance preview and cancellation do not alter shared data or committed preferences')
  action(page,'ex-appearance');d(page).locator('[data-appearance-preset=ribbon]').click();submit(page);assert page.locator('.ex-ribbon').is_visible();assert page.locator('#sidebar').is_visible();assert page.locator('.ex-file-cell small').first.is_visible();assert page.evaluate('Civora.engine.state.revision')==revision;dismiss(page);page.screenshot(path=str(OUT/'design-ribbon.png'),full_page=True);ok('Ribbon preset restores grouped commands, descriptions and rail without changing documents')
  # Actual account switch, with clearly identified browser-local test preferences.
  other=page.evaluate('Civora.engine.state.users.find(u=>u.active&&u.id!=="u-admin").id')
  action(page,'profile');d(page).locator('[name=actor]').select_option(other);submit(page);assert page.evaluate('Civora.explorer.layout.commandStyle')=='standard'
  action(page,'profile');d(page).locator('[name=actor]').select_option('u-admin');submit(page);assert page.evaluate('Civora.explorer.layout.commandStyle')=='ribbon';assert page.evaluate('[...__preferences.keys()].some(k=>k.startsWith("civora-explorer-ui:"))');ok('Preferences serialize through the explicit storage fixture and remain separated by local account identity')
  action(page,'ex-appearance');d(page).locator('[data-appearance-preset=review]').click();submit(page);assert page.locator('.ex-dock-right').is_visible();assert page.evaluate('Civora.explorer.layout.previewWidth')==420;assert not page.locator('#sidebar').is_visible();page.locator('[data-ex-row]').first.click();action(page,'ex-inspector-tab','[data-tab=properties]');dismiss(page);page.screenshot(path=str(OUT/'design-review.png'),full_page=True);ok('Review preset changes actual dock geometry and preserves commands and document selection')
  action(page,'ex-pane-menu');action(page,'ex-dock','[data-position=bottom]');assert page.locator('.ex-dock-bottom').count()==1;action(page,'ex-pane-menu');action(page,'ex-dock','[data-position=hidden]');assert page.locator('.ex-inspector').count()==0;action(page,'ex-menu','[data-menu=View]');action(page,'ex-dock','[data-position=bottom]');assert page.locator('.ex-inspector').count()==1;ok('Pane caption exposes bottom/right/hide controls and View restores hidden panes')
  action(page,'mobile-more');assert d(page).locator('[data-mobile-tool]').count()==25;d(page).locator('[data-mobile-tools-search]').fill('workflow');assert d(page).locator('[data-mobile-tool]:visible').count()==1;d(page).locator('[data-mobile-tool=automation]').click();page.wait_for_timeout(80);assert page.evaluate('Civora.ui.route')=='automation';page.evaluate('Civora.navigate("documents")');ok('All twenty-five workspaces remain reachable without enabling the navigation rail')
  action(page,'ex-menu','[data-menu=View]');action(page,'ex-reset');page.locator('[data-ex-row]').first.click();action(page,'ex-inspector-tab','[data-tab=preview]');page.wait_for_function('document.querySelector("#ex-file-preview img")?.complete');assert page.locator('#ex-file-preview img').get_attribute('src').startswith('blob:');dismiss(page);page.screenshot(path=str(OUT/'design-preview.png'),full_page=True);ok('Compact preview pane loads the original SVG through its existing renderer')
  action(page,'ex-menu','[data-menu=View]');action(page,'toggle-theme');assert page.evaluate('getComputedStyle(document.documentElement).getPropertyValue("--teal").trim()')=='#82bafa';dismiss(page);page.screenshot(path=str(OUT/'design-dark.png'),full_page=True);ok('Dark Explorer uses the coordinated blue/slate palette rather than legacy teal overrides')
  action(page,'ex-menu','[data-menu=View]');action(page,'toggle-theme');action(page,'clear-selection');sizes=[]
  for width,height in [(320,740),(390,844),(600,900),(740,390),(1024,768),(1600,1000)]:
   page.set_viewport_size({'width':width,'height':height});page.wait_for_timeout(120);sizes.append({'width':width,'height':height,'contentWidth':page.locator('#content').evaluate('(e)=>e.scrollWidth')});assert sizes[-1]['contentWidth']<=width+1
   if width<=780:assert page.locator('.ex-mobile-commandbar').is_visible();assert page.locator('.mobile-bottom-nav').is_visible();assert page.locator('.mobile-file-card').count()==15
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(140);dismiss(page);page.screenshot(path=str(OUT/'design-phone.png'),full_page=True);action(page,'ex-menu','[data-menu=View]');assert d(page).locator('[data-action=ex-appearance]').count()==1;d(page).locator('[data-action=ex-appearance]').click();page.wait_for_timeout(80);assert d(page).locator('[data-appearance-preset=explorer]').is_visible();close(page);ok('Responsive layouts retain cards, bottom navigation and visible appearance controls at phone and tablet widths')
  page.set_viewport_size({'width':1024,'height':768});page.wait_for_timeout(100);action(page,'ex-menu','[data-menu=View]');action(page,'mobile-preferences');d(page).locator('[name=inputMode]').select_option('touch');submit(page);assert page.locator('.ex-standard-tool').first.bounding_box()['height']>=44;assert page.locator('[data-ex-row]').first.bounding_box()['height']>=44;assert page.locator('.ex-tree-item').first.bounding_box()['height']>=44;dismiss(page);page.screenshot(path=str(OUT/'design-tablet.png'),full_page=True);ok('Explicit touch sizing overrides compact presentation on a hybrid desktop viewport')
  assert not errors,errors;ok('Explorer design regression suite completes without uncaught application errors')
 except Exception:
  print('ERRORS',errors,flush=True);page.screenshot(path=str(OUT/'design-failure.png'),full_page=True);raise
 finally:
  (OUT/'explorer-design-ui.json').write_text(json.dumps({'version':'0.8.0','mode':'actual MemoryRepository and command engine; opaque-origin UI; explicit localStorage preference fixture','results':results,'errors':errors},indent=2));browser.close()
