import test from 'node:test';
import assert from 'node:assert/strict';
import {fixture} from './support.mjs';
import {applyCommand,previewDocumentMove,validateWorkspace,currentVersion} from '../packages/core/index.js';
import {projectWorkspace} from '../packages/access/index.js';
import {defaultExplorerView,normalizeExplorerView,queryExplorer,explorerValue,explorerColumns,explorerCan,visibleExplorerViews,visibleExplorerBookmarks,explorerSelection,ExplorerHistory,explorerLink,resolveExplorerLink,validateExplorerState} from '../packages/explorer/index.js';
const view=f=>defaultExplorerView(f.project);
const save=(f,extra={},actor='u-admin')=>f.run('explorerView.save',{name:'Current delivery',scope:'personal',config:view(f),...extra},actor);

test('Explorer default configuration is deterministic and independently normalized',()=>{const a=defaultExplorerView('p');const b=normalizeExplorerView(a);assert.deepEqual(a,b);b.columns.push('title');assert.ok(!a.columns.includes('title'));assert.deepEqual(defaultExplorerView().columns,['name','number','state','revision','discipline','modifiedAt']);});
for(const [label,patch] of [
 ['missing filename column',{columns:['title']}],['duplicate columns',{columns:['name','name']}],['unknown columns',{columns:['name','eval']}],['prototype metadata key',{columns:['name','metadata.constructor']}],['duplicate sort',{sort:[{key:'name',direction:'asc'},{key:'name',direction:'desc'}]}],['invalid direction',{sort:[{key:'name',direction:'sideways'}]}],['large page',{pageSize:10000}],['invalid grouping',{groupBy:'__proto__'}],['excessive width',{widths:{name:901}}],['invalid filter operation',{filters:[{key:'name',op:'regex',value:'.*'}]}],['object literal',{filters:[{key:'name',op:'eq',value:{}}]}],['infinite number',{filters:[{key:'size',op:'eq',value:Infinity}]}],['empty numeric condition',{filters:[{key:'size',op:'gt',value:''}]}],['invalid date',{filters:[{key:'modifiedAt',op:'gt',value:'2026-02-30'}]}],['invalid range literal',{filters:[{key:'size',op:'lt',value:'one'}]}],['too many filters',{filters:Array.from({length:21},()=>({key:'name',op:'contains',value:'x'}))}],['unknown quick filter',{quickFilters:{admin:'true'}}],['invalid saved column filter',{columnFilters:{unknown:'x'}}]
])test('Explorer rejects '+label,()=>assert.throws(()=>normalizeExplorerView({...defaultExplorerView('p'),...patch})));

test('Metadata queries are literal, permission filtered and non-mutating',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);const original=structuredClone(f.state);const result=queryExplorer(f.state,f.viewer,view(f));assert.equal(result.total,1);assert.equal(result.items[0].id,f.doc);assert.deepEqual(f.state,original);assert.deepEqual(queryExplorer(f.state,f.viewer,{...view(f),query:'.*'}).items,[]);assert.equal(queryExplorer(f.state,f.viewer,{...view(f),query:'ORIGINAL'}).total,0);});
test('Query redacts hidden ancestor names and referenced document identifiers before searching',async()=>{const f=await fixture();f.grant('document',f.doc,'user:'+f.viewer,['read']);const hidden=await f.add('hidden-reference.txt');f.run('document.references',{id:f.doc,references:[hidden]});const out=queryExplorer(f.state,f.viewer,view(f));assert.equal(out.total,1);assert.ok(!JSON.stringify(out).includes(hidden));assert.equal(queryExplorer(f.state,f.viewer,{...view(f),filters:[{key:'folder',op:'contains',value:'Design'}]}).total,0);});
test('Full and permission-projected query results agree for a directly shared document',async()=>{const f=await fixture();f.grant('document',f.doc,'user:'+f.viewer,['read']);const projection=projectWorkspace(f.state,f.viewer);assert.deepEqual(queryExplorer(f.state,f.viewer,view(f)),queryExplorer(projection,f.viewer,view(f)));assert.ok(projection.folders.every(x=>Array.isArray(x.permissions)));assert.equal(explorerCan(projection,f.viewer,'read','document',f.doc),true);assert.equal(explorerCan(projection,f.author,'read','document',f.doc),false);});
test('Membership disable and another projected identity fail closed',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);f.run('user.update',{id:f.viewer,active:false});assert.throws(()=>queryExplorer(f.state,f.viewer,view(f)),/disabled/);});
test('Folder queries distinguish direct children, recursive contents and project root',async()=>{const f=await fixture(),sub=await f.add('nested.txt',{folderId:f.subfolder}),root=await f.add('root.txt',{folderId:null});assert.deepEqual(queryExplorer(f.state,'u-admin',{...view(f),folderId:f.folder,includeSubfolders:false}).ids,[f.doc]);assert.equal(queryExplorer(f.state,'u-admin',{...view(f),folderId:f.folder}).total,2);assert.deepEqual(queryExplorer(f.state,'u-admin',{...view(f),includeSubfolders:false}).ids,[root]);assert.deepEqual(queryExplorer(f.state,'u-admin',{...view(f),rootOnly:true}).ids,[root]);assert.equal(queryExplorer(f.state,'u-admin',view(f)).total,3);});
test('Natural order, numeric size and stable secondary sorting operate across pages',async()=>{const f=await fixture();const ten=await f.add('Drawing10.txt'),two=await f.add('Drawing2.txt');const out=queryExplorer(f.state,'u-admin',view(f),{offset:1,limit:1});assert.equal(out.total,3);assert.equal(out.items[0].id,two);assert.equal(queryExplorer(f.state,'u-admin',{...view(f),sort:[{key:'name',direction:'desc'}]}).items[0].id,ten);assert.throws(()=>queryExplorer(f.state,'u-admin',view(f),{limit:501}));assert.throws(()=>queryExplorer(f.state,'u-admin',view(f),{offset:-1}));});
test('Advanced OR filters remain intersected with quick and column filters',async()=>{const f=await fixture();await f.add('steel.txt',{discipline:'Structures'});await f.add('wall.txt',{discipline:'Architecture'});const config={...view(f),match:'any',filters:[{key:'name',op:'contains',value:'steel'},{key:'name',op:'contains',value:'wall'}],quickFilters:{discipline:'Structures',state:''},columnFilters:{name:'STEEL'}};assert.equal(queryExplorer(f.state,'u-admin',config).total,1);assert.equal(normalizeExplorerView(config).quickFilters.discipline,'Structures');});
test('Range, boolean, empty and metadata comparisons retain explicit meanings',async()=>{const f=await fixture();f.run('document.update',{id:f.doc,metadata:{zone:'Area 07'}});const q=filters=>queryExplorer(f.state,'u-admin',{...view(f),filters}).total;assert.equal(q([{key:'metadata.zone',op:'eq',value:'area 07'}]),1);assert.equal(q([{key:'metadata.missing',op:'empty'}]),1);assert.equal(q([{key:'metadata.zone',op:'notEmpty'}]),1);assert.equal(q([{key:'metadata.zone',op:'startsWith',value:'area'}]),1);assert.equal(q([{key:'size',op:'gt',value:2}]),1);assert.equal(q([{key:'size',op:'lte',value:2}]),0);assert.equal(q([{key:'metadata.zone',op:'ne',value:'area 07'}]),0);assert.equal(q([{key:'name',op:'notContains',value:'secret'}]),1);});
test('Grouping counts never include unreadable or recycled documents',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);const secret=await f.add('hidden.txt',{discipline:'Secret'}),trash=await f.add('trash.txt');f.grant('document',secret,'user:'+f.viewer,[],['read']);f.run('document.delete',{id:trash});const out=queryExplorer(f.state,f.viewer,{...view(f),groupBy:'discipline'},{limit:1});assert.equal(out.total,1);assert.equal(out.groups.reduce((n,g)=>n+g.count,0),1);assert.ok(!JSON.stringify(out).includes('Secret'));});
test('Read-only users can save personal configurations but cannot publish project views',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);const id=save(f,{},f.viewer);assert.equal(visibleExplorerViews(f.state,f.viewer)[0].id,id);assert.equal(visibleExplorerViews(f.state,'u-admin').length,0);assert.throws(()=>save(f,{name:'Shared',scope:'project'},f.viewer),/permission|Access|manager/i);});
test('Shared views require management and remain access-filtered on revocation',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.manager);const id=save(f,{scope:'project'},f.manager);assert.equal(visibleExplorerViews(f.state,'u-admin').length,1);assert.equal(visibleExplorerViews(f.state,f.viewer).length,0);f.grant('project',f.project,'user:'+f.viewer,['read']);assert.equal(visibleExplorerViews(f.state,f.viewer)[0].id,id);assert.equal(projectWorkspace(f.state,f.viewer).explorerViews.length,1);f.grant('project',f.project,'user:'+f.viewer,[],['read']);assert.equal(projectWorkspace(f.state,f.viewer).explorerViews.length,0);});
test('Saved views enforce owner, exact version, visibility and case-insensitive name uniqueness',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);const id=save(f,{},f.viewer);assert.throws(()=>save(f,{id,expectedVersion:1,name:'stolen'}),/belongs/);assert.throws(()=>save(f,{name:'CURRENT DELIVERY'},f.viewer),/already exists/);assert.throws(()=>save(f,{id,expectedVersion:0,name:'updated'},f.viewer),/changed/);save(f,{id,expectedVersion:1,name:'Updated'},f.viewer);assert.equal(f.state.explorerViews[0].version,2);assert.throws(()=>f.run('explorerView.remove',{id,expectedVersion:1},f.viewer),/changed/);assert.throws(()=>f.run('explorerView.remove',{id,expectedVersion:2}),/cannot/);f.run('explorerView.remove',{id,expectedVersion:2},f.viewer);assert.equal(f.state.explorerViews.length,0);});
test('Saved folder views and pins do not grant ancestor or sibling access',async()=>{const f=await fixture();f.grant('document',f.doc,'user:'+f.viewer,['read']);assert.throws(()=>save(f,{config:{...view(f),folderId:f.folder}},f.viewer));f.run('explorerBookmark.toggle',{scope:'document',resourceId:f.doc},f.viewer);const pins=visibleExplorerBookmarks(f.state,f.viewer);assert.equal(pins.length,1);assert.equal(Object.hasOwn(pins[0],'name'),false);assert.equal(visibleExplorerBookmarks(f.state,'u-admin').length,0);assert.throws(()=>f.run('explorerBookmark.toggle',{scope:'folder',resourceId:f.folder},f.viewer));});
test('Users may remove their personal view and pin after access is revoked',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);const id=save(f,{},f.viewer);f.run('explorerBookmark.toggle',{scope:'document',resourceId:f.doc},f.viewer);f.grant('project',f.project,'user:'+f.viewer,[],['read']);assert.equal(visibleExplorerBookmarks(f.state,f.viewer).length,0);assert.equal(visibleExplorerViews(f.state,f.viewer).length,0);f.run('explorerView.remove',{id,expectedVersion:1},f.viewer);assert.equal(f.run('explorerBookmark.toggle',{scope:'document',resourceId:f.doc},f.viewer),false);});
test('Folder deletion cleans scoped views and pins without orphaning the state',async()=>{const f=await fixture();save(f,{config:{...view(f),folderId:f.subfolder}});f.run('explorerBookmark.toggle',{scope:'folder',resourceId:f.subfolder});f.run('folder.delete',{id:f.subfolder});assert.equal(f.state.explorerViews.length,0);assert.equal(f.state.explorerBookmarks.length,0);validateWorkspace(f.state);});
test('Imported collections reject unknown targets, duplicate names, malformed configurations and excessive counts',async()=>{const f=await fixture();save(f);for(const edit of [s=>s.explorerViews[0].id='',s=>s.explorerViews[0].version=0,s=>s.explorerViews[0].config.columns=['name','constructor'],s=>s.explorerViews.push({...s.explorerViews[0],id:'second'}),s=>s.explorerBookmarks=[{id:'pin',scope:'folder',resourceId:'missing',userId:'u-admin',createdAt:new Date().toISOString()}],s=>s.explorerViews=Array.from({length:101},(_,i)=>({...s.explorerViews[0],id:'view'+i,name:'View '+i}))]){const state=structuredClone(f.state);edit(state);assert.throws(()=>validateExplorerState(state));}});
test('Older workspaces without Explorer collections remain readable',async()=>{const f=await fixture();delete f.state.explorerViews;delete f.state.explorerBookmarks;assert.doesNotThrow(()=>validateWorkspace(f.state));save(f);assert.equal(f.state.explorerViews.length,1);});
test('Atomic move preview is side-effect free and commits one revision and one audit event',async()=>{const f=await fixture(),second=await f.add('second.txt'),before=structuredClone(f.state),preview=previewDocumentMove(f.state,'u-admin',{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc,second]});assert.deepEqual(f.state,before);assert.equal(preview.allowed,true);const out=f.run('document.bulkMove',preview.payload);assert.equal(out.moved.length,2);assert.equal(f.state.revision,before.revision+1);assert.equal(f.state.audit.length,before.audit.length+1);for(const id of out.moved){assert.equal(f.state.documents.find(x=>x.id===id).folderId,f.subfolder);assert.deepEqual(f.state.documents.find(x=>x.id===id).versions,before.documents.find(x=>x.id===id).versions);}});
test('Atomic moves enforce every source and destination access rule',async()=>{const f=await fixture(),second=await f.add('other.txt');f.grant('project',f.project,'user:'+f.author);f.grant('document',second,'user:'+f.author,[],['write']);const before=structuredClone(f.state);assert.throws(()=>previewDocumentMove(f.state,f.author,{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc,second]}),/permit|permission/i);assert.deepEqual(f.state,before);f.grant('folder',f.subfolder,'user:'+f.author,[],['write']);assert.throws(()=>previewDocumentMove(f.state,f.author,{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc]}),/permit|permission/i);});
test('A late duplicate name rolls back the entire move rather than moving a prefix',async()=>{const f=await fixture(),second=await f.add('collision.txt');await f.add('collision.txt',{folderId:f.subfolder});const before=structuredClone(f.state);assert.throws(()=>previewDocumentMove(f.state,'u-admin',{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc,second]}),/exists/i);assert.deepEqual(f.state,before);});
test('Checkout locks, legal holds and archived state block bulk moves',async()=>{for(const kind of ['lock','hold','archived']){const f=await fixture();if(kind==='lock'){f.grant('project',f.project,'user:'+f.author);f.run('document.checkout',{id:f.doc},f.author);}if(kind==='hold')f.run('document.retention',{id:f.doc,legalHold:true});if(kind==='archived'){f.state.documents.find(d=>d.id===f.doc).state='Archived';}assert.throws(()=>previewDocumentMove(f.state,'u-admin',{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc]}));}});
test('Stale workspace, file revision, source folder and duplicate identities invalidate move commit',async()=>{for(const kind of ['revision','file','folder','duplicate']){const f=await fixture(),preview=previewDocumentMove(f.state,'u-admin',{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc]});if(kind==='revision')f.run('document.update',{id:f.doc,title:'Changed after preview'});if(kind==='file')preview.payload.items[0].versionId='no-such-version';if(kind==='folder')preview.payload.items[0].folderId=null;if(kind==='duplicate')preview.payload.items.push({...preview.payload.items[0]});const before=structuredClone(f.state);assert.throws(()=>f.run('document.bulkMove',preview.payload));assert.deepEqual(f.state,before);}});
test('Moves reject cross-project destinations, no-ops and oversized batches',async()=>{const f=await fixture(),other=f.run('folder.create',{projectId:f.other,name:'Elsewhere'});for(const payload of [{folderId:other,documentIds:[f.doc]},{folderId:f.folder,documentIds:[f.doc]},{folderId:f.subfolder,documentIds:Array(101).fill(f.doc)},{folderId:f.subfolder,documentIds:[]}])assert.throws(()=>previewDocumentMove(f.state,'u-admin',{projectId:f.project,...payload}));});
test('Selection ranges, additive toggles and anchors are side-effect free',()=>{const ids=['a','b','c','d'],original=new Set(['a']);let out=explorerSelection(ids,original,'c',{range:true,anchor:'a'});assert.deepEqual([...out.selection],['a','b','c']);assert.deepEqual([...original],['a']);out=explorerSelection(ids,out.selection,'b',{toggle:true});assert.deepEqual([...out.selection],['a','c']);assert.throws(()=>explorerSelection(ids,original,'missing'));});
test('Navigation history bounds entries, clones values and discards a forward branch',()=>{const h=new ExplorerHistory(3);h.visit({folder:'a'});h.visit({folder:'b'});h.visit({folder:'c'});assert.equal(h.back().folder,'b');h.visit({folder:'d'});assert.equal(h.canForward,false);h.visit({folder:'e'});assert.equal(h.items.length,3);const current=h.current;current.folder='changed';assert.equal(h.current.folder,'e');h.back();assert.equal(h.back().folder,'b');});
test('Stable links survive file renames and folder moves while enforcing permissions and workspace identity',async()=>{const f=await fixture();f.grant('document',f.doc,'user:'+f.viewer,['read']);const link=explorerLink(f.state,{projectId:f.project,folderId:f.folder,documentId:f.doc});assert.ok(!link.includes('a.txt'));assert.equal(resolveExplorerLink(f.state,f.viewer,link).documentId,f.doc);f.run('document.move',{id:f.doc,folderId:f.subfolder});f.run('document.update',{id:f.doc,name:'renamed.txt'});assert.equal(resolveExplorerLink(f.state,f.viewer,link).folderId,f.subfolder);assert.throws(()=>resolveExplorerLink(f.state,f.author,link));assert.throws(()=>resolveExplorerLink(f.state,'u-admin',link.replace(f.state.id,'wrong-workspace')));f.grant('document',f.doc,'user:'+f.viewer,[],['read']);assert.throws(()=>resolveExplorerLink(f.state,f.viewer,link));});
test('Directly shared folder links can open without disclosing project details',async()=>{const f=await fixture();f.grant('folder',f.folder,'user:'+f.viewer,['read']);const target=resolveExplorerLink(projectWorkspace(f.state,f.viewer),f.viewer,explorerLink(f.state,{projectId:f.project,folderId:f.folder}));assert.equal(target.folderId,f.folder);});
test('Column getters retain original revision bytes and resolve current membership names',async()=>{const f=await fixture(),d=f.state.documents.find(x=>x.id===f.doc);assert.equal(explorerValue(f.state,d,'size'),currentVersion(d).size);assert.equal(explorerValue(f.state,d,'filetype'),'TXT');assert.equal(explorerValue(f.state,d,'folder'),'Design');assert.equal(explorerValue(f.state,d,'revision'),'P01');assert.ok(explorerColumns(f.state.projects[0]).some(c=>c.key==='metadata.zone'));});
test('Bulk moves deliver one notification per document, including former-folder watchers, without inner transaction duplicates',async()=>{const f=await fixture();f.grant('project',f.project,'user:'+f.viewer,['read']);f.run('subscription.save',{scope:'folder',resourceId:f.folder,events:['document.moved']},f.viewer);f.run('subscription.save',{scope:'document',resourceId:f.doc,events:['document.moved']},f.viewer);const second=await f.add('second.txt');const preview=previewDocumentMove(f.state,'u-admin',{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc,second]});f.run('document.bulkMove',preview.payload);const out=f.state.notifications.filter(n=>n.userId===f.viewer&&n.event==='document.moved');assert.equal(out.length,2);assert.deepEqual(new Set(out.map(n=>n.resourceId)),new Set([f.doc,second]));});
test('A source-folder move notification cannot leak a document after destination access is denied',async()=>{const f=await fixture();f.grant('folder',f.folder,'user:'+f.viewer,['read']);f.run('subscription.save',{scope:'folder',resourceId:f.folder,events:['document.moved']},f.viewer);f.grant('folder',f.subfolder,'user:'+f.viewer,[],['read']);f.run('document.bulkMove',previewDocumentMove(f.state,'u-admin',{projectId:f.project,folderId:f.subfolder,documentIds:[f.doc]}).payload);assert.equal(f.state.notifications.filter(n=>n.userId===f.viewer&&n.event==='document.moved').length,0);});
