import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
import {createHash} from 'node:crypto';
import {defaultExplorerView} from '../packages/explorer/index.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function unusedPort(){const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));return port;}
test('Explorer integration over authenticated HTTP and persistent SQLite',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'civora-explorer-')),origin=`http://127.0.0.1:${await unusedPort()}`,password='explorer-test-unique-local-password';let child,logs='',admin='',authorCookie='',viewerCookie='',state,project,folder,target,doc,other,secret,author,viewer,shared,pin,viewId;
 const request=async(path,{method='GET',body,cookie=admin,requestOrigin=origin}={})=>{const response=await fetch(origin+path,{method,headers:{Cookie:cookie,...(method!=='GET'?{Origin:requestOrigin,'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return {status:response.status,headers:response.headers,data:(response.headers.get('content-type')||'').includes('application/json')?await response.json():await response.text()};};
 const refresh=async()=>{const out=await request('/api/workspace');assert.equal(out.status,200);state=out.data.state;return state;};
 const command=async(type,payload,{cookie=admin,expectedRevision=state.revision,file}={})=>request('/api/commands',{method:'POST',cookie,body:{expectedRevision,command:{type,payload},...(file?{file}:{})}});
 const run=async(type,payload,options)=>{const out=await command(type,payload,options);assert.equal(out.status,200,`${type}: ${JSON.stringify(out.data)}`);await refresh();return out.data.result;};
 const query=(view=defaultExplorerView(project),options={},cookie=admin,expectedRevision=state.revision)=>request('/api/explorer/query',{method:'POST',cookie,body:{expectedRevision,view,options}});
 const preview=(documentIds=[doc],folderId=target,cookie=admin,expectedRevision=state.revision)=>request('/api/explorer/move-preview',{method:'POST',cookie,body:{expectedRevision,projectId:project,folderId,documentIds}});
 async function add(name,folderId=folder){const bytes=Buffer.from('Original exact bytes: '+name+'\n'),hash=createHash('sha256').update(bytes).digest('hex');return run('document.create',{projectId:project,folderId,name,file:{hash,blobId:hash,size:bytes.length,mime:'text/plain'}},{file:{data:bytes.toString('base64'),mime:'text/plain'}});}
 async function start(){child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:new URL(origin).port,HOST:'127.0.0.1',CIVORA_PUBLIC_ORIGIN:origin,CIVORA_DATA_DIR:dir,CIVORA_ADMIN_PASSWORD:password,CIVORA_DB:'sqlite',CIVORA_AUTO_RENDITIONS:'0',CIVORA_SEED_DEMO:'0',CIVORA_AUTOMATION:'0'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);for(let i=0;i<200;i++){try{if((await request('/api/health')).status===200)return;}catch{}if(child.exitCode!==null)throw new Error(logs);await delay(30);}throw new Error(logs);}
 async function stop(){if(child?.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await done;}}
 async function login(email){const out=await request('/api/login',{method:'POST',cookie:'',body:{email,password}});assert.equal(out.status,200);return out.headers.get('set-cookie').split(';')[0];}
 try{await start();admin=await login('admin@civora.local');await refresh();
  await t.test('both Explorer endpoints require authentication and same-origin writes',async()=>{for(const path of ['/api/explorer/query','/api/explorer/move-preview']){assert.equal((await request(path,{method:'POST',cookie:'',body:{}})).status,401);assert.equal((await request(path,{method:'POST',requestOrigin:'https://untrusted.invalid',body:{}})).status,403);}project=await run('project.create',{name:'Explorer integration',code:'EXP'});folder=await run('folder.create',{projectId:project,name:'Design'});target=await run('folder.create',{projectId:project,name:'Delivery'});doc=await add('Drawing2.txt');other=await add('Drawing10.txt');secret=await add('restricted.txt');author=await run('user.create',{name:'Scoped Author',email:'author@explorer.test',role:'author'});viewer=await run('user.create',{name:'Scoped Viewer',email:'viewer@explorer.test',role:'viewer'});await run('access.set',{scope:'project',resourceId:project,inherit:true,entries:[{principal:'user:'+author,allow:['read','download','write'],deny:[]},{principal:'user:'+viewer,allow:['read'],deny:[]}]});await run('access.set',{scope:'document',resourceId:secret,inherit:true,entries:[{principal:'user:'+viewer,allow:[],deny:['read']},{principal:'user:'+author,allow:[],deny:['write']}]});for(const userId of [author,viewer])assert.equal((await request('/api/admin/password',{method:'POST',body:{userId,password}})).status,200);authorCookie=await login('author@explorer.test');viewerCookie=await login('viewer@explorer.test');});
  await t.test('ACL filtering precedes pagination, grouping, counts and output',async()=>{const config={...defaultExplorerView(project),groupBy:'discipline'},out=await query(config,{limit:1},viewerCookie);assert.equal(out.status,200);assert.equal(out.data.total,2);assert.equal(out.data.items[0].id,doc);assert.equal(out.data.nextOffset,1);assert.equal(out.data.groups[0].count,2);assert.ok(!JSON.stringify(out.data).includes(secret));assert.ok(!Object.hasOwn(out.data,'ids'));assert.ok(out.data.items.every(d=>d.permissions.includes('read')&&!d.permissions.includes('download')));const next=await query(config,{offset:out.data.nextOffset,limit:1},viewerCookie);assert.equal(next.data.items[0].id,other);assert.equal(next.data.nextOffset,null);});
  await t.test('pagination requires current revision and bounded declarative inputs',async()=>{const revision=state.revision;await run('document.update',{id:doc,title:'A later title'});assert.equal((await query(defaultExplorerView(project),{},viewerCookie,revision)).status,409);for(const options of [{limit:501},{offset:-1},null])assert.equal((await query(defaultExplorerView(project),options)).status,400);const invalid={...defaultExplorerView(project),filters:[{key:'name',op:'eval',value:'process.exit()'}]};assert.equal((await query(invalid)).status,400);});
  await t.test('members save personal views, managers share configurations, no view grants access',async()=>{viewId=await run('explorerView.save',{name:'My drawings',scope:'personal',config:defaultExplorerView(project)},{cookie:viewerCookie});shared=await run('explorerView.save',{name:'Delivery register',scope:'project',config:{...defaultExplorerView(project),columns:['name','title','revision'],columnFilters:{name:'Drawing'}}});const visible=(await request('/api/workspace',{cookie:viewerCookie})).data.state;assert.equal(visible.explorerViews.length,2);assert.equal((await command('explorerView.save',{name:'Unauthorized shared',scope:'project',config:defaultExplorerView(project)},{cookie:viewerCookie})).status,403);assert.equal((await command('explorerView.remove',{id:viewId,expectedVersion:1})).status,403);const config=visible.explorerViews.find(v=>v.id===shared).config;assert.equal((await query(config,{},viewerCookie)).data.total,2);});
  await t.test('personal pins retain identifiers only and obey inbox-style account isolation',async()=>{await run('explorerBookmark.toggle',{scope:'document',resourceId:doc},{cookie:viewerCookie});const v=(await request('/api/workspace',{cookie:viewerCookie})).data.state;pin=v.explorerBookmarks[0];assert.equal(pin.resourceId,doc);assert.equal(pin.userId,viewer);assert.ok(!Object.hasOwn(pin,'name'));assert.equal((await request('/api/workspace',{cookie:authorCookie})).data.state.explorerBookmarks.length,0);assert.equal((await command('explorerBookmark.toggle',{scope:'document',resourceId:secret},{cookie:viewerCookie})).status,403);});
  await t.test('move preview uses authoritative state and has no metadata or blob side effects',async()=>{const original=structuredClone(state),out=await preview([doc,other],target,authorCookie);assert.equal(out.status,200);assert.equal(out.data.allowed,true);assert.equal(out.data.sourceRevision,original.revision);assert.equal(out.data.payload.items.length,2);await refresh();assert.deepEqual(state,original);const denied=await preview([doc,secret],target,authorCookie);assert.equal(denied.status,200);assert.equal(denied.data.allowed,false);assert.equal(denied.data.code,'FORBIDDEN');assert.equal((await preview([doc],target,viewerCookie)).data.allowed,false);});
  await t.test('stale previews and an unauthorized second row cannot partially move documents',async()=>{const out=await preview([doc,other],target,authorCookie);await run('document.update',{id:doc,title:'Changed after preview'});const before=structuredClone(state);assert.equal((await command('document.bulkMove',out.data.payload,{cookie:authorCookie})).status,409);await refresh();assert.deepEqual(state,before);const payload={projectId:project,folderId:target,baseRevision:state.revision,items:[doc,secret].map(id=>{const d=state.documents.find(x=>x.id===id);return{id,versionId:d.versions.at(-1).id,folderId:d.folderId};})};assert.equal((await command('document.bulkMove',payload,{cookie:authorCookie})).status,403);await refresh();assert.deepEqual(state,before);});
  await t.test('successful batch produces one revision and preserves exact downloadable originals',async()=>{const out=await preview([doc,other],target,authorCookie),before=structuredClone(state),hash=state.documents.find(d=>d.id===doc).versions.at(-1).blobId;const moved=await run('document.bulkMove',out.data.payload,{cookie:authorCookie});assert.deepEqual(new Set(moved.moved),new Set([doc,other]));assert.equal(state.revision,before.revision+1);assert.equal(state.audit.length,before.audit.length+1);for(const id of moved.moved){const d=state.documents.find(d=>d.id===id);assert.equal(d.folderId,target);assert.deepEqual(d.versions,before.documents.find(d=>d.id===id).versions);}const blob=await request('/api/blobs/'+hash,{cookie:authorCookie});assert.equal(blob.status,200);assert.equal(blob.data,'Original exact bytes: Drawing2.txt\n');assert.equal((await request('/api/blobs/'+hash,{cookie:viewerCookie})).status,404);});
  await t.test('name conflicts, checkout locks and revocation reject preflight without partial writes',async()=>{await run('access.set',{scope:'document',secret,resourceId:secret,inherit:true,entries:[]});const collision=await add('Drawing2.txt',folder);const before=structuredClone(state);assert.equal((await preview([collision],target)).data.allowed,false);await refresh();assert.deepEqual(state,before);await run('document.checkout',{id:other},{cookie:authorCookie});const locked=await preview([other],folder);assert.equal(locked.data.allowed,false);await run('document.release',{id:other},{cookie:authorCookie});});
  await t.test('revoked project access removes shared and personal views, pins and query results',async()=>{await run('access.set',{scope:'project',resourceId:project,inherit:true,entries:[{principal:'user:'+viewer,allow:[],deny:['read']},{principal:'user:'+author,allow:['read','write','download'],deny:[]}]});const out=(await request('/api/workspace',{cookie:viewerCookie})).data.state;assert.equal(out.explorerViews.length,0);assert.equal(out.explorerBookmarks.length,0);assert.equal((await query(defaultExplorerView(project),{},viewerCookie)).status,404);await run('explorerView.remove',{id:viewId,expectedVersion:1},{cookie:viewerCookie});await run('explorerBookmark.toggle',{scope:'document',resourceId:doc},{cookie:viewerCookie});});
  await t.test('saved views, move results and source bytes persist across a real process restart',async()=>{const revision=state.revision;await stop();await start();admin=await login('admin@civora.local');await refresh();assert.equal(state.revision,revision);assert.equal(state.explorerViews.find(v=>v.id===shared).config.columnFilters.name,'Drawing');assert.equal(state.documents.find(d=>d.id===doc).folderId,target);const out=await query(state.explorerViews.find(v=>v.id===shared).config);assert.equal(out.status,200);assert.equal(out.data.total,3);});
 }finally{await stop();await rm(dir,{recursive:true,force:true});}
});
