import test from 'node:test';import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';import {createServer} from 'node:http';
import {migrateExplorerPreferences,EXPLORER_PREFERENCE_SCHEMA,explorerDetailView} from '../packages/explorer/index.js';
import {readReleaseManifest,classifyRelease,createAppUpdates} from '../app/updates.js';
import {serveStatic} from '../scripts/static.mjs';
const current={version:'0.8.1',build:'a'.repeat(20)};
const legacy={config:{...explorerDetailView('p'),query:'bridge',density:'comfortable'},layout:{commandStyle:'ribbon',navigationRail:true,fileDescriptions:true,rowLines:false,treeWidth:320,previewPosition:'right',previewWidth:425,columnFilters:true},expanded:['p','f'],recents:['d']};
test('Old appearance migrates once, retaining queries, widths and pane',()=>{
 const input=structuredClone(legacy),prefs=migrateExplorerPreferences(input,'p');assert.deepEqual(input,legacy);assert.equal(prefs.schema,EXPLORER_PREFERENCE_SCHEMA);assert.equal(prefs.layout.commandStyle,'standard');assert.equal(prefs.layout.navigationRail,false);assert.equal(prefs.layout.fileDescriptions,false);assert.equal(prefs.layout.treeWidth,320);assert.equal(prefs.layout.previewWidth,425);assert.equal(prefs.layout.previewPosition,'right');assert.equal(prefs.config.query,'bridge');assert.equal(prefs.config.density,'comfortable');assert.deepEqual(prefs.expanded,['p','f']);
});
test('Explicit Ribbon/Review choices survive reload after migration',()=>{const prefs=migrateExplorerPreferences(legacy,'p');prefs.layout.commandStyle='ribbon';prefs.layout.navigationRail=true;assert.deepEqual(migrateExplorerPreferences(prefs,'p'),prefs);});
test('Malformed or obsolete preferences cannot restore old chrome',()=>{for(const input of [null,[],true,7,'ribbon',{schema:0,...legacy},{schema:99,...legacy}])assert.equal(migrateExplorerPreferences(input,'p').layout.commandStyle,'standard');const prefs=migrateExplorerPreferences({expanded:['a','a',null,3,'x'.repeat(501)],recents:[true,'d','d'],config:{columns:['invalid']}},'p');assert.deepEqual(prefs.expanded,['a']);assert.deepEqual(prefs.recents,['d']);});
test('Presentation migration is idempotent and contains no workspace writes',()=>{const prefs=migrateExplorerPreferences(legacy,'p');assert.deepEqual(migrateExplorerPreferences(prefs,'p'),prefs);assert.deepEqual(Object.keys(prefs).sort(),['schema','layout','config','expanded','recents'].sort());});
test('Release checks bypass HTTP cache and validate bounded metadata',async()=>{let options;const remote=await readReleaseManifest(async(_,o)=>{options=o;return Response.json({format:'civora-release',...current});},'test');assert.deepEqual(remote,current);assert.equal(options.cache,'no-store');assert.equal(options.redirect,'error');for(const value of [{},{format:'civora-release',version:'<script>',build:'x'},{format:'civora-release',...current,build:'x'.repeat(5000)}])await assert.rejects(readReleaseManifest(async()=>Response.json(value),'test'));});
test('Build classification detects republished builds and older deployments',()=>{assert.equal(classifyRelease(current,current),'current');assert.equal(classifyRelease(current,{...current,build:'b'.repeat(20)}),'available');assert.equal(classifyRelease(current,{version:'0.8.0',build:'b'.repeat(20)}),'older');assert.equal(classifyRelease(current,{version:'0.9.0',build:'c'.repeat(20)}),'available');});
function environment(remote=current){let reloads=0,fetches=0;return {location:{protocol:'https:',href:'https://example.test/civora/',reload(){reloads++;}},fetch:async()=>{fetches++;return Response.json({format:'civora-release',...remote});},get reloads(){return reloads;},get fetches(){return fetches;}};}
test('Standalone builds never contact a server or silently reload',async()=>{const env=environment();env.__CIVORA_SINGLE_FILE__=true;const updates=createAppUpdates({...current,env});await updates.start();assert.equal(updates.status.kind,'standalone');assert.equal(env.fetches,0);await assert.rejects(updates.reload(),/standalone/);assert.equal(env.reloads,0);});
test('Detecting an available update does not reload the running UI',async()=>{const env=environment({version:'0.8.2',build:'b'.repeat(20)}),u=createAppUpdates({...current,env});await u.check();assert.equal(u.status.kind,'available');assert.equal(env.reloads,0);});
test('Update reload refuses temporary-memory sessions and open editing workflows',async()=>{const env=environment();for(const guard of [{volatile:()=>true},{canReload:()=>false}])await assert.rejects(createAppUpdates({...current,env,...guard}).reload());assert.equal(env.reloads,0);});
test('Reload rechecks activity after a delayed metadata response',async()=>{const env=environment();let open=false;env.fetch=async()=>{open=true;return Response.json({format:'civora-release',...current});};await assert.rejects(createAppUpdates({...current,env,canReload:()=>!open}).reload(),/activity changed/);assert.equal(env.reloads,0);});
test('Only an explicit safe reload navigates; no storage API is invoked',async()=>{const env=environment();assert.equal(await createAppUpdates({...current,env}).reload(),true);assert.equal(env.reloads,1);});
test('Unreachable or older deployments cannot trigger reloads',async()=>{for(const remote of [{version:'0.8.0',build:'b'.repeat(20)},null]){const env=environment(remote);if(!remote)env.fetch=async()=>{throw new Error('Offline');};await assert.rejects(createAppUpdates({...current,env}).reload());assert.equal(env.reloads,0);}});
test('All shipped HTML entries share the release ID without external CSS/JS dependencies',async()=>{const base=new URL('../',import.meta.url),m=JSON.parse(await readFile(new URL('release.json',base),'utf8'));for(const path of ['index.html','dist/civora.html','portal.html','dist/portal.html']){const html=await readFile(new URL(path,base),'utf8');assert.ok(html.includes(`<meta name="civora-build" content="${m.build}">`),path);assert.doesNotMatch(html,/<script[^>]+src=/);assert.doesNotMatch(html,/<link[^>]+rel="stylesheet"/);}assert.match(await readFile(new URL('index.html',base),'utf8'),/__CIVORA_SINGLE_FILE__ = false/);assert.match(await readFile(new URL('dist/civora.html',base),'utf8'),/__CIVORA_SINGLE_FILE__ = true/);});
test('Shell, release metadata and worker HTTP responses use no-store',async()=>{const server=createServer((q,r)=>serveStatic(q,r));await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const path of ['/','/index.html','/release.json','/sw.js','/dist/civora.html']){const response=await fetch(`http://127.0.0.1:${server.address().port}${path}`);assert.equal(response.status,200);assert.match(response.headers.get('cache-control'),/no-store/);assert.equal(response.headers.get('x-content-type-options'),'nosniff');await response.arrayBuffer();}}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}});

test('Queued commands remain observable until success without reordering',async()=>{
 const {WorkspaceEngine}=await import('../packages/storage/index.js');let release;const gate=new Promise(r=>release=r),order=[];
 const engine=new WorkspaceEngine({commit:async c=>{await gate;order.push(c.type);return {state:{revision:order.length},result:c.type};}},'u');engine.state={revision:0};
 const a=engine.run('first'),b=engine.run('second');assert.equal(engine.pending,2);release();assert.equal(await a,'first');assert.equal(await b,'second');assert.equal(engine.pending,0);assert.deepEqual(order,['first','second']);
});
test('Failed commands clear update busy state and do not block later commits',async()=>{
 const {WorkspaceEngine}=await import('../packages/storage/index.js');const engine=new WorkspaceEngine({commit:async c=>{if(c.type==='fail')throw new Error('denied');return {state:{revision:1},result:'ok'};}},'u');engine.state={revision:0};
 await assert.rejects(engine.run('fail'),/denied/);assert.equal(engine.pending,0);assert.equal(await engine.run('next'),'ok');assert.equal(engine.pending,0);
});
