import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,readFile,writeFile,mkdir,symlink,stat} from 'node:fs/promises';
import {tmpdir,hostname} from 'node:os';
import {join} from 'node:path';
import {createServer} from 'node:net';
import {request} from 'node:http';
import {createHash} from 'node:crypto';
import {HttpDirectoryFS} from '../packages/filesystem/index.js';
import {HttpRepository,WorkspaceEngine} from '../packages/storage/index.js';
import {WorkingCopyManager} from '../packages/filesystem/working-copies.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function raw(url,headers){return new Promise((resolve,reject)=>{const req=request(url,{headers},res=>{res.resume();res.on('end',()=>resolve(res.statusCode));});req.on('error',reject);req.end();});}
async function port(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
const sha=text=>createHash('sha256').update(text).digest('hex');
test('local companion: actual disk, authenticated HTTP, working copies, native allowlist and restart',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'civora-local-http-')),data=join(directory,'data'),working=join(directory,'working'),readonly=join(directory,'reference'),proof=join(directory,'launch-proof.json'),number=await port(),base=`http://127.0.0.1:${number}`,password='local-admin-test-password-234';
 await mkdir(working);await mkdir(readonly);await writeFile(join(readonly,'readme.txt'),'Reference original');
 const config=join(directory,'roots.json'),apps=join(directory,'apps.json'),script=join(directory,'native-fixture.mjs');
 await writeFile(config,JSON.stringify({version:1,roots:[{id:'working',label:'Native working files',path:working,userIds:['u-admin'],allowNativeOpen:true},{id:'reference',path:readonly,userIds:['u-admin'],readOnly:true}]}));
 await writeFile(script,`import {writeFileSync} from 'node:fs';writeFileSync(${JSON.stringify(proof)},JSON.stringify(process.argv.slice(2)));`);
 await writeFile(apps,JSON.stringify({version:1,applications:[{extensions:['.txt'],executable:process.execPath,args:[script,'{file}']}]}));
 let child,logs='',admin='',state,engine;
 const originalFetch=globalThis.fetch;
 async function api(path,{method='GET',body,cookie=admin,origin=base,headers={}}={}) { const response=await originalFetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(method!=='GET'?{Origin:origin,'Content-Type':'application/json'}:{}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});const bytes=Buffer.from(await response.arrayBuffer()),value=(response.headers.get('content-type')||'').includes('json')?JSON.parse(bytes):bytes;return {response,data:value}; }
 const post=(path,body,opts={})=>api(path,{method:'POST',body,...opts});
 async function start(extra=[]) { logs='';child=spawn(process.execPath,['scripts/local.mjs','--data',data,'--roots',config,'--applications',apps,'--port',String(number),...extra],{cwd:new URL('../',import.meta.url),env:{...process.env,CIVORA_ADMIN_PASSWORD:password,CIVORA_AUTO_RENDITIONS:'0',CIVORA_SEED_DEMO:'0'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);for(let n=0;n<150;n++){try{if((await api('/api/health',{cookie:''})).response.ok)return;}catch{}if(child.exitCode!==null)throw new Error(logs);await delay(25);}throw new Error('Local server startup timeout: '+logs); }
 async function stop() { engine?.close();engine=null;if(!child||child.exitCode!==null)return;const done=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await done; }
 async function login(){const r=await post('/api/login',{email:'admin@civora.local',password},{cookie:''});assert.equal(r.response.status,200,JSON.stringify(r.data));admin=r.response.headers.get('set-cookie').split(';')[0];state=(await api('/api/workspace')).data.state;}
 async function command(type,payload){const r=await post('/api/commands',{expectedRevision:state.revision,command:{type,payload}});assert.equal(r.response.status,200,JSON.stringify(r.data));state=r.data.state;return r.data.result;}
 const root='/api/local/roots/working';
 try{
 await start();
 await t.test('file bytes and configured root names require normal login',async()=>{for(const path of ['/api/local/status',root+'/list',root+'/file?path=a.txt'])assert.equal((await api(path,{cookie:''})).response.status,401);await login();const r=await api('/api/local/status');assert.equal(r.data.auth,'server-session');assert.equal(r.data.roots.length,2);assert.equal(r.data.roots[0].location,working);assert.equal(r.data.roots[0].native,true);assert.equal((await api('/app/local.js')).response.status,200);});
 await t.test('cross-site requests and DNS-rebinding Host values are rejected, including GET',async()=>{for(const headers of [{Origin:'https://evil.example'},{'Sec-Fetch-Site':'cross-site'},{Host:'evil.example'}])assert.equal(await raw(base+root+'/list',{Cookie:admin,...headers}),403,JSON.stringify(headers));assert.equal((await post(root+'/mkdir',{path:'bad'},{origin:'https://evil.example'})).response.status,403);});
 let fileInfo,trashId;
 await t.test('Unicode binary originals roundtrip, stale writes fail, and read-only roots reject mutation',async()=>{const path='設計/Żółć.bin',bytes=Buffer.from([0,1,255,128,32,254]);let r=await post(root+'/write',{path,data:bytes.toString('base64'),createOnly:true});assert.equal(r.response.status,200,JSON.stringify(r.data));fileInfo=r.data;assert.equal(r.data.hash,sha(bytes));assert.deepEqual((await api(root+'/file?path='+encodeURIComponent(path))).data,bytes);assert.equal((await post(root+'/write',{path,data:'YWJj',createOnly:true})).response.status,409);assert.equal((await post(root+'/write',{path,data:'YWJj',expectedHash:'0'.repeat(64)})).response.status,409);assert.equal((await post(root+'/write',{path:'bad',data:'===' ,createOnly:true})).response.status,400);assert.equal((await api('/api/local/roots/reference/file?path=readme.txt')).data.toString(),'Reference original');assert.equal((await post('/api/local/roots/reference/write',{path:'no.txt',data:'YQ==',createOnly:true})).response.status,403);});
 await t.test('large local uploads use bounded decoding without recursive-regex failure',async()=>{const bytes=Buffer.alloc(12*1024*1024,0xAD),r=await post(root+'/write',{path:'large.bin',data:bytes.toString('base64'),createOnly:true});assert.equal(r.response.status,200,JSON.stringify(r.data));assert.equal(r.data.hash,sha(bytes));assert.equal((await api(root+'/stat?path=large.bin')).data.size,bytes.length);});
 await t.test('traversal, symlinks, root lock and private account files cannot be read through the root',async()=>{await symlink(join(readonly,'readme.txt'),join(working,'escape'));for(const path of ['../data/accounts.json','/etc/passwd','C:/Windows/file','.civora-local.lock','escape']){const r=await api(root+'/file?path='+encodeURIComponent(path));assert.ok([400,403].includes(r.response.status),path+':'+r.response.status);}assert.equal((await api('/data-local/accounts.json')).response.status,404);assert.equal((await post(root+'/trash',{path:'.civora-local.lock',expectedHash:sha('x')})).response.status,403);const rows=(await api(root+'/list')).data.entries;assert.equal(rows.find(r=>r.name==='escape').kind,'blocked');assert.ok(!rows.some(r=>r.name==='.civora-local.lock'));});
 await t.test('file trash and restore preserve exact bytes without replacing destinations',async()=>{let r=await post(root+'/trash',{path:fileInfo.path,expectedHash:fileInfo.hash});assert.equal(r.response.status,200);trashId=r.data.id;assert.equal((await api(root+'/file?path='+encodeURIComponent(fileInfo.path))).response.status,404);assert.equal((await api(root+'/trash')).data.items[0].hash,fileInfo.hash);r=await post(root+'/restore',{id:trashId,destination:fileInfo.path});assert.equal(r.response.status,200);assert.equal(sha((await api(root+'/file?path='+encodeURIComponent(fileInfo.path))).data),fileInfo.hash);});
 let member='';
 await t.test('new team members have no local root access even with ordinary workspace membership',async()=>{const user=await command('user.create',{name:'Member without filesystem grant',email:'no-root@example.test',role:'author'});await post('/api/admin/password',{userId:user,password:'non-admin-local-password-456'});const login=await post('/api/login',{email:'no-root@example.test',password:'non-admin-local-password-456'},{cookie:''});member=login.response.headers.get('set-cookie').split(';')[0];assert.deepEqual((await api('/api/local/status',{cookie:member})).data.roots,[]);assert.equal((await api(root+'/list',{cookie:member})).response.status,404);assert.equal((await post(root+'/write',{path:'bad.txt',data:'YQ==',createOnly:true},{cookie:member})).response.status,404);});
 await t.test('native launch uses a fixed executable and separate filename argument; confirmation, hash and extension are enforced',async()=>{const path='drawing; echo NOT-A-COMMAND.txt';await post(root+'/write',{path,data:Buffer.from('native input').toString('base64'),createOnly:true});const expectedHash=sha('native input');assert.equal((await post(root+'/open',{path,expectedHash})).response.status,403);assert.equal((await post(root+'/open',{path,expectedHash:'0'.repeat(64),confirm:true})).response.status,409);assert.equal((await post(root+'/open',{path:fileInfo.path,expectedHash:fileInfo.hash,confirm:true})).response.status,403);assert.equal((await post(root+'/open',{path,expectedHash,confirm:true},{cookie:member})).response.status,404);assert.equal((await post(root+'/open',{path,expectedHash,confirm:true})).response.status,200);for(let i=0;i<50;i++){try{await stat(proof);break;}catch{await delay(20);}}assert.deepEqual(JSON.parse(await readFile(proof)),[join(working,path)]);assert.equal((await post(root+'/reveal',{path:'',confirm:true})).response.status,403);});
 await t.test('real HTTP adapters check out to disk and check in externally edited bytes',async()=>{
   globalThis.fetch=(url,init={})=>{const headers=new Headers(init.headers);headers.set('Cookie',admin);if(init.method&&init.method!=='GET')headers.set('Origin',base);return originalFetch(url,{...init,headers});};
   const repository=await new HttpRepository(base+'/api').open();repository.subscribe=()=>()=>{}; // SSE is exercised by the separate security suite.
   engine=await new WorkspaceEngine(repository,'u-admin').initialize();const project=await engine.run('project.create',{name:'Local delivery',code:'LOC'}),doc=await engine.addFile(new Blob(['Controlled original']),{name:'survey.txt',projectId:project,revision:'P01'});
   const disk=new HttpDirectoryFS({id:'working',label:'Real disk'},base+'/api/local'),manager=await new WorkingCopyManager(engine,disk).open(),copy=await manager.materialize(doc,{path:'Survey/survey.txt'});
   assert.equal(await readFile(join(working,copy.path),'utf8'),'Controlled original');await writeFile(join(working,copy.path),'Edited by native tool: Ω');const row=(await manager.scan())[0];assert.equal(row.status,'modified');await manager.checkin(copy.id,{revision:'P02',comment:'Real HTTP and disk',expectedLocalHash:row.localHash});const v=engine.state.documents.find(d=>d.id===doc).versions.at(-1);assert.equal(await (await repository.blob(v.hash)).text(),'Edited by native tool: Ω');assert.equal(v.label,'P02');assert.equal(engine.state.documents.find(d=>d.id===doc).checkedOutBy,null);
   globalThis.fetch=originalFetch;engine.close();engine=null;
 });
 await t.test('a second service cannot acquire an already-owned writable root',async()=>{const otherPort=await port(),p=spawn(process.execPath,['scripts/local.mjs','--data',join(directory,'second-data'),'--roots',config,'--port',String(otherPort)],{cwd:new URL('../',import.meta.url),env:{...process.env,CIVORA_ADMIN_PASSWORD:password}});let log='';p.stderr.on('data',d=>log+=d);p.stdout.on('data',d=>log+=d);const code=await new Promise(r=>p.once('exit',r));assert.notEqual(code,0);assert.match(log,/locked/);});
 await t.test('security events omit file contents and server credentials',async()=>{const r=await api('/api/admin/security-events');assert.equal(r.data.verification.valid,true);assert.ok(r.data.events.some(e=>e.kind==='local.open'));assert.ok(r.data.events.some(e=>e.kind==='local.write'));assert.ok(!JSON.stringify(r.data).includes('Edited by native tool'));assert.ok(!(await readFile(join(data,'accounts.json'),'utf8')).includes(password));});
 await t.test('originals, tracked working files, SQLite revisions and filesystem grants survive restart',async()=>{await stop();await assert.rejects(stat(join(working,'.civora-local.lock')),{code:'ENOENT'});await start();assert.equal((await api('/api/local/status')).response.status,401);await login();assert.equal((await api('/api/local/status')).data.roots.length,2);assert.equal(await readFile(join(working,'Survey/survey.txt'),'utf8'),'Edited by native tool: Ω');const d=state.documents.find(d=>d.name==='survey.txt');assert.equal(d.versions.length,2);assert.equal((await api(root+'/list?path=.civora-work&internal=1')).data.entries.length,1);});
 await t.test('stale root locks require explicit same-host, absent-process recovery',async()=>{await stop();await writeFile(join(working,'.civora-local.lock'),JSON.stringify({pid:2147483647,hostname:hostname(),token:'test-stale'}));await assert.rejects(start(),/locked/);await start(['--recover-locks']);await login();assert.equal((await api(root+'/list')).response.status,200);});
 }finally{globalThis.fetch=originalFetch;await stop();await rm(directory,{recursive:true,force:true});}
});
