import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';import {createHash} from 'node:crypto';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('Controlled copy and quick navigation on real authenticated HTTP / SQLite',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'civora-copy-')),origin=`http://127.0.0.1:${await port()}`,password='unique-copy-integration-password';let child,logs='',cookie='',state,project,target,doc,other,secret,author,viewer,ac='',vc='',copied,preview;
 const request=async(path,{method='GET',body,auth=cookie,from=origin}={})=>{const res=await fetch(origin+path,{method,headers:{Cookie:auth,...(method!=='GET'?{Origin:from,'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return{status:res.status,headers:res.headers,data:(res.headers.get('content-type')||'').includes('application/json')?await res.json():await res.text()};};
 const refresh=async()=>state=(await request('/api/workspace')).data.state;
 const command=(type,payload,opts={})=>request('/api/commands',{method:'POST',auth:opts.auth??cookie,body:{expectedRevision:opts.revision??state.revision,command:{type,payload},...(opts.file?{file:opts.file}:{})}});
 const run=async(type,payload,opts={})=>{const out=await command(type,payload,opts);assert.equal(out.status,200,JSON.stringify(out.data));await refresh();return out.data.result;};
 const source=id=>state.documents.find(d=>d.id===id);
 const copyInput=(ids=[doc],extra={})=>({expectedRevision:state.revision,projectId:project,folderId:target,reason:'Create a design alternative',copyMetadata:true,copyTags:true,referenceMode:'selected',items:ids.map(id=>({id,versionId:source(id).versions.at(-1).id,name:source(id).name})),...extra});
 const copyPreview=(p=copyInput(),auth=cookie)=>request('/api/explorer/copy-preview',{method:'POST',auth,body:p});
 const search=(body={},auth=cookie)=>request('/api/explorer/quick-search',{method:'POST',auth,body:{expectedRevision:state.revision,projectId:project,scope:'workspace',...body}});
 const original='Original approved source\nŁódź / 東京 / bytes\u0000';
 const file=text=>{const b=Buffer.from(text),hash=createHash('sha256').update(b).digest('hex');return{descriptor:{hash,blobId:hash,size:b.length,mime:'text/plain'},upload:{data:b.toString('base64'),mime:'text/plain'}};};
 async function add(name,text=original){const f=file(text);return run('document.create',{projectId:project,name,title:name,file:f.descriptor},{file:f.upload});}
 async function start(){child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:new URL(origin).port,HOST:'127.0.0.1',CIVORA_PUBLIC_ORIGIN:origin,CIVORA_DATA_DIR:dir,CIVORA_ADMIN_PASSWORD:password,CIVORA_DB:'sqlite',CIVORA_AUTO_RENDITIONS:'0',CIVORA_SEED_DEMO:'0',CIVORA_AUTOMATION:'0'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);for(let i=0;i<200;i++){try{if((await request('/api/health')).status===200)return;}catch{}if(child.exitCode!==null)throw Error(logs);await delay(25);}throw Error(logs);}
 async function stop(){if(child?.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await done;}}
 async function login(email){const out=await request('/api/login',{method:'POST',auth:'',body:{email,password}});assert.equal(out.status,200,JSON.stringify(out.data));return out.headers.get('set-cookie').split(';')[0];}
 try{await start();cookie=await login('admin@civora.local');await refresh();
  await t.test('new endpoints enforce sessions and Origin',async()=>{for(const path of ['/api/explorer/quick-search','/api/explorer/copy-preview']){assert.equal((await request(path,{method:'POST',auth:'',body:{}})).status,401);assert.equal((await request(path,{method:'POST',from:'https://hostile.invalid',body:{}})).status,403);}project=await run('project.create',{name:'Design library',code:'LIB'});target=await run('folder.create',{projectId:project,name:'Alternatives'});doc=await add('Drawing2.txt');other=await add('Drawing10.txt','Second original');secret=await add('Confidential.txt','Hidden original');author=await run('user.create',{name:'Author',email:'copy-author@example.test',role:'author'});viewer=await run('user.create',{name:'Viewer',email:'copy-viewer@example.test',role:'viewer'});await run('access.set',{scope:'project',resourceId:project,inherit:true,entries:[{principal:'user:'+author,allow:['read','download','write'],deny:[]},{principal:'user:'+viewer,allow:['read'],deny:[]}]});await run('access.set',{scope:'document',resourceId:secret,inherit:true,entries:[{principal:'user:'+author,allow:[],deny:['read']},{principal:'user:'+viewer,allow:[],deny:['read']}]});for(const userId of[author,viewer])assert.equal((await request('/api/admin/password',{method:'POST',body:{userId,password}})).status,200);ac=await login('copy-author@example.test');vc=await login('copy-viewer@example.test');});
  await t.test('quick-search applies ACL before counts and never accepts caller-supplied commands',async()=>{const out=await search({kind:'document',commands:[{id:'forged',label:'Injected command'}]},vc);assert.equal(out.status,200);assert.equal(out.data.counts.document,2);assert.ok(!JSON.stringify(out.data).includes(secret));assert.ok(!JSON.stringify(out.data).includes('forged'));const phrase=await search({query:'Drawing',limit:1},vc);assert.equal(phrase.data.items.length,1);assert.equal(phrase.data.items[0].id,doc);});
  await t.test('query and preview bind to current workspace revision',async()=>{const old=state.revision;await run('document.update',{id:doc,title:'Library drawing'});assert.equal((await search({expectedRevision:old},vc)).status,409);assert.equal((await copyPreview(copyInput([doc],{expectedRevision:old}),ac)).status,409);});
  await t.test('copy preview is read-only and derives hashes from controlled versions',async()=>{const before=structuredClone(state),out=await copyPreview(copyInput([doc,other]),ac);assert.equal(out.status,200);assert.equal(out.data.allowed,true);preview=out.data;assert.equal(preview.rows[0].hash,source(doc).versions.at(-1).hash);assert.equal(preview.rows.length,2);await refresh();assert.deepEqual(state,before);const bad=copyInput();bad.items[0].file={hash:'0'.repeat(64)};assert.equal((await copyPreview(bad)).data.allowed,false);});
  await t.test('one verified batch creates exact originals and one new workspace revision',async()=>{const before=state.revision,out=await command('document.bulkCopy',preview.payload,{auth:ac});assert.equal(out.status,200,JSON.stringify(out.data));copied=out.data.result.copied;await refresh();assert.equal(state.revision,before+1);for(const row of copied){const d=source(row.id);assert.equal(d.state,'Work in progress');assert.equal(d.versions[0].label,'P01');assert.notEqual(d.versions[0].id,source(row.sourceId).versions[0].id);}const blob=await request('/api/blobs/'+source(copied[0].id).versions[0].hash,{auth:ac});assert.equal(blob.status,200);assert.equal(blob.data,original);assert.equal(state.audit.at(-1).type,'document.bulkCopy');});
  await t.test('replaying stale preview cannot create duplicate copies',async()=>{const before=state.documents.length,out=await command('document.bulkCopy',preview.payload,{auth:ac,revision:preview.sourceRevision});assert.equal(out.status,409);await refresh();assert.equal(state.documents.length,before);});
  await t.test('historical source bytes remain selectable after check-in',async()=>{const old=source(doc).versions[0];await run('document.checkout',{id:doc});const newer=file('Newer source bytes');await run('document.checkin',{id:doc,revision:'P02',comment:'Later',file:newer.descriptor},{file:newer.upload});const p=copyInput();p.items[0].versionId=old.id;p.items[0].name='Historical.txt';const pv=await copyPreview(p,ac);assert.equal(pv.data.rows[0].historical,true);const out=await command('document.bulkCopy',pv.data.payload,{auth:ac});assert.equal(out.status,200,JSON.stringify(out.data));await refresh();assert.equal(source(out.data.result.copied[0].id).versions[0].hash,old.hash);});
  await t.test('revoking download after preview rejects the transaction without a partial copy',async()=>{const p=copyInput();p.items[0].name='Revoked.txt';const pv=(await copyPreview(p,ac)).data;await run('access.set',{scope:'document',resourceId:doc,inherit:true,entries:[{principal:'user:'+author,allow:[],deny:['download']}]});const before=state.documents.length;assert.equal((await command('document.bulkCopy',pv.payload,{auth:ac})).status,409);assert.equal((await command('document.bulkCopy',{...pv.payload,baseRevision:state.revision},{auth:ac})).status,403);await refresh();assert.equal(state.documents.length,before);const bad=await copyPreview(copyInput([doc,other]),ac);assert.equal(bad.data.allowed,false);});
  await t.test('read-only members cannot copy or inject file data',async()=>{const out=await copyPreview(copyInput(),vc);assert.equal(out.data.allowed,false);assert.equal((await command('document.bulkCopy',{...copyInput(),baseRevision:state.revision},{file:file('forged').upload})).status,400);});
  await t.test('permission revocation removes prior quick-search results and counts',async()=>{const before=(await search({query:'Historical'},vc)).data.counts.document;assert.equal(before,1);const historical=state.documents.find(d=>d.name==='Historical.txt');await run('access.set',{scope:'document',resourceId:historical.id,inherit:true,entries:[{principal:'user:'+viewer,allow:[],deny:['read']}]});const out=await search({query:'Historical',recents:[historical.id]},vc);assert.equal(out.data.counts.document,0);assert.ok(!JSON.stringify(out.data).includes(historical.id));});
  await t.test('copied records, audit mapping, ACL and exact original bytes survive restart',async()=>{const revision=state.revision,id=copied[0].id;await stop();await start();cookie=await login('admin@civora.local');await refresh();assert.equal(state.revision,revision);assert.equal(source(id).folderId,target);assert.ok(state.audit.some(a=>a.copySources?.some(x=>x.id===id)));const out=await request('/api/blobs/'+source(id).versions[0].hash);assert.equal(out.data,original);});
 }finally{await stop();await rm(dir,{recursive:true,force:true});}
});
