"""Explicit delayed-fetch fixture on the actual 0.9 UI. Not live browser HTTP.
Server authentication and exact downloads are exercised separately in Node.
"""
import hashlib,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results'/'0.9.0';OUT.mkdir(exist_ok=True)
results=[];errors=[]
def ok(name):results.append({'name':name,'passed':True});print('PASS',name,flush=True)
def close(page):page.evaluate("document.querySelectorAll('dialog[open]').forEach(d=>d.close())");page.wait_for_timeout(50)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox']);page=browser.new_page(viewport={'width':1500,'height':980});page.set_default_timeout(7000)
 try:
  page.expose_function('__testDigest',lambda data:list(hashlib.sha256(bytes(data)).digest()));page.evaluate('''()=>{Object.defineProperty(crypto,'subtle',{value:{digest:async(_,data)=>Uint8Array.from(await __testDigest(Array.from(new Uint8Array(data instanceof ArrayBuffer?data:data.buffer)))).buffer}});crypto.randomUUID=()=>{let b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};history.replaceState=()=>{};}''');page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'dist/civora.html').read_text());page.wait_for_function('!!window.Civora')
  seed=page.evaluate('''async()=>{const e=Civora.engine,p=Civora.ui.projectId,id=await e.addFile(new File(['Original transport bytes'],'Transport original.txt'),{projectId:p}),folder=await e.run('folder.create',{projectId:p,name:'Transport destination'});window.__fixture={pending:[],calls:[]};const original=fetch;window.fetch=async(url,options)=>{if(String(url).startsWith('/fixture-api/explorer/')){const request={path:String(url),body:JSON.parse(options.body)};__fixture.calls.push(request);return new Promise(resolve=>__fixture.pending.push({...request,resolve}));}return original(url,options);};window.__respond=(index=0,patch={})=>{const pending=__fixture.pending.splice(index,1)[0],b=pending.body,d=e.state.documents.find(d=>d.id===id),v=d.versions.at(-1);let response;if(pending.path.endsWith('quick-search'))response={revision:b.expectedRevision,query:b.query,scope:b.scope,kind:b.kind,items:[{kind:'document',id,projectId:p,folderId:null,label:d.name,detail:'Transport fixture',revision:v.label}],counts:{document:1,folder:0,command:0,view:0},total:1};else{const payload={...b};delete payload.expectedRevision;payload.baseRevision=b.expectedRevision;response={allowed:true,sourceRevision:b.expectedRevision,payload,rows:b.items.map(item=>({sourceId:item.id,sourceVersionId:item.versionId,sourceName:d.name,sourceRevision:v.label,historical:false,sourceCheckedOut:false,name:item.name,number:'FIXTURE-ONLY',title:item.title,metadata:{},omittedMetadata:[],omittedReferences:0,remappedReferences:0,hash:v.hash,size:v.size,revision:'P01',state:'Work in progress'}))};}pending.resolve(new Response(JSON.stringify({...response,...patch}),{headers:{'Content-Type':'application/json'}}));};e.repository.kind='server';e.repository.base='/fixture-api';return {id,p,folder};}''')
  page.keyboard.press('Control+k');page.wait_for_function('__fixture.pending.length===1');page.locator('#command-query').fill('Transport');page.wait_for_function('__fixture.pending.length===2');page.evaluate('__respond(1)');page.wait_for_timeout(80);assert page.locator('[data-search-result]').count()==1;page.evaluate('__respond(0,{items:[],counts:{document:0,folder:0,command:0,view:0},total:0})');page.wait_for_timeout(80);assert page.locator('[data-search-result]').count()==1;ok('Out-of-order server search replies cannot replace newer query results')
  page.locator('#command-query').fill('Changed query');page.keyboard.press('Enter');assert page.locator('.quick-switcher[open]').count()==1;page.wait_for_function('__fixture.pending.length===1');page.evaluate('__respond(0,{revision:-1})');page.wait_for_timeout(80);assert 'does not match' in page.locator('[data-quick-status]').inner_text();assert page.locator('[data-search-result]').count()==0;ok('Pending search blocks stale Enter selection and rejects a mismatching response revision')
  page.locator('[data-quick-refresh]').click();page.wait_for_function('__fixture.pending.length===1');page.evaluate('async(s)=>Civora.engine.run("document.update",{id:s.id,title:"Permission/revision context changed"})',seed);page.wait_for_function('__fixture.pending.length===2');page.evaluate('__respond(0)');page.wait_for_timeout(50);assert page.locator('[data-search-result]').count()==0;page.evaluate('__respond(0)');page.wait_for_timeout(80);assert page.locator('[data-search-result]').count()==1;ok('A live engine revision change supersedes an outstanding search response')
  page.locator('#command-query').fill('Closed');page.wait_for_function('__fixture.pending.length===1');close(page);page.evaluate('__respond()');page.wait_for_timeout(80);assert page.locator('.quick-switcher[open]').count()==0;ok('Closing a pending switcher discards results and does not reopen navigation')
  # Preview responses exercise client binding only; no fixture-authorized write is submitted.
  page.evaluate('(s)=>Civora.explorer.copyDialog([s.id])',seed);d=page.locator('dialog[open]').last;d.locator('[name=copy-folder]').select_option(seed['folder']);d.locator('[name=copy-reason]').fill('Transport binding check');d.locator('[data-copy-validate]').click();page.wait_for_function('__fixture.pending.length===1');d.locator('[data-copy-name]').fill('Changed destination.txt');page.evaluate('__respond()');page.wait_for_timeout(80);assert d.locator('[type=submit]').is_disabled();assert d.locator('[data-copy-preview]').inner_text()=='';ok('Changed copy inputs invalidate a delayed validation response')
  d.locator('[data-copy-validate]').click();page.wait_for_function('__fixture.pending.length===1');page.evaluate('__respond(0,{payload:{projectId:"wrong",baseRevision:0,items:[]}})');page.wait_for_timeout(80);assert 'does not match' in d.locator('[data-copy-status]').inner_text();assert d.locator('[type=submit]').is_disabled();ok('Mismatching copy destinations or source payloads cannot enable creation')
  d.locator('[data-copy-validate]').click();page.wait_for_function('__fixture.pending.length===1');page.evaluate('__respond()');page.wait_for_timeout(80);assert d.locator('[type=submit]').is_enabled();revision=page.evaluate('Civora.engine.state.revision');d.locator('[data-copy-name]').fill('Closed before response.txt');d.locator('[data-copy-validate]').click();page.wait_for_function('__fixture.pending.length===1');close(page);page.evaluate('__respond()');page.wait_for_timeout(80);assert page.locator('dialog[open]').count()==0;assert page.evaluate('Civora.engine.state.revision')==revision;assert not errors,errors;ok('Only an exact matching response validates; closing the copy dialog never writes data')
 except Exception:
  print('ERRORS',errors);page.screenshot(path=str(OUT/'refinement-transport-failure.png'),full_page=True);raise
 finally:
  (OUT/'refinement-transport-ui.json').write_text(json.dumps({'version':'0.9.0','mode':'explicit delayed response fixture, actual UI and memory command engine; not real browser-server auth','results':results,'errors':errors},indent=2));browser.close()
