"""0.9 actual UI/memory engine. Crypto shim only; browser URL access is blocked.
No real-origin authentication, IndexedDB or physical-device qualification.
"""
import hashlib,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results'/'0.9.0';OUT.mkdir(exist_ok=True)
results=[];errors=[]
def ok(name):results.append({'name':name,'passed':True});print('PASS',name,flush=True)
def dlg(page):return page.locator('dialog[open]').last
def close(page):page.evaluate("document.querySelectorAll('dialog[open]').forEach(d=>d.close())");page.wait_for_timeout(70)
def dismiss(page):page.locator('#toast-host .toast').evaluate_all('(xs)=>xs.forEach(x=>x.click())')
def action(page,name,extra=''):page.locator(f'[data-action="{name}"]{extra}:visible').first.click();page.wait_for_timeout(70)
def install(page):
 page.expose_function('__testDigest',lambda data:list(hashlib.sha256(bytes(data)).digest()))
 page.evaluate('''()=>{Object.defineProperty(crypto,'subtle',{value:{digest:async(_,data)=>Uint8Array.from(await __testDigest(Array.from(data instanceof ArrayBuffer?new Uint8Array(data):new Uint8Array(data.buffer,data.byteOffset,data.byteLength)))).buffer}});crypto.randomUUID=()=>{let b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};history.replaceState=()=>{};}''')
 page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'dist/civora.html').read_text(),wait_until='load');page.wait_for_function('!!window.Civora');dismiss(page)
def palette(page,query=''):
 (page.locator('.global-search').tap() if page.viewport_size['width']<781 else page.keyboard.press('Control+k'));page.wait_for_selector('.quick-switcher[open]');page.locator('#command-query').fill(query);page.wait_for_function("document.querySelector('#command-results')?.getAttribute('aria-busy')==='false'");return dlg(page)
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox']);page=browser.new_page(viewport={'width':1540,'height':960},has_touch=True);page.set_default_timeout(9000)
 try:
  install(page);assert page.locator('#app-version-status').inner_text()=='v0.10.0';assert 'Civora 0.10.0' in page.locator('.ex-statusbar').inner_text();assert not page.locator('#sidebar').is_visible();ok('Version labels agree and unified Explorer chrome remains the default')
  page.locator('[data-ex-row]').first.click();first=page.evaluate('Civora.explorer.activeId');assert page.locator('.ex-preview-context-name').inner_text();action(page,'ex-inspector-tab','[data-tab=versions]');name=page.evaluate('Civora.engine.state.users.find(u=>u.id===Civora.engine.state.documents.find(d=>d.id===Civora.explorer.activeId).versions.at(-1).createdBy).name');assert name in page.locator('.ex-inspector-body').inner_text();action(page,'ex-preview-next');assert page.evaluate('Civora.explorer.activeId')!=first;assert page.locator('[data-tab=versions]').get_attribute('aria-selected')=='true';action(page,'ex-preview-previous');assert page.evaluate('Civora.explorer.activeId')==first;ok('Preview previous/next preserves the active tab and displays the stored revision author')
  action(page,'ex-inspector-tab','[data-tab=properties]');page.screenshot(path=str(OUT/'refined-explorer.png'),full_page=True)
  d=palette(page);assert d.locator('[role=combobox]').count()==1;assert d.locator('[role=option]').count()>3;assert d.locator('[data-quick-kind]').count()==5;assert page.locator('#command-query').evaluate('(e)=>document.activeElement===e');before=page.evaluate('Civora.engine.state.revision');page.screenshot(path=str(OUT/'quick-switcher.png'),full_page=True);ok('Quick switcher exposes category counts, current-project scope and keyboard combobox navigation')
  d.locator('#command-query').fill('> appearance');page.wait_for_timeout(200);page.keyboard.press('Enter');page.wait_for_selector('[data-appearance-preset]');assert page.evaluate('Civora.engine.state.revision')==before;close(page);ok('Command-prefix search opens the real appearance editor without editing document data')
  d=palette(page,'> open reviews');page.keyboard.press('Enter');page.wait_for_function('Civora.ui.route==="reviews"');assert not page.locator('#sidebar').is_visible();d=palette(page,'> open documents');page.keyboard.press('Enter');page.wait_for_function('Civora.ui.route==="documents"');ok('Universal commands navigate across workspaces without restoring the old interface')
  source_name=page.evaluate('Civora.engine.state.documents.find(d=>d.id===Civora.explorer.activeId)?.name||Civora.engine.state.documents.find(d=>d.projectId===Civora.ui.projectId).name');d=palette(page,source_name);d.locator('[data-quick-kind=document]').click();page.wait_for_timeout(100);assert d.locator('[data-search-result]').count()>=1;target=d.locator('[data-search-result]').first.get_attribute('data-search-result');page.keyboard.press('ArrowDown');page.keyboard.press('ArrowUp');page.keyboard.press('Enter');page.wait_for_function('(id)=>Civora.explorer.activeId===id',arg=target);assert page.locator('dialog[open]').count()==0;ok('Document search resolves the actual scoped record into the Explorer inspector')
  d=palette(page);page.evaluate('''()=>{document.querySelector('.quick-switcher').close();document.dispatchEvent(new KeyboardEvent('keydown',{key:'k',ctrlKey:true,bubbles:true}));}''');page.wait_for_timeout(120);assert page.locator('.quick-switcher[open]').count()==1;page.locator('#command-query').fill('> notifications');page.wait_for_timeout(150);assert page.locator('[role=option]').count()>0;close(page);ok('Rapid close/reopen does not let an old dialog close handler detach the new switcher')
  action(page,'ex-appearance');count=page.locator('dialog[open]').count();page.keyboard.press('Control+k');page.wait_for_timeout(80);assert page.locator('dialog[open]').count()==count;assert page.locator('.quick-switcher[open]').count()==0;close(page);dismiss(page);ok('Quick switcher does not replace an existing unsaved form')
  # Actual saved view and filters through visible controls.
  action(page,'ex-save');d=dlg(page);d.locator('[name=name]').fill('Refinement register');d.locator('[type=submit]').click();page.wait_for_timeout(130);columns=page.evaluate('Civora.explorer.configuration.columns');page.locator('#state-filter').select_option('Work in progress');assert page.locator('[data-kind=state]').count()==1;assert page.locator('.ex-view-dirty').inner_text()=='Unsaved view changes';action(page,'ex-clear');assert page.evaluate('Civora.explorer.configuration.columns')==columns;assert page.locator('[data-kind=state]').count()==0;ok('Filter chips identify unsaved view changes and clearing filters preserves register columns')
  # New sources created by real engine, not fixture results.
  seed=page.evaluate(r'''async()=>{const e=Civora.engine,p=Civora.ui.projectId,folder=await e.run('folder.create',{projectId:p,name:'Alternative design'});const a=await e.addFile(new File(['Design alternative original A\n'],'Alternative A.txt'),{projectId:p,title:'Station layout alternative',tags:['design']}),b=await e.addFile(new File(['Original linked schedule B\n'],'Alternative B.txt'),{projectId:p,title:'Associated schedule'});await e.run('document.references',{id:a,references:[b]});Civora.explorer.go(p);return {a,b,folder,p};}''')
  page.evaluate('(s)=>Civora.explorer.copyDialog([s.a,s.b])',seed);d=dlg(page);assert d.locator('[type=submit]').is_disabled();d.locator('[name=copy-folder]').select_option(seed['folder']);d.locator('[data-copy-suggest]').click();d.locator('[name=copy-references]').select_option('selected');d.locator('[name=copy-reason]').fill('Prepare an alternative station layout for coordination');assert d.locator('[data-copy-source]').count()==2;page.screenshot(path=str(OUT/'copy-editor.png'),full_page=True);ok('Controlled-copy editor offers destination, exact stored revisions, collision-safe naming and explicit reference policy')
  d.locator('[data-copy-validate]').click();page.wait_for_function('!document.querySelector(".copy-dialog [type=submit]").disabled');assert d.locator('.copy-preview-table tbody tr').count()==2;assert '1 remapped' in d.locator('[data-copy-preview]').inner_text();revision=page.evaluate('Civora.engine.state.revision');page.screenshot(path=str(OUT/'copy-validation.png'),full_page=True);ok('Preview uses the actual command engine and shows allocated numbers with selected-reference remapping')
  d.locator('[data-copy-title]').first.fill('Changed after preview');assert d.locator('[type=submit]').is_disabled();d.locator('[data-copy-validate]').click();page.wait_for_function('!document.querySelector(".copy-dialog [type=submit]").disabled');assert page.evaluate('Civora.engine.state.revision')==revision;d.locator('[type=submit]').click();page.wait_for_function('!document.querySelector(".copy-dialog[open]")');assert page.evaluate('Civora.engine.state.revision')==revision+1
  copied=page.evaluate('(s)=>Civora.engine.state.documents.filter(d=>d.folderId===s.folder)',seed);assert len(copied)==2;assert copied[0]['state']=='Work in progress';assert copied[0]['references']==[copied[1]['id']];assert page.evaluate('Civora.ui.selection.size')==2;assert page.evaluate('(id)=>Civora.engine.repository.blob(Civora.engine.state.documents.find(d=>d.id===id).versions[0].blobId).then(b=>b.text())',copied[0]['id'])=='Design alternative original A\n';ok('Changing inputs invalidates preview; applying creates one atomic verified batch and selects the new documents')
  # Duplicate safe names at the already occupied destination; source versions are retained.
  page.evaluate('(s)=>Civora.explorer.copyDialog([s.a])',seed);d=dlg(page);d.locator('[name=copy-folder]').select_option(seed['folder']);d.locator('[data-copy-suggest]').click();assert ' - copy' in d.locator('[data-copy-name]').input_value();d.locator('[name=copy-reason]').fill('Stale preview test');d.locator('[data-copy-validate]').click();page.wait_for_function('!document.querySelector(".copy-dialog [type=submit]").disabled');page.evaluate('async(s)=>Civora.engine.run("document.update",{id:s.a,title:"Source changed after preview"})',seed);revision=page.evaluate('Civora.engine.state.revision');d.locator('[type=submit]').click();page.wait_for_timeout(80);assert 'workspace changed' in d.locator('.form-error').inner_text().lower();assert page.evaluate('Civora.engine.state.revision')==revision;close(page);ok('Live source changes invalidate an approved copy without creating a prefix or consuming numbering')
  # Mobile actual dialogs, real commands, CSS/touch dimensions. No physical device claim.
  page.set_viewport_size({'width':390,'height':844});page.wait_for_timeout(100);dismiss(page);d=palette(page,'alternative');page.screenshot(path=str(OUT/'mobile-search.png'),full_page=True);assert d.bounding_box()['width']<=390;assert page.evaluate('document.documentElement.scrollWidth')<=390;assert d.locator('#command-query').evaluate('(e)=>parseFloat(getComputedStyle(e).fontSize)')>=16;d.locator('[data-quick-kind=folder]').tap();page.wait_for_timeout(80);assert d.locator('[role=option]').count()==1;d.locator('[role=option]').tap();page.wait_for_timeout(100);assert page.evaluate('Civora.ui.folderId')==seed['folder'];ok('Phone search uses touch-friendly controls and opens folders without page-width overflow')
  page.evaluate('(s)=>Civora.explorer.copyDialog([s.a,s.b])',seed);d=dlg(page);assert d.bounding_box()['width']<=390;assert page.evaluate('document.documentElement.scrollWidth')<=390;d.locator('[name=copy-reason]').fill('Phone layout reuse');d.locator('[data-copy-validate]').tap();page.wait_for_function('!document.querySelector(".copy-dialog [type=submit]").disabled');page.screenshot(path=str(OUT/'mobile-copy.png'),full_page=True);assert d.locator('[type=submit]').bounding_box()['height']>=40;close(page);ok('Phone controlled-copy form stacks inputs, validates the real batch and retains a reachable confirmation action')
  page.set_viewport_size({'width':1540,'height':960});page.wait_for_timeout(100);action(page,'ex-menu','[data-menu=View]');action(page,'toggle-theme');d=palette(page,'>');page.screenshot(path=str(OUT/'dark-search.png'),full_page=True);close(page);dismiss(page);page.screenshot(path=str(OUT/'refined-dark.png'),full_page=True);assert not errors,errors;ok('New components share dark appearance and complete without page errors')
 except Exception:
  print('ERRORS',errors,flush=True);page.screenshot(path=str(OUT/'refinement-failure.png'),full_page=True);raise
 finally:
  (OUT/'refinement-ui.json').write_text(json.dumps({'version':'0.9.0','mode':'actual command engine / memory repository, opaque-origin crypto shim, browser-emulated touch; no physical device qualification','results':results,'errors':errors},indent=2));browser.close()
