import test from 'node:test';import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';import {createHash} from 'node:crypto';
import {readVerifiedRevision,decodeComparisonText,compareLines} from '../packages/comparison/index.js';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('Controlled renaming and revision acquisition on authenticated HTTP / SQLite',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'civora-rename-')),origin=`http://127.0.0.1:${await port()}`,password='unique-rename-integration-password';let child,logs='',cookie='',state,project,doc,other,hidden,author,viewer,ac='',vc='',preview;
 const request=async(path,{method='GET',body,auth=cookie,from=origin}={})=>{const res=await fetch(origin+path,{method,headers:{Cookie:auth,...(method!=='GET'?{Origin:from,'Content-Type':'application/json'}:{})},...(body!==undefined?{body:JSON.stringify(body)}:{})});return{status:res.status,headers:res.headers,data:(res.headers.get('content-type')||'').includes('application/json')?await res.json():await res.text()};};
 const refresh=async()=>state=(await request('/api/workspace')).data.state;
 const command=(type,payload,opts={})=>request('/api/commands',{method:'POST',auth:opts.auth??cookie,body:{expectedRevision:opts.revision??state.revision,command:{type,payload},...(opts.file?{file:opts.file}:{})}});
 const run=async(type,payload,opts={})=>{const out=await command(type,payload,opts);assert.equal(out.status,200,JSON.stringify(out.data));await refresh();return out.data.result;};
 const source=id=>state.documents.find(d=>d.id===id);
 const input=(ids=[doc],names=ids.map((_,i)=>`Renamed-${i}.txt`))=>({projectId:project,reason:'Align the issued filenames',items:ids.map((id,i)=>({id,versionId:source(id).versions.at(-1).id,folderId:source(id).folderId,expectedName:source(id).name,name:names[i]}))});
 const pv=(body=input(),auth=ac)=>request('/api/explorer/rename-preview',{method:'POST',auth,body:{...body,expectedRevision:state.revision}});
 const file=text=>{const b=Buffer.from(text),hash=createHash('sha256').update(b).digest('hex');return{descriptor:{hash,blobId:hash,size:b.length,mime:'text/plain'},upload:{data:b.toString('base64'),mime:'text/plain'}};};
 async function add(name,text){const f=file(text);return run('document.create',{projectId:project,name,title:name,file:f.descriptor},{file:f.upload});}
 async function start(){child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:new URL(origin).port,HOST:'127.0.0.1',CIVORA_PUBLIC_ORIGIN:origin,CIVORA_DATA_DIR:dir,CIVORA_ADMIN_PASSWORD:password,CIVORA_DB:'sqlite',CIVORA_AUTO_RENDITIONS:'0',CIVORA_SEED_DEMO:'0',CIVORA_AUTOMATION:'0'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);for(let i=0;i<200;i++){try{if((await request('/api/health')).status===200)return;}catch{}if(child.exitCode!==null)throw Error(logs);await delay(25);}throw Error(logs);}
 async function stop(){if(child?.exitCode===null){const done=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await done;}}
 async function login(email){const out=await request('/api/login',{method:'POST',auth:'',body:{email,password}});assert.equal(out.status,200,JSON.stringify(out.data));return out.headers.get('set-cookie').split(';')[0];}
 try{await start();cookie=await login('admin@civora.local');await refresh();
  await t.test('Preview requires authentication and same-origin writes',async()=>{for(const [auth,from,status] of [['',origin,401],[cookie,'https://hostile.invalid',403]])assert.equal((await request('/api/explorer/rename-preview',{method:'POST',auth,from,body:{}})).status,status);
   project=await run('project.create',{name:'Coordination register',code:'COORD'});doc=await add('Drawing-A.txt','Header\nKeep this\nEnd\n');other=await add('Drawing-B.txt','Original B');hidden=await add('Reserved-hidden.txt','Hidden title and bytes');author=await run('user.create',{name:'Author',email:'rename-author@example.test',role:'author'});viewer=await run('user.create',{name:'Viewer',email:'rename-viewer@example.test',role:'viewer'});
   await run('access.set',{scope:'project',resourceId:project,inherit:true,entries:[{principal:'user:'+author,allow:['read','write','download'],deny:[]},{principal:'user:'+viewer,allow:['read'],deny:[]}]});await run('access.set',{scope:'document',resourceId:hidden,inherit:true,entries:[{principal:'user:'+author,allow:[],deny:['read']},{principal:'user:'+viewer,allow:[],deny:['read']}]});
   for(const userId of [author,viewer])assert.equal((await request('/api/admin/password',{method:'POST',body:{userId,password}})).status,200);ac=await login('rename-author@example.test');vc=await login('rename-viewer@example.test');
  });
  await t.test('Validation is read-only and permits an exact final-name swap',async()=>{const before=structuredClone(state);const out=await pv(input([doc,other],['Drawing-B.txt','Drawing-A.txt']));assert.equal(out.status,200);assert.equal(out.data.allowed,true);preview=out.data;assert.equal(preview.rows[0].from,'Drawing-A.txt');await refresh();assert.deepEqual(state,before);});
  await t.test('Validated batch changes only names in one revision with per-source audit mapping',async()=>{const before=structuredClone(state);const out=await command('document.bulkRename',preview.payload,{auth:ac});assert.equal(out.status,200,JSON.stringify(out.data));await refresh();assert.equal(state.revision,before.revision+1);assert.equal(source(doc).name,'Drawing-B.txt');assert.equal(source(other).name,'Drawing-A.txt');for(const id of[doc,other]){const old=before.documents.find(d=>d.id===id);for(const key of['id','versions','number','folderId','references','metadata'])assert.deepEqual(source(id)[key],old[key]);}assert.equal(state.audit.at(-1).type,'document.bulkRename');assert.equal(state.audit.at(-1).renameChanges.length,2);assert.equal(out.data.result.renamed.length,2);});
  await t.test('Replayed and stale source previews cannot commit twice',async()=>{const before=structuredClone(state);const replay=await command('document.bulkRename',preview.payload,{auth:ac,revision:preview.sourceRevision});assert.equal(replay.status,409);const stale=await pv({...preview.payload,baseRevision:undefined});assert.equal(stale.data.allowed,false);await refresh();assert.deepEqual(state,before);});
  await t.test('Hidden name collisions are generic and do not partly rename the earlier rows',async()=>{const before=structuredClone(state);const p=input([doc,other],['Safe.txt','Reserved-hidden.txt']);const out=await pv(p);assert.equal(out.data.allowed,false);assert.match(out.data.error,/conflicts/);assert.ok(!JSON.stringify(out.data).includes(hidden));assert.ok(!JSON.stringify(out.data).includes('Hidden title'));const result=await command('document.bulkRename',{...p,baseRevision:state.revision},{auth:ac});assert.equal(result.status,400);await refresh();assert.deepEqual(state,before);});
  await t.test('Read-only users and injected metadata cannot authorize a rename',async()=>{assert.equal((await pv(input(),vc)).data.allowed,false);assert.equal((await command('document.bulkRename',{...input(),baseRevision:state.revision},{auth:vc})).status,403);const p=input();p.items[0].state='Published';assert.equal((await pv(p)).data.allowed,false);});
  await t.test('Exact prior and current original bytes remain readable and produce the correct insertion diff',async()=>{await run('document.checkout',{id:doc});const fresh=file('Header\nInserted line\nKeep this\nEnd\n');await run('document.checkin',{id:doc,revision:'P02',comment:'One real insertion',file:fresh.descriptor},{file:fresh.upload});const versions=source(doc).versions;const get=async id=>{const response=await fetch(origin+'/api/blobs/'+id,{headers:{Cookie:ac}});assert.equal(response.status,200);return response.blob();};const a=await readVerifiedRevision(versions[0],get),b=await readVerifiedRevision(versions[1],get);const [left,right]=await Promise.all([decodeComparisonText(a),decodeComparisonText(b)]);const diff=compareLines(left.text,right.text);assert.equal(diff.inserted,1);assert.equal(diff.deleted,0);assert.equal(diff.blocks.length,1);assert.equal(await a.text(),'Header\nKeep this\nEnd\n');});
  await t.test('Revoking write after validation defeats both old and rebased payloads',async()=>{preview=(await pv()).data;assert.equal(preview.allowed,true);await run('access.set',{scope:'document',resourceId:doc,inherit:true,entries:[{principal:'user:'+author,allow:[],deny:['write']}]});const before=structuredClone(state);assert.equal((await command('document.bulkRename',preview.payload,{auth:ac,revision:preview.sourceRevision})).status,409);assert.equal((await command('document.bulkRename',{...preview.payload,baseRevision:state.revision},{auth:ac})).status,403);await refresh();assert.deepEqual(state,before);});
  await t.test('Metadata-only access never grants historical file download',async()=>{const v=source(doc).versions[0];assert.equal((await request('/api/blobs/'+v.hash,{auth:vc})).status,404);await run('access.set',{scope:'document',resourceId:doc,inherit:true,entries:[{principal:'user:'+author,allow:[],deny:['write','download']}]});assert.equal((await request('/api/blobs/'+v.hash,{auth:ac})).status,404);assert.equal((await request('/api/workspace',{auth:vc})).status,200);});
  await t.test('Renamed identities, historical bytes and audit mapping survive a process restart',async()=>{const before=structuredClone(state);await stop();await start();cookie=await login('admin@civora.local');await refresh();assert.deepEqual(state,before);assert.equal(source(doc).name,'Drawing-B.txt');assert.equal(state.audit.filter(a=>a.renameChanges?.some(r=>r.id===doc)).length,1);assert.equal((await request('/api/blobs/'+source(doc).versions[0].hash)).data,'Header\nKeep this\nEnd\n');});
 }finally{await stop();await rm(dir,{recursive:true,force:true});}
});
