"""0.10 UI verification on actual app/memory engine. Opaque-origin crypto shim.
No real browser-origin storage, authentication, native camera or physical-device claim.
"""
import hashlib,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results'/'0.10.0';OUT.mkdir(exist_ok=True)
results=[];errors=[]
def ok(name):results.append({'name':name,'passed':True});print('PASS',name,flush=True)
def close(page):page.evaluate("document.querySelectorAll('dialog[open]').forEach(d=>d.close())");page.wait_for_timeout(80)
def dismiss(page):page.locator('#toast-host .toast').evaluate_all('(xs)=>xs.forEach(x=>x.click())')
def compare(page,seed,key='text'):
 page.evaluate('(s)=>Civora.explorer.go(s.p,null,{documentId:s.id})',{'p':seed['p'],'id':seed[key]})
 if page.viewport_size['width']<781:
  page.locator('.ex-mobile-commandbar [data-menu="Document"]').click()
  page.locator('[data-action="compare-versions"]:visible').last.click()
 else:
  page.locator('[data-action="ex-inspector-tab"][data-tab="versions"]').click()
  page.locator('.ex-version-heading [data-action="compare-versions"]').click()
 page.wait_for_function("document.querySelector('[data-cmp-status]')?.textContent.startsWith('Verified')")
 return page.locator('.comparison-dialog[open]')
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox']);page=browser.new_page(viewport={'width':1540,'height':1000},has_touch=True);page.set_default_timeout(9000)
 try:
  page.expose_function('__testDigest',lambda data:list(hashlib.sha256(bytes(data)).digest()))
  page.evaluate('''()=>{Object.defineProperty(crypto,'subtle',{value:{digest:async(_,data)=>Uint8Array.from(await __testDigest(Array.from(data instanceof ArrayBuffer?new Uint8Array(data):new Uint8Array(data.buffer,data.byteOffset,data.byteLength)))).buffer}});crypto.randomUUID=()=>{let b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};history.replaceState=()=>{};}''')
  page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'dist/civora.html').read_text(),wait_until='load');page.wait_for_function('!!window.Civora');dismiss(page)
  assert page.locator('#app-version-status').inner_text()=='v0.10.0';assert not page.locator('#sidebar').is_visible();ok('Current release uses the unified Explorer shell without restoring the old interface')
  seed=page.evaluate(r'''async()=>{const e=Civora.engine,p=Civora.ui.projectId;const a='STATION 04 — COORDINATION NOTES\n\nPackage: Eastern concourse\nDiscipline: Civil and structures\n\nDESIGN REQUIREMENTS\nPlatform clear width: 6.00 m\nCanopy drainage: internal downpipes\n\nREVIEW CHECKLIST\nSurvey control verified\nStructural interfaces checked\n\nIssue purpose: For coordination\n';const b=a.replace('6.00 m','6.50 m').replace('Structural interfaces checked\n','Structural interfaces checked\nAccessibility route confirmed\n');const text=await e.addFile(new File([a],'Station-04-Coordination.txt',{type:'text/plain'}),{projectId:p,title:'Eastern concourse — design coordination'});await e.run('document.checkout',{id:text});await e.checkin(new File([b],'Station-04-Coordination.txt',{type:'text/plain'}),{id:text,revision:'P02',comment:'Increase clear width and record the accessibility review'});const other=await e.addFile(new File(['Inspection schedule\n'],'Station-04-Schedule.txt',{type:'text/plain'}),{projectId:p});const svg=(shift,label)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="520" viewBox="0 0 1000 520"><rect width="1000" height="520" fill="#fff"/><g fill="none" stroke="#e6e9ed" stroke-width="1">${Array.from({length:20},(_,i)=>`<path d="M${i*50} 0V520 M0 ${i*50}H1000"/>`).join('')}</g><text x="45" y="54" font-family="sans-serif" font-size="23" fill="#253d58">STATION 04 · EASTERN CONCOURSE</text><text x="45" y="82" font-family="sans-serif" font-size="13" fill="#64748b">Coordination drawing — synthetic test original</text><g stroke="#23486c" stroke-width="3" fill="#eef4fa"><rect x="80" y="140" width="830" height="220"/><rect x="160" y="175" width="150" height="130"/><rect x="440" y="175" width="${180+shift}" height="130"/><path d="M80 390H910 M80 382V398 M910 382V398"/></g><g font-family="sans-serif" fill="#253d58"><text x="185" y="246" font-size="17">ACCESS</text><text x="465" y="245" font-size="17">CONCOURSE</text><text x="420" y="418" font-size="14">${label}</text><text x="45" y="480" font-size="12">Same pixel scale · Original drawing bytes preserved</text></g></svg>`;const image=await e.addFile(new File([svg(0,'Baseline layout')],'Station-04-Plan.svg',{type:'image/svg+xml'}),{projectId:p,title:'Eastern concourse — plan revision'});await e.run('document.checkout',{id:image});await e.checkin(new File([svg(65,'Revised clear width')],'Station-04-Plan.svg',{type:'image/svg+xml'}),{id:image,revision:'P02',comment:'Widen the central concourse'});return {text,other,image,p};}''')
  # Correct JavaScript raw strings above deliberately use explicit newline replacement here.
  d=compare(page,seed);page.wait_for_selector('[data-cmp-row]');assert d.locator('[data-cmp-summary]').inner_text().find('change blocks')>=0;assert d.locator('[data-cmp=export]').is_enabled();before=page.evaluate('Civora.engine.state.revision');ok('Versions pane opens the actual hash-verified insertion-aware comparison without changing state')
  d.locator('[data-cmp=next-change]').click();assert d.locator('[data-cmp-row][aria-current=true]').count()==1;d.locator('[name=compare-changes]').check();assert d.locator('.cmp-diff-row.equal').count()==0;d.locator('[name=compare-changes]').uncheck();d.locator('[name=compare-layout]').select_option('unified');assert d.locator('.cmp-unified').count()==1;d.locator('[name=compare-layout]').select_option('split');page.screenshot(path=str(OUT/'comparison-text.png'),full_page=True);ok('Change navigation, changes-only filtering and unified/split layouts operate on actual diff rows')
  with page.expect_download() as info:d.locator('[data-cmp=export]').click()
  download=info.value;download.save_as(OUT/'comparison-report.json');report=json.loads((OUT/'comparison-report.json').read_text());assert report['format']=='civora-revision-comparison';assert report['verified'];assert report['comparison']['complete'];assert report['target']['label']=='P02';assert page.evaluate('Civora.engine.state.revision')==before;ok('Downloaded JSON report identifies exact verified revisions and the complete comparison without a write')
  d.locator('[data-cmp-tab=evidence]').click();assert d.locator('.cmp-evidence section').count()==2;assert 'SHA-256' in d.locator('[data-cmp-output]').inner_text();assert 'UTF' in d.locator('[data-cmp-output]').inner_text().upper();page.screenshot(path=str(OUT/'comparison-evidence.png'),full_page=True);d.locator('[data-cmp-tab=content]').click();ok('Source evidence exposes actual hashes, revision notes, authors, sizes and decoded encoding information')
  d.locator('[data-cmp=swap]').click();page.wait_for_function("document.querySelector('[data-cmp-status]')?.textContent.startsWith('Verified')");assert d.locator('[name=compare-left]').input_value()==report['target']['id'];close(page);ok('Swapping baseline and target reloads and verifies the selected originals')
  d=compare(page,seed,'image');page.wait_for_selector('.cmp-canvas');d.locator('[data-cmp-range]').fill('38');assert '38%' in d.locator('.cmp-target').get_attribute('style');page.screenshot(path=str(OUT/'comparison-drawing.png'),full_page=True);d.locator('[name=compare-image-mode]').select_option('overlay');d.locator('[data-cmp-range]').fill('65');assert '0.65' in d.locator('.cmp-target').get_attribute('style');d.locator('[name=compare-image-mode]').select_option('side');assert d.locator('.cmp-image-frame').count()==2;close(page);ok('Original SVG revisions render in same-scale wipe, opacity-overlay and side-by-side modes')
  # New source with several hundred real lines verifies bounded DOM rendering and paging.
  long=page.evaluate('''async(s)=>{const e=Civora.engine,a=Array.from({length:420},(_,i)=>'Row '+i),b=[...a];b.splice(370,0,'New far-away requirement');const id=await e.addFile(new File([a.join('\\n')],'Long-notes.txt'),{projectId:s.p});await e.run('document.checkout',{id});await e.checkin(new File([b.join('\\n')],'Long-notes.txt'),{id,revision:'P02',comment:'Add one requirement'});return id;}''',seed)
  d=compare(page,{**seed,'text':long});page.wait_for_selector('[data-cmp-row]');assert d.locator('[data-cmp-row]').count()<=120;d.locator('[data-cmp=next-change]').click();assert 'New far-away requirement' in d.locator('[data-cmp-output]').inner_text();assert d.locator('[data-cmp-row]').count()<=120;close(page);ok('Long comparisons page at 120 rows and jump directly to off-page changes without truncating the result')
  page.evaluate('(s)=>Civora.explorer.renameDialog([s.text,s.other])',seed);d=page.locator('.rename-dialog[open]');assert d.locator('[type=submit]').is_disabled();d.locator('[name=rename-pattern]').fill('ISSUED-{seq:3}-{name}');d.locator('[data-rename-generate]').click();assert d.locator('[data-rename-name]').first.input_value().startswith('ISSUED-001-');d.locator('[name=rename-reason]').fill('Align the issued coordination register');d.locator('[data-rename-validate]').click();page.wait_for_function('!document.querySelector(".rename-dialog [type=submit]").disabled');revision=page.evaluate('Civora.engine.state.revision');page.screenshot(path=str(OUT/'rename-preview.png'),full_page=True);ok('Rename generator preserves extensions and validates all actual source records without saving')
  d.locator('[data-rename-name]').first.fill('Edited-after-preview.txt');assert d.locator('[type=submit]').is_disabled();d.locator('[data-rename-generate]').click();d.locator('[data-rename-validate]').click();page.wait_for_function('!document.querySelector(".rename-dialog [type=submit]").disabled');d.locator('[type=submit]').click();page.wait_for_function('!document.querySelector(".rename-dialog[open]")');assert page.evaluate('Civora.engine.state.revision')==revision+1;assert page.evaluate('(s)=>Civora.engine.state.documents.find(d=>d.id===s.text).name',seed).startswith('ISSUED-001-');assert page.evaluate('(s)=>Civora.engine.state.documents.find(d=>d.id===s.text).versions.length',seed)==2;ok('Editing invalidates rename approval; applying one validated batch preserves stored revisions')
  page.evaluate('(s)=>Civora.explorer.renameDialog([s.text])',seed);d=page.locator('.rename-dialog[open]');d.locator('[data-rename-name]').fill('Again.txt');d.locator('[name=rename-reason]').fill('Check stale preview handling');d.locator('[data-rename-validate]').click();page.wait_for_function('!document.querySelector(".rename-dialog [type=submit]").disabled');page.evaluate('async(s)=>Civora.engine.run("document.update",{id:s.other,title:"Changed elsewhere"})',seed);assert d.locator('[type=submit]').is_disabled();close(page);ok('Intervening workspace changes visibly invalidate an approved rename before submission')
  page.set_viewport_size({'width':390,'height':844});dismiss(page);d=compare(page,seed);page.wait_for_selector('[data-cmp-row]');assert d.locator('[name=compare-layout]').input_value()=='unified';assert page.evaluate('document.documentElement.scrollWidth')<=390;assert d.locator('[name=compare-left]').bounding_box()['height']>=42;page.screenshot(path=str(OUT/'comparison-mobile.png'),full_page=True);d.locator('[data-cmp-tab=evidence]').tap();assert d.locator('.cmp-evidence section').count()==2;close(page);ok('Phone comparison defaults to unified text, preserves page zoom and does not overflow the viewport')
  page.evaluate('(s)=>Civora.explorer.renameDialog([s.text,s.other])',seed);d=page.locator('.rename-dialog[open]');d.locator('[name=rename-pattern]').fill('SITE-{seq:3}');d.locator('[data-rename-generate]').tap();d.locator('[name=rename-reason]').fill('Phone filename review');d.locator('[data-rename-validate]').tap();page.wait_for_function('!document.querySelector(".rename-dialog [type=submit]").disabled');assert page.evaluate('document.documentElement.scrollWidth')<=390;assert d.locator('[type=submit]').bounding_box()['height']>=44;page.screenshot(path=str(OUT/'rename-mobile.png'),full_page=True);close(page);ok('Phone rename fields stack with touch targets and a reachable sticky confirmation footer')
  page.set_viewport_size({'width':1540,'height':1000});page.locator('[data-action=ex-menu][data-menu=View]:visible').first.click();page.locator('[data-action=toggle-theme]:visible').click();d=compare(page,seed);page.wait_for_selector('[data-cmp-row]');assert page.evaluate('getComputedStyle(document.documentElement).getPropertyValue("--teal").trim()')=='#82bafa';assert page.evaluate('document.documentElement.dataset.theme')=='dark';page.screenshot(path=str(OUT/'comparison-dark.png'),full_page=True);close(page);page.locator('[data-action=ex-menu][data-menu=View]:visible').first.click();page.locator('[data-action=toggle-theme]:visible').click();assert page.evaluate('document.documentElement.dataset.theme')=='light';ok('Actual View menu switches the workbench between coordinated dark and light appearance')
  d=compare(page,seed);page.wait_for_selector('[data-cmp-row]');page.evaluate('''async()=>{window.__comparisonActor=Civora.engine.actorId;const id=await Civora.engine.run('user.create',{name:'Unassigned user',email:'unassigned-ui@example.test',role:'viewer'});Civora.engine.actorId=id;}''');page.wait_for_function("document.querySelector('[data-cmp-output]')?.textContent==='' && document.querySelector('[data-cmp=export]')?.disabled && document.querySelector('[data-cmp-status]')?.textContent.includes('changed')");assert 'changed' in d.locator('[data-cmp-status]').inner_text();close(page);page.evaluate('async()=>{Civora.engine.actorId=__comparisonActor;await Civora.engine.refresh();}');ok('Account changes remove loaded comparison content and disable exporting rather than exposing the prior account data')
  assert not errors,errors;page.evaluate('(s)=>Civora.explorer.go(s.p,null,{documentId:s.text})',seed);dismiss(page);page.screenshot(path=str(OUT/'explorer.png'),full_page=True);ok('Completed workbench operations leave the existing Explorer and stored documents usable without page errors')
 except Exception:
  print('ERRORS',errors,flush=True);page.screenshot(path=str(OUT/'workbench-failure.png'),full_page=True);raise
 finally:
  (OUT/'revision-workbench-ui.json').write_text(json.dumps({'version':'0.10.0','mode':'actual app / memory repository, opaque-origin crypto shim, Chromium emulated touch; no live browser auth or physical device qualification','results':results,'errors':errors},indent=2));browser.close()
