import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';import {createHash} from 'node:crypto';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function port(){const s=createServer();await new Promise(r=>s.listen(0,'127.0.0.1',r));const p=s.address().port;await new Promise(r=>s.close(r));return p;}
test('resource authorization, durable renditions and recipient portal over real HTTP',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'civora-security-')),number=await port(),base=`http://127.0.0.1:${number}`,password='test-administrator-password-123';let child,logs='',state,admin='',member='',recipient='',project,other,doc,hidden,user,job,delivery,transmittal,sourceHash,secret;
 async function start(){child=spawn(process.execPath,['server/index.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:String(number),HOST:'127.0.0.1',CIVORA_PUBLIC_ORIGIN:base,CIVORA_DATA_DIR:directory,CIVORA_DB:'sqlite',CIVORA_ADMIN_PASSWORD:password,CIVORA_SEED_DEMO:'0',CIVORA_AUTO_RENDITIONS:'0'}});child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)return;}catch{}if(child.exitCode!==null)throw new Error(logs);await delay(30);}throw new Error(logs);}
 async function stop(){if(!child||child.exitCode!==null)return;const p=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await p;}
 async function api(path,{method='GET',body,cookie=admin,origin=base}={}){const response=await fetch(base+path,{method,headers:{...(cookie?{Cookie:cookie}:{}),...(method!=='GET'?{Origin:origin,'Content-Type':'application/json'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=(response.headers.get('content-type')||'').includes('json')?await response.json():await response.text();return{response,data};}
 const post=(path,body,cookie=admin)=>api(path,{method:'POST',body,cookie});
 async function login(){const r=await post('/api/login',{email:'admin@civora.local',password},'');assert.equal(r.response.status,200);admin=r.response.headers.get('set-cookie').split(';')[0];state=(await api('/api/workspace')).data.state;}
 async function run(type,payload={},file){const r=await post('/api/commands',{expectedRevision:state.revision,command:{type,payload},...(file?{file}:{})});assert.equal(r.response.status,200,JSON.stringify(r.data));state=r.data.state;return r.data.result;}
 async function upload(projectId,name,text,id){const bytes=Buffer.from(text),hash=createHash('sha256').update(bytes).digest('hex'),file={hash,blobId:hash,size:bytes.length,mime:'text/plain'};return run(id?'document.checkin':'document.create',id?{id,revision:'P02',file}:{projectId,name,title:name,revision:'P01',file},{data:bytes.toString('base64'),mime:'text/plain'});}
 try{await start();await login();project=await run('project.create',{name:'Visible project',code:'VIS'});other=await run('project.create',{name:'Confidential project',code:'SEC'});doc=await upload(project,'report.txt','Pinned original report');hidden=await upload(other,'secret.txt','Hidden confidential bytes');sourceHash=state.documents.find(d=>d.id===doc).versions[0].hash;user=await run('user.create',{name:'Scoped member',email:'scoped@example.test',role:'author'});await post('/api/admin/password',{userId:user,password:'scoped-member-password-123'});const session=await post('/api/login',{email:'scoped@example.test',password:'scoped-member-password-123'},'');member=session.response.headers.get('set-cookie').split(';')[0];
 await t.test('fresh member receives no documents or private workspace metadata',async()=>{const r=await api('/api/workspace',{cookie:member});assert.equal(r.response.status,200);assert.deepEqual(r.data.state.documents,[]);assert.deepEqual(r.data.state.projects,[]);assert.equal(r.data.state.audit.length,0);assert.ok(!JSON.stringify(r.data).includes('Confidential project'));assert.equal((await api('/api/blobs/'+sourceHash,{cookie:member})).response.status,404);});
 await run('access.set',{scope:'project',resourceId:project,inherit:true,entries:[{principal:'user:'+user,allow:['read','download','write','review'],deny:[]}]});
 await t.test('resource policy scopes workspace, listing and original-file endpoint consistently',async()=>{const r=(await api('/api/workspace',{cookie:member})).data.state;assert.deepEqual(r.documents.map(d=>d.id),[doc]);assert.deepEqual(r.projects.map(p=>p.id),[project]);const list=(await api('/api/documents?limit=1',{cookie:member})).data;assert.equal(list.total,1);assert.equal(list.items[0].id,doc);assert.equal((await api('/api/blobs/'+sourceHash,{cookie:member})).data,'Pinned original report');const secretHash=state.documents.find(d=>d.id===hidden).versions[0].hash;assert.equal((await api('/api/blobs/'+secretHash,{cookie:member})).response.status,404);});
 await t.test('forged actor and hidden document IDs do not bypass command authorization',async()=>{const r=await post('/api/commands',{expectedRevision:state.revision,actorId:'u-admin',command:{type:'document.update',payload:{id:hidden,title:'Unauthorized'}}},member);assert.equal(r.response.status,403);assert.equal((await api('/api/admin/operations',{cookie:member})).response.status,403);});
 await t.test('hidden-only changes do not generate member SSE notifications',async()=>{const abort=new AbortController(),res=await fetch(base+'/api/events',{headers:{Cookie:member},signal:abort.signal}),reader=res.body.getReader();assert.match(new TextDecoder().decode((await reader.read()).value),/revision/);let seen='';const reading=(async()=>{try{while(true){const r=await reader.read();if(r.done)break;seen+=new TextDecoder().decode(r.value);}}catch{}})();await run('document.update',{id:hidden,title:'Hidden edit must not notify'});await delay(120);assert.ok(!seen.includes('data:'),seen);await run('document.update',{id:doc,title:'Visible change'});for(let i=0;i<20&&!seen.includes('data:');i++)await delay(20);assert.ok(seen.includes('data:'),seen);abort.abort();await reading;});
 await t.test('document pagination rejects stale cursors and malformed offsets',async()=>{assert.equal((await api('/api/documents?revision=0',{cookie:member})).response.status,409);assert.equal((await api('/api/documents?offset=-1',{cookie:member})).response.status,400);assert.equal((await api('/api/documents?limit=2.5',{cookie:member})).response.status,400);});
 await t.test('rendition worker generates a durable source-pinned PDF and deduplicates requests',async()=>{const r=await post('/api/jobs',{documentId:doc,format:'pdf'},member);assert.equal(r.response.status,202);job=r.data.job.id;const again=await post('/api/jobs',{documentId:doc,format:'pdf'},member);assert.equal(again.data.job.id,job);let row;for(let i=0;i<100;i++){row=(await api('/api/jobs/'+job,{cookie:member})).data.job;if(row?.status==='completed')break;if(row?.status==='failed')throw new Error(row.error);await delay(30);}assert.equal(row.status,'completed');assert.equal(row.input.hash,sourceHash);const output=await api('/api/jobs/'+job+'/content',{cookie:member});assert.equal(output.response.status,200);assert.ok(output.data.startsWith('%PDF-'));assert.equal(createHash('sha256').update(output.data).digest('hex'),row.output.hash);});
 await t.test('revoking download blocks source bytes and existing rendition bytes immediately',async()=>{await run('access.set',{scope:'document',resourceId:doc,inherit:true,entries:[{principal:'user:'+user,allow:[],deny:['download']}]});assert.equal((await api('/api/blobs/'+sourceHash,{cookie:member})).response.status,404);assert.equal((await api('/api/jobs/'+job+'/content',{cookie:member})).response.status,404);assert.equal((await api('/api/jobs',{cookie:member})).data.jobs.length,0);assert.equal((await api('/api/workspace',{cookie:member})).data.state.documents.length,1);await run('access.remove',{scope:'document',resourceId:doc});});
 transmittal=await run('transmittal.create',{projectId:project,title:'Pinned external delivery',documentIds:[doc],recipients:['recipient@example.test']});await run('transmittal.issue',{id:transmittal});
 await t.test('issued delivery accepts only a named recipient and returns a one-time private invitation',async()=>{assert.equal((await post('/api/deliveries',{transmittalId:transmittal,email:'outsider@example.test'})).response.status,400);const r=await post('/api/deliveries',{transmittalId:transmittal,email:'recipient@example.test',days:7});assert.equal(r.response.status,201);delivery=r.data.delivery.id;secret=new URLSearchParams(new URL(r.data.invitationUrl).hash.slice(1)).get('invite');assert.ok(secret);assert.equal(r.data.delivery.invite_hash,undefined);assert.match(r.data.notice,/No email/);});
 await t.test('recipient enrollment creates separate password session and consumes invitation',async()=>{const r=await post('/api/portal/enroll',{token:secret,password:'recipient-password-123'},'');assert.equal(r.response.status,200);assert.match(r.response.headers.get('set-cookie'),/HttpOnly; SameSite=Strict; Path=\/api\/portal/);recipient=r.response.headers.get('set-cookie').split(';')[0];assert.equal((await post('/api/portal/enroll',{token:secret,password:'recipient-password-123'},'')).response.status,401);assert.equal((await api('/api/portal/deliveries',{cookie:admin})).response.status,401);assert.equal((await api('/api/workspace',{cookie:recipient})).response.status,401);});
 await t.test('portal lists only this recipient package, not project, member or audit data',async()=>{const r=await api('/api/portal/deliveries',{cookie:recipient});assert.equal(r.response.status,200);assert.equal(r.data.deliveries.length,1);assert.equal(r.data.deliveries[0].id,delivery);assert.equal(r.data.deliveries[0].documents[0].hash,sourceHash);assert.ok(!JSON.stringify(r.data).includes('Confidential project'));assert.equal(r.data.users,undefined);assert.equal(r.data.audit,undefined);});
 await run('document.checkout',{id:doc});await upload(project,'report.txt','New current report',doc);
 await t.test('recipient download stays pinned after the source document changes',async()=>{assert.equal((await api(`/api/portal/deliveries/${delivery}/files/${doc}`,{cookie:recipient})).data,'Pinned original report');assert.equal((await api(`/api/portal/deliveries/${delivery}/files/${hidden}`,{cookie:recipient})).response.status,404);assert.notEqual(state.documents.find(d=>d.id===doc).versions.at(-1).hash,sourceHash);});
 let receipt;
 await t.test('acknowledgment records authenticated identity, hashes and idempotent receipt',async()=>{const r=await post(`/api/portal/deliveries/${delivery}/acknowledge`,{note:'Received pinned package'},recipient);assert.equal(r.response.status,200);receipt=r.data.receipt;assert.equal(receipt.email,'recipient@example.test');assert.equal(receipt.documents[0].hash,sourceHash);const again=await post(`/api/portal/deliveries/${delivery}/acknowledge`,{note:'Attempted rewrite'},recipient);assert.deepEqual(again.data.receipt,receipt);});
 await t.test('cross-origin writes are blocked for member and recipient endpoints',async()=>{for(const path of['/api/commands',`/api/portal/deliveries/${delivery}/acknowledge`])assert.equal((await api(path,{method:'POST',body:{},cookie:recipient,origin:'https://attacker.example'})).response.status,403);});
 await t.test('operations data and stored credentials contain no invitation plaintext',async()=>{const events=(await api('/api/admin/security-events')).data;assert.equal(events.verification.valid,true);assert.ok(events.events.some(e=>e.kind==='portal.download'));assert.ok(!JSON.stringify(events).includes(secret));const accounts=await readFile(join(directory,'accounts.json'),'utf8');assert.ok(!accounts.includes(password));assert.ok(!accounts.includes('recipient-password-123'));});
 await t.test('job output, recipient session and receipt survive server restart',async()=>{await stop();await start();assert.equal((await api('/api/workspace')).response.status,401);assert.equal((await api('/api/portal/deliveries',{cookie:recipient})).data.deliveries[0].receipt.email,receipt.email);await login();assert.equal((await api('/api/jobs/'+job)).data.job.status,'completed');assert.ok((await api('/api/jobs/'+job+'/content')).data.startsWith('%PDF-'));});
 await t.test('revocation stops future recipient downloads despite an existing valid session',async()=>{assert.equal((await post(`/api/deliveries/${delivery}/revoke`,{})).response.status,200);assert.equal((await api(`/api/portal/deliveries/${delivery}/files/${doc}`,{cookie:recipient})).response.status,404);assert.deepEqual((await api('/api/portal/deliveries',{cookie:recipient})).data.deliveries,[]);});
 await t.test('static recipient UI is available but server credentials and converter configuration are not',async()=>{assert.equal((await api('/portal.html',{cookie:''})).response.status,200);for(const path of['/server/operations.mjs','/data/operations.sqlite','/data/accounts.json','/.env'])assert.equal((await api(path)).response.status,404);});
 }finally{await stop();await rm(directory,{recursive:true,force:true});}
});
