// Generated worker executed with explicit Cache/Fetch/client fixtures.
// Does NOT qualify the real browser service-worker lifecycle.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';import {webcrypto} from 'node:crypto';
const source=await readFile(new URL('../sw.js',import.meta.url),'utf8');
const key=r=>typeof r==='string'?r:r.url;
async function worker(scope='https://example.test/civora/'){
 const handlers={},stores=new Map(),calls=[],assets=new Map();let claims=0,skips=0,network=null;
 const cacheObject=()=>({entries:new Map(),async put(r,v){this.entries.set(key(r),v.clone());},async match(r){return this.entries.get(key(r))?.clone();},async delete(r){return this.entries.delete(key(r));},async keys(){return [...this.entries.keys()].map(url=>({url}));}});
 const caches={async open(n){if(!stores.has(n))stores.set(n,cacheObject());return stores.get(n);},async keys(){return [...stores.keys()];},async delete(n){return stores.delete(n);},match(){throw new Error('Cross-cache fallback is prohibited.');}};
 const self={registration:{scope},addEventListener:(type,fn)=>handlers[type]=fn,skipWaiting:async()=>{skips++;},clients:{claim:async()=>{claims++;}}};
 const context=vm.createContext({self,caches,crypto:webcrypto,URL,Request,Response,console,fetch:async req=>{calls.push(req);if(network)return network(req);const data=assets.get(key(req));return data?new Response(data):new Response('404',{status:404});}});vm.runInContext(source,context);const spec=vm.runInContext('({CACHE,PREFIX,BUILD,ASSETS})',context);
 for(const a of spec.ASSETS)assets.set(new URL(a.path,scope).href,await readFile(new URL('../'+a.path.slice(2),import.meta.url)));
 async function lifecycle(name){let promise;handlers[name]({waitUntil(p){promise=p;}});await promise;}
 async function request(path,options={}){let promise;handlers.fetch({request:new Request(new URL(path,scope),options),respondWith(p){promise=p;}});return promise?await promise:undefined;}
 return {spec,stores,caches,assets,calls,lifecycle,request,setNetwork:fn=>network=fn,get claims(){return claims;},get skips(){return skips;},scope};
}
test('Offline install hashes a complete shell before activation',async()=>{const w=await worker();await w.lifecycle('install');assert.equal(w.skips,1);assert.equal(w.stores.size,1);assert.equal(w.calls.length,3);assert.ok(w.calls.every(r=>r.cache==='no-store'));assert.equal((await(await w.caches.open(w.spec.CACHE)).keys()).length,3);});
test('Corrupt or partial deployments cannot replace the offline shell',async()=>{const w=await worker();w.assets.set(w.scope+'index.html',Buffer.from('old UI'));await assert.rejects(w.lifecycle('install'),/incomplete deployment/);assert.equal(w.skips,0);assert.equal(w.stores.size,0);});
test('Offline navigation never searches older caches for HTML',async()=>{const w=await worker();await w.lifecycle('install');const old=await w.caches.open('civora-shell-v8');await old.put(w.scope,new Response('OLD UI'));w.setNetwork(()=>{throw new Error('offline');});assert.match(await(await w.request('./')).text(),new RegExp(w.spec.BUILD));});
test('Missing current shell fails offline instead of reviving legacy HTML',async()=>{const w=await worker();await(await w.caches.open('civora-shell-v8')).put(w.scope,new Response('OLD UI'));w.setNetwork(()=>{throw new Error('offline');});assert.equal((await w.request('./')).type,'error');});
test('Online navigation requests fresh HTML rather than serving cached interface',async()=>{const w=await worker();await w.lifecycle('install');w.setNetwork(req=>{assert.equal(req.cache,'no-store');return new Response('FRESH COMPLETE PAGE');});assert.equal(await(await w.request('./')).text(),'FRESH COMPLETE PAGE');});
test('Server authentication/errors are never masked with cached HTML',async()=>{const w=await worker();await w.lifecycle('install');for(const status of [401,500]){w.setNetwork(()=>new Response('error',{status}));assert.equal((await w.request('./')).status,status);}});
test('APIs, portals, original files, OAuth and foreign requests bypass cache',async()=>{const w=await worker();for(const path of ['./api/session','./api/files/a','./portal.html','./oauth-callback.html','./?code=x&state=y','./index.html?state=y','https://other.test/index.html','./release.json'])assert.equal(await w.request(path),undefined,path);assert.equal(await w.request('./',{method:'POST'}),undefined);assert.equal(w.calls.length,0);});
test('Activation removes only this install’s legacy assets and preserves sibling/data caches',async()=>{const w=await worker();await w.lifecycle('install');const old=await w.caches.open('civora-shell-v8');await old.put(w.scope+'index.html',new Response('old'));await old.put('https://example.test/other/index.html',new Response('sibling'));await w.caches.open('unrelated-documents');await w.caches.open(w.spec.PREFIX+'previous');await w.lifecycle('activate');assert.equal(w.claims,1);assert.ok(w.stores.has('unrelated-documents'));assert.ok(!w.stores.has(w.spec.PREFIX+'previous'));assert.equal((await old.keys()).length,1);assert.equal(await(await old.match('https://example.test/other/index.html')).text(),'sibling');});
test('Cache names are isolated by install path on a shared origin',async()=>{const a=await worker('https://example.test/a/'),b=await worker('https://example.test/b/');assert.notEqual(a.spec.CACHE,b.spec.CACHE);assert.equal(await a.request('https://example.test/b/index.html'),undefined);});
test('Bad later network responses cannot overwrite the verified offline shell',async()=>{const w=await worker();await w.lifecycle('install');w.setNetwork(()=>new Response('<h1>deployment error</h1>'));await w.request('./');w.setNetwork(()=>{throw new Error('offline');});assert.match(await(await w.request('./index.html')).text(),new RegExp(w.spec.BUILD));});
