import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createServer } from 'node:net';
import { createHash } from 'node:crypto';
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function availablePort(){const server=createServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;await new Promise(r=>server.close(r));return port;}
test('authenticated SQLite team server integration',async t=>{
 const directory=await mkdtemp(join(tmpdir(),'civora-server-test-')),port=await availablePort(),base=`http://127.0.0.1:${port}`,password='test-only-unique-pass-123';let process,logs='',cookie='',state,project,document,viewer;
 async function start(){process=spawn(globalThis.process.execPath,['server/index.mjs'],{cwd:new URL('../',import.meta.url),env:{...globalThis.process.env,PORT:String(port),HOST:'127.0.0.1',CIVORA_PUBLIC_ORIGIN:base,CIVORA_DATA_DIR:directory,CIVORA_DB:'sqlite',CIVORA_ADMIN_PASSWORD:password,CIVORA_SEED_DEMO:'0'}});process.stdout.on('data',d=>logs+=d);process.stderr.on('data',d=>logs+=d);for(let i=0;i<100;i++){try{if((await fetch(base+'/api/health')).ok)return;}catch{}if(process.exitCode!==null)throw new Error(logs);await delay(50);}throw new Error('Server did not start: '+logs);}
 async function stop(){if(!process||process.exitCode!==null)return;const exit=new Promise(r=>process.once('exit',r));process.kill('SIGTERM');await exit;}
 async function api(path,{method='GET',body,auth=cookie,origin=base}={}){const response=await fetch(base+path,{method,headers:{...(auth?{Cookie:auth}:{}),...(method!=='GET'?{'Origin':origin,'Content-Type':'application/json'}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const data=(response.headers.get('content-type')||'').includes('json')?await response.json():await response.text();return{response,data};}
 async function command(type,payload,extra={}){return api('/api/commands',{method:'POST',body:{command:{type,payload},expectedRevision:state.revision,...extra}});}
 async function login(email='admin@civora.local',pass=password){const result=await api('/api/login',{method:'POST',body:{email,password:pass},auth:''});assert.equal(result.response.status,200,JSON.stringify(result.data));cookie=result.response.headers.get('set-cookie').split(';')[0];state=(await api('/api/workspace')).data.state;return result;}
 try{await start();
  await t.test('unauthenticated workspace is denied',async()=>{assert.equal((await api('/api/workspace',{auth:''})).response.status,401);});
  await t.test('invalid password is denied without exposing account existence',async()=>{const out=await api('/api/login',{method:'POST',body:{email:'missing@example.test',password:'bad'},auth:''});assert.equal(out.response.status,401);assert.equal(out.data.error,'Invalid email or password.');});
  await t.test('sign-in sets HttpOnly SameSite cookie and returns empty workspace',async()=>{const out=await login();assert.match(out.response.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);assert.equal(state.projects.length,0);assert.equal(out.data.user.id,'u-admin');});
  await t.test('cross-origin mutations are denied',async()=>{const out=await api('/api/commands',{method:'POST',origin:'https://attacker.example',body:{command:{type:'project.create',payload:{name:'Bad',code:'BAD'}},expectedRevision:state.revision}});assert.equal(out.response.status,403);});
  await t.test('server applies a real project command',async()=>{const out=await command('project.create',{name:'Server project',code:'SERVER'});assert.equal(out.response.status,200,JSON.stringify(out.data));state=out.data.state;project=out.data.result;assert.equal(state.projects[0].name,'Server project');});
  await t.test('stale expected revision is rejected',async()=>{const out=await command('project.update',{id:project,name:'Lost update'},{expectedRevision:0});assert.equal(out.response.status,409);assert.equal(out.data.code,'CONFLICT');});
  await t.test('file hashes are independently checked by server',async()=>{const bytes=Buffer.from('Hello team workspace'),hash=createHash('sha256').update(bytes).digest('hex');const payload={projectId:project,name:'hello.txt',number:'SV-001',title:'Uploaded file',revision:'P01',file:{hash,blobId:hash,size:bytes.length,mime:'text/plain'}};const bad=await command('document.create',payload,{file:{data:Buffer.from('Wrong bytes').toString('base64'),mime:'text/plain'}});assert.equal(bad.response.status,400);const good=await command('document.create',payload,{file:{data:bytes.toString('base64'),mime:'text/plain'}});assert.equal(good.response.status,200,JSON.stringify(good.data));state=good.data.state;document=good.data.result;const content=await api('/api/blobs/'+hash);assert.equal(content.data,bytes.toString());assert.equal(content.response.headers.get('cache-control'),'no-store');});
  await t.test('client actor spoofing does not replace authenticated identity',async()=>{const out=await command('document.update',{id:document,title:'Authenticated edit'},{actorId:'evil-client'});assert.equal(out.response.status,200);state=out.data.state;assert.equal(state.audit.at(-1).by,'u-admin');});
  await t.test('admin can add a viewer and set a password',async()=>{const out=await command('user.create',{name:'Read Only',email:'readonly@example.test',role:'viewer'});assert.equal(out.response.status,200);state=out.data.state;viewer=out.data.result;assert.equal((await api('/api/admin/password',{method:'POST',body:{userId:viewer,password:'readonly-test-pass-123'}})).response.status,200);});
  await t.test('viewer can read but cannot forge an administrator write',async()=>{const adminCookie=cookie;await login('readonly@example.test','readonly-test-pass-123');const out=await command('project.update',{id:project,name:'Escalated'},{actorId:'u-admin'});assert.equal(out.response.status,403);const pass=await api('/api/admin/password',{method:'POST',body:{userId:'u-admin',password:'attacker-test-pass'}});assert.equal(pass.response.status,403);cookie=adminCookie;state=(await api('/api/workspace')).data.state;});
  await t.test('SSE emits authenticated revision notifications',async()=>{const controller=new AbortController(),res=await fetch(base+'/api/events',{headers:{Cookie:cookie},signal:controller.signal});assert.equal(res.status,200);const reader=res.body.getReader(),first=await reader.read();assert.match(new TextDecoder().decode(first.value),/"revision":/);controller.abort();});
  await t.test('private server files are never statically served',async()=>{for(const path of ['/server/index.mjs','/data/accounts.json','/.env','/scripts/serve.mjs','/packages/../../server/index.mjs'])assert.equal((await api(path)).response.status,404,path);});
  await t.test('password store contains salted hashes rather than plaintext',async()=>{const text=await readFile(join(directory,'accounts.json'),'utf8');assert.ok(!text.includes(password));assert.ok(!text.includes('readonly-test-pass-123'));assert.equal(JSON.parse(text)['u-admin'].hash.length,128);});
  await t.test('database and file bytes survive a server restart',async()=>{const revision=state.revision;await stop();await start();assert.equal((await api('/api/workspace')).response.status,401);await login();assert.equal(state.revision,revision);assert.equal(state.documents.find(d=>d.id===document).title,'Authenticated edit');const hash=state.documents[0].versions[0].hash;assert.equal((await api('/api/blobs/'+hash)).data,'Hello team workspace');});
  await t.test('logout invalidates the session',async()=>{assert.equal((await api('/api/logout',{method:'POST',body:{}})).response.status,200);assert.equal((await api('/api/workspace')).response.status,401);});
 }finally{await stop();await rm(directory,{recursive:true,force:true});}
});
