// Direct HTTP verification; this does not qualify browser navigation or CSP enforcement.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,readdir,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve} from 'node:path';
import {serveStatic,ROOT} from '../scripts/static.mjs';
const results=[];
const server=createServer((req,res)=>serveStatic(req,res).catch(e=>{if(!res.headersSent)res.writeHead(500);res.end();}));
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const origin=`http://127.0.0.1:${server.address().port}`;
try {
 const paths=['/','/index.html','/release.json','/portal.html','/dist/civora.html','/dist/portal.html','/manifest.webmanifest','/sw.js','/docs/WORKBENCH.md','/app/comparison.js','/app/document-rename.js','/packages/comparison/index.js','/packages/document-rename/index.js','/docs/REFINEMENTS.md','/app/navigation.js','/app/document-copy.js','/packages/navigation/index.js','/packages/document-copy/index.js','/docs/EXPLORER.md','/docs/EXPLORER-DESIGN.md','/docs/MOBILE-TOUCH.md','/docs/DOCUMENT-SETS.md','/app/mobile.js','/app/document-sets.js','/packages/interactions/index.js','/packages/document-sets/index.js','/packages/document-sets/archive.js','/docs/UI-PARITY.md','/app/explorer.js','/packages/explorer/index.js','/app/automation.js','/packages/automation/index.js','/docs/WORKFLOW-AUTOMATION.md','/app/document-control.js','/app/styles.css','/packages/document-control/index.js','/packages/document-control/register.js','/packages/document-control/archive.js','/packages/document-control/references.js','/docs/LOCAL-SYSTEM.md',...(await readdir(resolve(ROOT,'dist/lib'))).filter(n=>n.endsWith('.js')).map(n=>'/dist/lib/'+n)];
 for(const path of paths){
  const response=await fetch(origin+path),data=Buffer.from(await response.arrayBuffer());
  assert.equal(response.status,200,path);assert.ok(data.length,path);assert.equal(response.headers.get('x-content-type-options'),'nosniff');
  if(path==='/'||path.endsWith('.html')){const csp=response.headers.get('content-security-policy');assert.ok(csp?.includes("object-src 'none'"));for(const block of data.toString().matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/\ssrc\s*=/.test(block[1]))continue;assert.ok(csp.includes("'sha256-"+createHash('sha256').update(block[2]).digest('base64')+"'"),'Inline script hash missing from response policy');}}
  if(path==='/sw.js')assert.ok(data.toString().includes('civora-shell:'));
  results.push({path,status:response.status,passed:true,bytes:data.length});
 }
 for(const path of ['/server/index.mjs','/server/accounts.mjs','/data/workspace.sqlite','/data-local/workspace.sqlite','/package.json','/.env','/tests/document-control-http.test.mjs','/packages/%2e%2e/server/index.mjs']){const response=await fetch(origin+path);assert.equal(response.status,404,path);await response.arrayBuffer();results.push({path,status:404,passed:true});}
 const head=await fetch(origin+'/dist/civora.html',{method:'HEAD'});assert.equal(head.status,200);assert.equal((await head.arrayBuffer()).byteLength,0);results.push({path:'/dist/civora.html',method:'HEAD',passed:true});
 const post=await fetch(origin+'/',{method:'POST'});assert.equal(post.status,405);await post.arrayBuffer();results.push({path:'/',method:'POST',passed:true});
 const html=await readFile(resolve(ROOT,'dist/civora.html'));assert.equal(html.includes(Buffer.from('Civora 0.10.0')),true);
 console.log(`${results.length} static HTTP checks passed; inline-script CSP hashes match generated bytes.`);
} finally {
 server.closeAllConnections();await new Promise(r=>server.close(r));
 await mkdir(resolve(ROOT,'test-results'),{recursive:true});
 await writeFile(resolve(ROOT,'test-results/static-http.json'),JSON.stringify({mode:'real Node HTTP; not a browser navigation or CSP-enforcement test',results},null,2));
}
