import test from 'node:test';import assert from 'node:assert/strict';
import {SnapshotSync,workspaceFingerprint} from '../packages/sync/index.js';import {createEmptyWorkspace} from '../packages/core/index.js';import {exportBackup} from '../packages/storage/index.js';import {makeEngine} from './support.mjs';
class Provider{constructor(){this.files=new Map();this.writes=0;this.fail=false;}async list(){if(this.fail)throw new Error('Authorization expired');return[...this.files].map(([id,b])=>({id,name:`civora-sync-test-${b.sync.commitId}.json`,size:JSON.stringify(b).length,date:b.savedAt||'2026-09-22'}));}async load(id){return structuredClone(this.files.get(id));}async save(backup){const id=crypto.randomUUID();this.files.set(id,structuredClone(backup));this.writes++;return{id};}}
async function setup(){const state=createEmptyWorkspace(),a=await makeEngine(state),b=await makeEngine(state),provider=new Provider(),syncA=new SnapshotSync({engine:a,provider,channel:'test'}),syncB=new SnapshotSync({engine:b,provider,channel:'test'});return{a,b,provider,syncA,syncB};}
test('initial publication and unchanged checks do not duplicate immutable snapshots',async()=>{const s=await setup();await s.syncA.tick();assert.equal(s.provider.writes,1);assert.equal(s.syncA.status,'synced');await s.syncA.tick();assert.equal(s.provider.writes,1);await s.syncB.tick();assert.equal(s.syncB.base,s.syncA.base);});
test('clean client fast-forwards verified remote changes',async()=>{const s=await setup();await s.syncA.tick();await s.syncB.tick();await s.a.run('project.create',{name:'Remote project',code:'REM'});await s.syncA.tick();await s.syncB.tick();assert.equal(s.syncB.status,'synced');assert.equal(s.b.state.projects[0].name,'Remote project');assert.equal(await workspaceFingerprint(s.a.state),await workspaceFingerprint(s.b.state));});
test('divergent local work stops automatic overwrites and local resolution retains history',async()=>{const s=await setup();await s.syncA.tick();await s.syncB.tick();await s.a.run('project.create',{name:'A project',code:'AA'});await s.b.run('project.create',{name:'B project',code:'BB'});await s.syncA.tick();await s.syncB.tick();assert.equal(s.syncB.status,'conflict');assert.equal(s.b.state.projects[0].code,'BB');const before=s.provider.files.size;await s.syncB.resolve('local');assert.equal(s.provider.files.size,before+1);assert.equal(s.syncB.status,'synced');});
test('simultaneous writers create distinct heads, then explicit remote choice joins history',async()=>{const s=await setup();await s.syncA.tick();await s.syncB.tick();const base=s.syncA.base;await s.a.run('project.create',{name:'A',code:'AA'});await s.b.run('project.create',{name:'B',code:'BB'});await Promise.all([s.syncA.push(s.a.state,[base]),s.syncB.push(s.b.state,[base])]);await s.syncA.tick();assert.equal(s.syncA.status,'conflict');assert.equal(s.syncA.conflict.heads.length,2);const chosen=s.syncA.conflict.heads.find(h=>h.writerId===s.syncB.writerId);await s.syncA.resolve('remote',chosen.commitId);assert.equal(s.a.state.projects[0].code,'BB');assert.equal((await s.syncA.remote()).length,1);assert.equal(s.provider.files.size,4);});
test('remote byte tampering is rejected before importing the workspace',async()=>{const s=await setup();await s.syncA.tick();const backup=[...s.provider.files.values()][0];backup.workspace.name='Tampered workspace';await s.syncB.tick();assert.equal(s.syncB.status,'error');assert.match(s.syncB.message,/fingerprint/);assert.notEqual(s.b.state.name,'Tampered workspace');});
test('missing parent history blocks automatic reconciliation',async()=>{const s=await setup();await s.syncA.tick();await s.a.run('project.create',{name:'Next',code:'NEXT'});await s.syncA.tick();s.provider.files.delete([...s.provider.files.keys()][0]);await s.syncB.tick();assert.equal(s.syncB.status,'error');assert.match(s.syncB.message,/parent|incomplete/);});
test('disconnected cycle is rejected even when a valid head also exists',async()=>{const s=await setup();await s.syncA.tick();const b=await exportBackup(s.a.repository,s.a.state),first=crypto.randomUUID(),second=crypto.randomUUID(),fingerprint=await workspaceFingerprint(s.a.state);for(const[id,parent]of[[first,second],[second,first]]){const v=structuredClone(b);v.sync={protocol:'civora-sync/1',channel:'test',commitId:id,parents:[parent],writerId:'test',fingerprint};await s.provider.save(v);}await s.syncB.tick();assert.equal(s.syncB.status,'error');assert.match(s.syncB.message,/cyclic/);});
test('backup-only mode refuses remote replacement',async()=>{const s=await setup();s.syncB.mode='backup';await s.syncA.tick();await s.syncB.tick();await s.a.run('project.create',{name:'Remote',code:'REM'});await s.syncA.tick();await s.syncB.tick();assert.equal(s.syncB.status,'conflict');await assert.rejects(()=>s.syncB.resolve('remote',s.syncA.base),/disabled/);});
test('paused synchronization does not import pending remote data',async()=>{const s=await setup();await s.syncA.tick();await s.syncB.tick();await s.a.run('project.create',{name:'Remote',code:'REM'});await s.syncA.tick();let release;const list=s.provider.list.bind(s.provider);s.provider.list=()=>new Promise(r=>{release=()=>list().then(r);});const pending=s.syncB.tick();while(!release)await new Promise(r=>setTimeout(r,1));s.syncB.stop();release();await pending;assert.equal(s.syncB.status,'paused');assert.equal(s.b.state.projects.length,0);});
test('expired provider authorization stops with reauthorization status',async()=>{const s=await setup();s.provider.fail=true;await s.syncA.tick();assert.equal(s.syncA.status,'reauthorize');assert.equal(s.provider.writes,0);});
test('snapshot channels, intervals and filtered states are guarded',async()=>{const s=await setup();assert.throws(()=>new SnapshotSync({engine:s.a,provider:s.provider,channel:'../secret'}),/channel/);assert.throws(()=>new SnapshotSync({engine:s.a,provider:s.provider,channel:'test',intervalMs:NaN}),/interval/);s.a.state.projection={filtered:true};await s.syncA.tick();assert.equal(s.syncA.status,'error');assert.match(s.syncA.message,/administrator/);});
test('server database cannot be placed in incoming sync mode',async()=>{const s=await setup();s.a.repository.kind='server';assert.throws(()=>new SnapshotSync({engine:s.a,provider:s.provider,channel:'test'}),/outgoing backup/);});
