"""Actual UI/command engine; explicitly delayed Blob and HTTP response fixtures.
Not live browser auth. Real HTTP ACL and persistence have a separate Node suite.
"""
import hashlib,json,os
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'test-results'/'0.10.0';OUT.mkdir(exist_ok=True)
results=[];errors=[]
def ok(name):results.append({'name':name,'passed':True});print('PASS',name,flush=True)
def close(page):page.evaluate("document.querySelectorAll('dialog[open]').forEach(d=>d.close())");page.wait_for_timeout(60)
def compare(page,seed):
 page.evaluate('(s)=>Civora.explorer.go(s.project,null,{documentId:s.id})',seed)
 page.locator('[data-action="ex-inspector-tab"][data-tab="versions"]').click();page.locator('.ex-version-heading [data-action="compare-versions"]').click()
 return page.locator('.comparison-dialog[open]')
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM','/usr/bin/chromium'),args=['--no-sandbox']);page=browser.new_page(viewport={'width':1450,'height':980});page.set_default_timeout(7000)
 try:
  page.expose_function('__testDigest',lambda data:list(hashlib.sha256(bytes(data)).digest()))
  page.evaluate('''()=>{Object.defineProperty(crypto,'subtle',{value:{digest:async(_,data)=>Uint8Array.from(await __testDigest(Array.from(data instanceof ArrayBuffer?new Uint8Array(data):new Uint8Array(data.buffer,data.byteOffset,data.byteLength)))).buffer}});crypto.randomUUID=()=>{let b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;let h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};history.replaceState=()=>{};}''')
  page.on('pageerror',lambda e:errors.append(str(e)));page.set_content((ROOT/'dist/civora.html').read_text());page.wait_for_function('!!window.Civora')
  seed=page.evaluate('''async()=>{const e=Civora.engine,project=Civora.ui.projectId,id=await e.addFile(new File(['ALPHA baseline\\n'],'Races.txt'),{projectId:project});for(const [revision,text] of [['P02','BETA middle\\n'],['P03','GAMMA current\\n']]){await e.run('document.checkout',{id});await e.checkin(new File([text],'Races.txt'),{id,revision,comment:'Race fixture source'});}const repo=e.repository,original=repo.blob.bind(repo);window.__blobMode='delay';window.__blobs=[];window.__decodes=[];repo.blob=async id=>{const b=await original(id);if(__blobMode==='corrupt')return new Blob([new Uint8Array(b.size)]);if(__blobMode==='delay')return new Promise(resolve=>__blobs.push(()=>resolve(b)));if(__blobMode==='decode'){return new class extends Blob{calls=0;async arrayBuffer(){this.calls++;if(this.calls===2)await new Promise(resolve=>__decodes.push(resolve));return super.arrayBuffer();}}([b],{type:b.type});}return b;};return {id,project,versions:e.state.documents.find(d=>d.id===id).versions.map(v=>v.id)};}''')
  d=compare(page,seed);page.wait_for_function('__blobs.length===1');page.evaluate("__blobMode='normal'");d.locator('[name=compare-left]').select_option(seed['versions'][0]);page.wait_for_selector('[data-cmp-row]');assert 'ALPHA' in d.locator('[data-cmp-output]').inner_text();page.evaluate('__blobs.shift()()');page.wait_for_timeout(100);assert 'ALPHA' in d.locator('[data-cmp-output]').inner_text();assert d.locator('[name=compare-left]').input_value()==seed['versions'][0];ok('A delayed older Blob result cannot overwrite a newer revision pair')
  page.evaluate("__blobMode='delay'");d.locator('[data-cmp=retry]').click();page.wait_for_function('__blobs.length===1');close(page);page.evaluate('__blobs.shift()()');page.wait_for_timeout(80);assert page.locator('.comparison-dialog[open]').count()==0;ok('Closing during acquisition discards late original bytes without reopening the dialog')
  page.evaluate("__blobMode='corrupt'");d=compare(page,seed);page.wait_for_function("document.querySelector('[data-cmp-status]').textContent.includes('SHA-256')");assert d.locator('[data-cmp-output]').inner_text()=='';assert d.locator('[data-cmp=export]').is_disabled();ok('Corrupted but equally sized original bytes are rejected before content display or export');close(page)
  page.evaluate("__blobMode='decode'");d=compare(page,seed);page.wait_for_function('__decodes.length===1');page.evaluate("__blobMode='normal'");d.locator('[name=compare-left]').select_option(seed['versions'][0]);page.wait_for_selector('[data-cmp-row]');assert 'ALPHA' in d.locator('[data-cmp-output]').inner_text();page.evaluate('__decodes.shift()()');page.wait_for_function('__decodes.length===1');page.evaluate('__decodes.shift()()');page.wait_for_timeout(80);d.locator('[name=compare-whitespace]').check();assert 'ALPHA' in d.locator('[data-cmp-output]').inner_text();assert 'BETA' not in d.locator('[data-cmp-output]').inner_text();ok('Late text decoding cannot poison a newer comparison or its option recalculation');close(page)
  # Separate explicit HTTP preview transport, derived from the actual request only.
  page.evaluate('''()=>{const e=Civora.engine;window.__pending=[];const original=fetch;window.fetch=(url,options)=>String(url).includes('/rename-preview')?new Promise(resolve=>__pending.push({body:JSON.parse(options.body),resolve})):original(url,options);window.__respond=(patch={})=>{const {body,resolve}=__pending.shift(),payload={...body};delete payload.expectedRevision;payload.baseRevision=body.expectedRevision;resolve(new Response(JSON.stringify({allowed:true,sourceRevision:body.expectedRevision,payload,rows:body.items.map(r=>({id:r.id,from:r.expectedName,to:r.name.trim(),changed:r.name.trim()!==r.expectedName})),...patch}),{headers:{'Content-Type':'application/json'}}));};e.repository.kind='server';e.repository.base='/fixture-api';}''')
  page.evaluate('(s)=>Civora.explorer.renameDialog([s.id])',seed);d=page.locator('.rename-dialog[open]');d.locator('[data-rename-name]').fill('First.txt');d.locator('[name=rename-reason]').fill('Delayed response test');d.locator('[data-rename-validate]').click();page.wait_for_function('__pending.length===1');d.locator('[data-rename-name]').fill('Second.txt');page.evaluate('__respond()');page.wait_for_timeout(80);assert d.locator('[type=submit]').is_disabled();assert d.locator('[data-rename-preview]').inner_text()=='';ok('Changed rename inputs invalidate an outstanding validation response')
  d.locator('[data-rename-validate]').click();page.wait_for_function('__pending.length===1');page.evaluate('__respond({payload:{items:[],baseRevision:0}})');page.wait_for_timeout(80);assert d.locator('[type=submit]').is_disabled();assert 'does not match' in d.locator('[data-rename-status]').inner_text();ok('Forged or mismatching preview payloads cannot enable a rename')
  d.locator('[data-rename-validate]').click();page.wait_for_function('__pending.length===1');page.evaluate('__respond()');page.wait_for_function('!document.querySelector(".rename-dialog [type=submit]").disabled');revision=page.evaluate('Civora.engine.state.revision');d.locator('[data-rename-name]').fill('Third.txt');d.locator('[data-rename-validate]').click();page.wait_for_function('__pending.length===1');close(page);page.evaluate('__respond()');page.wait_for_timeout(80);assert page.locator('.rename-dialog[open]').count()==0;assert page.evaluate('Civora.engine.state.revision')==revision;ok('Only exact responses validate; closing a pending rename never commits a write')
  page.evaluate('(s)=>Civora.explorer.renameDialog([s.id])',seed);page.evaluate("Civora.engine.actorId='not-this-account'");page.wait_for_function('!document.querySelector(".rename-dialog[open]")');assert not errors,errors;ok('Account switches close source-bearing rename forms even without a workspace event')
 except Exception:
  print('ERRORS',errors,flush=True);page.screenshot(path=str(OUT/'races-failure.png'),full_page=True);raise
 finally:
  (OUT/'workbench-races-ui.json').write_text(json.dumps({'version':'0.10.0','mode':'actual UI with explicit delayed Blob/decoder and HTTP response fixtures; no live browser authentication','results':results,'errors':errors},indent=2));browser.close()
