import { comparisonKind, readVerifiedRevision, decodeComparisonText, compareLines, comparisonReport } from '../packages/comparison/index.js';
import { explorerCan } from '../packages/explorer/index.js';
import { escapeHTML as e, icon, openDialog, formatBytes, formatDate, downloadBlob } from '../packages/controls/index.js';
/** Read-only compare workbench. Loaded content is discarded on identity/access changes. */
export function createComparison(ctx){
 const E=ctx.getEngine,S=ctx.getState;
 function open(id){
  const engine=E(),repo=engine.repository,actorId=engine.actorId,workspaceId=S().id;
  const find=()=>S().documents.find(d=>d.id===id&&!d.deletedAt);
  const valid=()=>E()===engine&&E().repository===repo&&E().actorId===actorId&&S().id===workspaceId&&!!find()&&explorerCan(S(),actorId,'download','document',id);
  if(!valid())throw new Error('Download access to this document is required to compare revisions.');
  const original=find();if(original.versions.length<2)throw new Error('Check in another revision before comparing.');
  let leftId=original.versions.at(-2).id,rightId=original.versions.at(-1).id,serial=0,aborter=null,urls=[],snapshot=null,report=null,diff=null,decoded=null,tab='content',page=0,block=-1,imageMode='wipe',imagePosition=50,imageZoom=100;
  const pageSize=120;
  const body=`<div class="cmp-pair"><label class="field"><span>Baseline revision</span><select name="compare-left" aria-label="Baseline revision"></select></label><button class="btn cmp-swap" type="button" data-cmp="swap" aria-label="Swap baseline and target">${icon('refresh',16)}<span>Swap</span></button><label class="field"><span>Target revision</span><select name="compare-right" aria-label="Target revision"></select></label></div><div class="cmp-status" role="status" data-cmp-status>Loading and verifying original files…</div><div class="cmp-tabs"><div role="tablist" aria-label="Comparison panels"><button type="button" role="tab" aria-selected="true" data-cmp-tab="content">Content comparison</button><button type="button" role="tab" aria-selected="false" data-cmp-tab="evidence">Source evidence</button></div><button type="button" class="btn small" data-cmp="export" disabled>${icon('download',14)}Export report</button><button type="button" class="btn small cmp-options-toggle" data-cmp="options" aria-expanded="false">${icon('settings',14)}Options</button><button type="button" class="btn small" data-cmp="retry">${icon('refresh',14)}Reload</button></div><div class="cmp-options" data-cmp-text-options hidden><label class="field"><span>Layout</span><select name="compare-layout"><option value="split">Side by side</option><option value="unified">Unified</option></select></label><label><input type="checkbox" name="compare-whitespace">Ignore spaces / tabs</label><label><input type="checkbox" name="compare-eol" checked>Ignore line endings</label><label><input type="checkbox" name="compare-changes">Changes only</label><label><input type="checkbox" name="compare-wrap" checked>Wrap long lines</label></div><div class="cmp-summary" data-cmp-summary></div><div class="cmp-toolbar" data-cmp-navigation hidden><button class="btn small" type="button" data-cmp="previous-change">${icon('up',14)}Previous change</button><button class="btn small" type="button" data-cmp="next-change">${icon('down',14)}Next change</button><span data-cmp-change-status></span><span class="grow"></span><button class="btn small" type="button" data-cmp="previous-page">Previous page</button><span data-cmp-page-status></span><button class="btn small" type="button" data-cmp="next-page">Next page</button></div><div class="cmp-output" data-cmp-output role="region" aria-label="Revision comparison results" tabindex="0"></div><p class="cmp-footnote">Read-only comparison of exact stored originals. Current filenames identify the records; historical metadata, CAD semantics and digital signatures are not inferred.</p>`;
  const dialog=openDialog({title:'Compare revisions',subtitle:`${original.number} · ${original.name}`,wide:true,body,onClose(){serial++;aborter?.abort();clearInterval(watch);clearURLs();snapshot=null;report=null;diff=null;decoded=null;engine.removeEventListener('change',changed);engine.removeEventListener('connectionerror',unavailable);}});dialog.classList.add('comparison-dialog');
  const q=s=>dialog.querySelector(s),output=q('[data-cmp-output]'),status=q('[data-cmp-status]');
  q('[name=compare-layout]').value=innerWidth<=780?'unified':'split';
  function clearURLs(){urls.forEach(URL.revokeObjectURL);urls=[];}
  function clear(message){serial++;aborter?.abort();clearURLs();snapshot=null;report=null;diff=null;decoded=null;output.replaceChildren();q('[data-cmp-summary]').replaceChildren();q('[data-cmp-navigation]').hidden=true;q('[data-cmp-text-options]').hidden=true;q('[data-cmp=export]').disabled=true;status.textContent=message;}
  function refreshOptions(){const d=find();if(!d)return;for(const [side,value]of[['left',leftId],['right',rightId]])q(`[name=compare-${side}]`).innerHTML=d.versions.map(v=>`<option value="${e(v.id)}" ${v.id===value?'selected':''}>${e(v.label)}${v.id===d.versions.at(-1).id?' · current':''} · ${e(formatDate(v.createdAt))}</option>`).join('');}
  function current(){return dialog.open&&valid()&&snapshot&&S().revision===snapshot.revision&&find().versions.some(v=>v.id===snapshot.left.id&&v.hash===snapshot.left.hash)&&find().versions.some(v=>v.id===snapshot.right.id&&v.hash===snapshot.right.hash)&&snapshot.left.id===leftId&&snapshot.right.id===rightId;}
  function evidence(){if(!snapshot)return;output.innerHTML=`<div class="cmp-evidence">${[['Baseline',snapshot.left],['Target',snapshot.right]].map(([label,v],i)=>`<section><h3>${label} · ${e(v.label)}</h3><dl><dt>Created</dt><dd>${e(formatDate(v.createdAt))}</dd><dt>Author</dt><dd>${e(S().users.find(u=>u.id===v.createdBy)?.name||'Unknown member')}</dd><dt>Revision note</dt><dd>${e(v.comment||'—')}</dd><dt>Original size</dt><dd>${e(formatBytes(v.size))}</dd><dt>SHA-256 · verified</dt><dd class="cmp-hash">${e(v.hash)}</dd><dt>Revision ID</dt><dd class="cmp-hash">${e(v.id)}</dd>${decoded?`<dt>Text encoding</dt><dd>${e(decoded[i].encoding)}${decoded[i].bom?' · BOM':''}</dd><dt>Line endings</dt><dd>${decoded[i].newlines.crlf} CRLF · ${decoded[i].newlines.lf} LF · ${decoded[i].newlines.cr} CR</dd>`:''}</dl><button type="button" class="btn small" data-cmp="download-${i===0?'left':'right'}">${icon('download',14)}Download ${e(v.label)}</button></section>`).join('')}</div><div class="note-box mt16">These hashes were computed from retrieved bytes in this session. They are integrity evidence, not qualified signatures. Per-revision metadata environments are not stored.</div>`;}
  function rowsForView(){return diff.rows.map((r,index)=>({...r,index})).filter(r=>!q('[name=compare-changes]').checked||r.kind!=='equal');}
  function renderText(){if(!diff)return;const rows=rowsForView();page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(rows.length/pageSize)-1)));const visible=rows.slice(page*pageSize,(page+1)*pageSize),split=q('[name=compare-layout]').value==='split';
    const content=(r,side)=>`<span class="cmp-line-number">${r[side+'Number']??''}</span><code>${e(r[side])}${r[side+'Number']!==null&&r[side+'Eol']===''?'<small class="cmp-no-newline">[no final newline]</small>':''}</code>`;
    output.classList.toggle('cmp-nowrap',!q('[name=compare-wrap]').checked);
    output.innerHTML=rows.length?`<div class="cmp-lines ${split?'cmp-split':'cmp-unified'}" role="table" aria-label="${split?'Side by side':'Unified'} text differences"><div class="cmp-line-head" role="row"><span>Baseline · ${e(snapshot.left.label)}</span><span>Target · ${e(snapshot.right.label)}</span></div>${visible.map(r=>`<div class="cmp-diff-row ${r.kind}" role="row" data-cmp-row="${r.index}" tabindex="-1" ${block>=0&&r.index===diff.blocks[block]?'aria-current="true"':''}>${split?`<div class="cmp-cell cmp-before" role="cell"><span class="cmp-mark" aria-label="${r.kind==='equal'?'Unchanged':r.leftNumber===null?'Absent':'Removed'}">${r.kind==='equal'?'':r.leftNumber===null?'':'−'}</span>${content(r,'left')}</div><div class="cmp-cell cmp-after" role="cell"><span class="cmp-mark" aria-label="${r.kind==='equal'?'Unchanged':r.rightNumber===null?'Absent':'Added'}">${r.kind==='equal'?'':r.rightNumber===null?'':'+'}</span>${content(r,'right')}</div>`:r.kind==='equal'?`<div class="cmp-cell" role="cell"><span class="cmp-mark"> </span>${content(r,'right')}</div>`:`${r.leftNumber!==null?`<div class="cmp-cell cmp-before" role="cell"><span class="cmp-mark" aria-label="Removed">−</span>${content(r,'left')}</div>`:''}${r.rightNumber!==null?`<div class="cmp-cell cmp-after" role="cell"><span class="cmp-mark" aria-label="Added">+</span>${content(r,'right')}</div>`:''}`}</div>`).join('')}</div>`:`<div class="cmp-empty">${icon('check',28)}<h3>${diff.rows.length?'No changes under the selected options':'Both text revisions are empty'}</h3><p>${diff.ignored?'Ignored whitespace or line-ending differences remain in the originals.':'Both hashes and source information are available in Source evidence.'}</p></div>`;
    q('[data-cmp-navigation]').dataset.pages=rows.length>pageSize?'many':'single';
    q('[data-cmp-page-status]').textContent=`${rows.length?page*pageSize+1:0}–${Math.min((page+1)*pageSize,rows.length)} of ${rows.length} rows`;
    q('[data-cmp-change-status]').textContent=diff.blocks.length?`${block>=0?block+1:'—'} / ${diff.blocks.length} change blocks`:'No change blocks';
    q('[data-cmp=previous-page]').disabled=page===0;q('[data-cmp=next-page]').disabled=(page+1)*pageSize>=rows.length;
    q('[data-cmp=previous-change]').disabled=!diff.blocks.length;q('[data-cmp=next-change]').disabled=!diff.blocks.length;
  }
  function recalculate(){if(!decoded||!snapshot)return;page=0;block=-1;try{diff=compareLines(decoded[0].text,decoded[1].text,{ignoreWhitespace:q('[name=compare-whitespace]').checked,ignoreLineEndings:q('[name=compare-eol]').checked});report=comparisonReport({document:find(),baseline:snapshot.left,target:snapshot.right,result:diff,decoding:decoded.map(({encoding,bom,newlines})=>({encoding,bom,newlines}))});q('[data-cmp-summary]').innerHTML=`<span class="cmp-stat added"><strong>+${diff.inserted}</strong> added lines</span><span class="cmp-stat removed"><strong>−${diff.deleted}</strong> removed lines</span><span class="cmp-stat"><strong>${diff.blocks.length}</strong> change blocks</span><span class="cmp-stat">${diff.ignored} ignored line differences</span>`;}
    catch(error){diff=null;report=comparisonReport({document:find(),baseline:snapshot.left,target:snapshot.right,result:null,warning:error.message});}
    render();
  }
  function render(){q('[data-cmp-navigation]').hidden=tab!=='content'||!diff;q('[data-cmp-text-options]').hidden=tab!=='content'||!decoded;q('[data-cmp=export]').disabled=!current()||!report;
    if(!snapshot){output.replaceChildren();return;}if(tab==='evidence')return evidence();if(diff)return renderText();if(snapshot?.images)return renderImage();output.innerHTML=`<div class="cmp-empty">${icon('file',28)}<h3>${e(report?.warning||'Original-file comparison')}</h3><p>${snapshot?.left.hash===snapshot?.right.hash?'The original bytes are identical.':'The original bytes differ.'} See Source evidence for verified hashes and downloads. No semantic binary/CAD comparison is performed.</p></div>`;
  }
  async function loadImage(blob,name,signal){if(signal.aborted)throw new Error('Comparison cancelled.');const mime=/\.svg$/i.test(name)?'image/svg+xml':blob.type;const url=URL.createObjectURL(new Blob([blob],{type:mime}));urls.push(url);const image=new Image();image.decoding='async';image.src=url;await new Promise((resolve,reject)=>{const finish=fn=>{signal.removeEventListener('abort',cancel);image.onload=image.onerror=null;fn();},cancel=()=>finish(()=>reject(new Error('Comparison cancelled.')));image.onload=()=>finish(resolve);image.onerror=()=>finish(()=>reject(new Error('The original image could not be decoded.')));signal.addEventListener('abort',cancel,{once:true});if(image.complete&&image.naturalWidth)finish(resolve);});if(image.naturalWidth*image.naturalHeight>40000000)throw new Error('Images above 40 megapixels are not displayed in this comparison.');return {url,width:image.naturalWidth,height:image.naturalHeight};}
  function renderImage(){const [a,b]=snapshot.images,W=Math.max(a.width,b.width),H=Math.max(a.height,b.height),image=(img,label)=>`<img alt="${label}" src="${img.url}" draggable="false" style="width:${img.width/W*100}%;height:${img.height/H*100}%">`;
    output.innerHTML=`<div class="cmp-image-tools"><label class="field"><span>Visual comparison</span><select name="compare-image-mode"><option value="wipe">Wipe</option><option value="overlay">Opacity overlay</option><option value="side">Side by side</option></select></label><label class="cmp-range"><span>${imageMode==='overlay'?'Target opacity':'Wipe position'}</span><input type="range" min="0" max="100" value="${imagePosition}" data-cmp-range aria-label="${imageMode==='overlay'?'Target opacity':'Wipe position'}"><output>${imagePosition}%</output></label><label class="field"><span>Zoom</span><select name="compare-image-zoom">${[50,100,150,200,300].map(n=>`<option value="${n}" ${n===imageZoom?'selected':''}>${n===100?'Fit width':n+'%'}</option>`).join('')}</select></label></div><div class="cmp-image-labels"><span>Baseline · ${e(snapshot.left.label)} · ${a.width} × ${a.height}</span><span>Target · ${e(snapshot.right.label)} · ${b.width} × ${b.height}</span></div><div class="cmp-image-scroll" tabindex="0" aria-label="Image comparison. Use scrollbars when zoomed.">${imageMode==='side'?`<div class="cmp-image-side" style="width:${imageZoom}%">${[a,b].map((img,i)=>`<div style="aspect-ratio:${W}/${H}" class="cmp-image-frame">${image(img,i?'Target':'Baseline')}</div>`).join('')}</div>`:`<div class="cmp-canvas" style="aspect-ratio:${W}/${H};width:${imageZoom}%">${image(a,'Baseline')}<div class="cmp-target" style="${imageMode==='overlay'?'opacity:'+(imagePosition/100):'clip-path:inset(0 0 0 '+imagePosition+'%)'}">${image(b,'Target')}</div>${imageMode==='wipe'?`<div class="cmp-wipe-line" style="left:${imagePosition}%"></div>`:''}</div>`}</div><p class="cmp-image-note">Same pixel scale, top-left alignment, no automatic registration. Blank margins indicate unequal image sizes. The slider also accepts arrow keys; no drag is required. Animated images are not frame-synchronized.</p>`;
    q('[name=compare-image-mode]').value=imageMode;q('[data-cmp-range]').disabled=imageMode==='side';
    q('[data-cmp-range]').oninput=ev=>{imagePosition=Number(ev.target.value);ev.target.nextElementSibling.value=imagePosition+'%';const target=q('.cmp-target');if(target){if(imageMode==='overlay')target.style.opacity=String(imagePosition/100);else{target.style.clipPath=`inset(0 0 0 ${imagePosition}%)`;q('.cmp-wipe-line').style.left=imagePosition+'%';}}};
    q('[name=compare-image-mode]').onchange=ev=>{imageMode=ev.target.value;renderImage();};q('[name=compare-image-zoom]').onchange=ev=>{imageZoom=Number(ev.target.value);renderImage();};
  }
  async function load(){clear('Loading and verifying both original revisions…');if(!dialog.open)return;if(!valid()){status.textContent='Workspace, account or download permission changed. Close and reopen this comparison.';return;}refreshOptions();
    const ticket=serial,revision=S().revision,d=find(),left=d.versions.find(v=>v.id===leftId),right=d.versions.find(v=>v.id===rightId);if(!left||!right){status.textContent='Selected revisions are no longer available.';return;}aborter=new AbortController();const signal=aborter.signal,alive=()=>ticket===serial&&dialog.open&&valid()&&S().revision===revision&&!signal.aborted;
    try{const a=await readVerifiedRevision(left,id=>repo.blob(id),{signal});if(!alive())return;const b=await readVerifiedRevision(right,blobId=>left.hash===right.hash?a:repo.blob(blobId),{signal});if(!alive())return;
      snapshot={left:structuredClone(left),right:structuredClone(right),blobs:[a,b],revision};status.textContent=left.hash===right.hash?'Verified · original file bytes are identical':'Verified · original file bytes differ';
      const kind=comparisonKind(d.name);report=comparisonReport({document:d,baseline:left,target:right,result:null});
      if(kind==='text'){try{const texts=[await decodeComparisonText(a),await decodeComparisonText(b)];if(!alive())return;decoded=texts;recalculate();}catch(error){if(!alive())return;decoded=null;report.warning=error.message;render();}}
      else if(kind==='image'){try{const images=[await loadImage(a,d.name,signal),await loadImage(b,d.name,signal)];if(!alive())return;snapshot.images=images;report.visual={baseline:{width:images[0].width,height:images[0].height},target:{width:images[1].width,height:images[1].height},alignment:'top-left, same pixel scale; no automatic registration'};}catch(error){if(!alive())return;report.warning=error.message;}render();}
      else{report.warning='Binary originals: hash and size comparison only';render();}
    }catch(error){if(alive()){clear('Comparison unavailable: '+error.message);}}
  }
  function changed(){if(!dialog.open)return;if(!valid()){clear('Document access or account changed. Previously loaded content has been removed.');return;}load();}
  function unavailable(){clear('Server connection changed. Reload after refreshing the workspace.');}
  const watch=setInterval(()=>{if(dialog.open&&(!valid()||snapshot&&S().revision!==snapshot.revision))changed();},500);
  engine.addEventListener('change',changed);engine.addEventListener('connectionerror',unavailable);
  q('[name=compare-left]').onchange=ev=>{leftId=ev.target.value;load();};q('[name=compare-right]').onchange=ev=>{rightId=ev.target.value;load();};
  for(const selector of ['compare-whitespace','compare-eol'])q(`[name=${selector}]`).onchange=recalculate;
  for(const selector of ['compare-layout','compare-changes','compare-wrap'])q(`[name=${selector}]`).onchange=()=>{page=0;block=-1;render();};
  q('[role=tablist]').addEventListener('keydown',event=>{
    if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;
    const buttons=[...dialog.querySelectorAll('[data-cmp-tab]')],index=buttons.indexOf(document.activeElement);if(index<0)return;event.preventDefault();
    const next=event.key==='Home'?0:event.key==='End'?buttons.length-1:(index+(event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[next].click();buttons[next].focus();
  });
  dialog.addEventListener('click',event=>{const t=event.target.closest('[data-cmp-tab]');if(t){tab=t.dataset.cmpTab;dialog.querySelectorAll('[data-cmp-tab]').forEach(b=>b.setAttribute('aria-selected',String(b===t)));render();return;}const button=event.target.closest('[data-cmp]');if(!button)return;const action=button.dataset.cmp;
    if(action==='options'){const expanded=dialog.classList.toggle('cmp-options-expanded');button.setAttribute('aria-expanded',String(expanded));return;}if(action==='retry'){load();return;}if(action==='swap'){[leftId,rightId]=[rightId,leftId];load();return;}
    if(!current()){clear('The comparison context changed. Reload the selected revisions.');return;}
    if(action==='export'){downloadBlob(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),`comparison-${find().number.replace(/[^\w.-]+/g,'_')}-${snapshot.left.label.replace(/[^\w.-]+/g,'_')}-${snapshot.right.label.replace(/[^\w.-]+/g,'_')}.json`);return;}
    if(action.startsWith('download-')){downloadBlob(snapshot.blobs[action==='download-left'?0:1],find().name);return;}
    if(action==='previous-page'||action==='next-page'){page+=action==='next-page'?1:-1;renderText();output.scrollTop=0;}
    if((action==='previous-change'||action==='next-change')&&diff?.blocks.length){block=block<0?(action==='next-change'?0:diff.blocks.length-1):(block+(action==='next-change'?1:-1)+diff.blocks.length)%diff.blocks.length;const index=diff.blocks[block],rows=rowsForView();page=Math.floor(rows.findIndex(r=>r.index===index)/pageSize);renderText();const row=q(`[data-cmp-row="${index}"]`);row?.scrollIntoView({block:'nearest'});row?.focus({preventScroll:true});}
  });
  refreshOptions();load();return dialog;
 }
 return {open};
}
