import { previewDocumentRename } from '../packages/core/index.js';
import { suggestRenames, RENAME_LIMITS } from '../packages/document-rename/index.js';
import { explorerCan, folderPath } from '../packages/explorer/index.js';
import { fetchJSON } from '../packages/storage/index.js';
import { escapeHTML as e, icon, toast } from '../packages/controls/index.js';
/** One rename editor for mouse, keyboard and touch. All writes use the command engine. */
export function createRenameFeatures(ctx){
 const E=ctx.getEngine,S=ctx.getState;
 function open(ids){
  const engine=E(),actorId=engine.actorId,workspaceId=S().id,repo=engine.repository;
  const sources=ids.map(id=>S().documents.find(d=>d.id===id&&!d.deletedAt));
  if(!ids.length||ids.length>RENAME_LIMITS.documents||sources.some(d=>!d))throw new Error('Choose 1–100 active documents.');
  if(new Set(ids).size!==ids.length||sources.some(d=>d.projectId!==sources[0].projectId))throw new Error('Choose distinct documents in one project.');
  if(sources.some(d=>!explorerCan(S(),actorId,'write','document',d.id)))throw new Error('Write access to every selected document is required.');
  const origin=sources.map(d=>({id:d.id,versionId:d.versions.at(-1).id,folderId:d.folderId,expectedName:d.name}));
  let form,dialog,approved=null,signature='',serial=0;
  const same=()=>E()===engine&&E().actorId===actorId&&E().repository===repo&&S().id===workspaceId;
  const body=`<div class="rename-intro">${icon('edit',20)}<div><strong>Rename ${ids.length} controlled document${ids.length===1?'':'s'}</strong><p>File bytes, document numbers, revision IDs and references are retained. Native CAD paths inside files and external working copies are not rewritten.</p></div></div><details class="rename-builder" open><summary>Generate filenames</summary><div class="rename-pattern"><label class="field"><span>Pattern for filename without extension</span><input name="rename-pattern" value="{name}" maxlength="300"><small>{name} · {number} · {seq:3}. Original extensions are appended.</small></label><label class="field"><span>Start sequence</span><input name="rename-start" type="number" min="0" max="999999999" value="1"></label></div><div class="rename-replacement"><label class="field"><span>Find in original name · literal</span><input name="rename-find" maxlength="240"></label><label class="field"><span>Replace with</span><input name="rename-replace" maxlength="240"></label><button class="btn" type="button" data-rename-generate>${icon('refresh',14)}Generate names</button></div><p class="small muted">Generation always uses the original selection order and filenames, not a previous generated result.</p></details><div class="rename-list" role="group" aria-label="Before and after filenames">${sources.map((d,i)=>`<div class="rename-row" data-rename-row="${e(d.id)}"><div class="rename-original"><span class="rename-order">${i+1}</span><span><strong>${e(d.name)}</strong><small>${e(d.number)} · ${e(folderPath(S(),d.folderId)||'Project root')}</small></span></div><span class="rename-arrow" aria-hidden="true">→</span><label class="field"><span>New filename</span><input data-rename-name value="${e(d.name)}" required maxlength="240" aria-label="New filename for ${e(d.name)}"></label><span data-rename-row-status>Unchanged</span></div>`).join('')}</div><label class="field mt16"><span>Reason <b>*</b></span><input name="rename-reason" required maxlength="500" placeholder="For example: align filenames with the handover register"></label><div class="rename-validation"><button class="btn" type="button" data-rename-validate>${icon('shield',14)}Validate names</button><span role="status" data-rename-status>No filenames will change until the batch is validated and applied.</span></div><div data-rename-preview></div>`;
  const read=()=>({projectId:sources[0].projectId,reason:form.elements['rename-reason'].value,items:origin.map((row,i)=>({...row,name:form.querySelectorAll('[data-rename-name]')[i].value}))});
  const invalidate=(message='Names changed. Validate the complete batch again.')=>{serial++;approved=null;signature='';if(!form)return;form.querySelector('[type=submit]').disabled=true;form.querySelector('[data-rename-status]').textContent=message;form.querySelector('[data-rename-preview]').replaceChildren();};
  function rowLabels(){form.querySelectorAll('[data-rename-row]').forEach((row,i)=>{const changed=row.querySelector('input').value.trim()!==sources[i].name;row.classList.toggle('is-changing',changed);row.querySelector('[data-rename-row-status]').textContent=changed?'Will rename':'Unchanged';});}
  function changed(){invalidate('Workspace changed. Revalidate before applying. Changed sources may require reopening this editor.');if(!same()||sources.some(d=>!explorerCan(S(),actorId,'write','document',d.id))){dialog?.close();}}
  dialog=ctx.formDialog('Rename documents',body,async()=>{
    if(!same())throw new Error('Workspace or account changed. Reopen this editor.');
    if(!approved||JSON.stringify(read())!==signature||S().revision!==approved.sourceRevision)throw new Error('Validate these exact names at the current workspace revision first.');
    const out=await engine.run('document.bulkRename',approved.payload);ctx.onRenamed?.(out);toast(`${out.renamed.length} document${out.renamed.length===1?'':'s'} renamed in one transaction.`);
  },{wide:true,label:'Apply validated names',canSubmit:()=>!!approved&&same()&&S().revision===approved.sourceRevision&&JSON.stringify(read())===signature,onMount(f,d){form=f;form.querySelector('[type=submit]').disabled=true;
    form.addEventListener('input',()=>{invalidate();rowLabels();});form.addEventListener('change',()=>invalidate());
    form.querySelector('[data-rename-generate]').onclick=()=>{try{const names=suggestRenames(sources,{pattern:form.elements['rename-pattern'].value,find:form.elements['rename-find'].value,replace:form.elements['rename-replace'].value,start:Number(form.elements['rename-start'].value)});form.querySelectorAll('[data-rename-name]').forEach((el,i)=>el.value=names[i].name);invalidate('Names generated. Review each row, then validate.');rowLabels();}catch(error){invalidate(error.message);}};
    form.querySelector('[data-rename-validate]').onclick=async()=>{invalidate('Validating permissions, source versions and all final filenames…');const ticket=++serial,revision=S().revision,request=read(),requestSignature=JSON.stringify(request),button=form.querySelector('[data-rename-validate]');button.disabled=true;
      try{if(!same())throw new Error('Workspace or account changed. Reopen this editor.');if(!form.reportValidity())throw new Error('Complete all required fields.');
        const response=repo.kind==='server'?await fetchJSON((repo.base||'/api')+'/explorer/rename-preview',{method:'POST',body:JSON.stringify({...request,expectedRevision:revision})}):previewDocumentRename(engine.state,actorId,request);
        if(ticket!==serial||!d.open)return;if(!same()||S().revision!==revision)throw new Error('The workspace changed while validating. Try again.');if(!response.allowed)throw new Error(response.error||'Rename denied.');
        if(response.sourceRevision!==revision||JSON.stringify(response.payload)!==JSON.stringify({...request,baseRevision:revision})||!Array.isArray(response.rows)||response.rows.length!==sources.length||response.rows.some((r,i)=>r.id!==request.items[i].id||r.from!==request.items[i].expectedName||r.to!==request.items[i].name.trim()))throw new Error('The rename preview does not match this exact request.');
        approved=response;signature=requestSignature;const count=response.rows.filter(r=>r.changed).length;form.querySelector('[type=submit]').disabled=false;form.querySelector('[data-rename-status]').textContent=`${count} rename${count===1?'':'s'} validated at workspace revision ${revision}.`;
        form.querySelector('[data-rename-preview]').innerHTML=`<div class="rename-success">${icon('check',18)}<strong>${count} filename change${count===1?'':'s'} · one transaction</strong><span>Original bytes and history retained. Final-name swaps are supported.</span></div>`;
      }catch(error){if(ticket===serial&&d.open)invalidate(error.message);}finally{if(button.isConnected)button.disabled=false;}
    };
  }});dialog.classList.add('rename-dialog');const watch=setInterval(()=>{if(dialog.open&&!same())dialog.close();},500);engine.addEventListener('change',changed);dialog.addEventListener('close',()=>{clearInterval(watch);serial++;approved=null;engine.removeEventListener('change',changed);},{once:true});return dialog;
 }
 return {open};
}
