import { visibleDocumentSets, resolveDocumentSet, setMembers, setVersion } from '../packages/document-sets/index.js';
import { exportDocumentSetArchive } from '../packages/document-sets/archive.js';
import { explorerCan } from '../packages/explorer/index.js';
import { currentVersion } from '../packages/core/index.js';
import { escapeHTML as e, icon, fileBadge, statusBadge, formatBytes, openDialog, formField as field, downloadBlob, toast, emptyState } from '../packages/controls/index.js';
/** Responsive set manager. Membership edits and freeze operations use the reducer. */
export function createDocumentSetFeatures(ctx){
 const E=ctx.getEngine,S=ctx.getState,U=ctx.getUI,b=ctx.button;
 const can=(p,id)=>explorerCan(S(),E().actorId,p,'project',id);
 let chosen='',identity='';
 const current=()=>visibleDocumentSets(S(),E().actorId,U().projectId);
 const records=(id)=>resolveDocumentSet(S(),E().actorId,id,{allowRecycled:true});
 const note=text=>`<div class="note-box mb16">${icon('shield',16)}<span>${e(text)}</span></div>`;
 const identityKey=()=>[E().repository.kind,E().repository.base||E().repository.identity||'',S().id,E().actorId].join(':');
 function sync(){const key=identityKey();if(key!==identity){identity=key;chosen='';}if(!current().some(s=>s.id===chosen))chosen=current()[0]?.id||'';}
 function memberList(id){const resolved=records(id);return `<div class="set-members-table table-wrap"><table><thead><tr><th>Order</th><th>Document</th><th>Binding</th><th>Selected revision</th><th>Readiness</th><th></th></tr></thead><tbody>${resolved.records.map((r,i)=>`<tr data-set-member="${e(r.documentId)}"><td>${String(i+1).padStart(2,'0')}</td><td><div class="row gap8">${fileBadge(r.name)}<span class="truncate"><strong>${e(r.name)}</strong><small class="file-subtitle">${e(r.number)} · ${e(r.path)}</small></span></div></td><td><span class="badge ${r.binding==='fixed'?'blue':'gray'}">${r.binding==='fixed'?'Fixed revision':'Latest revision'}</span></td><td><strong class="mono">${e(r.revision)}</strong><small class="file-subtitle">${formatBytes(r.size)}</small></td><td>${r.recycled?statusBadge('Recycled'):r.newerRevision?'<span class="badge amber">Newer: '+e(r.latestRevision)+'</span>':'<span class="badge green">Current</span>'}</td><td>${b('View','preview-version','eye',`data-id="${e(r.documentId)}" data-version="${e(r.versionId)}"`,'small')}</td></tr>`).join('')||'<tr><td colspan="6">This set is empty. Edit its membership to add documents.</td></tr>'}</tbody></table></div>`;}
 function detail(id){const r=records(id),set=r.set;return `<section class="set-details"><div class="set-detail-header"><div><span class="eyebrow">${set.locked?'LOCKED PACKAGE':'CONTROLLED COLLECTION'} · DEFINITION ${r.version}</span><h2>${e(set.name)}</h2><p>${e(set.description||'Ordered references without duplicate files.')}</p></div>${statusBadge(set.locked?'Locked':'Editable')}</div><div class="set-summary-strip"><span><strong>${r.records.length}</strong> members</span><span><strong>${r.records.filter(m=>m.binding==='fixed').length}</strong> fixed</span><span><strong>${r.newerCount}</strong> newer versions</span><span><strong>${formatBytes(r.totalBytes)}</strong> original bytes</span></div><div class="set-commandbar">${!set.locked&&can('write',set.projectId)?b('Edit members','set-edit','edit',`data-id="${e(id)}"`):''}${can('manage',set.projectId)?b(set.locked?'Unlock set':'Lock & pin set',set.locked?'set-unlock':'set-lock','lock',`data-id="${e(id)}"`):''}${b('Export ZIP','set-export','download',`data-id="${e(id)}"`,'primary')}${b('Manifest','set-manifest','list',`data-id="${e(id)}"`)}${b('Deliver','set-deliver','send',`data-id="${e(id)}"`)}${!set.locked&&can('write',set.projectId)?b('Delete set','set-delete','trash',`data-id="${e(id)}"`,'text'):''}</div>${set.locked?note('This manager-locked set retains exact revisions, names and paths from the locking operation. Later file revisions do not replace these members. Unlocking is audited and leaves the fixed bindings in place.'):note('Latest bindings follow future check-ins. Fixed bindings preserve a revision. A set is not an access grant; every member must remain readable.')}${memberList(id)}</section>`;}
 function page(){sync();const sets=current(),total=sets.reduce((n,s)=>n+s.documentIds.length,0);return ctx.heading('Document sets','Live collections. Exact revisions. One controlled package.',can('write',U().projectId)?b('New document set','set-new','plus','','primary'):'')+`<div class="sets-workbench"><aside class="sets-catalog"><div class="sets-catalog-heading"><strong>Project collections</strong><span>${sets.length}</span></div>${sets.map(set=>`<button class="set-catalog-item ${chosen===set.id?'selected':''}" data-action="set-select" data-id="${e(set.id)}" aria-pressed="${chosen===set.id}">${icon(set.locked?'lock':'layers',20)}<span><strong>${e(set.name)}</strong><small>${set.documentIds.length} documents · ${set.locked?'Locked':'Live / fixed'} · v${setVersion(set)}</small></span>${icon('chevron',15)}</button>`).join('')||'<p class="muted">No sets in this project yet.</p>'}<div class="sets-catalog-note">${total} document memberships<br>No original files are duplicated.</div></aside>${chosen?detail(chosen):emptyState('Organize a delivery package','Add documents from any folder in this project, choose revision bindings, and preserve their order.',b('Create a document set','set-new','plus','','primary'))}</div>`;}
 function edit(id='',selected=[...U().selection]){
  sync();
  const existing=id?records(id).set:null;if(existing?.locked)throw new Error('Unlock this set before editing.');
  const initialEngine=E(),initialActor=E().actorId,initialIdentity=identityKey(),projectId=existing?.projectId||U().projectId;
  let members=existing?setMembers(existing):selected.map(documentId=>({documentId,versionId:null}));
  const available=S().documents.filter(d=>d.projectId===projectId&&!d.deletedAt),liveDocs=()=>S().documents.filter(d=>d.projectId===projectId&&!d.deletedAt);
  let query='';
  const row=(m,i)=>{const d=available.find(d=>d.id===m.documentId)||S().documents.find(d=>d.id===m.documentId);return `<div class="set-member-editor" data-set-edit-member="${e(m.documentId)}"><span class="set-order">${String(i+1).padStart(2,'0')}</span>${fileBadge(d?.name||'Missing')}<span class="set-edit-filename"><strong>${e(d?.name||'Unavailable document')}</strong><small>${e(d?.number||'')}</small></span><label><span class="sr-only">Revision for ${e(d?.name||'document')}</span><select data-set-binding="${e(m.documentId)}"><option value="" ${!m.versionId?'selected':''}>Latest revision</option>${(d?.versions||[]).map(v=>`<option value="${e(v.id)}" ${m.versionId===v.id?'selected':''}>Fixed · ${e(v.label)}</option>`).join('')}</select></label><span class="set-order-actions"><button type="button" class="icon-button" data-member-up="${i}" aria-label="Move ${e(d?.name||'document')} earlier" ${i?'':'disabled'}>${icon('up')}</button><button type="button" class="icon-button" data-member-down="${i}" aria-label="Move ${e(d?.name||'document')} later" ${i===members.length-1?'disabled':''}>${icon('down')}</button><button type="button" class="icon-button" data-member-remove="${i}" aria-label="Remove ${e(d?.name||'document')} from set">${icon('close')}</button></span></div>`;};
  const dialog=ctx.formDialog(existing?'Edit document set':'New document set',note('Choose an ordered list of documents. Fixed bindings select an exact historical revision. Use the move buttons on touch screens or with a keyboard; no dragging is required.')+`<div class="form-grid">${field('Set name','name',existing?.name||'',{required:true})}${field('Description','description',existing?.description||'')}</div><div class="set-members-heading"><h3>Ordered members</h3><button type="button" class="btn small" data-set-pin-all>Pin current revisions</button><button type="button" class="btn small" data-set-live-all>Use latest for all</button></div><div data-set-members-editor></div><h3 class="mt24">Add project documents</h3><label class="field mt16"><span>Find documents</span><input type="search" data-set-find placeholder="Filter by filename, number or title"></label><div data-set-candidates class="set-candidates"></div>`,async(data)=>{
   if(E()!==initialEngine||E().actorId!==initialActor||identityKey()!==initialIdentity)throw new Error('Workspace or account changed. Reopen the editor.');
   const payload={projectId,name:data.get('name'),description:data.get('description'),members:structuredClone(members)};if(existing)Object.assign(payload,{id:existing.id,expectedVersion:setVersion(existing)});
   const result=await E().run(existing?'set.update':'set.create',payload);chosen=existing?.id||result;ctx.navigate('sets');toast('Document set saved without copying files.');
  },{wide:true,label:'Save set',onMount(form){
   const update=()=>{form.querySelector('[data-set-members-editor]').innerHTML=members.map(row).join('')||'<p class="muted">No members selected.</p>';const candidates=available.filter(d=>!members.some(m=>m.documentId===d.id)&&(d.name+' '+d.number+' '+d.title).toLowerCase().includes(query));form.querySelector('[data-set-candidates]').innerHTML=candidates.slice(0,100).map(d=>`<button type="button" class="set-candidate" data-member-add="${e(d.id)}">${icon('plus',18)}${fileBadge(d.name)}<span><strong>${e(d.name)}</strong><small>${e(d.number)} · ${e(currentVersion(d).label)}</small></span></button>`).join('')+(candidates.length>100?'<p>Showing first 100 matches. Refine your search.</p>':'');};
   form.querySelector('[data-set-find]').addEventListener('input',ev=>{query=ev.target.value.toLowerCase();update();});
   form.addEventListener('change',ev=>{const id=ev.target.dataset.setBinding;if(id)members.find(m=>m.documentId===id).versionId=ev.target.value||null;});
   form.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;let changed=true;
    if(b.hasAttribute('data-member-add')){if(members.length>=1000)return toast('A set supports up to 1,000 members.','error');if(!members.some(m=>m.documentId===b.dataset.memberAdd))members.push({documentId:b.dataset.memberAdd,versionId:null});}
    else if(b.hasAttribute('data-member-remove'))members.splice(Number(b.dataset.memberRemove),1);
    else if(b.hasAttribute('data-member-up')){const i=Number(b.dataset.memberUp);if(i>0)[members[i-1],members[i]]=[members[i],members[i-1]];}
    else if(b.hasAttribute('data-member-down')){const i=Number(b.dataset.memberDown);if(i<members.length-1)[members[i+1],members[i]]=[members[i],members[i+1]];}
    else if(b.hasAttribute('data-set-pin-all'))members=members.map(m=>({documentId:m.documentId,versionId:currentVersion(liveDocs().find(d=>d.id===m.documentId)||available.find(d=>d.id===m.documentId)).id}));
    else if(b.hasAttribute('data-set-live-all'))members=members.map(m=>({...m,versionId:null}));else changed=false;
    if(changed){ev.preventDefault();const name=b.getAttribute('aria-label');update();if(name)[...form.querySelectorAll('[aria-label]')].find(x=>x.getAttribute('aria-label')===name)?.focus();}
   });update();
  }});return dialog;
 }
 function open(id){const set=records(id).set;identity=identityKey();chosen=id;ctx.navigate('sets',{projectId:set.projectId});}
 function lock(id,unlock=false){const set=records(id).set,initialEngine=E(),actor=E().actorId;return ctx.formDialog(unlock?'Unlock document set':'Lock & pin document set',note(unlock?'This enables editing but retains every fixed revision binding. Existing transmittals are unchanged.':'Every Latest member will be pinned to its current revision, and filenames and paths will be frozen. The set definition becomes read-only until a manager unlocks it.')+field('Reason','reason','',{required:true,type:'textarea'}),async(data)=>{if(E()!==initialEngine||E().actorId!==actor)throw new Error('Account or workspace changed.');await E().run(unlock?'set.unlock':'set.lock',{id,expectedVersion:setVersion(set),reason:data.get('reason')});ctx.render();toast(unlock?'Set unlocked; fixed revisions retained.':'Set locked and every member pinned.');},{label:unlock?'Unlock set':'Lock & pin'});}
 async function exportSet(id){const r=records(id),initial=E(),actor=E().actorId,controller=new AbortController();let finished=false;const dialog=openDialog({title:'Export document set',body:`<p>${e(r.set.name)} · ${r.records.length} original files</p><p data-set-progress role="status">Checking revisions and download permissions…</p><button class="btn" data-set-cancel>Cancel export</button>`,onClose(){if(!finished)controller.abort();}});dialog.querySelector('[data-set-cancel]').onclick=()=>dialog.close();
  try{let zip;
   if(initial.repository.kind==='server'){
    const response=await fetch((initial.repository.base||'/api')+'/sets/export',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,expectedVersion:r.version,expectedRevision:initial.state.revision}),signal:controller.signal});if(!response.ok){const problem=await response.json();throw new Error(problem.error||'Set export failed.');}zip=await response.blob();
   }else{const output=await exportDocumentSetArchive(()=>{if(E()!==initial||E().actorId!==actor)throw new Error('Workspace or account changed.');return S();},actor,id,initial.repository,{expectedVersion:r.version,signal:controller.signal,onProgress:p=>{dialog.querySelector('[data-set-progress]').textContent=`Verified ${p.done} of ${p.total}: ${p.name}`;}});zip=output.zip;}
   controller.signal.throwIfAborted();if(E()!==initial||E().actorId!==actor)throw new Error('Workspace or account changed.');finished=true;downloadBlob(zip,r.set.name+'.zip');dialog.close();toast('Verified set package exported.');
  }catch(error){if(error.name==='AbortError')return;dialog.querySelector('[data-set-progress]').textContent=error.message;dialog.querySelector('[data-set-cancel]').textContent='Close';throw error;}
 }
 function deliver(id){const r=records(id),initial=E(),actor=E().actorId;return ctx.formDialog('Prepare delivery from set',note('The draft will freeze this set’s selected revisions, not substitute newer file versions. Existing share and download permissions are required for all members.')+`<p><strong>${e(r.set.name)}</strong> · ${r.records.length} members · definition ${r.version}</p><div class="form-grid">${field('Package title','title',r.set.name,{required:true,full:true})}${field('Purpose','purpose','For information',{options:['For information','For coordination','For approval','For construction','For record']})}${field('Response due','dueDate','',{type:'date'})}${field('Recipients','recipients','',{required:true,full:true,placeholder:'recipient@example.com'})}${field('Cover message','message','',{type:'textarea',full:true})}</div>`,async(data)=>{if(E()!==initial||E().actorId!==actor)throw new Error('Workspace or account changed.');await E().run('transmittal.create',{projectId:r.set.projectId,setId:id,expectedSetVersion:r.version,...Object.fromEntries(data)});ctx.navigate('transmittals');toast('Delivery draft pins the selected set revisions.');},{label:'Create delivery draft'});}
 async function handleAction(action,button){const id=button?.dataset.id;
  if(action==='new-set'||action==='set-new'){edit();return true;}if(action==='edit-set'||action==='set-edit'){edit(id);return true;}if(action==='open-set'||action==='set-open'||action==='set-select'){open(id);return true;}
  if(action==='transmit-set'||action==='set-deliver'){deliver(id);return true;}
  if(!action.startsWith('set-'))return false;
  if(action==='set-lock')lock(id);else if(action==='set-unlock')lock(id,true);else if(action==='set-export')await exportSet(id);else if(action==='set-manifest'){const r=records(id);downloadBlob(new Blob([JSON.stringify({format:'civora-set-manifest',version:1,workspaceId:S().id,...r},null,2)],{type:'application/json'}),r.set.name+'-manifest.json');}
  else if(action==='set-delete'){const set=records(id).set,initial=E(),actor=E().actorId;ctx.confirmAction('Delete document set','This removes only the collection. Original documents and issued packages remain unchanged.',async()=>{if(E()!==initial||E().actorId!==actor)throw new Error('Workspace or account changed.');await E().run('set.delete',{id,expectedVersion:setVersion(set)});chosen='';ctx.render();},{danger:true,label:'Delete set'});}else return false;return true;
 }
 return {page,handleAction,edit,open};
}
