import { createRenameFeatures } from './document-rename.js';
import { APP_VERSION } from './version.js';
import { createCopyFeatures } from './document-copy.js';
import { bindLongPress } from '../packages/interactions/index.js';
import { visibleDocumentSets, setVersion } from '../packages/document-sets/index.js';
import { EXPLORER_PREFERENCE_SCHEMA, migrateExplorerPreferences, defaultExplorerLayout, normalizeExplorerLayout, explorerPresentationPreset, explorerDetailView, defaultExplorerView, normalizeExplorerView, explorerColumns, explorerValue, queryExplorer, visibleExplorerViews, visibleExplorerBookmarks, explorerCan, folderPath, ExplorerHistory, explorerSelection, explorerLink, resolveExplorerLink, FILTER_OPERATORS } from '../packages/explorer/index.js';
import { currentVersion, previewDocumentMove, userName } from '../packages/core/index.js';
import { fetchJSON } from '../packages/storage/index.js';
import { collectDroppedFiles } from '../packages/filesystem/drop.js';
import { mountPreview } from '../packages/viewer/index.js';
import { escapeHTML as e, icon, fileBadge, statusBadge, avatar, formatBytes, formatDate, relativeTime, emptyState, openDialog, toast, downloadBlob, formField as field } from '../packages/controls/index.js';
/** Explorer is a presentation adapter. All writes go through WorkspaceEngine. */
export function createExplorer(ctx){
 const E=ctx.getEngine,S=ctx.getState,U=ctx.getUI,R=ctx.render;
 let identity='',config=defaultExplorerView(),layout={},expanded=new Set(),activeId='',anchor=null,activeView='',clipboard=null,recents=[],navHistory=new ExplorerHistory(),pageResult=null,filterValues={},treeSearch='',ribbonTab='home',inspectorTab='properties',controller=null,preview=null,previewTicket=0,scroll={x:0,y:0,tree:0},debounce=null,popup=null,selectedGroup='',focusAfter='',lastRowClick=null;
 let touchSelecting=false,treeTypeahead='',treeTypeaheadAt=0;
 const mobileCards=()=>!!ctx.mobile?.cards;
 const baseLayout=defaultExplorerLayout;
 const prefKey=()=>`civora-explorer-ui:${identity}`;
 const err=error=>toast(error?.message||String(error),'error');
 const run=promise=>Promise.resolve(promise).catch(err);
 const project=()=>S().projects.find(p=>p.id===U().projectId);
 const doc=id=>S().documents.find(d=>d.id===id&&!d.deletedAt);
 const selected=()=>[...U().selection].map(doc).filter(Boolean);
 const focused=()=>doc(activeId);
 const can=(permission,scope,id)=>explorerCan(S(),E().actorId,permission,scope,id);
 function form(title,body,submit,options={}){return ctx.formDialog(title,body,(data,element,dialog)=>submit(Object.fromEntries(data),element,dialog),{...options,onMount:options.onMount?(_form,dialog)=>options.onMount(dialog):undefined});}
 const b=(label,action,glyph='',attrs='',cls='')=>ctx.button(label,action,glyph,attrs,cls);
 const ib=(glyph,action,label,attrs='')=>`<button class="icon-button" data-action="${action}" title="${e(label)}" aria-label="${e(label)}" ${attrs}>${icon(glyph,16)}</button>`;
 const note=text=>`<div class="note-box mb16">${icon('shield',16)}<span>${e(text)}</span></div>`;
 const copyFeature=createCopyFeatures({...ctx,onCopied(response,projectId,folderId){go(projectId,folderId);U().selection=new Set(response.copied.map(i=>i.id));activeId=response.copied[0]?.id||'';R();}});
 function copyDialog(ids=[...U().selection]){return copyFeature.open(ids);}
 const renameFeature=createRenameFeatures({...ctx,onRenamed(){R();}});
 function renameDialog(ids=[...U().selection]){return renameFeature.open(ids);}
 function persist(){ctx.safeWrite(prefKey(),{schema:EXPLORER_PREFERENCE_SCHEMA,config,layout,expanded:[...expanded].slice(0,1000),recents:recents.slice(0,30)});}
 function sync(){
  const state=S(),repo=E().repository,key=JSON.stringify([repo.kind,repo.base||repo.name||repo.identity||'',state.id,state.createdAt||'',E().actorId]);
  if(identity!==key){selectedGroup='';lastRowClick=null;identity=key;
   const current=ctx.safeRead(prefKey(),null),legacy=ctx.safeRead(`civora-explorer-v6:${identity}`,{});
   const prefs=migrateExplorerPreferences(current??legacy,U().projectId);layout=prefs.layout;config=prefs.config;
   expanded=new Set(prefs.expanded);recents=prefs.recents;activeId='';anchor=null;activeView='';filterValues={};clipboard=null;navHistory=new ExplorerHistory();U().selection.clear();persist();
  }
  if(config.projectId!==U().projectId){expanded.add('project:'+U().projectId);config=explorerDetailView(U().projectId);activeView='';activeId='';anchor=null;filterValues={};U().selection.clear();}
  if(U().folderId&&!state.folders.some(f=>f.id===U().folderId&&f.projectId===U().projectId))U().folderId='';
  config.folderId=U().folderId||null;config.query=U().query||'';
  if(activeId&&!doc(activeId))activeId='';for(const id of [...U().selection])if(!doc(id)||doc(id).projectId!==U().projectId)U().selection.delete(id);
  recents=recents.filter(id=>doc(id));if(!navHistory.current)navHistory.visit(location());
 }
 function location(){return {projectId:U().projectId,folderId:U().folderId||'',query:U().query||'',viewId:activeView};}
 function remember(id){recents=[id,...recents.filter(x=>x!==id)].slice(0,30);persist();}
 function writeAddress(){try{history.replaceState(null,'',locationURL());}catch{}}
 function locationURL(){return `${globalThis.location.pathname}${globalThis.location.search}${explorerLink(S(),{projectId:U().projectId,folderId:U().folderId,documentId:activeId})}`;}
 function go(projectId,folderId='',{record=true,viewId='',documentId='',query=''}={}){
  const prj=S().projects.find(p=>p.id===projectId);if(!prj)throw new Error('Project no longer available.');
  document.body.classList.remove('ex-tree-overlay');touchSelecting=false;selectedGroup='';U().route='documents';U().projectId=projectId;U().folderId=folderId||'';U().query=query;U().stateFilter='';U().discipline='';U().page=0;U().selection.clear();anchor=null;activeId=documentId;filterValues={};activeView=viewId;
  const view=visibleExplorerViews(S(),E().actorId).find(v=>v.id===viewId);
  config=view?normalizeExplorerView(view.config):normalizeExplorerView({...config,projectId,folderId:folderId||null,query,filters:[],includeSubfolders:folderId?false:true,rootOnly:false});
  if(view){U().folderId=config.folderId||'';U().query=config.query;U().stateFilter=config.quickFilters.state;U().discipline=config.quickFilters.discipline;filterValues={...config.columnFilters};layout.columnFilters=Object.keys(filterValues).some(k=>filterValues[k]);}if(documentId){U().selection.add(documentId);remember(documentId);}
  expanded.add('project:'+U().projectId);for(let id=U().folderId;id;){expanded.add(id);id=S().folders.find(f=>f.id===id)?.parentId;}
  if(record)navHistory.visit(location());scroll={x:0,y:0,tree:scroll.tree};persist();writeAddress();R();
 }
 function navigateHistory(forward){const target=forward?navHistory.forward():navHistory.back();if(!target)return;try{go(target.projectId,target.folderId,{record:false,viewId:target.viewId,query:target.query});}catch(error){err(error);}}
 function setFocus(id,event={}){const out=explorerSelection(pageResult.ids,U().selection,id,{toggle:!!(event.ctrlKey||event.metaKey),range:!!event.shiftKey,anchor});U().selection=out.selection;anchor=out.anchor;activeId=id;remember(id);writeAddress();focusAfter=id;R();}
 function currentConfig(){return {...config,columnFilters:filterValues,quickFilters:{state:U().stateFilter||'',discipline:U().discipline||''}};}
 function columnLabel(key){return explorerColumns(project()).find(c=>c.key===key)?.label||key.replace('metadata.','');}
 function dataValue(d,key){const value=explorerValue(S(),d,key);if(key==='name')return `<div class="ex-file-cell">${fileBadge(d.name)}<span><strong>${e(d.name)}</strong><small>${e(d.title)}</small></span>${d.checkedOutBy?`<span class="ex-lock" title="Checked out to ${e(userName(S(),d.checkedOutBy))}">${icon('lock',12)}</span>`:''}</div>`;if(key==='state')return statusBadge(value);if(key==='size')return e(formatBytes(value));if(key==='modifiedAt')return `<span title="${e(value)}">${e(formatDate(value,{year:'numeric'}))}</span>`;if(key==='dueDate')return e(value||'—');if(key==='revision'||key==='number')return `<span class="mono">${e(value||'—')}</span>`;return e(value===''?'—':value);}
 function menuItem(label,action,glyph='',attrs='',disabled=false){return {label,action,glyph,attrs,disabled};}
 function menus(name){const d=focused(),one=!!d,ids=selected(),many=ids.length>0;
  switch(name){
   case'File':return [menuItem('New project','new-project','plus'),menuItem('New folder','new-folder','folder'),menuItem('Upload documents…','upload','upload'),'separator',menuItem('Local system','ex-route','folder','data-route="local"'),menuItem('Storage & connections','ex-route','database','data-route="connections"'),menuItem('Export document register','export-register','download')];
   case'Datasource':return [menuItem('Storage & connections…','ex-route','database','data-route="connections"'),menuItem('All projects','ex-route','grid','data-route="projects"'),menuItem('New project…','new-project','plus'),'separator',menuItem('Refresh datasource','ex-refresh','refresh'),menuItem('Local working copies','ex-route','folder','data-route="local"'),menuItem('Workspace settings','ex-route','settings','data-route="settings"')];
   case'Folder':return [menuItem('New folder…','new-folder','folder'),menuItem('Folder properties…','edit-folder','edit','',!U().folderId),menuItem('Parent folder','ex-up','up','',!U().folderId),'separator',menuItem('Pin this location','ex-pin-location','star'),menuItem('Copy location link','ex-copy-link','link'),menuItem('Paste / preview move…','ex-paste','folder','',!clipboard),menuItem('Upload documents…','upload','upload'),menuItem('Export document register','export-register','download')];
   case'Window':return [menuItem('All workspaces…','mobile-more','grid'),'separator',...ctx.navItems.map(([route,glyph,label])=>menuItem(label,'ex-route',glyph,`data-route="${route}"`)),menuItem('Settings','ex-route','settings','data-route="settings"')];
   case'Document':return [menuItem('Open document','open-document','external',`data-id="${e(d?.id||'')}"`,!one),menuItem('Properties','edit-document','edit',`data-id="${e(d?.id||'')}"`,!one),menuItem('Download original','download-document','download',`data-id="${e(d?.id||'')}"`,!one||!can('download','document',d?.id)),'separator',menuItem('Check out','checkout','lock',`data-id="${e(d?.id||'')}"`,!one||!!d.checkedOutBy||d.state!=='Work in progress'||!can('write','document',d.id)),menuItem('Check in…','checkin','upload',`data-id="${e(d?.id||'')}"`,!one||d.checkedOutBy!==E().actorId),menuItem('Release checkout…','release-checkout','unlock',`data-id="${e(d?.id||'')}"`,!one||!d.checkedOutBy),'separator',menuItem('Copy as new documents…','ex-copy','copy','',!many||ids.some(x=>!can('download','document',x.id))),menuItem('Rename selected…','ex-rename','edit','',!many||ids.some(x=>!can('write','document',x.id))),menuItem('Compare revisions…','compare-versions','layers',`data-id="${e(d?.id||'')}"`,!one||d.versions.length<2||!can('download','document',d.id)),menuItem('Move selected…','ex-move','folder','',!many),menuItem('Cut selected','ex-cut','copy','',!many),menuItem('Paste / preview move…','ex-paste','folder','',!clipboard),menuItem('Copy address link','ex-copy-link','link'),menuItem('Add / remove shortcut','ex-pin','star','',!one),menuItem('Recycle document…','recycle-document','trash',`data-id="${e(d?.id||'')}"`,!one||!can('write','document',d.id))];
   case'View':return [menuItem('Explorer appearance…','ex-appearance','settings'),menuItem('Standard toolbar','ex-command-style',layout.commandStyle==='standard'?'check':'minus','data-style="standard"'),menuItem('Ribbon toolbar','ex-command-style',layout.commandStyle==='ribbon'?'check':'minus','data-style="ribbon"'),'separator',menuItem('Columns, sorting & density…','ex-columns','grid'),menuItem('Advanced search…','ex-filter','search'),menuItem('Save Explorer view…','ex-save','star'),menuItem('Manage saved views…','ex-manage-views','settings'),'separator',menuItem('Preview below list','ex-dock','rectangle','data-position="bottom"'),menuItem('Preview on right','ex-dock','rectangle','data-position="right"'),menuItem('Hide preview pane','ex-dock','close','data-position="hidden"'),menuItem('Show / hide tree','ex-toggle-tree','folder'),menuItem('Show / hide column filters','ex-toggle-filters','filter'),menuItem('Show / hide command toolbar','ex-toggle-ribbon','menu'),menuItem('Show / hide workspace rail','ex-toggle-rail','grid'),menuItem('Grid lines','ex-row-lines',layout.rowLines?'check':'minus'),menuItem('Secondary file descriptions','ex-file-descriptions',layout.fileDescriptions?'check':'minus'),menuItem('Input & responsive layout…','mobile-preferences','settings'),menuItem('Light / dark appearance','toggle-theme','moon'),menuItem('Reset Explorer layout','ex-reset','refresh')];
   case'Tools':return [['Document control','control','shield'],['Workflow automation','automation','workflow'],['Local working copies','local','folder'],['Model coordination','models','layers'],['Rendition studio','renditions','grid'],['People & access','members','users'],['Operations & security','operations','shield']].map(([label,route,glyph])=>menuItem(label,'ex-route',glyph,`data-route="${route}"`));
   case'Workspace':return ctx.navItems.map(([route,glyph,label])=>menuItem(label,'ex-route',glyph,`data-route="${route}"`));
   case'Help':return [menuItem('Explorer shortcuts','ex-shortcuts','book'),menuItem('Capabilities and boundaries','help','help')];
   default:return [];
  }
 }
 function openMenu(name,anchorElement,point=null,items=null){
  closeMenu();anchorElement?.setAttribute('aria-expanded','true');const list=items||menus(name),menu=document.createElement('div');menu.className='ex-context';menu.setAttribute('role','menu');menu.setAttribute('aria-label',name);
  menu.innerHTML=`<div class="ex-menu-label">${e(name)}</div>`+list.map(item=>item==='separator'?'<div role="separator" class="ex-menu-separator"></div>':`<button role="menuitem" data-action="${e(item.action)}" ${item.attrs} ${item.disabled?'disabled':''}>${icon(item.glyph||'file',15)}<span>${e(item.label)}</span></button>`).join('');
  if(ctx.mobile?.small){const dialog=openDialog({title:name==='Document'?'Document actions':name+' commands',body:menu.innerHTML,onClose(){if(popup?.element===dialog)popup=null;}});dialog.classList.add('ex-action-sheet');popup={element:dialog,anchor:anchorElement};dialog.querySelector('.dialog-body').addEventListener('click',ev=>{if(ev.target.closest('[data-action]'))closeMenu(false);});return;}
  document.body.append(menu);popup={element:menu,anchor:anchorElement};const rect=anchorElement?.getBoundingClientRect()||{left:20,bottom:50};menu.style.left=Math.max(6,Math.min(point?.x??rect.left,innerWidth-menu.offsetWidth-8))+'px';menu.style.top=Math.max(6,Math.min(point?.y??rect.bottom,innerHeight-menu.offsetHeight-8))+'px';
  menu.querySelector('button:not(:disabled)')?.focus();menu.addEventListener('click',()=>closeMenu(false));menu.addEventListener('keydown',event=>{const buttons=[...menu.querySelectorAll('button:not(:disabled)')],i=buttons.indexOf(document.activeElement);if(['ArrowDown','ArrowUp','Home','End','Escape'].includes(event.key)){event.preventDefault();event.stopPropagation();if(event.key==='Escape'){closeMenu();return;}buttons[event.key==='Home'?0:event.key==='End'?buttons.length-1:(i+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}});
 }
 function closeMenu(restore=true){if(popup){const {element,anchor}=popup;popup=null;anchor?.setAttribute?.('aria-expanded','false');if(element.tagName==='DIALOG')element.close();else element.remove();if(restore)anchor?.focus?.({preventScroll:true});}}
 document.addEventListener('pointerdown',event=>{if(popup&&!popup.element.contains(event.target)&&!event.target.closest('[data-action="ex-menu"]'))closeMenu(false);});
 function standardToolbar(){
  const d=focused(),attr=d?`data-id="${e(d.id)}"`:'',tool=(label,action,glyph,extra='',disabled=false,show=false)=>`<button class="ex-standard-tool ${show?'with-label':''}" data-action="${action}" aria-label="${e(label)}" title="${e(label)}" ${extra} ${disabled?'disabled':''}>${icon(glyph,17)}${show?`<span>${e(label)}</span>`:''}</button>`,sep='<span class="ex-toolbar-separator" role="separator"></span>';
  const body=tool('Upload documents','upload','upload','',false,true)+tool('New folder','new-folder','folder')+sep+
   tool('Open document','open-document','external',attr,!d,true)+tool('Document properties','edit-document','edit',attr,!d)+tool('Download original','download-document','download',attr,!d||!can('download','document',d?.id))+sep+
   tool('Check out','checkout','lock',attr,!d||!!d?.checkedOutBy||d?.state!=='Work in progress'||!can('write','document',d?.id),true)+tool('Check in','checkin','upload',attr,!d||d?.checkedOutBy!==E().actorId,true)+tool('Move selected','ex-move','folder','',!U().selection.size)+sep+
   tool('Copy address link','ex-copy-link','link')+tool('Pin document','ex-pin','star','',!d)+tool('Refresh workspace','ex-refresh','refresh')+sep+
   tool('Search builder','ex-filter','search','',false,true)+tool('Column filters','ex-toggle-filters','filter',`aria-pressed="${layout.columnFilters}"`)+tool('Configure columns','ex-columns','grid')+
   '<span class="grow"></span>'+tool('All workspaces','mobile-more','grid','',false,true)+tool('Explorer appearance','ex-appearance','settings');
  return `${layout.ribbonVisible?`<div class="ex-standard-toolbar" role="toolbar" aria-label="Standard document toolbar">${body}</div>`:''}<div class="ex-mobile-commandbar"><button data-action="ex-menu" data-menu="File">${icon('plus',16)}<span>Create</span></button><button data-action="ex-menu" data-menu="Document">${icon('file',16)}<span>Document</span></button><button data-action="ex-menu" data-menu="View">${icon('grid',16)}<span>View</span></button><button data-action="mobile-more">${icon('more',16)}<span>Tools</span></button></div>`;
 }
 function ribbon(){const d=focused(),attr=d?`data-id="${e(d.id)}"`:'',group=(title,items)=>`<div class="ex-ribbon-group"><div>${items}</div><small>${title}</small></div>`,cmd=(title,action,glyph,extra='',disabled=false)=>b(title,action,glyph,`${extra} ${disabled?'disabled':''}`,'ex-ribbon-command');
  const home=group('CREATE',cmd('Upload','upload','upload')+cmd('New folder','new-folder','folder'))+group('DOCUMENT',cmd('Open','open-document','external',attr,!d)+cmd('Properties','edit-document','edit',attr,!d)+cmd('Download','download-document','download',attr,!d||!can('download','document',d?.id)))+group('VERSION CONTROL',cmd('Check out','checkout','lock',attr,!d||!!d?.checkedOutBy||d?.state!=='Work in progress'||!can('write','document',d?.id))+cmd('Check in','checkin','upload',attr,!d||d?.checkedOutBy!==E().actorId))+group('ORGANIZE',cmd('Move','ex-move','folder','',!U().selection.size)+cmd('Pin','ex-pin','star','',!d)+cmd('Copy link','ex-copy-link','link'));
  const review=group('COORDINATE',cmd('New review','new-review','review','',!U().selection.size)+cmd('Issue / RFI','document-issue','issue',attr,!d)+cmd('Transition','ex-transition','workflow','',!d))+group('DELIVER',cmd('Transmittal','new-transmittal','send','',!U().selection.size)+cmd('Baseline','control-baseline-new','layers','',!U().selection.size)+cmd('Document set','new-set','box','',!U().selection.size))+group('GOVERN',cmd('Bulk properties','control-bulk','edit','',!U().selection.size)+cmd('Editable CSV','control-register-export','download','',!U().selection.size));
  const view=group('DOCUMENT LIST',cmd('Columns','ex-columns','grid')+cmd('Filters','ex-toggle-filters','filter')+cmd('Advanced search','ex-filter','search'))+group('SAVED VIEWS',cmd('Save view','ex-save','star')+cmd('Manage views','ex-manage-views','settings'))+group('LAYOUT',cmd('Preview below','ex-dock','rectangle','data-position="bottom"')+cmd('Preview right','ex-dock','rectangle','data-position="right"')+cmd('Appearance','toggle-theme','moon')+cmd('Reset','ex-reset','refresh'));
  const menu=`<div class="ex-menubar" role="menubar" aria-label="Explorer menus">${['Datasource','Folder','Document','View','Tools','Window','Help'].map(label=>`<button data-action="ex-menu" data-menu="${label}" role="menuitem" aria-haspopup="menu" aria-expanded="false">${label}</button>`).join('')}<span class="grow"></span>${ib('settings','ex-appearance','Explorer appearance')}</div>`;
  if(layout.commandStyle==='standard')return menu+standardToolbar();
  return menu+`<div class="ex-ribbon-tabs" role="tablist" aria-label="Command ribbon">${[['home','Home'],['review','Review & deliver'],['view','View']].map(([id,label])=>`<button role="tab" aria-selected="${ribbonTab===id}" data-action="ex-ribbon-tab" data-tab="${id}">${label}</button>`).join('')}<span class="grow"></span>${ib(layout.ribbonVisible?'up':'down','ex-toggle-ribbon',layout.ribbonVisible?'Collapse ribbon':'Expand ribbon')}</div>${layout.ribbonVisible?`<div class="ex-ribbon" role="tabpanel">${ribbonTab==='home'?home:ribbonTab==='review'?review:view}</div>`:''}`;
 }
 function tree(){
  const state=S(),bookmarks=visibleExplorerBookmarks(state,E().actorId),needle=treeSearch.toLowerCase(),folders=state.folders,byParent=new Map(),matches=new Set();
  for(const f of folders){const k=f.projectId+':'+(f.parentId||'');if(!byParent.has(k))byParent.set(k,[]);byParent.get(k).push(f);if(!needle||f.name.toLowerCase().includes(needle)){let id=f.id;while(id&&!matches.has(id)){matches.add(id);id=folders.find(f=>f.id===id)?.parentId;}}}
  const line=(label,id,scope,depth,children,selected,count=0)=>`<div class="ex-tree-line" style="--level:${depth+1}">${children?ib(expanded.has(scope==='project'?'project:'+id:id)||needle?'minus':'plus','ex-expand','Expand or collapse '+label,`data-id="${e(scope==='project'?'project:'+id:id)}"`):'<span class="ex-tree-spacer"></span>'}<button id="ex-node-${e(id)}" role="treeitem" title="${e(label)}" aria-level="${depth+2}" ${children?`aria-expanded="${expanded.has(scope==='project'?'project:'+id:id)||!!needle}"`:''} aria-selected="${selected}" class="ex-tree-item ${selected?'active':''}" data-tree-target data-action="ex-tree" data-scope="${scope}" data-id="${e(id)}" data-project="${e(scope==='project'?id:folders.find(f=>f.id===id)?.projectId||'')}" ${scope==='folder'?`data-ex-drop="${e(id)}"`:''}>${icon(scope==='project'?'box':'folder',16)}<span>${e(label)}</span>${count?`<small>${count}</small>`:''}</button></div>`;
  const branch=(projectId,parent,depth)=> (byParent.get(projectId+':'+(parent||''))||[]).filter(f=>!needle||matches.has(f.id)).map(f=>{const children=(byParent.get(projectId+':'+f.id)||[]).length>0;return line(f.name,f.id,'folder',depth,children,U().folderId===f.id)+((expanded.has(f.id)||needle)&&children?branch(projectId,f.id,depth+1):'');}).join('');
  const views=visibleExplorerViews(state,E().actorId).filter(v=>v.projectId===U().projectId);
  const projectTree=state.projects.filter(p=>!needle||p.name.toLowerCase().includes(needle)||folders.some(f=>f.projectId===p.id&&matches.has(f.id))).map(p=>line(`${p.code} · ${p.name}`,p.id,'project',0,true,p.id===U().projectId&&!U().folderId,state.documents.filter(d=>d.projectId===p.id&&!d.deletedAt).length)+((expanded.has('project:'+p.id)||needle)?branch(p.id,null,1):'')).join('');
  const collection=(id,label,glyph,content,count)=>`<section class="ex-tree-collection"><div class="ex-collection-heading"><button data-action="ex-collection" data-id="${id}" aria-expanded="${!expanded.has('closed:'+id)}">${icon(expanded.has('closed:'+id)?'plus':'minus',12)}${icon(glyph,15)}<span>${label}</span><small>${count}</small></button>${id==='searches'?ib('plus','ex-save','Save current Explorer view'):''}</div>${expanded.has('closed:'+id)?'':`<div class="ex-collection-content">${content}</div>`}</section>`;
  const quick=`<button class="ex-shortcut ${selectedGroup==='recent'?'active':''}" data-action="ex-recent">${icon('history',15)}<span>Recently opened</span><small>${recents.filter(id=>doc(id)?.projectId===U().projectId).length}</small></button>${bookmarks.map(v=>{const item=v.scope==='document'?doc(v.resourceId):state[v.scope==='project'?'projects':'folders'].find(x=>x.id===v.resourceId);return item?`<button class="ex-shortcut" data-action="ex-shortcut-open" data-id="${e(v.id)}">${icon('star',14)}<span>${e(item.name)}</span></button>`:'';}).join('')}`;
  const sets=visibleDocumentSets(state,E().actorId,U().projectId);
  return `<aside class="ex-tree" aria-label="Datasource and folder explorer"><div class="ex-tree-header">${icon('database',14)}<strong>Datasources</strong>${ib('refresh','ex-refresh','Refresh datasource')}${ib('close','ex-toggle-tree','Hide Explorer tree')}</div><label class="ex-tree-search">${icon('search',14)}<input id="ex-tree-search" value="${e(treeSearch)}" placeholder="Find a folder…" aria-label="Filter folder tree"></label><div class="ex-tree-scroll"><div class="ex-datasource-root">${icon('database',16)}<strong>Civora Explorer Datasources</strong></div><div class="ex-datasource">${icon('database',16)}<strong>${e(E().repository.kind==='server'?'Team workspace':E().repository.kind==='directory'?'Disk workspace':'Browser workspace')}</strong><span class="ex-connection-dot ${E().repository.kind==='memory'?'warning':''}" title="${E().repository.kind==='memory'?'Temporary memory, not saved':'Current workspace'}"></span></div><div role="tree" aria-label="Project folders"><div class="ex-documents-root" role="treeitem" aria-level="1" aria-expanded="true" aria-selected="false">${icon('folder',16)}<strong>Documents</strong></div>${projectTree}</div>${collection('searches','Saved searches','search',views.map(v=>`<button class="ex-shortcut ${activeView===v.id?'active':''}" data-action="ex-view" data-id="${e(v.id)}">${icon(v.scope==='project'?'users':'search',14)}<span>${e(v.name)}</span></button>`).join('')||'<p class="ex-tree-hint">Save and reuse a document search.</p>',views.length)}${collection('sets','Document sets','layers',sets.map(set=>`<button class="ex-shortcut" data-action="set-open" data-id="${e(set.id)}">${icon(set.locked?'lock':'layers',14)}<span>${e(set.name)}</span><small>v${setVersion(set)}</small></button>`).join('')||'<p class="ex-tree-hint">No document sets in this project.</p>',sets.length)}${collection('shortcuts','My shortcuts','star',quick,bookmarks.length)}<div class="ex-tree-section">PROJECT TOOLS</div>${[['reviews','review','Reviews & approvals'],['transmittals','send','Transmittals'],['local','folder','Local working copies'],['recycle','trash','Recycle bin']].map(([route,glyph,label])=>`<button class="ex-shortcut" data-nav="${route}">${icon(glyph,15)}<span>${label}</span></button>`).join('')}</div><div class="ex-tree-foot">${icon('shield',13)} Access-filtered navigation</div></aside>`;
 }

 function address(){const parts=[];for(let id=U().folderId;id;){const f=S().folders.find(f=>f.id===id);if(!f)break;parts.unshift(f);id=f.parentId;}
  return `<div class="ex-addressbar"><div class="row gap4">${ib('left','ex-back','Back (Alt+Left)',navHistory.canBack?'':'disabled')}${ib('arrow','ex-forward','Forward (Alt+Right)',navHistory.canForward?'':'disabled')}${ib('up','ex-up','Parent folder (Alt+Up)',U().folderId?'':'disabled')}${ib('refresh','ex-refresh','Refresh workspace')}</div><label class="ex-address-label">Address</label><div class="ex-address" aria-label="Current folder address">${!layout.treeVisible||innerWidth<=780?ib('folder','ex-toggle-tree','Show Explorer tree'):icon('folder',16)}<button data-action="ex-tree" data-scope="project" data-id="${e(U().projectId)}">${e(project()?.code||'Workspace')}</button>${parts.map(f=>`${icon('chevron',13)}<button data-action="ex-tree" data-scope="folder" data-id="${e(f.id)}">${e(f.name)}</button>`).join('')}${!parts.length?'<span class="subtle"> / All documents</span>':''}${focused()?`<span class="ex-address-file" title="${e(focused().name)}">${icon('chevron',12)}${e(focused().name)}</span>`:''}<span class="grow"></span>${ib('link','ex-copy-link','Copy an address link')}${ib('external','ex-go-link','Go to an address link')}</div><label class="ex-search">${icon('search',15)}<input type="search" id="document-search" value="${e(U().query)}" placeholder="Search in this location" aria-label="Search documents"></label></div>`;
 }
 function filterChips(){
  const chips=[];const chip=(kind,key,label)=>chips.push(`<button class="ex-filter-chip" data-action="ex-remove-filter" data-kind="${kind}" data-key="${e(key)}" title="Remove ${e(label)}">${e(label)}${icon('close',12)}</button>`);
  if(U().query)chip('query','','Search: '+U().query);
  if(U().stateFilter)chip('state','','State: '+U().stateFilter);
  if(U().discipline)chip('discipline','','Discipline: '+U().discipline);
  config.filters.forEach((f,i)=>chip('advanced',String(i),columnLabel(f.key)+' '+f.op+' '+(f.value??'')));
  for(const [key,value]of Object.entries(filterValues))if(value)chip('column',key,columnLabel(key)+': '+value);
  if(selectedGroup)chip('collection','','Collection: '+selectedGroup);
  const saved=visibleExplorerViews(S(),E().actorId).find(v=>v.id===activeView);
  const dirty=saved&&JSON.stringify(normalizeExplorerView(saved.config))!==JSON.stringify(normalizeExplorerView(currentConfig()));
  return chips.length||dirty?`<div class="ex-active-filters" aria-label="Active search filters"><span>${icon('filter',13)}Refine</span>${chips.join('')}${chips.length?b('Clear filters','ex-clear','close','','small'):''}<span class="grow"></span>${dirty?'<span class="ex-view-dirty">Unsaved view changes</span>':''}</div>`:'';
 }
 function advancePreview(direction){const ids=pageResult.items.map(d=>d.id),index=ids.indexOf(activeId),next=index+direction;if(index<0||next<0||next>=ids.length)return;activeId=ids[next];if(U().selection.size<=1)U().selection=new Set([activeId]);remember(activeId);writeAddress();R();}
 function inspector(){
  if(layout.previewPosition==='hidden')return '';
  const d=focused(),tabs=[['properties',d?'Document properties':U().folderId?'Folder properties':'Project properties'],['folder','Folder properties'],['attributes','Attributes'],['preview','File preview'],['versions','Versions'],['references','Dependency viewer'],['access','Access control'],['audit','Audit trail']];
  const pair=(k,v)=>`<div><dt>${e(k)}</dt><dd>${v}</dd></div>`;let body='';
  if(!d||inspectorTab==='folder'){const f=S().folders.find(f=>f.id===(inspectorTab==='folder'&&d?d.folderId:U().folderId)),p=project();body=`<div class="ex-placeholder-properties">${icon(f?'folder':'box',28)}<div><h3>${e(f?.name||p?.name||'Project')}</h3><p>Read-only folder context. Opening this location clears document selection.</p><dl class="ex-property-grid">${pair('Location',e(folderPath(S(),f?.id)||'Project root'))}${pair('Project',e(p?.code||''))}${pair('Client',e(p?.client||'—'))}${pair('Phase',e(p?.phase||'—'))}</dl>${b('Pin this location','ex-pin-location','star')}${f?b('Open this folder','ex-tree','folder',`data-id="${e(f.id)}" data-scope="folder" data-project="${e(f.projectId)}"`):b('Project properties','edit-project','edit')}</div></div>`;}
  else if(inspectorTab==='properties'){body=`<div class="ex-property-overview"><div class="ex-property-file">${fileBadge(d.name,true)}<div><strong>${e(d.title)}</strong><small>${e(d.number)} · ${e(d.name)}</small><div class="row gap4">${statusBadge(d.state)}<span class="mono">${e(currentVersion(d).label)}</span></div></div></div><dl class="ex-property-grid">${[['Document number',e(d.number)],['Filename',e(d.name)],['Description',e(d.description||d.title)],['Workflow',e(S().workflows.find(w=>w.id===d.workflowId)?.name||'')],['Version',e(currentVersion(d).label)],['Discipline',e(d.discipline)],['Checked out to',e(d.checkedOutBy?userName(S(),d.checkedOutBy):'Available')],['Size',formatBytes(currentVersion(d).size)],['Modified by',e(userName(S(),d.modifiedBy))],['Modified',e(new Date(d.modifiedAt).toLocaleString('en-GB'))],['Folder',e(folderPath(S(),d.folderId)||'Project root')],['Tags',e(d.tags.join(', ')||'—')],...(project()?.fields||[]).map(f=>[f.label,e(d.metadata[f.key]??'—')])].map(([k,v])=>pair(k,v)).join('')}</dl></div>`;}
  else if(inspectorTab==='attributes'){const fields=project()?.fields||[];body=`<div class="ex-attributes-panel"><div class="ex-attribute-heading"><strong>${e(project()?.name||'Project')} · Metadata environment</strong>${b('Edit attributes','edit-document','edit',`data-id="${e(d.id)}" ${can('write','document',d.id)?'':'disabled'}`,'small')}</div><table class="ex-detail-table"><thead><tr><th>Attribute</th><th>Value</th><th>Type</th><th>Required</th></tr></thead><tbody>${fields.map(f=>`<tr><td>${e(f.label)}</td><td>${e(d.metadata?.[f.key]??'—')}</td><td>${e(f.type||'text')}</td><td>${f.required?'Yes':'No'}</td></tr>`).join('')||'<tr><td colspan="4">No custom metadata fields configured.</td></tr>'}</tbody></table></div>`;}
  else if(inspectorTab==='preview'){body=can('download','document',d.id)?`<div class="ex-preview-wrapper"><div id="ex-file-preview"><p class="ex-loading">Loading original revision…</p></div><div class="ex-preview-actions">${b('Full viewer','preview-version','external',`data-id="${e(d.id)}" data-version="${e(currentVersion(d).id)}"`,'small')}<small>Original ${e(currentVersion(d).label)} · ${e(formatBytes(currentVersion(d).size))}</small></div></div>`:emptyState('Content download not permitted','You can inspect metadata; file previews require download permission.');}
  else if(inspectorTab==='versions'){body=`<div class="ex-version-heading"><span>${d.versions.length} retained revisions · originals unchanged</span>${b('Compare revisions','compare-versions','layers',`data-id="${e(d.id)}" ${d.versions.length>1&&can('download','document',d.id)?'':'disabled'}`,'small')}</div><table class="ex-detail-table"><thead><tr><th>Version</th><th>Created</th><th>Author</th><th>Comment</th><th>Size</th><th></th></tr></thead><tbody>${[...d.versions].reverse().map(v=>`<tr><td class="mono">${e(v.label)}${v.id===currentVersion(d).id?' <span class="ex-current">Current</span>':''}</td><td>${e(formatDate(v.createdAt||v.at,{year:'numeric'}))}</td><td>${e(userName(S(),v.createdBy||v.by))}</td><td>${e(v.comment)}</td><td>${formatBytes(v.size)}</td><td>${ib('eye','preview-version','Preview this revision',`data-id="${e(d.id)}" data-version="${e(v.id)}" ${can('download','document',d.id)?'':'disabled'}`)}${ib('download','download-document','Download this revision',`data-id="${e(d.id)}" data-version="${e(v.id)}" ${can('download','document',d.id)?'':'disabled'}`)}</td></tr>`).join('')}</tbody></table>`;}
  else if(inspectorTab==='references'){const outgoing=d.references.map(doc).filter(Boolean),incoming=S().documents.filter(x=>!x.deletedAt&&x.references.includes(d.id));body=`<div class="ex-dependency-columns">${[['Uses these documents',outgoing],['Used by these documents',incoming]].map(([title,list])=>`<section><h3>${title} <span class="subtle">${list.length}</span></h3>${list.map(x=>`<button class="ex-dependency" data-action="ex-reveal" data-id="${e(x.id)}">${fileBadge(x.name)}<span><strong>${e(x.number)}</strong><small>${e(x.name)}</small></span>${icon('arrow',14)}</button>`).join('')||'<p class="subtle">No visible relationships</p>'}</section>`).join('')}</div><div class="ex-detail-foot">${b('Edit references','edit-references','link',`data-id="${e(d.id)}"`,'small')}<span class="small muted">Only authorized dependencies are displayed. Binary CAD parsing is not implied.</span></div>`;}
  else if(inspectorTab==='access'){body=`<div class="ex-permission-heading"><strong>${e(userName(S(),E().actorId))}</strong><p>Effective permissions for the signed-in account${E().repository.kind==='server'?'':'; local sandbox profiles are not authentication'}.</p></div><div class="ex-permissions">${['read','download','write','review','publish','share','manage'].map(p=>`<div class="${can(p,'document',d.id)?'allowed':'denied'}">${icon(can(p,'document',d.id)?'check':'lock',17)}<span>${p[0].toUpperCase()+p.slice(1)}</span><small>${can(p,'document',d.id)?'Allowed':'Not allowed'}</small></div>`).join('')}</div><div class="ex-detail-foot">${b('Manage access policies','ex-route','shield','data-route="members"','small')}</div>`;}
  else {const events=S().audit.filter(a=>a.targetId===d.id||a.renameChanges?.some(row=>row.id===d.id)).slice(-40).reverse();body=S().users.find(u=>u.id===E().actorId)?.role==='admin'?`<div class="ex-audit">${events.map(a=>`<div>${avatar(userName(S(),a.by),'xs')}<span><strong>${e(a.summary)}</strong><small>${e(userName(S(),a.by))} · ${e(new Date(a.at).toLocaleString('en-GB'))} · r${a.sequence}</small></span></div>`).join('')||'<p>No direct document audit events.</p>'}</div>`:emptyState('Administrator-only audit trail','Raw audit entries can contain historical protected metadata. Current revision history is available in Versions.');}
  return `<section class="ex-inspector" aria-label="Preview and properties pane">${d?`<div class="ex-preview-context"><span class="ex-preview-context-name">${fileBadge(d.name)}<strong>${e(d.name)}</strong><small>${e(currentVersion(d).label)}</small></span><span class="grow"></span><span class="ex-preview-position">${Math.max(0,pageResult.items.findIndex(x=>x.id===d.id)+1)} / ${pageResult.items.length} on page</span>${ib('left','ex-preview-previous','Preview previous document on this page',pageResult.items.findIndex(x=>x.id===d.id)>0?'':'disabled')}${ib('arrow','ex-preview-next','Preview next document on this page',pageResult.items.findIndex(x=>x.id===d.id)>=0&&pageResult.items.findIndex(x=>x.id===d.id)<pageResult.items.length-1?'':'disabled')}${ib('copy','ex-copy','Copy this document as new',`data-id="${e(d.id)}" ${can('download','document',d.id)?'':'disabled'}`)}</div>`:''}<div class="ex-inspector-tabs" role="tablist" aria-label="Preview pane tabs">${tabs.map(([id,label])=>`<button role="tab" tabindex="${inspectorTab===id?0:-1}" aria-selected="${inspectorTab===id}" data-action="ex-inspector-tab" data-tab="${id}">${e(label)}</button>`).join('')}<span class="grow"></span>${d?ib('external','open-document','Open full document',`data-id="${e(d.id)}"`):''}${ib('rectangle','ex-pane-menu','Preview pane position')}${ib('close','ex-dock','Close preview pane','data-position="hidden"')}</div><div class="ex-inspector-body" role="tabpanel">${body}</div></section>`;
 }
 function table(){const columns=explorerColumns(project()),rows=pageResult.items,visibleIds=new Set(rows.map(d=>d.id));let group;
  const colWidth=key=>config.widths[key]||columns.find(c=>c.key===key)?.width||150;
  return `<div class="ex-grid-scroll" tabindex="-1"><table class="document-table ex-document-table" aria-label="Controlled documents" aria-rowcount="${pageResult.total+1}" style="min-width:${config.columns.reduce((n,k)=>n+colWidth(k),44)}px"><colgroup><col style="width:38px">${config.columns.map(k=>`<col data-ex-col="${e(k)}" style="width:${colWidth(k)}px">`).join('')}</colgroup><thead><tr><th><input id="select-all-docs" type="checkbox" aria-label="Select visible documents" ${rows.length&&rows.every(d=>U().selection.has(d.id))?'checked':''}></th>${config.columns.map(key=>{const s=config.sort.find(s=>s.key===key),i=config.sort.findIndex(s=>s.key===key);return `<th draggable="true" data-ex-column="${e(key)}" aria-sort="${s?(s.direction==='asc'?'ascending':'descending'):'none'}"><button data-action="ex-sort" data-key="${e(key)}" title="Sort by ${e(columnLabel(key))}; use Columns for multi-sort">${e(columnLabel(key))}${s?`${icon(s.direction==='asc'?'up':'down',12)}${config.sort.length>1?`<sup>${i+1}</sup>`:''}`:''}</button><span id="ex-width-${e(key)}" class="ex-column-resize" data-resize-column="${e(key)}" role="separator" aria-label="Resize ${e(columnLabel(key))}" aria-orientation="vertical" tabindex="0"></span></th>`;}).join('')}</tr>${layout.columnFilters?`<tr class="ex-column-filters"><th>${ib('close','ex-clear-column-filters','Clear column filters')}</th>${config.columns.map(key=>`<th><input id="ex-filter-${e(key)}" data-ex-column-filter="${e(key)}" type="search" value="${e(filterValues[key]||'')}" placeholder="Filter…" aria-label="Filter ${e(columnLabel(key))}"></th>`).join('')}</tr>`:''}</thead><tbody>${rows.map((d,i)=>{const value=config.groupBy?String(explorerValue(S(),d,config.groupBy)):null,header=config.groupBy&&group!==value?`<tr class="ex-group-row"><td colspan="${config.columns.length+1}">${icon('layers',13)} ${e(columnLabel(config.groupBy))}: <strong>${e(value||'Not set')}</strong><span>${pageResult.groups.find(g=>g.key===value)?.count||0} documents</span></td></tr>`:'';group=value;return header+`<tr data-doc-row="${e(d.id)}" data-ex-row="${e(d.id)}" tabindex="${d.id===activeId||!activeId&&i===0?'0':'-1'}" aria-selected="${U().selection.has(d.id)}" aria-rowindex="${U().page*config.pageSize+i+2}" draggable="true" class="${U().selection.has(d.id)?'selected':''} ${d.id===activeId?'ex-focused':''} ${clipboard?.items.some(x=>x.id===d.id)?'ex-cut-row':''}"><td><input data-select-doc="${e(d.id)}" type="checkbox" aria-label="Select ${e(d.name)}" ${U().selection.has(d.id)?'checked':''}></td>${config.columns.map(key=>`<td title="${e(explorerValue(S(),d,key))}">${dataValue(d,key)}</td>`).join('')}</tr>`;}).join('')||`<tr><td colspan="${config.columns.length+1}">${emptyState('No documents match this view','Change the folder, clear the filters, or upload new documents.',b('Clear filters','ex-clear','filter'))}</td></tr>`}</tbody></table></div>`;
 }
 function mobileFiles(result){return `<div class="mobile-files-heading"><label class="mobile-select-all"><input type="checkbox" id="select-all-docs" aria-label="Select this page" ${result.items.length&&result.items.every(d=>U().selection.has(d.id))?'checked':''}> This page</label><span class="grow"></span>${b(touchSelecting?'Done selecting':'Select files','ex-touch-select','check','','small')}${b('Sort','ex-touch-sort','list','','small')}</div><div class="ex-grid-scroll mobile-file-list" role="list" aria-label="Project documents">${result.items.map(d=>`<article role="listitem" tabindex="0" class="mobile-file-card ${U().selection.has(d.id)?'selected':''}" data-ex-row="${e(d.id)}"><div class="mobile-file-top"><label class="mobile-file-check"><input type="checkbox" data-select-doc="${e(d.id)}" aria-label="Select ${e(d.name)}" ${U().selection.has(d.id)?'checked':''}></label>${fileBadge(d.name)}<button class="mobile-file-name" data-action="ex-touch-open" data-id="${e(d.id)}"><strong>${e(d.name)}</strong><span>${e(d.title)}</span></button><button class="icon-button mobile-file-more" data-action="ex-touch-menu" data-id="${e(d.id)}" aria-label="Actions for ${e(d.name)}">${icon('more')}</button></div><div class="mobile-file-meta"><span class="mono">${e(d.number)}</span><span class="mono">${e(currentVersion(d).label)}</span>${d.checkedOutBy?icon('lock',14):''}</div><div class="mobile-file-footer">${statusBadge(d.state)}<span class="grow"></span><span>${e(d.discipline||'General')}</span>${b('Preview','preview-version','eye',`data-id="${e(d.id)}" data-version="${e(currentVersion(d).id)}"`,'small')}</div></article>`).join('')||emptyState('No documents match','Change the filters or upload a document.')}</div>`;}
 function prepareShell(){sync();document.body.classList.toggle('ex-rail-hidden',!layout.navigationRail);}
 function page(){prepareShell();let result;
  try{result=queryExplorer(S(),E().actorId,currentConfig(),{offset:Math.max(0,U().page)*config.pageSize,limit:config.pageSize,columnFilters:filterValues});if(selectedGroup==='recent'){const ids=new Set(recents);const allowed=result.ids.filter(id=>ids.has(id)),start=U().page*config.pageSize;result={...result,total:allowed.length,ids:allowed,items:allowed.slice(start,start+config.pageSize).map(doc),groups:[]};}}
  catch(error){return ctx.heading('Documents','The current Explorer query is unavailable.')+note(error.message)+b('Reset Explorer layout','ex-reset','refresh');}
  if(U().page>0&&U().page*config.pageSize>=result.total){U().page=Math.max(0,Math.ceil(result.total/config.pageSize)-1);return page();}pageResult=result;
  if(activeId&&!result.ids.includes(activeId)){activeId='';}for(const id of [...U().selection])if(!result.ids.includes(id))U().selection.delete(id);
  const total=result.total,views=visibleExplorerViews(S(),E().actorId).filter(v=>v.projectId===U().projectId),p=project(),pages=Math.max(1,Math.ceil(total/config.pageSize));
  const controls=`<div class="ex-list-heading"><div class="ex-register-location"><h1>${icon('list',15)} Documents</h1><span>${e(selectedGroup==='recent'?'Recently opened':U().folderId?S().folders.find(f=>f.id===U().folderId)?.name:p?.name||'Project')}<i>·</i>${total} visible</span></div><div class="ex-list-tools"><label class="ex-view-select">${icon('list',14)}<select id="ex-view-select" aria-label="Explorer saved view"><option value="">${activeView?'Unsaved view':'Detailed view'}</option>${views.map(v=>`<option value="${e(v.id)}" ${v.id===activeView?'selected':''}>${e(v.name)}${v.scope==='project'?' · shared':''}</option>`).join('')}</select></label>${ib('filter','ex-filter','Advanced document search')}${ib('grid','ex-columns','Configure columns')}${ib('more','ex-menu','View options','data-menu="View"')}</div></div><div class="ex-filterbar"><label><input id="ex-recursive" type="checkbox" ${config.includeSubfolders?'checked':''}> Include subfolders</label><select id="state-filter" aria-label="Filter by workflow state"><option value="">All states</option>${[...new Set(S().workflows.flatMap(w=>w.states))].map(s=>`<option ${U().stateFilter===s?'selected':''}>${e(s)}</option>`).join('')}</select><select id="discipline-filter" aria-label="Filter by discipline"><option value="">All disciplines</option>${[...new Set(S().documents.filter(d=>d.projectId===U().projectId&&!d.deletedAt).map(d=>d.discipline))].map(s=>`<option ${U().discipline===s?'selected':''}>${e(s)}</option>`).join('')}</select>${config.filters.length?`<button class="ex-active-filter" data-action="ex-filter">${config.filters.length} advanced conditions ${icon('filter',12)}</button>`:''}${selectedGroup==='recent'?b('Show all','ex-clear','close','','small'):''}<span class="grow"></span>${b('Save view','ex-save','star','','small')}${ib('list','file-list','List view')}${ib('grid','file-grid','Card view')}</div>`;
  const selection=U().selection.size?`<div class="ex-selection-bar"><strong>${U().selection.size} selected</strong>${b('Properties','control-bulk','edit','','small')}${b('Copy','ex-copy','copy','','small')}${b('Rename','ex-rename','edit','','small')}${b('Move','ex-move','folder','','small')}${b('Editable CSV','control-register-export','download','','small')}${b('Review','new-review','review','','small')}${b('Baseline','control-baseline-new','layers','','small')}${b('Create set','new-set','box','','small')}${b('Transmittal','new-transmittal','send','','small')}<span class="grow"></span>${ib('close','clear-selection','Clear document selection')}</div>`:'<div class="ex-selection-bar ex-selection-idle"><span>Select documents to organize, review or deliver</span><span class="grow"></span><span>Double-click to open · Shift-click to select a range</span></div>';
  const content=mobileCards()?mobileFiles(result):U().fileMode==='grid'?`<div class="ex-card-scroll"><div class="document-grid">${result.items.map(d=>`<button class="document-card" data-action="ex-card" data-id="${e(d.id)}"><div class="document-thumb">${/\.(svg|png|jpe?g|webp)$/i.test(d.name)?`<img data-thumbnail="${e(d.id)}" alt="${e(d.title)}">`:fileBadge(d.name,true)}</div><div class="document-card-body"><h3>${e(d.title)}</h3><span class="file-subtitle">${e(d.number)} · ${e(currentVersion(d).label)}</span>${statusBadge(d.state)}</div></button>`).join('')||emptyState('No documents match','Change your filters.')}</div></div>`:table();
  const pagesHTML=`<div class="ex-pagination"><span>${total?`${U().page*config.pageSize+1}–${Math.min((U().page+1)*config.pageSize,total)} of ${total}`:'No'} documents</span><span class="grow"></span><select id="ex-page-size" aria-label="Rows per page">${[50,100,250,500].map(n=>`<option value="${n}" ${n===config.pageSize?'selected':''}>${n} rows</option>`).join('')}</select>${ib('left','ex-page-prev','Previous page',U().page?'':'disabled')}<span>${U().page+1} / ${pages}</span>${ib('arrow','ex-page-next','Next page',U().page+1<pages?'':'disabled')}</div>`;
  return `<div class="ex-workspace ex-style-${layout.commandStyle} ${layout.rowLines?'ex-row-lines':''} ${layout.fileDescriptions?'ex-description-lines':'ex-single-line'} ex-density-${config.density}${mobileCards()?' ex-mobile-cards':''}" data-explorer style="--ex-tree-width:${layout.treeWidth}px;--ex-preview-size:${layout.previewSize}px;--ex-preview-width:${layout.previewWidth}px">${ribbon()}${address()}<div class="ex-body ${layout.treeVisible?'':'ex-tree-hidden'}">${layout.treeVisible?tree()+`<div id="ex-tree-separator" class="ex-splitter ex-tree-splitter" data-ex-resize="tree" role="separator" tabindex="0" aria-label="Resize folder tree" aria-orientation="vertical" aria-valuemin="190" aria-valuemax="480" aria-valuenow="${layout.treeWidth}"></div>`:''}<div class="ex-workarea ex-dock-${layout.previewPosition}"><div class="ex-document-area">${controls}${filterChips()}${selection}${content}${pagesHTML}</div>${layout.previewPosition!=='hidden'?`<div id="ex-preview-separator" class="ex-splitter ex-preview-splitter" data-ex-resize="preview" role="separator" tabindex="0" aria-label="Resize preview pane" aria-orientation="${layout.previewPosition==='bottom'?'horizontal':'vertical'}" aria-valuenow="${layout.previewPosition==='bottom'?layout.previewSize:layout.previewWidth}" aria-valuemin="160" aria-valuemax="650"></div>`+inspector():''}</div></div><footer class="ex-statusbar"><span class="ex-status-dot ${E().repository.kind==='memory'?'warning':''}"></span><span>${E().repository.kind==='server'?'Authenticated team workspace':E().repository.kind==='memory'?'Temporary memory · export before closing':E().repository.kind==='directory'?'Disk folder · local sandbox':'Browser database · local sandbox'}</span><span class="ex-status-path">${e(p?.code||'')} / ${e(folderPath(S(),U().folderId)||'All documents')}</span><span class="grow"></span><span>${U().selection.size?U().selection.size+' selected · ':''}r${S().revision}</span><span>Civora ${e(APP_VERSION)}</span></footer></div>`;
 }
 function columnsDialog(){
  const columns=explorerColumns(project()),order=[...config.columns,...columns.map(c=>c.key).filter(k=>!config.columns.includes(k))];
  const body=()=>note('Column order, width and density are personal layout preferences. Save a view to reuse them across sessions or share a project configuration.')+`<div class="ex-column-editor">${order.map(key=>{const c=columns.find(x=>x.key===key)||{key,label:key,width:160};return `<div class="ex-column-option" data-column-option="${e(key)}"><label><input type="checkbox" name="column" value="${e(key)}" ${config.columns.includes(key)?'checked':''} ${key==='name'?'disabled':''}>${e(c.label)}</label><label class="ex-width-field">Width <input type="number" min="64" max="900" value="${config.widths[key]||c.width}" data-column-width="${e(key)}" aria-label="${e(c.label)} width"></label><button type="button" class="icon-button" data-column-up title="Move column earlier">${icon('up',14)}</button><button type="button" class="icon-button" data-column-down title="Move column later">${icon('down',14)}</button></div>`;}).join('')}</div><div class="form-grid mt16"><label class="field"><span>Group documents by</span><select name="group"><option value="">No grouping</option>${columns.map(c=>`<option value="${e(c.key)}" ${config.groupBy===c.key?'selected':''}>${e(c.label)}</option>`).join('')}</select></label><label class="field"><span>Row density</span><select name="density">${['compact','standard','comfortable'].map(v=>`<option ${config.density===v?'selected':''}>${v}</option>`).join('')}</select></label></div><p class="muted small mt16">Drag a column header to reorder. Drag its right edge to resize. Shift-click a header to add a secondary or tertiary sort.</p>`;
  form('Configure document columns',body(),async(data,form)=>{const keys=[...form.querySelectorAll('[data-column-option]')].filter(row=>row.dataset.columnOption==='name'||row.querySelector('[name=column]').checked).map(row=>row.dataset.columnOption),widths={};for(const input of form.querySelectorAll('[data-column-width]'))widths[input.dataset.columnWidth]=Number(input.value);config=normalizeExplorerView({...config,columns:keys,widths,groupBy:data.group,density:data.density});persist();R();},{wide:true,label:'Apply columns',onMount(dialog){dialog.addEventListener('click',event=>{const button=event.target.closest('[data-column-up],[data-column-down]');if(!button)return;const row=button.closest('[data-column-option]');if(button.hasAttribute('data-column-up')&&row.previousElementSibling)row.parentNode.insertBefore(row,row.previousElementSibling);else if(button.hasAttribute('data-column-down')&&row.nextElementSibling)row.parentNode.insertBefore(row.nextElementSibling,row);});}});
 }
 function filterDialog(){
  const columns=explorerColumns(project());let filters=structuredClone(config.filters.length?config.filters:[{key:'name',op:'contains',value:''}]);
  const row=f=>`<div class="ex-condition-row" data-ex-condition><select data-filter-key aria-label="Search field">${columns.map(c=>`<option value="${e(c.key)}" ${c.key===f.key?'selected':''}>${e(c.label)}</option>`).join('')}</select><select data-filter-op aria-label="Search comparison">${FILTER_OPERATORS.map(op=>`<option value="${op}" ${f.op===op?'selected':''}>${e(({eq:'equals',ne:'does not equal',gt:'greater than',gte:'at least',lt:'less than',lte:'at most',notContains:'does not contain',startsWith:'starts with',empty:'is empty',notEmpty:'is not empty'})[op]||op)}</option>`).join('')}</select><input data-filter-value value="${e(f.value??'')}" aria-label="Search value" placeholder="Literal value, number or ISO date"><button class="icon-button" data-remove-filter type="button" aria-label="Remove condition">${icon('close',14)}</button></div>`;
  const read=form=>[...form.querySelectorAll('[data-ex-condition]')].map(r=>({key:r.querySelector('[data-filter-key]').value,op:r.querySelector('[data-filter-op]').value,value:r.querySelector('[data-filter-value]').value}));
  form('Advanced document search',note('Search evaluates only documents you can currently read. Values are literal: there are no regular expressions or executable queries.')+`<div class="form-grid">${field('Search text','query',U().query,{placeholder:'Words in names, numbers, titles, metadata and tags'})}<label class="field"><span>Match conditions</span><select name="match"><option value="all" ${config.match==='all'?'selected':''}>All conditions (AND)</option><option value="any" ${config.match==='any'?'selected':''}>Any condition (OR)</option></select></label></div><div id="ex-condition-list">${filters.map(row).join('')}</div><div class="row mt16"><button type="button" class="btn" data-add-filter>${icon('plus',14)}Add condition</button><button type="button" class="btn" data-preview-filter>Preview matches</button><span id="ex-filter-count" role="status"></span></div><label class="row mt16"><input type="checkbox" name="recursive" ${config.includeSubfolders?'checked':''}>Include nested folders</label>`,async(data,form)=>{config=normalizeExplorerView({...config,query:data.query,match:data.match,filters:read(form),includeSubfolders:form.elements.recursive.checked});U().query=config.query;U().stateFilter='';U().discipline='';U().page=0;filterValues={};selectedGroup='';persist();R();},{wide:true,label:'Apply search',onMount(dialog){dialog.addEventListener('click',event=>{if(event.target.closest('[data-remove-filter]'))event.target.closest('[data-ex-condition]').remove();if(event.target.closest('[data-add-filter]')){const list=dialog.querySelector('#ex-condition-list');if(list.children.length>=20)return err(new Error('At most twenty search conditions are supported.'));list.insertAdjacentHTML('beforeend',row({key:'name',op:'contains',value:''}));}if(event.target.closest('[data-preview-filter]')){try{const form=dialog.querySelector('form'),view=normalizeExplorerView({...config,query:form.elements.query.value,match:form.elements.match.value,filters:read(form),includeSubfolders:form.elements.recursive.checked});dialog.querySelector('#ex-filter-count').textContent=queryExplorer(S(),E().actorId,view).total+' readable documents match';}catch(error){dialog.querySelector('#ex-filter-count').textContent=error.message;}}});}});
 }
 function saveViewDialog(viewId=''){
  const existing=visibleExplorerViews(S(),E().actorId).find(v=>v.id===(viewId||activeView)),owned=existing&&(existing.scope==='personal'?existing.userId===E().actorId:can('manage','project',existing.projectId)),base=owned?existing:null;
  form(base?'Save Explorer view':'Create Explorer view',note('Personal views belong to your account. Project views share a configuration, not access to documents. The current columns, filters, sorting, grouping and folder scope are stored.')+field('View name','name',base?.name||'',{required:true,maxlength:100})+`<label class="field mt16"><span>Visibility</span><select name="scope" ${base?'disabled':''}><option value="personal" ${base?.scope!=='project'?'selected':''}>Personal · only this account</option>${can('manage','project',U().projectId)?`<option value="project" ${base?.scope==='project'?'selected':''}>Project · shared with project readers</option>`:''}</select></label>`,async(data,form)=>{const payload={projectId:U().projectId,name:data.name,scope:base?.scope||data.scope,config:structuredClone(currentConfig())};if(base){payload.id=base.id;payload.expectedVersion=base.version;}const result=await E().run('explorerView.save',payload);activeView=typeof result==='string'?result:result.id;persist();R();toast('Explorer view saved.');},{label:base?'Update view':'Save view'});
 }
 function manageViews(){
  const rows=visibleExplorerViews(S(),E().actorId).filter(v=>v.projectId===U().projectId),dialog=openDialog({title:'Saved Explorer views',subtitle:'Saved searches and layouts are separate from the legacy document search bookmarks.',wide:true,body:`<div class="ex-view-manager">${rows.map(v=>`<div class="ex-view-record"><span class="grow"><strong>${e(v.name)}</strong><small>${v.scope==='project'?'Shared project view':'Personal view'} · v${v.version} · ${e(relativeTime(v.modifiedAt))}</small></span>${b('Open','ex-view','folder',`data-id="${e(v.id)}"`)}${(v.scope==='personal'?v.userId===E().actorId:can('manage','project',v.projectId))?b('Delete','ex-view-remove','trash',`data-id="${e(v.id)}"`):''}</div>`).join('')||emptyState('No saved views','Configure the list and choose Save view.')}</div><div class="row mt16">${b('Save current as a new view','ex-save-new','plus')}</div>`});return dialog;
 }
 function closeTopDialog(button){button?.closest?.('dialog')?.close();}
 function moveDialog(ids=[...U().selection],destination=undefined,fromClipboard=false){
  const list=ids.map(doc).filter(Boolean);if(!list.length)throw new Error('Select documents to move.');if(list.length!==ids.length||list.some(d=>d.projectId!==U().projectId))throw new Error('Move documents within one readable project.');if(list.length>100)throw new Error('At most 100 documents can be moved atomically.');
  const initialIdentity=identity,initialEngine=E(),projectId=U().projectId,sources=list.map(d=>({id:d.id,versionId:currentVersion(d).id,folderId:d.folderId||null})),folders=S().folders.filter(f=>f.projectId===projectId&&can('write','folder',f.id));let approved=null,validationSerial=0;
  const choices=[{id:'',name:'Project root'},...folders.map(f=>({id:f.id,name:folderPath(S(),f.id)}))];
  form('Move controlled documents',note('Moves are previewed and committed as one transaction. Locks, permissions, duplicate names and the exact source revisions are checked again. This does not rewrite CAD references inside file bytes.')+`<label class="field"><span>Destination folder</span><select name="destination" id="ex-move-destination">${choices.map(f=>`<option value="${e(f.id)}" ${f.id===(destination??U().folderId)?'selected':''}>${e(f.name)}</option>`).join('')}</select></label><div class="ex-move-list mt16">${list.map(d=>`<div>${fileBadge(d.name)}<span><strong>${e(d.name)}</strong><small>${e(folderPath(S(),d.folderId)||'Project root')} · ${e(currentVersion(d).label)}</small></span></div>`).join('')}</div><div class="row mt16"><button class="btn" type="button" id="ex-move-preview">${icon('shield',14)}Validate move</button><span id="ex-move-status" role="status">Validate the destination before applying.</span></div>`,async(data)=>{
   if(identity!==initialIdentity||E()!==initialEngine)throw new Error('Workspace or account changed. Reopen the move dialog.');if(!approved||approved.payload.folderId!==(data.destination||null))throw new Error('Validate this destination first.');if(S().revision!==approved.sourceRevision)throw new Error('The workspace changed after preview. Validate the move again.');await E().run('document.bulkMove',approved.payload);if(fromClipboard)clipboard=null;U().selection.clear();activeId='';go(projectId,data.destination);toast(`${ids.length} document${ids.length===1?'':'s'} moved atomically.`);
  },{wide:true,label:'Apply move',onMount(dialog){const select=dialog.querySelector('#ex-move-destination'),status=dialog.querySelector('#ex-move-status'),button=dialog.querySelector('#ex-move-preview');select.addEventListener('change',()=>{validationSerial++;approved=null;status.textContent='Destination changed. Validate again.';});button.addEventListener('click',()=>run((async()=>{const serial=++validationSerial,sourceRevision=S().revision,destinationId=select.value||null;approved=null;button.disabled=true;try{
    if(identity!==initialIdentity||E()!==initialEngine)throw new Error('Workspace or account changed.');for(const source of sources){const current=doc(source.id);if(!current||currentVersion(current).id!==source.versionId||(current.folderId||null)!==source.folderId)throw new Error('A source document changed. Reopen the move dialog.');}
    if(fromClipboard&&(!clipboard||clipboard.identity!==identity||clipboard.items.some(item=>{const d=doc(item.id);return !d||currentVersion(d).id!==item.versionId||(d.folderId||null)!==item.folderId;})))throw new Error('The cut selection is stale. Cut the documents again.');
    const payload={projectId,folderId:destinationId,documentIds:ids};const response=E().repository.kind==='server'?await fetchJSON((E().repository.base||'/api')+'/explorer/move-preview',{method:'POST',body:JSON.stringify({...payload,expectedRevision:sourceRevision})}):previewDocumentMove(E().state,E().actorId,payload);
    if(serial!==validationSerial||!dialog.open)return;if(identity!==initialIdentity||E()!==initialEngine)throw new Error('Workspace or account changed. Reopen the move dialog.');if(S().revision!==sourceRevision)throw new Error('The workspace changed while validating. Validate again.');if(response.sourceRevision!==sourceRevision||response.allowed&&(!response.payload||response.payload.projectId!==projectId||response.payload.folderId!==destinationId||response.payload.baseRevision!==sourceRevision||JSON.stringify(response.payload.items)!==JSON.stringify(sources)))throw new Error('The move preview does not match these sources and destination. Validate again.');
    if(!response.allowed)throw new Error(response.error||'Move is not allowed.');approved=response;status.textContent=`Validated ${ids.length} document${ids.length===1?'':'s'} at workspace revision ${response.sourceRevision}. No changes made yet.`;
   }catch(error){if(serial===validationSerial&&dialog.open){status.textContent=error.message;throw error;}}finally{button.disabled=false;}})()));}});
 }
 async function copyLink(target={projectId:U().projectId,folderId:U().folderId,documentId:activeId}){
  const hash=explorerLink(S(),target),url=/^https?:$/.test(globalThis.location.protocol)?globalThis.location.origin+globalThis.location.pathname+globalThis.location.search+hash:hash;
  try{await navigator.clipboard.writeText(url);toast('Permission-checked workspace link copied.');}catch{form('Copy workspace link',note('This link contains stable record identifiers, not an access token. Recipients must open the same workspace and have permission.')+`<textarea readonly class="invitation-link" aria-label="Workspace link">${e(url)}</textarea>`,()=>{},{label:'Done',onMount(dialog){const input=dialog.querySelector('textarea');input.focus();input.select();}});}
 }
 function goLinkDialog(){form('Go to workspace link',note('Paste a Civora document, folder or project link. Workspace identity and your current permissions are checked; no external page is opened.')+field('Civora link','link','',{required:true}),async(data)=>{const hash=data.link.includes('#')?data.link.slice(data.link.indexOf('#')):data.link;applyLink(hash);},{label:'Go to location'});}
 function applyLink(hash){const target=resolveExplorerLink(S(),E().actorId,hash);go(target.projectId,target.folderId,{documentId:target.documentId});}
 function shortcuts(){openDialog({title:'Explorer keyboard shortcuts',body:`<div class="ex-shortcuts">${[['↑ / ↓','Move document focus'],['Shift + ↑ / ↓','Extend selection'],['Ctrl / ⌘ + click','Toggle one document'],['Shift + click','Select a range'],['Ctrl / ⌘ + A','Select this page'],['Enter / double-click','Open full properties'],['Space','Toggle the focused document'],['F2','Edit document properties'],['Shift + F2','Rename selected documents'],['Alt + D','Open a Civora location link'],['F6 / Shift + F6','Cycle tree, list, preview tabs and search'],['Ctrl / ⌘ + K','Go to anything: documents, folders and commands'],['Ctrl / ⌘ + Shift + C','Copy selected as new controlled documents'],['Ctrl / ⌘ + X','Cut a controlled document selection'],['Ctrl / ⌘ + V','Preview move into this folder'],['Alt + ← / →','Back / forward through folders'],['Alt + ↑','Parent folder'],['Escape','Clear selection or close a menu'],['Shift + column click','Add another sort key']].map(([key,action])=>`<div><kbd>${e(key)}</kbd><span>${e(action)}</span></div>`).join('')}</div><p class="small muted mt16">Document shortcuts apply when focus is in the list, not while typing. Splitters and column widths also support arrow-key adjustment.</p>`});}
 function appearanceDialog(){
  const currentLayout={...layout},currentDensity=config.density;
  form('Explorer appearance',`<p class="ex-appearance-intro">A familiar engineering desktop, adapted for the browser. These settings affect this browser and account only.</p><div class="ex-preset-options" role="group" aria-label="Workspace appearance presets">${[['explorer','Explorer','Compact standard toolbar · datasource tree'],['ribbon','Ribbon','Grouped commands · workspace rail'],['review','Review','Standard toolbar · right-side properties']].map(([id,label,description])=>`<button type="button" data-appearance-preset="${id}" aria-pressed="false"><span class="ex-preset-preview ex-preset-${id}"><i></i><i></i><i></i></span><strong>${label}</strong><small>${description}</small></button>`).join('')}</div><div class="form-grid mt16">${field('Command layout','commandStyle',layout.commandStyle,{options:[{value:'standard',label:'Standard toolbar (Explorer)'},{value:'ribbon',label:'Grouped ribbon'}]})}${field('Preview pane','previewPosition',layout.previewPosition,{options:[{value:'bottom',label:'Below document list'},{value:'right',label:'Right of document list'},{value:'hidden',label:'Hidden'}]})}${field('Row density','density',config.density,{options:[{value:'compact',label:'Compact'},{value:'standard',label:'Standard'},{value:'comfortable',label:'Comfortable'}]})}${field('Workspace navigation rail','navigationRail',layout.navigationRail?'yes':'no',{options:[{value:'no',label:'Hidden — use Window / All workspaces'},{value:'yes',label:'Visible'}]})}</div><div class="ex-appearance-checks">${[['rowLines','Document grid lines'],['fileDescriptions','Secondary descriptions beneath filenames'],['columnFilters','Inline column filter row'],['ribbonVisible','Show command toolbar'],['treeVisible','Show datasource tree']].map(([id,label])=>`<label><input type="checkbox" name="${id}" ${layout[id]?'checked':''}>${label}</label>`).join('')}</div><p class="small muted mt16">Touch mode keeps larger targets regardless of the selected row density. Mobile cards and the bottom navigation remain available.</p>`,data=>{
   layout=normalizeExplorerLayout({...currentLayout,commandStyle:data.commandStyle,previewPosition:data.previewPosition,navigationRail:data.navigationRail==='yes',...Object.fromEntries(['rowLines','fileDescriptions','columnFilters','ribbonVisible','treeVisible'].map(key=>[key,data[key]==='on']))});
   config=normalizeExplorerView({...config,density:data.density});persist();R();toast('Explorer appearance updated.');
  },{wide:true,label:'Apply appearance',onMount(dialog){for(const button of dialog.querySelectorAll('[data-appearance-preset]'))button.addEventListener('click',()=>{const preset=explorerPresentationPreset(button.dataset.appearancePreset,currentLayout);Object.assign(currentLayout,preset);for(const key of ['commandStyle','previewPosition'])dialog.querySelector(`[name=${key}]`).value=preset[key];dialog.querySelector('[name=navigationRail]').value=preset.navigationRail?'yes':'no';dialog.querySelector('[name=density]').value=button.dataset.appearancePreset==='ribbon'?'standard':currentDensity;for(const key of ['rowLines','fileDescriptions','columnFilters','ribbonVisible','treeVisible'])dialog.querySelector(`[name=${key}]`).checked=preset[key];for(const item of dialog.querySelectorAll('[data-appearance-preset]'))item.setAttribute('aria-pressed',String(item===button));});}});
 }
 async function handleAction(action,button){
  if(action==='bulk-move'&&U().route==='documents'){moveDialog();return true;}
  if(!action.startsWith('ex-'))return false;sync();const id=button?.dataset.id;
  switch(action){
   case 'ex-menu':openMenu(button.dataset.menu,button);break;
   case 'ex-appearance':appearanceDialog();break;
   case 'ex-command-style':layout=normalizeExplorerLayout({...layout,commandStyle:button.dataset.style,ribbonVisible:true});persist();R();break;
   case 'ex-toggle-rail':layout.navigationRail=!layout.navigationRail;persist();R();break;
   case 'ex-row-lines':layout.rowLines=!layout.rowLines;persist();R();break;
   case 'ex-file-descriptions':layout.fileDescriptions=!layout.fileDescriptions;persist();R();break;
   case 'ex-collection':{const key='closed:'+id;expanded.has(key)?expanded.delete(key):expanded.add(key);persist();R();break;}
   case 'ex-pane-menu':openMenu('Preview pane',button,null,[menuItem('Below document list','ex-dock','rectangle','data-position="bottom"'),menuItem('Right of document list','ex-dock','rectangle','data-position="right"'),menuItem('Hide preview','ex-dock','close','data-position="hidden"')]);break;
   case 'ex-touch-select':touchSelecting=!touchSelecting;if(!touchSelecting)U().selection.clear();R();break;
   case 'ex-touch-open':if(touchSelecting)setFocus(id,{ctrlKey:true});else await ctx.openDocument(id);break;
   case 'ex-touch-menu':if(!U().selection.has(id))U().selection=new Set([id]);activeId=id;anchor=id;R();openMenu('Document',document.querySelector(`[data-action=ex-touch-menu][data-id="${CSS.escape(id)}"]`)||button);break;
   case 'ex-touch-sort':form('Sort documents',field('Column','key',config.sort[0]?.key||'name',{options:explorerColumns(project()).map(c=>({value:c.key,label:c.label}))})+field('Direction','direction',config.sort[0]?.direction||'asc',{options:[{value:'asc',label:'Ascending'},{value:'desc',label:'Descending'}]}),data=>{config=normalizeExplorerView({...config,sort:[{key:data.key,direction:data.direction}]});U().page=0;persist();R();},{label:'Apply sort'});break;
   case 'ex-ribbon-tab':if(ctx.mobile?.small){const tab=button.dataset.tab;openMenu(tab==='home'?'File':tab==='view'?'View':'Review & deliver',button,null,tab==='review'?[menuItem('Reviews','ex-route','review','data-route=reviews'),menuItem('My work','ex-route','review','data-route=inbox'),menuItem('Document sets','ex-route','layers','data-route=sets'),menuItem('Transmittals','ex-route','send','data-route=transmittals'),menuItem('Issues & RFIs','ex-route','issue','data-route=issues')]:null);}else{ribbonTab=button.dataset.tab;persist();R();}break;
   case 'ex-toggle-ribbon':case 'ex-ribbon-toggle':layout.ribbonVisible=!layout.ribbonVisible;persist();R();break;
   case 'ex-toggle-tree':case 'ex-tree-toggle':if(innerWidth<=780){layout.treeVisible=true;document.body.classList.toggle('ex-tree-overlay');R();}else{layout.treeVisible=!layout.treeVisible;persist();R();}break;
   case 'ex-expand':expanded.has(id)?expanded.delete(id):expanded.add(id);persist();R();break;
   case 'ex-tree':go(button.dataset.project||(button.dataset.scope==='folder'?S().folders.find(f=>f.id===id)?.projectId:id),button.dataset.scope==='folder'?id:'');break;
   case 'ex-route':ctx.navigate(button.dataset.route);break;
   case 'ex-shortcut-open':{const mark=visibleExplorerBookmarks(S(),E().actorId).find(x=>x.id===id);if(!mark)throw new Error('Shortcut unavailable.');if(mark.scope==='document'){const d=doc(mark.resourceId);go(d.projectId,d.folderId,{documentId:d.id});}else if(mark.scope==='folder'){const f=S().folders.find(x=>x.id===mark.resourceId);go(f.projectId,f.id);}else go(mark.resourceId);break;}
   case 'ex-recent':go(U().projectId);selectedGroup='recent';R();break;
   case 'ex-reveal':{const d=doc(id);if(!d)throw new Error('Document is no longer readable.');closeTopDialog(button);go(d.projectId,d.folderId,{documentId:id});break;}
   case 'ex-card':setFocus(id);break;
   case 'ex-back':navigateHistory(false);break;
   case 'ex-forward':navigateHistory(true);break;
   case 'ex-up':go(U().projectId,S().folders.find(f=>f.id===U().folderId)?.parentId||'');break;
   case 'ex-refresh':if(typeof E().refresh==='function')await E().refresh();else if(typeof E().reload==='function')await E().reload();R();break;
   case 'ex-copy-link':case 'ex-link':await copyLink();break;
   case 'ex-go-link':goLinkDialog();break;
   case 'ex-inspector-tab':inspectorTab=button.dataset.tab;R();break;
   case 'ex-dock':layout.previewPosition=button.dataset.position||(['bottom','right','hidden'][(['bottom','right','hidden'].indexOf(layout.previewPosition)+1)%3]);persist();R();break;
   case 'ex-sort':{const key=button.dataset.key,prior=config.sort.find(s=>s.key===key),direction=prior?.direction==='asc'?'desc':'asc';if(button.dataset.shift==='true'){config.sort=[...config.sort.filter(s=>s.key!==key),{key,direction}].slice(-3);delete button.dataset.shift;}else config.sort=[{key,direction}];U().page=0;persist();R();break;}
   case 'ex-clear-column-filters':filterValues={};U().page=0;R();break;
   case 'ex-columns':columnsDialog();break;
   case 'ex-toggle-filters':case 'ex-column-filters':layout.columnFilters=!layout.columnFilters;filterValues={};U().page=0;persist();R();break;
   case 'ex-filter':filterDialog();break;
   case 'ex-preview-previous':advancePreview(-1);break;
   case 'ex-preview-next':advancePreview(1);break;
   case 'ex-remove-filter':{const kind=button.dataset.kind,key=button.dataset.key;if(kind==='query'){U().query='';config.query='';}else if(kind==='state')U().stateFilter='';else if(kind==='discipline')U().discipline='';else if(kind==='advanced')config.filters=config.filters.filter((_,i)=>i!==Number(key));else if(kind==='column')delete filterValues[key];else if(kind==='collection')selectedGroup='';U().page=0;persist();R();break;}
   case 'ex-clear':config={...config,query:'',filters:[],columnFilters:{},quickFilters:{state:'',discipline:''}};U().query='';U().stateFilter='';U().discipline='';U().page=0;filterValues={};selectedGroup='';persist();R();break;
   case 'ex-reset':config=explorerDetailView(U().projectId,U().folderId||null);layout=baseLayout();filterValues={};activeView='';selectedGroup='';U().query='';U().stateFilter='';U().discipline='';U().page=0;persist();R();break;
   case 'ex-save':saveViewDialog();break;
   case 'ex-save-new':closeTopDialog(button);{const prior=activeView;activeView='';saveViewDialog();activeView=prior;}break;
   case 'ex-manage-views':case 'ex-views':manageViews();break;
   case 'ex-view':{const v=visibleExplorerViews(S(),E().actorId).find(v=>v.id===id);if(!v)throw new Error('View is no longer available.');closeTopDialog(button);go(v.projectId,v.config.folderId,{viewId:id});break;}
   case 'ex-view-remove':{const v=visibleExplorerViews(S(),E().actorId).find(v=>v.id===id);if(!v)throw new Error('View is no longer available.');closeTopDialog(button);ctx.confirmAction('Delete saved view?',`Remove “${v.name}”? Documents and their revisions are not deleted.`,async()=>{await E().run('explorerView.remove',{id:v.id,expectedVersion:v.version});if(activeView===v.id)activeView='';R();},{label:'Delete view',danger:true});break;}
   case 'ex-pin-location':button={dataset:{scope:U().folderId?'folder':'project',resource:U().folderId||U().projectId}};
   case 'ex-pin':{const scope=button.dataset.scope||(activeId?'document':U().folderId?'folder':'project'),resourceId=button.dataset.resource||(scope==='document'?activeId:scope==='folder'?U().folderId:U().projectId);await E().run('explorerBookmark.toggle',{scope,resourceId});R();break;}
   case 'ex-cut':{const items=selected();if(!items.length)throw new Error('Select documents to cut.');if(items.length>100)throw new Error('Cut at most 100 documents per atomic move.');clipboard={identity,projectId:U().projectId,items:items.map(d=>({id:d.id,folderId:d.folderId||null,versionId:currentVersion(d).id}))};toast(`${items.length} document${items.length===1?'':'s'} ready to move. Navigate to a destination and paste.`);R();break;}
   case 'ex-paste':if(!clipboard||clipboard.identity!==identity)throw new Error('No controlled-document selection has been cut in this account.');if(clipboard.projectId!==U().projectId)throw new Error('Move within the same project. Cross-project copying is not supported.');moveDialog(clipboard.items.map(x=>x.id),U().folderId,true);break;
   case 'ex-rename':renameDialog(button.dataset.id?[button.dataset.id]:undefined);break;
   case 'ex-copy':copyDialog(button.dataset.id?[button.dataset.id]:undefined);break;
   case 'ex-move':moveDialog();break;
   case 'ex-transition':if(!activeId)throw new Error('Select a document.');ctx.automation.previewDialog(activeId);break;
   case 'ex-page-prev':U().page=Math.max(0,U().page-1);scroll.y=0;R();break;
   case 'ex-page-next':if((U().page+1)*config.pageSize<pageResult.total)U().page++;scroll.y=0;R();break;
   case 'ex-shortcuts':shortcuts();break;
   default:throw new Error('Unknown Explorer action: '+action);
  }return true;
 }
 function beforeRender(){const host=document.querySelector('[data-explorer]');if(host){const grid=host.querySelector('.ex-grid-scroll'),tree=host.querySelector('.ex-tree-scroll');if(grid){scroll.x=grid.scrollLeft;scroll.y=grid.scrollTop;}if(tree)scroll.tree=tree.scrollTop;}clearTimeout(debounce);controller?.abort();controller=null;previewTicket++;preview?.destroy();preview=null;closeMenu(false);}
 function afterRender(){
  const host=document.querySelector('[data-explorer]');if(!host)return;controller=new AbortController();const signal=controller.signal,on=(target,type,fn)=>target?.addEventListener(type,fn,{signal}),grid=host.querySelector('.ex-grid-scroll'),tree=host.querySelector('.ex-tree-scroll');if(grid){grid.scrollLeft=scroll.x;grid.scrollTop=scroll.y;}if(tree)tree.scrollTop=scroll.tree;
  if(focusAfter){const row=[...host.querySelectorAll('[data-ex-row]')].find(row=>row.dataset.exRow===focusAfter);row?.focus({preventScroll:true});row?.scrollIntoView({block:'nearest',inline:'nearest'});focusAfter='';}
  bindLongPress(host,value=>{const row=value.target.closest('[data-ex-row]');if(!row||value.target.closest('input,button,select,a,textarea'))return false;const id=row.dataset.exRow;if(!U().selection.has(id))U().selection=new Set([id]);activeId=id;anchor=id;openMenu('Document',row,{x:value.x,y:value.y});return true;},{signal});
  const applyFilter=()=>{U().page=0;persist();R();};
  on(host,'input',event=>{const input=event.target;if(input.id==='document-search'){event.stopPropagation();U().query=input.value;config.query=input.value;clearTimeout(debounce);debounce=setTimeout(applyFilter,160);}else if(input.hasAttribute('data-ex-column-filter')){event.stopPropagation();filterValues[input.dataset.exColumnFilter]=input.value;clearTimeout(debounce);debounce=setTimeout(applyFilter,180);}else if(input.id==='ex-tree-search'){event.stopPropagation();treeSearch=input.value;clearTimeout(debounce);debounce=setTimeout(R,160);}});
  on(host,'change',event=>{const input=event.target;if(input.hasAttribute('data-select-doc')){event.stopPropagation();const id=input.dataset.selectDoc;input.checked?U().selection.add(id):U().selection.delete(id);activeId=id;anchor=id;if(mobileCards())touchSelecting=U().selection.size>0;remember(id);R();}else if(input.id==='select-all-docs'){event.stopPropagation();for(const d of pageResult.items)input.checked?U().selection.add(d.id):U().selection.delete(d.id);activeId=pageResult.items.find(d=>U().selection.has(d.id))?.id||'';R();}else if(['state-filter','discipline-filter'].includes(input.id)){event.stopPropagation();U()[input.id==='state-filter'?'stateFilter':'discipline']=input.value;applyFilter();}else if(input.id==='ex-recursive'){config.includeSubfolders=input.checked;applyFilter();}else if(input.id==='ex-page-size'){config.pageSize=Number(input.value);applyFilter();}else if(input.id==='ex-view-select'){event.stopPropagation();if(input.value)run(handleAction('ex-view',{dataset:{id:input.value}}));else{activeView='';go(U().projectId);} }});
  on(host,'click',event=>{const input=event.target.closest('input,select,textarea');if(input){event.stopPropagation();return;}const action=event.target.closest('[data-action]');if(action){if(action.dataset.action==='ex-sort')action.dataset.shift=String(event.shiftKey);if(action.dataset.action==='clear-selection'){activeId='';anchor=null;touchSelecting=false;}return;}const row=event.target.closest('[data-ex-row]');if(row){event.stopPropagation();const id=row.dataset.exRow,now=performance.now();if(!event.ctrlKey&&!event.metaKey&&!event.shiftKey&&lastRowClick?.id===id&&now-lastRowClick.at<450){lastRowClick=null;run(ctx.openDocument(id));}else{setFocus(id,event);lastRowClick={id,at:now};}}});
  on(host,'dblclick',event=>{const row=event.target.closest('[data-ex-row]');if(row&&!event.target.closest('input,button,a')){event.preventDefault();event.stopPropagation();}});
  on(host,'contextmenu',event=>{const row=event.target.closest('[data-ex-row]'),node=event.target.closest('[data-action="ex-tree"]');if(row){event.preventDefault();event.stopPropagation();const id=row.dataset.exRow;if(!U().selection.has(id)){U().selection=new Set([id]);anchor=id;}activeId=id;R();openMenu('Document',document.querySelector(`[data-ex-row="${CSS.escape(id)}"]`),{x:event.clientX,y:event.clientY});}else if(node){event.preventDefault();event.stopPropagation();const scope=node.dataset.scope,id=node.dataset.id;openMenu('Location',node,{x:event.clientX,y:event.clientY},[menuItem('Open folder','ex-tree','folder',`data-scope="${e(scope)}" data-id="${e(id)}" data-project="${e(node.dataset.project||id)}"`),menuItem('Pin / unpin location','ex-pin','star',`data-scope="${e(scope)}" data-resource="${e(id)}"`)]);}});
  on(host,'keydown',event=>{
   if(event.altKey&&event.key.toLowerCase()==='d'){event.preventDefault();event.stopPropagation();goLinkDialog();return;}
   if(event.key==='F6'){event.preventDefault();event.stopPropagation();const targets=[host.querySelector('.ex-tree-search input'),host.querySelector('.ex-document-table tr[tabindex="0"]')||host.querySelector('.mobile-file-title button'),host.querySelector('.ex-inspector-tabs [aria-selected="true"]'),host.querySelector('#document-search')].filter(Boolean);const index=targets.indexOf(document.activeElement);targets[(index+(event.shiftKey?-1:1)+targets.length)%targets.length]?.focus();return;}
   if(event.target.closest('.ex-menubar')&&['ArrowLeft','ArrowRight','Home','End','ArrowDown'].includes(event.key)){event.preventDefault();event.stopPropagation();const items=[...host.querySelectorAll('.ex-menubar [data-menu]')],index=items.indexOf(event.target.closest('[data-menu]'));if(index<0)return;if(event.key==='ArrowDown')openMenu(items[index].dataset.menu,items[index]);else items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowLeft'?-1:1)+items.length)%items.length]?.focus();return;}
   if(event.target.closest('.ex-inspector-tabs')&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();event.stopPropagation();const items=[...host.querySelectorAll('.ex-inspector-tabs [role=tab]')],index=items.indexOf(event.target.closest('[role=tab]')),next=items[event.key==='Home'?0:event.key==='End'?items.length-1:(index+(event.key==='ArrowLeft'?-1:1)+items.length)%items.length];if(next){inspectorTab=next.dataset.tab;R();host.isConnected||document.querySelector(`.ex-inspector-tabs [data-tab="${inspectorTab}"]`)?.focus();}return;}
   if(event.target.matches('input,select,textarea')||event.target.closest('[contenteditable=true]'))return;
   const separator=event.target.closest('[data-ex-resize],[data-resize-column]');if(separator&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const delta=['ArrowRight','ArrowDown'].includes(event.key)?16:-16;adjustSize(separator,delta);persist();R();return;}
   if(event.altKey&&['ArrowLeft','ArrowRight','ArrowUp'].includes(event.key)){event.preventDefault();event.stopPropagation();run(handleAction(event.key==='ArrowLeft'?'ex-back':event.key==='ArrowRight'?'ex-forward':'ex-up',{dataset:{}}));return;}
   const node=event.target.closest('.ex-tree [data-action="ex-tree"]');
   if(node){const nodes=[...host.querySelectorAll('.ex-tree [data-action="ex-tree"]')],i=nodes.indexOf(node),nodeId=node.dataset.id,isProject=node.dataset.scope==='project',key=isProject?'project:'+nodeId:nodeId;
    const refocus=id=>document.getElementById('ex-node-'+id)?.focus({preventScroll:true});
    if(['ArrowDown','ArrowUp','ArrowRight','ArrowLeft','Home','End'].includes(event.key)){
     event.preventDefault();event.stopPropagation();
     if(event.key==='ArrowRight'){
      if(node.hasAttribute('aria-expanded')&&!expanded.has(key)){expanded.add(key);persist();R();refocus(nodeId);}
      else if(node.hasAttribute('aria-expanded'))nodes[i+1]?.focus();
     }else if(event.key==='ArrowLeft'){
      if(node.hasAttribute('aria-expanded')&&expanded.has(key)){expanded.delete(key);persist();R();refocus(nodeId);}
      else if(!isProject){const f=S().folders.find(f=>f.id===nodeId);refocus(f?.parentId||f?.projectId);}
     }else nodes[event.key==='Home'?0:event.key==='End'?nodes.length-1:Math.min(nodes.length-1,Math.max(0,i+(event.key==='ArrowDown'?1:-1)))]?.focus();
     return;
    }
    if(event.key.length===1&&!event.ctrlKey&&!event.metaKey&&!event.altKey&&event.key!==' '){event.preventDefault();const now=performance.now();treeTypeahead=now-treeTypeaheadAt<650?treeTypeahead+event.key.toLowerCase():event.key.toLowerCase();treeTypeaheadAt=now;const ordered=[...nodes.slice(i+1),...nodes.slice(0,i+1)];ordered.find(n=>n.textContent.trim().toLowerCase().startsWith(treeTypeahead))?.focus();return;}
   }

   if(!event.target.closest('.ex-document-area'))return;const ids=pageResult.items.map(d=>d.id),i=ids.indexOf(activeId),ctrl=event.ctrlKey||event.metaKey;
   if(['ArrowDown','ArrowUp','Home','End'].includes(event.key)&&ids.length){event.preventDefault();event.stopPropagation();const index=event.key==='Home'?0:event.key==='End'?ids.length-1:Math.min(ids.length-1,Math.max(0,i+(event.key==='ArrowDown'?1:-1)));setFocus(ids[index],{shiftKey:event.shiftKey});}
   else if(ctrl&&event.key.toLowerCase()==='a'){event.preventDefault();event.stopPropagation();U().selection=new Set(ids);activeId=activeId||ids[0]||'';R();}
   else if(ctrl&&event.shiftKey&&event.key.toLowerCase()==='c'){event.preventDefault();event.stopPropagation();run(handleAction('ex-copy',{dataset:{}}));}
   else if(ctrl&&['x','v'].includes(event.key.toLowerCase())){event.preventDefault();event.stopPropagation();run(handleAction(event.key.toLowerCase()==='x'?'ex-cut':'ex-paste',{dataset:{}}));}
   else if(event.key===' '&&activeId){event.preventDefault();event.stopPropagation();setFocus(activeId,{ctrlKey:true});}
   else if(event.key==='Enter'&&activeId&&!event.target.closest('button')){event.preventDefault();event.stopPropagation();run(ctx.openDocument(activeId));}
   else if(event.key==='F2'&&event.shiftKey&&U().selection.size){event.preventDefault();event.stopPropagation();run(handleAction('ex-rename',{dataset:{}}));}
   else if(event.key==='F2'&&activeId){event.preventDefault();event.stopPropagation();run(ctx.dispatch('edit-document',{dataset:{id:activeId},closest:()=>null}));}
   else if(event.key==='Escape'){event.preventDefault();activeId='';U().selection.clear();R();}
  });
  on(host,'pointerdown',event=>{const target=event.target.closest('[data-ex-resize],[data-resize-column]');if(!target||event.button!==0)return;event.preventDefault();event.stopPropagation();const startX=event.clientX,startY=event.clientY,start=target.dataset.resizeColumn?(config.widths[target.dataset.resizeColumn]||explorerColumns(project()).find(c=>c.key===target.dataset.resizeColumn)?.width||160):target.dataset.exResize==='tree'?layout.treeWidth:layout.previewPosition==='bottom'?layout.previewSize:layout.previewWidth;target.setPointerCapture(event.pointerId);const move=next=>{const delta=target.dataset.resizeColumn||target.dataset.exResize==='tree'?next.clientX-startX:layout.previewPosition==='bottom'?startY-next.clientY:startX-next.clientX;setSize(target,start+delta);const outer=document.querySelector('[data-explorer]');outer.style.setProperty('--ex-tree-width',layout.treeWidth+'px');outer.style.setProperty('--ex-preview-size',layout.previewSize+'px');outer.style.setProperty('--ex-preview-width',layout.previewWidth+'px');if(target.dataset.resizeColumn){const index=config.columns.indexOf(target.dataset.resizeColumn);const col=host.querySelectorAll('.ex-document-table col')[index+1];if(col)col.style.width=config.widths[target.dataset.resizeColumn]+'px';}};const up=()=>{target.removeEventListener('pointermove',move);target.removeEventListener('pointerup',up);target.removeEventListener('pointercancel',up);persist();R();};target.addEventListener('pointermove',move);target.addEventListener('pointerup',up);target.addEventListener('pointercancel',up);});
  on(host,'dragstart',event=>{const header=event.target.closest('[data-ex-column]'),row=event.target.closest('[data-ex-row]');if(header&&!event.target.closest('[data-resize-column]')){event.stopPropagation();event.dataTransfer.setData('application/x-civora-column',header.dataset.exColumn);event.dataTransfer.effectAllowed='move';}else if(row){event.stopPropagation();const id=row.dataset.exRow,ids=U().selection.has(id)?[...U().selection]:[id];event.dataTransfer.setData('application/x-civora-explorer',JSON.stringify({identity,projectId:U().projectId,items:ids.map(id=>({id,versionId:currentVersion(doc(id)).id,folderId:doc(id).folderId||null}))}));event.dataTransfer.effectAllowed='move';}});
  on(host,'dragover',event=>{if(event.target.closest('[data-ex-drop],[data-ex-column]')||event.dataTransfer.types.includes('Files')){event.preventDefault();event.stopPropagation();event.dataTransfer.dropEffect=event.dataTransfer.types.includes('Files')?'copy':'move';}});
  on(host,'drop',event=>{event.preventDefault();event.stopPropagation();run((async()=>{const column=event.dataTransfer.getData('application/x-civora-column'),targetHeader=event.target.closest('[data-ex-column]');if(column&&targetHeader){if(!config.columns.includes(column))return;const target=targetHeader.dataset.exColumn;config.columns=config.columns.filter(k=>k!==column);config.columns.splice(Math.max(0,config.columns.indexOf(target)),0,column);persist();R();return;}
   const target=event.target.closest('[data-ex-drop]'),folderId=target?target.dataset.exDrop||'':U().folderId,projectId=target?.dataset.project||U().projectId;
   const payload=event.dataTransfer.getData('application/x-civora-explorer');if(payload){let data;try{data=JSON.parse(payload);}catch{throw new Error('Invalid document drag payload.');}if(data.identity!==identity||data.projectId!==projectId)throw new Error('Move documents within the same workspace, account and project.');if(!Array.isArray(data.items)||!data.items.length||data.items.length>100)throw new Error('Move at most 100 documents at a time.');for(const item of data.items){const d=doc(item.id);if(!d||currentVersion(d).id!==item.versionId||(d.folderId||null)!==item.folderId)throw new Error('Dragged source changed. Start the drag again.');}moveDialog(data.items.map(x=>x.id),folderId);return;}
   if(event.dataTransfer.files.length||[...event.dataTransfer.items].some(i=>i.kind==='file')){const initialIdentity=identity,initialEngine=E(),captured=await collectDroppedFiles(event.dataTransfer);if(identity!==initialIdentity||E()!==initialEngine)throw new Error('Workspace or account changed while reading dropped files. Drop the files again.');go(projectId,folderId);await ctx.importFiles(captured);}
  })());});
  if(inspectorTab==='preview'&&activeId){const target=host.querySelector('#ex-file-preview'),d=doc(activeId),ticket=++previewTicket,initial=E(),version=d&&currentVersion(d);if(target&&d&&can('download','document',d.id))run((async()=>{try{const blob=await initial.repository.blob(version.blobId);if(ticket!==previewTicket||initial!==E()||!target.isConnected||!can('download','document',d.id))return;const handle=await mountPreview(target,{blob,name:d.name,markups:(S().markups||[]).filter(m=>m.documentId===d.id&&m.versionId===version.id)});if(ticket!==previewTicket||initial!==E()||!target.isConnected){handle.destroy();return;}preview=handle;}catch(error){if(ticket===previewTicket&&target.isConnected)target.textContent='Preview unavailable: '+error.message;}})());}
 }
 function setSize(target,value){if(target.dataset.resizeColumn)config.widths[target.dataset.resizeColumn]=Math.max(64,Math.min(900,Math.round(value)));else if(target.dataset.exResize==='tree')layout.treeWidth=Math.max(190,Math.min(480,Math.round(value)));else if(layout.previewPosition==='bottom')layout.previewSize=Math.max(160,Math.min(600,Math.round(value)));else layout.previewWidth=Math.max(260,Math.min(650,Math.round(value)));}
 function adjustSize(target,delta){const value=target.dataset.resizeColumn?(config.widths[target.dataset.resizeColumn]||explorerColumns(project()).find(c=>c.key===target.dataset.resizeColumn)?.width||160):target.dataset.exResize==='tree'?layout.treeWidth:layout.previewPosition==='bottom'?layout.previewSize:layout.previewWidth;setSize(target,value+delta);}
 return {page,prepareShell,handleAction,beforeRender,afterRender,go,applyLink,moveDialog,copyDialog,renameDialog,close:beforeRender,openResource(kind,id){const target=kind==='document'?doc(id):S().folders.find(f=>f.id===id);if(!target||!can('read',kind,id))throw new Error('The location is no longer available.');go(target.projectId,kind==='folder'?target.id:target.folderId,{documentId:kind==='document'?target.id:''});},get recents(){return recents.filter(id=>doc(id));},get configuration(){return structuredClone(config);},get layout(){return {...layout};},get activeId(){return activeId;},get result(){return pageResult?{total:pageResult.total,ids:[...pageResult.ids]}:null;}};
}
