import { BrowserDirectoryFS, HttpDirectoryFS, FolderBookmarks, DirectoryMonitor, filesystemCapabilities, portableName, relativePath, joinPath, hashBlob, optionalRead } from '../packages/filesystem/index.js';
import { DirectoryRepository } from '../packages/filesystem/repository.js';
import { WorkingCopyManager, importTree, exportTree, workingPath, documentPermission } from '../packages/filesystem/working-copies.js';
import { decodeTextFile, encodeTextFile } from '../packages/filesystem/text.js';
import { createEmptyWorkspace, currentVersion, copy, uid } from '../packages/core/index.js';
import { fetchJSON } from '../packages/storage/index.js';
import { createZip } from '../packages/storage/archive.js';
import { escapeHTML as e, icon, fileBadge, formatBytes, formatDate, toast, downloadBlob, openDialog, formField as field, emptyState } from '../packages/controls/index.js';
export function createLocalFeatures(ctx) {
  const { getEngine:E, getState:S, getUI:U, render, navigate, heading, button:b, formDialog, confirmAction, activateEngine, preferences, safeWrite, openDocument } = ctx;
  const bookmarks = new FolderBookmarks(), mounts = new Map();
  let source = null, actorId = '', activeId = '', path = '', tab = 'files', entries = [], rows = [], trash = [], recents = [], capabilities = null, loading = false, initialLoaded = false, error = '', manager = null, monitor = null, task = null, lastReport = null, lastScan = '', fileQuery = '', page = 0;
  const active = () => mounts.get(activeId), team = () => E().repository.kind === 'server', selected = id => rows.find(r => r.id === id), fileAt = path => entries.find(f => f.path === path), canWrite = () => !!active() && !active().readOnly;
  const note = (text, warning = false) => `<div class="note-box ${warning ? 'local-warning' : ''}">${icon(warning ? 'issue' : 'shield',16)}<span>${text}</span></div>`;
  const action = (text,name,glyph,extra='',style='small') => b(text,'local-'+name,glyph,extra,style);
  function resetContext() {
    if (source === E() && actorId === E().actorId) return;
    task?.controller.abort(); monitor?.stop(); manager?.close(); manager = null; monitor = null; entries = []; rows = []; trash = []; error = ''; capabilities = null; initialLoaded = false; loading = false; source = E(); actorId = E().actorId; path = ''; page = 0;
    const repositoryFS = E().repository.fs;
    for (const [id,fs] of mounts) if (fs !== repositoryFS) { fs.close(); mounts.delete(id); }
    if (repositoryFS) { mounts.set(repositoryFS.id,repositoryFS); activeId = repositoryFS.id; } else activeId = '';
  }
  function contextToken() { return { engine:E(), actor:E().actorId, fs:active() }; }
  function current(token) { return token.engine === E() && token.actor === E().actorId && (!token.fs || token.fs === active()); }
  async function attach(fs, remember = true) {
    mounts.set(fs.id,fs); activeId = fs.id; path = ''; page = 0; error = ''; manager?.close(); manager = null; monitor?.stop(); monitor = null;
    if (remember && fs.kind === 'browser-folder') { try { await bookmarks.save(fs); recents = await bookmarks.list(); } catch { toast('Folder opened for this session. This browser could not remember its handle.'); } }
    await refresh(); navigate('local');
  }
  async function pick(readOnly = false) {
    if (!globalThis.showDirectoryPicker) throw new Error('This browser has no folder picker. Use Import folder or the authenticated localhost edition.');
    const handle = await showDirectoryPicker({ id:'civora-local-system',mode:readOnly?'read':'readwrite' });
    const existing = [...mounts.values()].find(fs=>fs.kind==='browser-folder'&&fs.handle===handle);
    await attach(existing || new BrowserDirectoryFS(handle,{readOnly}));
  }
  async function refresh() {
    if (!active()) { entries=[];rows=[];trash=[]; render(); return; }
    const token = contextToken(); error = ''; const fs = active(); loading = true;
    try {
      const nextEntries = await fs.list(path);
      if (!current(token)) return;
      entries = nextEntries;
      if (!manager) manager = await new WorkingCopyManager(E(),fs).open();
      rows = await manager.scan();
      if (tab === 'trash') trash = await fs.trashList();
      lastScan = new Date().toLocaleTimeString();
    } catch (err) { if (current(token)) error = err.message; }
    finally { if (current(token)) { loading = false; if(U().route==='local')render(); } }
  }
  async function load() {
    if (initialLoaded || loading) return; initialLoaded = true; loading = true; const engine = E(), who = E().actorId;
    try { try { recents = await bookmarks.list(); } catch { recents = []; }
      if (team()) {
        try {
          capabilities = await fetchJSON('/api/local/status');
          if (engine !== E() || who !== E().actorId) return;
          for (const root of capabilities.roots) { const fs = new HttpDirectoryFS(root); fs.revealEnabled = root.reveal; mounts.set(fs.id,fs); }
          if (!activeId) activeId = capabilities.roots[0]?.id || '';
        } catch (err) { capabilities = { enabled:false, error:err.message }; }
      }
    } finally { loading = false; if(engine===E()&&who===E().actorId) await refresh(); }
  }
  function mountPanel() {
    return `<aside class="local-volumes"><div class="local-section-label">CONNECTED LOCATIONS <span>${mounts.size}</span></div>${[...mounts.values()].map(fs=>`<button class="local-volume ${fs.id===activeId?'active':''}" data-action="local-select-root" data-id="${e(fs.id)}">${icon(fs.kind==='browser-folder'?'folder':'database',20)}<span><strong>${e(fs.label)}</strong><small>${fs.kind==='browser-folder'?'Browser-granted folder':'Localhost disk'} · ${fs.readOnly?'read-only':'read/write'}</small></span>${fs.id===activeId?'<i class="local-indicator"></i>':''}</button>`).join('') || '<p class="small muted local-inset">No folders connected. Your computer is not scanned automatically.</p>'}
      ${action('Connect a folder','pick','plus','','local-connect')}${action('Connect read-only','pick-readonly','lock','','text local-connect')}
      <div class="local-section-label mt24">RECENT BROWSER FOLDERS</div>${recents.slice(0,6).map(r=>`<div class="local-recent"><button data-action="local-reconnect" data-id="${e(r.id)}">${icon('history',14)}<span class="truncate">${e(r.label)}</span></button><button class="icon-button" title="Forget folder handle" aria-label="Forget ${e(r.label)}" data-action="local-forget" data-id="${e(r.id)}">${icon('close',12)}</button></div>`).join('')||'<p class="small muted local-inset">Reopen an approved folder after restarting your browser.</p>'}
      <div class="local-private">${icon('shield',23)}<strong>Scoped by you</strong><p>Only connected folders are exposed. Team permissions still govern controlled document downloads and check-ins.</p>${action('Local setup guide','guide','book','','text')}</div></aside>`;
  }
  function statusBadge(status) { const cls=['modified','conflict','out of date','access revoked'].includes(status)?status==='modified'?'modified':'attention':'normal';return `<span class="local-status ${cls}"><i></i>${e(status)}</span>`; }
  function filesPanel() {
    const all = entries.filter(row=>!fileQuery||row.name.toLowerCase().includes(fileQuery.toLowerCase())), shown = all.slice(page*60,(page+1)*60);
    return `<div class="local-browser-bar"><button class="icon-button" data-action="local-up" title="Parent folder" ${!path?'disabled':''}>${icon('left',16)}</button><span class="local-path">${icon('folder',14)}${e(active()?.label||'Select a location')}<span>/</span><strong>${e(path||'Root folder')}</strong></span>${action('Refresh','refresh','history',loading?'disabled':'')}</div>
      <div class="toolbar local-file-toolbar"><label class="search-input">${icon('search',15)}<input id="local-file-query" value="${e(fileQuery)}" placeholder="Find in this folder…" aria-label="Search local files"></label><span class="grow"></span>${action('New folder','mkdir','plus',!canWrite()?'disabled':'')}${action('New text file','new-file','file',!canWrite()?'disabled':'')}${action('Add files','upload','upload',!canWrite()?'disabled':'')}</div>
      ${active()?`<div class="table-wrap"><table class="local-file-table"><thead><tr><th>Name</th><th>Size</th><th>Modified</th><th>Actions</th></tr></thead><tbody>${shown.map(f=>`<tr><td><div class="row">${f.kind==='directory'?'<span class="local-folder-icon">'+icon('folder',21)+'</span>':fileBadge(f.name)}<button class="local-file-name" data-action="${f.kind==='directory'?'local-folder':'local-file'}" data-path="${e(f.path)}" ${f.kind==='blocked'?'disabled':''}>${e(f.name)}</button>${f.kind==='blocked'?statusBadge('blocked'):''}</div></td><td>${f.kind==='file'?formatBytes(f.size):'—'}</td><td class="nowrap muted">${formatDate(f.modifiedAt)}</td><td><div class="row">${f.kind==='file'?action('Open','file','eye',`data-path="${e(f.path)}"`)+action('Import','import-file','upload',`data-path="${e(f.path)}"`):f.kind==='directory'?action('Import tree','import-dir','upload',`data-path="${e(f.path)}"`):''}</div></td></tr>`).join('')||`<tr><td colspan="4"><div class="local-empty-inline">${icon('folder',34)}<strong>${fileQuery?'No matching files':'This folder is empty'}</strong><span>${fileQuery?'Try a different name.':'Create a folder, add files, or check out a controlled document.'}</span></div></td></tr>`}</tbody></table></div><div class="table-bottom"><span>${all.length} items · ${active().readOnly?'read-only':'SHA-256 guarded writes'}</span><div class="row">${action('Previous','previous','left',page===0?'disabled':'')}${action('Next','next','arrow',(page+1)*60>=all.length?'disabled':'')}</div></div>`:emptyState('Connect your working folder','Keep native files and controlled revisions together without uploading your entire computer.',action('Choose folder','pick','folder','','primary'))}`;
  }
  function workingPanel() {
    return `<div class="local-panel-head"><div><h2>Managed working copies</h2><p>Edit with your tools. Check in a verified revision when it is ready.</p></div>${action('Check out to disk','checkout','download',!canWrite()?'disabled':'','primary')}</div>
      ${note('Disk edits do not automatically change controlled documents. Each check-in verifies the source revision, current lock, permissions, and the exact local file hash.')}
      <div class="table-wrap mt16"><table class="local-working-table"><thead><tr><th>Document / local path</th><th>Revision</th><th>Local state</th><th>Actions</th></tr></thead><tbody>${rows.map(row=>`<tr><td><button class="local-file-name" data-action="local-document" data-id="${e(row.documentId)}">${e(row.name||row.documentId)}</button><small class="local-file-path">${e(row.path)}</small></td><td><span class="tag mono">${e(row.revision)}</span>${row.remoteChanged?` <span class="small muted">→ ${e(row.remoteRevision)}</span>`:''}</td><td>${statusBadge(row.status)}<small class="local-file-path">${row.owned?'Checked out by you':row.status==='access revoked'?'Existing disk copy cannot be recalled':'No checkout held by you'}</small></td><td><div class="row wrap">${row.canCheckin?action('Check in','checkin','upload',`data-id="${e(row.id)}"`,'primary small'):!row.owned&&!row.remoteChanged&&!active()?.readOnly?action('Check out','acquire','lock',`data-id="${e(row.id)}"`):''}${action('Inspect','work-inspect','eye',`data-id="${e(row.id)}"`)}${action('Refresh','work-refresh','history',`data-id="${e(row.id)}" ${!canWrite()?'disabled':''}`)}${action('Unlink','untrack','close',`data-id="${e(row.id)}" ${!canWrite()?'disabled':''}`)}</div></td></tr>`).join('')||`<tr><td colspan="4"><div class="local-empty-inline">${icon('download',30)}<strong>No tracked working copies</strong><span>Check out a document to a connected folder, then edit it locally.</span></div></td></tr>`}</tbody></table></div>
      <div class="local-watch-bar"><span>${icon('activity',16)}${monitor?.running?'Checking disk changes every 5 seconds':'Disk change checking is paused'}${lastScan?' · last scan '+e(lastScan):''}</span><div class="row">${action(monitor?.running?'Pause checks':'Watch changes','watch',monitor?.running?'close':'activity',!active()?'disabled':'')}${action('Scan now','refresh','history',!active()?'disabled':'')}</div></div>`;
  }
  function workspacePanel() {
    const repo=E().repository, disk=repo.kind==='directory';
    return `<div class="local-panel-head"><div><h2>Folder-backed workspace</h2><p>Store the workspace itself on your own disk, not only in browser storage.</p></div>${disk?'<span class="local-status normal"><i></i>Folder workspace active</span>':''}</div>
      <div class="local-workspace-grid"><article class="local-info-card">${icon('database',28)}<h3>Current storage</h3><strong>${disk?e(repo.fs.label):team()?'Authenticated team database':repo.kind==='memory'?'Temporary memory':'Browser IndexedDB'}</strong><p>${disk?'Each successful edit writes an immutable checkpoint and verifies content-addressed original files.':team()?'The localhost edition persists SQLite and files under its configured data directory. Browser folder workspaces remain a separate local sandbox.':'Move a copy of this workspace to a selected folder, or open an existing disk workspace.'}</p></article><article class="local-info-card">${icon('history',28)}<h3>Recovery by design</h3><p>Originals are retained by SHA-256. Checkpoints are immutable. The HEAD pointer selects the current checkpoint. Failed reads never silently reset a workspace.</p><span class="small muted">Single cooperating browser origin. Not a network multi-writer database.</span></article></div>
      ${note('Folder workspace permissions are local workflow rules—not OS authentication. Anyone with filesystem access can read its contents. Use the authenticated localhost/team edition for identity enforcement.',true)}
      <div class="form-actions">${action('Create empty on disk','create-workspace','plus',!active()||active()?.kind!=='browser-folder'||!canWrite()?'disabled':'')}${action('Copy current workspace to disk','copy-workspace','download',!active()||active()?.kind!=='browser-folder'||!canWrite()||team()?'disabled':'')}${action('Open folder workspace','open-workspace','folder',!active()||active()?.kind!=='browser-folder'?'disabled':'','primary')}${disk?action('Verify all originals','verify','shield')+action('Checkpoint recovery','history','history'):active()?.kind==='browser-folder'?action('Checkpoint recovery','history','history'):''}</div>
      <div class="local-file-layout"><code>.civora/<br> &nbsp;format.json &nbsp; <span>Workspace identity</span><br> &nbsp;HEAD.json &nbsp; &nbsp; <span>Verified current checkpoint</span><br> &nbsp;commits/ &nbsp; &nbsp; &nbsp;<span>Immutable metadata revisions</span><br> &nbsp;blobs/ &nbsp; &nbsp; &nbsp; &nbsp;<span>Original bytes by SHA-256</span><br>.civora-work/ &nbsp; <span>Per-workspace, per-user working-copy index</span><br>.civora-trash/ &nbsp;<span>Recoverable local files</span></code></div>`;
  }
  function transferPanel() {
    return `<div class="local-panel-head"><div><h2>Transfer center</h2><p>Bring in an existing folder tree, or export pinned project documents.</p></div></div>
      <div class="local-workspace-grid"><article class="local-info-card">${icon('upload',27)}<h3>Import folders</h3><p>Keep the nested folder structure and original bytes. Imports create controlled documents; existing documents are never silently replaced.</p>${action('Choose folder to import','import-picker','folder','','primary')}${active()?action('Import connected folder','import-dir','upload',`data-path="${e(path)}"`):''}</article><article class="local-info-card">${icon('download',27)}<h3>Export this project</h3><p>Write exact current revisions into a new folder with a manifest. No existing destination is overwritten.</p>${action('Export to connected folder','export-project','folder',!canWrite()?'disabled':'','primary')}${action('Download project ZIP','export-zip','download')}</article></div>
      ${note('Imports and folder exports are sequential audited operations. Cancellation stops the next file; completed files are retained and listed in a report. Up to 5,000 imported files per batch, 50 MiB per file.')}
      ${lastReport?`<div class="local-report"><div class="row spread"><h3>Last transfer</h3>${action('Save report','report','download')}</div><div class="row wrap"><span class="tag">${lastReport.created?.length||0} completed</span><span class="tag">${lastReport.failed?.length||0} failed</span><span class="tag">${lastReport.cancelled?'Cancelled':'Finished'}</span></div><div class="table-wrap"><table><thead><tr><th>Path</th><th>Result</th></tr></thead><tbody>${[...(lastReport.failed||[]).map(x=>({...x,failed:true})),...(lastReport.created||[])].slice(0,100).map(r=>`<tr><td>${e(r.path)}</td><td>${r.failed?e(r.error):'Completed'}</td></tr>`).join('')}</tbody></table></div></div>`:''}`;
  }
  function trashPanel() {
    return `<div class="local-panel-head"><div><h2>Local file recovery</h2><p>Restore removed files or previous bytes without overwriting a destination.</p></div>${action('Refresh','refresh','history',!active()?'disabled':'')}</div>${note('This is local filesystem trash, separate from the controlled-document recycle bin. There is no permanent-delete action in this interface.')}
      <div class="table-wrap mt16"><table><thead><tr><th>Original path</th><th>Reason</th><th>Saved</th><th>Size</th><th></th></tr></thead><tbody>${trash.map(r=>`<tr><td class="mono">${e(r.path)}</td><td>${e(r.reason||'trash')}</td><td>${formatDate(r.at)}</td><td>${formatBytes(r.size)}</td><td>${action('Restore as…','restore-trash','history',`data-id="${e(r.id)}" ${!canWrite()?'disabled':''}`)}</td></tr>`).join('')||'<tr><td colspan="5"><div class="local-empty-inline"><strong>No recovery items</strong><span>Trash is retained inside the connected folder.</span></div></td></tr>'}</tbody></table></div>`;
  }
  function pageHTML() {
    const fs=active(),support=filesystemCapabilities(),modified=rows.filter(r=>r.status==='modified').length,conflicts=rows.filter(r=>['conflict','out of date'].includes(r.status)).length;
    return `${heading('Local system','Your files, your tools, your disk. Connected to controlled project delivery.',action('Import folder','import-picker','upload')+action('Connect folder','pick','folder','','primary'),'ON THIS COMPUTER')}
      <div class="local-hero"><div class="local-hero-icon">${icon('database',30)}</div><div><h2>${fs?e(fs.label):'A workspace that stays with you.'}</h2><p>${fs?`${fs.kind==='browser-folder'?'Explicit browser folder grant':'Authenticated loopback connection'} · ${fs.readOnly?'Read-only access':'Read / write access'} · Original revisions remain controlled`:'Connect a local folder or start the localhost edition. Nothing on your computer is scanned without an explicit connection.'}</p>${fs?.location?`<code class="local-absolute-path">${e(fs.location)}</code>`:''}</div><span class="local-hero-badge">${fs?'<i></i> Connected':'Local-first'}</span></div>
      <div class="local-metrics"><div><span>Connected folders</span><strong>${mounts.size}</strong><small>Scoped filesystem access</small></div><div><span>Working copies</span><strong>${rows.length}</strong><small>Linked to controlled revisions</small></div><div><span>Local modifications</span><strong>${modified}</strong><small>Ready for review and check-in</small></div><div><span>Needs reconciliation</span><strong>${conflicts}</strong><small>No silent overwrites</small></div></div>
      ${!support.directoryPicker&&!capabilities?.enabled?note('Direct folder pickers are unavailable here. Folder import and ZIP downloads still work. For browsers without direct folder access, run <code>npm run local</code> and sign in.'):''}
      ${error?`<div class="note-box local-warning" role="alert">${icon('issue',16)}<span>${e(error)}</span></div>`:''}
      ${task?`<div class="local-task" role="status"><span class="spinner"></span><div><strong>${e(task.label)}</strong><small>${e(task.detail||'Preparing files…')}</small></div><span class="grow"></span>${action('Cancel after current file','cancel','close')}</div>`:''}
      <div class="local-layout">${mountPanel()}<section class="local-main"><div class="local-tabs" role="tablist">${[['files','folder','File explorer'],['working','edit','Working copies'],['workspace','database','Workspace on disk'],['transfer','send','Transfers'],['trash','history','Recovery']].map(([key,glyph,title])=>`<button role="tab" aria-selected="${tab===key}" data-action="local-tab" data-tab="${key}" class="${tab===key?'active':''}">${icon(glyph,15)}${title}</button>`).join('')}</div><div class="local-tab-content">${tab==='working'?workingPanel():tab==='workspace'?workspacePanel():tab==='transfer'?transferPanel():tab==='trash'?trashPanel():filesPanel()}</div></section></div>
      <div class="local-bottom"><span>${icon('shield',13)}${team()?'Signed in · local roots have separate explicit access grants':'Local profiles do not authenticate OS users'}</span><span>${fs?action('Disconnect this folder','disconnect','close',E().repository.fs===fs?'disabled title="Switch storage before disconnecting the active workspace folder"':'','text'):''}</span></div>`;
  }
  function userPath(value) { relativePath(value); if(value.split('/').some(s=>s.toLowerCase().startsWith('.civora')))throw new Error('Application metadata folders are reserved. Choose a normal file path.');return value; }
  function requireFS(write=false) { const fs=active();if(!fs)throw new Error('Connect a local folder first.');if(write&&fs.readOnly)throw new Error('This folder is read-only.');return fs; }
  async function workManager() { const fs=requireFS(); if(!manager)manager=await new WorkingCopyManager(E(),fs).open();return manager; }
  async function runTask(label,operation) {
    if(task)throw new Error('A file transfer is already running.');const controller=new AbortController(),token=contextToken();task={label,controller,detail:''};render();
    try{return await operation(controller.signal,progress=>{if(!current(token))controller.abort();if(task){task.detail=typeof progress==='string'?progress:`${progress.completed??progress.created?.length??0} completed${progress.total?' of '+progress.total:''}${progress.failed?.length?' · '+progress.failed.length+' failed':''}`;if(U().route==='local')render();}});}
    finally{task=null;if(U().route==='local')render();}
  }
  function displayedPath(fs,filePath=''){if(!fs.location)return fs.label+(filePath?'/'+filePath:'');const sep=fs.location.includes('\\')?'\\':'/';return fs.location+(filePath?(fs.location.endsWith(sep)?'':sep)+filePath.split('/').join(sep):'');}
  async function fileDialog(filePath) {
    const fs=requireFS(),file=await fs.read(filePath),hash=await hashBlob(file);let decoded=null;try{decoded=await decodeTextFile(file);}catch{}
    const dialog=openDialog({title:filePath.split('/').at(-1),subtitle:'Local disk file · not a controlled revision until imported or checked in',wide:true,body:`<div class="local-inspector-path">${icon('folder',15)}<code>${e(displayedPath(fs,filePath))}</code></div><dl class="detail-properties"><dt>Size</dt><dd>${formatBytes(file.size)}</dd><dt>SHA-256</dt><dd class="hash">${e(hash)}</dd><dt>Access</dt><dd>${fs.readOnly?'Read-only':'Read / write with conflict checks'}</dd>${decoded?`<dt>Encoding</dt><dd>${e(decoded.encoding.toUpperCase())}${decoded.bom?' + BOM':''} · ${decoded.newline==='\r\n'?'CRLF':decoded.newline==='\r'?'CR':'LF'}${decoded.mixedNewlines?' · mixed line endings will be normalized on edit':''}</dd>`:''}</dl>${decoded?`<pre class="local-text-preview">${e(decoded.text.slice(0,60000))}${decoded.text.length>60000?'\n… preview truncated …':''}</pre>`:`<div class="local-empty-inline">${fileBadge(filePath)}<strong>Original binary content preserved</strong><span>Download, import into a project, or open in an explicitly configured native application.</span></div>`}<div class="form-actions">${action('Copy path','copy-path','copy',`data-path="${e(filePath)}"`)}${action('Download','download','download',`data-path="${e(filePath)}"`)}${decoded?action('Edit text','edit-text','edit',`data-path="${e(filePath)}" ${!canWrite()?'disabled':''}`):''}${action('Rename / move','move','arrow',`data-path="${e(filePath)}" ${!canWrite()?'disabled':''}`)}${action('Move to local trash','trash','trash',`data-path="${e(filePath)}" ${!canWrite()?'disabled':''}`,'danger')}${fs.native?action('Open native application','native-open','external',`data-path="${e(filePath)}"`,'primary'):''}${fs.revealEnabled?action('Reveal on computer','reveal','folder',`data-path="${e(filePath)}"`):''}</div>`});return dialog;
  }
  async function textEditor(filePath) {
    const fs=requireFS(true),file=await fs.read(filePath),hash=await hashBlob(file),decoded=await decodeTextFile(file);
    return formDialog('Edit local text file',`<div class="local-inspector-path"><code>${e(filePath)}</code><span>${e(decoded.encoding)}${decoded.bom?' · BOM':''}</span></div>${decoded.mixedNewlines?note('Mixed line endings will be normalized to the detected predominant convention on save.',true):''}<textarea name="text" class="local-editor" spellcheck="false" aria-label="Local file contents">${e(decoded.text)}</textarea>${note('Save changes this disk file only. For a managed working copy, use Check in separately to create a controlled revision.')}`,async data=>{
      if(data.get('text')===decoded.text.replace(/\r\n|\r/g,'\n'))return;
      if(fs.kind==='browser-folder') { const now=await hashBlob(await fs.read(filePath));if(now!==hash)throw new Error('The local file changed. Close and reopen the editor before saving.');await fs.archive(filePath,file,'replace'); }
      await fs.write(filePath,encodeTextFile(decoded,data.get('text')),{expectedHash:hash});toast('Saved on disk. Controlled revisions were not changed.');await refresh();
    },{label:'Save to disk',wide:true});
  }
  function newFile() {
    const fs=requireFS(true);return formDialog('New local text file',`${field('Relative filename','name','Notes.txt',{required:true,full:true})}${field('Contents','contents','',{type:'textarea',full:true})}`,async data=>{const target=userPath(joinPath(path,data.get('name')));await fs.write(target,new Blob([data.get('contents')],{type:'text/plain'}),{createOnly:true});await refresh();toast('Local file created.');},{label:'Create file'});
  }
  async function checkOutDialog(documentId='') {
    const fs=requireFS(true),available=S().documents.filter(d=>!d.deletedAt&&documentPermission(E(),'download',d)&&(!U().projectId||d.projectId===U().projectId));if(!available.length)throw new Error('Upload a document to this project first.');
    const doc=available.find(d=>d.id===documentId)||available[0];
    return formDialog('Create a managed working copy',`<div class="form-grid">${field('Controlled document','documentId',doc.id,{options:available.map(d=>({value:d.id,label:d.number+' · '+d.name})),full:true})}${field('Local relative path','path',workingPath(S(),doc),{required:true,full:true})}${field('Access mode','mode',doc.state==='Work in progress'?'checkout':'copy',{options:[{value:'checkout',label:'Check out for editing (exclusive lock)'},{value:'copy',label:'Copy exact revision without checkout'}],full:true})}</div>${note('Existing files are never overwritten. Browser mode cannot launch desktop applications; open the displayed file yourself or configure the localhost native-app allowlist.')}`,async data=>{const m=await workManager();await m.materialize(data.get('documentId'),{path:userPath(data.get('path')),checkout:data.get('mode')==='checkout'});tab='working';await refresh();navigate('local');toast('Verified original written to the working folder.');},{label:'Create working copy',onMount(form){form.querySelector('[name=documentId]').onchange=event=>{const d=available.find(d=>d.id===event.target.value);form.querySelector('[name=path]').value=workingPath(S(),d);form.querySelector('[name=mode]').value=d.state==='Work in progress'?'checkout':'copy';};}});
  }
  async function checkInDialog(id) {
    const m=await workManager();await E().refresh();const link=m.links.find(r=>r.id===id);if(!link)throw new Error('Working copy not found.');const row=await m.status(link);if(!row.canCheckin)throw new Error('Check out a modified, current working copy before checking it in.');
    const old=row.revision,match=old.match(/^(.*?)(\d+)$/),next=match?match[1]+String(Number(match[2])+1).padStart(match[2].length,'0'):old+'-next';
    return formDialog('Check in local changes',`<div class="local-inspector-path"><code>${e(row.path)}</code></div><div class="form-grid">${field('New revision label','revision',next,{required:true})}${field('Revision note','comment','Edited in local working copy',{required:true,type:'textarea',full:true})}</div><div class="hash">SHA-256: ${e(row.localHash)}</div>${note('This creates an immutable revision and releases your checkout. A different local hash or source revision cancels the check-in.')}`,async data=>{await m.checkin(id,{revision:data.get('revision'),comment:data.get('comment'),expectedLocalHash:row.localHash});await refresh();toast('New revision committed. Checkout released.');},{label:'Check in revision'});
  }
  function importPicker() {
    const input=document.createElement('input');input.type='file';input.multiple=true;input.setAttribute('webkitdirectory','');input.setAttribute('directory','');input.style.display='none';document.body.append(input);
    input.onchange=()=>{const picked=[...input.files].map(f=>({path:f.webkitRelativePath||f.name,file:f}));input.remove();if(picked.length)importDialog(picked);};input.oncancel=()=>input.remove();input.click();
  }
  function importDialog(picked) {
    const project=S().projects.find(p=>p.id===U().projectId)||S().projects[0];if(!project)throw new Error('Create a project before importing files.');
    const metadata=(project.fields||[]).map(f=>field(f.label,'meta_'+f.key,'',{required:f.required,type:f.type==='number'?'number':f.type==='date'?'date':'text'})).join('');
    return formDialog('Import local folder tree',`<p class="subtitle">${picked.length} files into <strong>${e(project.name)}</strong>. Directory names are preserved.</p><div class="local-import-list">${picked.slice(0,8).map(f=>`<div>${icon('file',13)}<span>${e(f.path)}</span></div>`).join('')}${picked.length>8?`<small>and ${picked.length-8} more files</small>`:''}</div><div class="form-grid">${field('Parent project folder','folderId',U().folderId||'',{options:[{value:'',label:'Project root'},...S().folders.filter(f=>f.projectId===project.id).map(f=>({value:f.id,label:f.name}))],full:true})}${field('Initial revision','revision','P01',{required:true})}${field('Discipline','discipline','General',{options:['General','Architecture','Structures','Civil','MEP','Landscape']})}${metadata}</div>${note('Existing filenames cause a reported error, not an automatic replacement. Each successful import is committed independently.')}`,async data=>{
      const engine=E();tab='transfer';navigate('local');const meta=Object.fromEntries((project.fields||[]).map(f=>[f.key,data.get('meta_'+f.key)]));
      lastReport=await runTask('Importing folder tree',(signal,onProgress)=>importTree(engine,picked,{projectId:project.id,folderId:data.get('folderId')||null,revision:data.get('revision'),discipline:data.get('discipline'),metadata:meta,signal,onProgress}));render();toast(`${lastReport.created.length} files imported; ${lastReport.failed.length} failed.`,lastReport.failed.length?'error':'success');
    },{label:'Import documents',wide:true});
  }
  async function importDirectory(selectedPath='') {
    const fs=requireFS();const scanned=await fs.list(selectedPath,{recursive:true});const files=scanned.filter(f=>f.kind==='file').map(f=>({path:f.path,read:()=>fs.read(f.path)}));if(!files.length)throw new Error('There are no importable files in this folder.');return importDialog(files);
  }
  function projectDocs() { return S().documents.filter(d=>!d.deletedAt&&d.projectId===U().projectId&&documentPermission(E(),'download',d)); }
  async function exportProject(zip=false) {
    const engine=E(),ids=projectDocs().map(d=>d.id),project=S().projects.find(p=>p.id===U().projectId);if(!ids.length)throw new Error('This project has no downloadable documents.');
    if(zip){return runTask('Building pinned project ZIP',async(signal,onProgress)=>{const items=[],manifest=[],state=copy(engine.state);let bytes=0;for(const id of ids){signal.throwIfAborted();const doc=state.documents.find(d=>d.id===id),v=currentVersion(doc),file=await engine.repository.blob(v.blobId);bytes+=file.size;if(bytes>180*1024*1024)throw new Error('ZIP export is limited to 180 MiB. Use folder export for a larger project.');if(await hashBlob(file)!==v.hash)throw new Error('Source checksum failed.');const name=workingPath(state,doc);items.push({name,data:file});manifest.push({documentId:id,versionId:v.id,hash:v.hash,revision:v.label,path:name});onProgress(`${manifest.length} of ${ids.length} originals verified`);}items.push({name:'manifest.json',data:JSON.stringify({format:'civora-project-export',version:1,project:project?.code,files:manifest},null,2)});downloadBlob(await createZip(items),`${portableName(project?.code||'Project')}-local-export.zip`);toast('Project ZIP exported.');});}
    const fs=requireFS(true),base=`Exports/${portableName(project?.code||'Project')}-${new Date().toISOString().replace(/[:.]/g,'-')}`;tab='transfer';navigate('local');
    lastReport=await runTask('Exporting pinned project documents',(signal,onProgress)=>exportTree(engine,fs,ids,{basePath:base,signal,onProgress}));
    await fs.write(joinPath(base,'manifest.json'),new Blob([JSON.stringify({format:'civora-project-export',version:1,...lastReport},null,2)]),{createOnly:true});await refresh();toast(`${lastReport.created.length} files exported; ${lastReport.failed.length} skipped.`);
  }
  async function folderWorkspace(mode) {
    const fs=requireFS(mode!=='open');if(fs.kind!=='browser-folder')throw new Error('Use the localhost SQLite workspace for the companion; direct folder workspaces use a browser directory grant.');
    if(mode==='copy'&&team())throw new Error('Team data is not silently copied into a local sandbox. Use an explicit document export.');
    const repository=await new DirectoryRepository(fs,{create:mode!=='open'}).open();let state=await repository.read();
    if(mode==='open'){if(!state)throw new Error('This folder has no initialized workspace.');}
    else {
      if(state)throw new Error('A folder workspace already exists here. Open it instead; it was not overwritten.');
      const sourceEngine=E();state=mode==='copy'?copy(sourceEngine.state):createEmptyWorkspace();if(mode==='create')state.name='My local folder workspace';
      await runTask('Writing verified disk workspace',async(signal,onProgress)=>{const files=new Map(),ids=[...new Set(state.documents.flatMap(d=>d.versions.map(v=>v.blobId)))];let n=0;for(const id of ids){signal.throwIfAborted();files.set(id,await sourceEngine.repository.blob(id));onProgress(`${++n} of ${ids.length} originals prepared`);}signal.throwIfAborted();await repository.initialize(state,files);});
    }
    const user=state.users.find(u=>u.id===E().actorId&&u.active)||state.users.find(u=>u.active&&u.role==='admin');
    await activateEngine(repository,user.id,state,new Map());preferences.useServer=false;safeWrite('civora-preferences',preferences);tab='workspace';navigate('local');toast('Folder-backed workspace opened. Local profiles are not authentication.');
  }
  async function checkpointDialog() {
    const fs=requireFS(),repo=E().repository.kind==='directory'&&E().repository.fs===fs?E().repository:await new DirectoryRepository(fs).open();const history=await repo.history();
    const dialog=openDialog({title:'Verified folder checkpoints',subtitle:'Restoration preserves originals and creates a new monotonic workspace revision.',wide:true,body:`${note('A checkpoint can be staged before a crash without becoming current. Choose a checkpoint explicitly; no automatic rollback is performed.',true)}<div class="table-wrap mt16"><table><thead><tr><th>Revision</th><th>Saved</th><th>Documents</th><th>Checksum</th><th></th></tr></thead><tbody>${history.map(h=>`<tr><td class="mono">${h.valid?'r'+h.revision:'—'}${h.current?' · current':''}</td><td>${e(h.at)}</td><td>${h.documents??'—'}</td><td>${h.valid?'Verified':e(h.error)}</td><td><button class="btn small" data-recover-commit="${e(h.id)}" ${!h.valid||fs.readOnly?'disabled':''}>Restore</button></td></tr>`).join('')}</tbody></table></div>`});
    dialog.querySelectorAll('[data-recover-commit]').forEach(button=>{button.onclick=async()=>{try{const head=await optionalRead(fs,'.civora/HEAD.json'),expectedHeadHash=head?await hashBlob(head):null;confirmAction('Restore this disk checkpoint?','This replaces the selected folder workspace metadata. Working files outside .civora are retained. Export a backup of current work first.',async()=>{await repo.recover(button.dataset.recoverCommit,{expectedHeadHash});dialog.close();if(E().repository===repo)await E().refresh();else await folderWorkspace('open');toast('Checkpoint restored after original-file verification.');},{label:'Restore checkpoint',danger:true});}catch(err){toast(err.message,'error');}}});
  }
  function guide() { return openDialog({title:'Local system setup',wide:true,body:`<div class="local-workspace-grid"><article class="local-info-card"><h3>Browser folders</h3><p>Use Connect folder to grant access. The browser may require a renewed grant after restart. Use Import folder and ZIP downloads where directory pickers are unavailable.</p><p>Writable folder workspaces require Web Locks. Do not open the same disk workspace from multiple browser origins or native writers.</p></article><article class="local-info-card"><h3>Authenticated localhost</h3><pre class="code-block">npm run local\n# or choose paths:\nnpm run local -- --data /path/to/data --files /path/to/working</pre><p>Open the printed localhost address, sign in as admin@civora.local using the initial password printed in the terminal, then open Local system. No package installation is required.</p></article></div>${note('The localhost service grants only configured roots and users. Native opening requires an administrator-owned executable allowlist; it is disabled by default. A local OS user who can read the data directory can access its files independently of Civora.',true)}<p class="small muted mt16">See docs/LOCAL-SYSTEM.md for Windows/macOS launchers, mounted drives, read-only roots, stale-lock recovery, backup procedures, limits, and security boundaries.</p>`}); }
  async function handleAction(name,btn) {
    if(!name.startsWith('local-'))return false;const id=btn.dataset.id,p=btn.dataset.path||'',op=name.slice(6),dialog=btn.closest('dialog');
    switch(op){
      case'pick':await pick(false);break;case'pick-readonly':await pick(true);break;
      case'select-root':activeId=id;path='';page=0;manager?.close();manager=null;monitor?.stop();monitor=null;await refresh();break;
      case'reconnect':{const bookmark=recents.find(r=>r.id===id);if(!bookmark)throw new Error('Folder bookmark not found.');const fs=new BrowserDirectoryFS(bookmark.handle,bookmark);if(await fs.permission(true)!=='granted')throw new Error('Folder permission was not granted.');await attach(fs);break;}
      case'forget':await bookmarks.forget(id);recents=await bookmarks.list();render();toast('Saved handle forgotten. Browser site permissions can also be revoked in browser settings.');break;
      case'disconnect':{const fs=requireFS();if(E().repository.fs===fs)throw new Error('Switch workspace storage before disconnecting its folder.');monitor?.stop();manager?.close();manager=null;fs.close();mounts.delete(activeId);activeId=[...mounts.keys()][0]||'';path='';await refresh();break;}
      case'tab':tab=btn.dataset.tab;if(tab==='trash')await refresh();else render();break;
      case'folder':path=p;page=0;fileQuery='';await refresh();break;case'up':path=path.split('/').slice(0,-1).join('/');page=0;fileQuery='';await refresh();break;
      case'refresh':await refresh();break;case'previous':page=Math.max(0,page-1);render();break;case'next':page++;render();break;
      case'mkdir':{const fs=requireFS(true);formDialog('Create local folder',field('Folder name','name','',{required:true}),async data=>{await fs.mkdir(userPath(joinPath(path,data.get('name'))));await refresh();},{label:'Create folder'});break;}
      case'new-file':newFile();break;
      case'upload':{const fs=requireFS(true),base=path,input=document.createElement('input');input.type='file';input.multiple=true;input.onchange=async()=>{try{await runTask('Writing selected local files',async(signal,onProgress)=>{let n=0;for(const f of input.files){signal.throwIfAborted();await fs.write(userPath(joinPath(base,f.name)),f,{createOnly:true});onProgress(`${++n} files written`);}});await refresh();}catch(err){toast(err.message,'error');}};input.click();break;}
      case'copy-path':{const value=displayedPath(requireFS(),p);try{await navigator.clipboard.writeText(value);toast('File path copied.');}catch{openDialog({title:'Local file path',body:field('Select and copy this path','path',value,{full:true})});}break;}
      case'file':await fileDialog(p);break;case'edit-text':await textEditor(p);break;
      case'download':downloadBlob(await requireFS().read(p),p.split('/').at(-1));break;
      case'move':{const fs=requireFS(true),info=await fs.stat(p);formDialog('Rename or move local file',field('New relative path','destination',p,{required:true,full:true})+note('This portable operation copies and verifies bytes before removing the source. The destination must not exist.'),async data=>{await fs.move(p,userPath(data.get('destination')),{expectedHash:info.hash});dialog?.close();await refresh();},{label:'Move file'});break;}
      case'trash':{const fs=requireFS(true),info=await fs.stat(p);confirmAction('Move this disk file to local trash?',`${p}. This does not recycle its controlled document. Existing working-copy links will show a missing file.`,async()=>{await fs.trash(p,{expectedHash:info.hash});dialog?.close();await refresh();},{label:'Move to local trash',danger:true});break;}
      case'restore-trash':{const fs=requireFS(true),record=trash.find(r=>r.id===id);formDialog('Restore local bytes',field('Destination relative path','destination',record?.path||'',{required:true,full:true})+note('A destination that already exists is never replaced.'),async data=>{await fs.restoreTrash(id,userPath(data.get('destination')));await refresh();},{label:'Restore file'});break;}
      case'native-open':{const fs=requireFS(),info=await fs.stat(p);confirmAction('Open this file in a native application?',`The localhost service will launch the administrator-configured application for ${p}. Only open content you trust.`,async()=>{await fs.nativeOpen(p,info.hash);toast('Native application launch requested. Check in changes separately.');},{label:'Open application'});break;}
      case'reveal':await requireFS().reveal(p);break;
      case'checkout':if(U().route!=='local')navigate('local');if(!active()){toast('Connect a folder, then use Check out to disk.');break;}await checkOutDialog(id||'');break;
      case'document':openDocument(id);break;
      case'acquire':await(await workManager()).acquire(id);await refresh();break;
      case'checkin':await checkInDialog(id);break;
      case'work-inspect':{const row=selected(id);if(row)await fileDialog(row.path);break;}
      case'work-refresh':{const m=await workManager(),link=m.links.find(l=>l.id===id),row=await m.status(link);confirmAction('Refresh the working copy from the controlled revision?','Modified local bytes will be copied to a separate .local-timestamp file first. The controlled original remains unchanged.',async()=>{const result=await m.refresh(id,{expectedLocalHash:row.localHash||null,keepModified:true});await refresh();toast(result.preserved?'Local edits preserved at '+result.preserved:'Working copy refreshed.');},{label:'Preserve edits and refresh'});break;}
      case'untrack':confirmAction('Remove this working-copy link?','The disk file is retained. Any document checkout lock remains held until you explicitly release it.',async()=>{await(await workManager()).untrack(id);await refresh();},{label:'Remove link'});break;
      case'watch':{await workManager();if(monitor?.running)monitor.stop();else{monitor=new DirectoryMonitor(async()=>{await E().refresh();const result=await manager.scan();rows=result;lastScan=new Date().toLocaleTimeString();if(U().route==='local')render();return result;});monitor.addEventListener('error',event=>{error=event.detail.message;monitor.stop();if(U().route==='local')render();});monitor.start();}render();break;}
      case'import-picker':importPicker();break;case'import-dir':await importDirectory(p);break;case'import-file':{const fs=requireFS();importDialog([{path:p,read:()=>fs.read(p)}]);break;}
      case'export-project':await exportProject();break;case'export-zip':await exportProject(true);break;
      case'report':downloadBlob(new Blob([JSON.stringify(lastReport,null,2)],{type:'application/json'}),'civora-local-transfer-report.json');break;
      case'cancel':task?.controller.abort();break;
      case'create-workspace':case'copy-workspace':confirmAction(op==='create-workspace'?'Create an empty disk workspace?':'Copy this local workspace to disk?','The existing browser workspace is retained. A selected folder that already contains a workspace will not be overwritten.',()=>folderWorkspace(op==='create-workspace'?'create':'copy'),{label:'Create disk workspace'});break;
      case'open-workspace':await folderWorkspace('open');break;
      case'verify':{const report=await runTask('Verifying every original',(signal,onProgress)=>E().repository.integrity(null,{signal,onProgress}));openDialog({title:'Disk integrity verified',body:`<p>${report.files} original files, ${report.revisions} revisions, ${formatBytes(report.bytes)} verified against SHA-256.</p><p class="small muted">Checked ${e(report.checkedAt)}. This is content-integrity evidence, not an independent security assessment.</p>`});break;}
      case'history':await checkpointDialog();break;case'guide':guide();break;
      default:return false;
    }return true;
  }
  document.addEventListener('input',event=>{if(event.target.id==='local-file-query'){fileQuery=event.target.value;page=0;render();}});
  function beforeRender(){resetContext();}
  function afterRender(){if(U().route==='local'&&!initialLoaded)void load();}
  return { page:pageHTML,handleAction,beforeRender,afterRender,attach,attachHandle:(handle,options={})=>attach(new BrowserDirectoryFS(handle,options),options.remember!==false),refresh,importDialog,get manager(){return manager;},get mounts(){return mounts;},get active(){return active();},get rows(){return rows;},get lastReport(){return lastReport;},close(){monitor?.stop();task?.controller.abort();manager?.close();for(const fs of mounts.values())if(fs!==E().repository.fs)fs.close();mounts.clear();} };
}
