import { escapeHTML as e, icon, openDialog, formField as field, toast } from '../packages/controls/index.js';
/** Browser/touch shell adapter. Does not grant access, cache originals, or queue writes. */
export function createMobileUI(ctx){
 const P=ctx.preferences,U=ctx.getUI,E=ctx.getEngine,S=ctx.getState;
 const media=matchMedia('(max-width: 780px)'),coarse=matchMedia('(pointer: coarse)');let installEvent=null;
 const save=()=>ctx.safeWrite('civora-preferences',P);
 const small=()=>media.matches;
 function environment(){document.documentElement.dataset.inputMode=P.inputMode==='touch'||P.inputMode!=='pointer'&&coarse.matches?'touch':'pointer';document.documentElement.style.setProperty('--visual-height',`${Math.round(globalThis.visualViewport?.height||innerHeight)}px`);}
 function repaint(){environment();if(E()?.state)ctx.render();}
 media.addEventListener('change',repaint);coarse.addEventListener('change',repaint);globalThis.visualViewport?.addEventListener('resize',environment);globalThis.addEventListener('online',repaint);globalThis.addEventListener('offline',repaint);
 globalThis.addEventListener('beforeinstallprompt',ev=>{ev.preventDefault();installEvent=ev;});globalThis.addEventListener('appinstalled',()=>{installEvent=null;});environment();
 function shell(){return `<nav class="mobile-bottom-nav" aria-label="Mobile workspace navigation">${[['documents','folder','Files'],['inbox','review','My work'],['add','plus','Add'],['notifications','bell','Updates'],['more','menu','More']].map(([route,glyph,label])=>`<button data-action="mobile-${route==='add'?'add':route==='more'?'more':'route'}" ${['add','more'].includes(route)?'':`data-route="${route}"`} class="${U().route===route?'active':''} ${route==='add'?'mobile-add-button':''}" ${U().route===route?'aria-current="page"':''}>${icon(glyph,21)}<span>${label}</span>${route==='notifications'&&ctx.unreadCount()?`<i aria-label="${ctx.unreadCount()} unread notifications">${Math.min(99,ctx.unreadCount())}</i>`:''}</button>`).join('')}</nav>${navigator.onLine===false?`<div class="device-offline-banner" role="status">${icon('cloud',15)}${E().repository.kind==='server'?'Device offline · Team changes are not queued':'Device offline · Local workspace only'}</div>`:''}`;}
 function more(){const routes=ctx.routeNames,dialog=openDialog({title:'Workspace',subtitle:E().repository.kind==='server'?'Authenticated team workspace':'Local sandbox · not authentication',body:`<label class="field"><span>Current project</span><select data-mobile-project aria-label="Current project">${S().projects.map(p=>`<option value="${e(p.id)}" ${p.id===U().projectId?'selected':''}>${e(p.code)} · ${e(p.name)}</option>`).join('')}</select></label><label class="field mt16"><span>Find a workspace tool</span><input type="search" data-mobile-tools-search placeholder="Reviews, sets, local files…"></label><div class="mobile-tool-grid">${Object.entries(routes).map(([route,label])=>`<button data-mobile-tool="${e(route)}" class="${U().route===route?'active':''}"><span>${e(label)}</span>${icon('chevron',15)}</button>`).join('')}</div><div class="mobile-menu-footer"><button class="btn" data-mobile-preferences>${icon('settings',18)}Input & layout</button><button class="btn" data-mobile-profile>${icon('users',18)}Account</button>${installEvent?'<button class="btn" data-mobile-install>Install app</button>':''}</div>`});dialog.classList.add('mobile-navigation-dialog');
  dialog.querySelector('[data-mobile-tools-search]').oninput=ev=>{for(const b of dialog.querySelectorAll('[data-mobile-tool]'))b.hidden=!b.textContent.toLowerCase().includes(ev.target.value.toLowerCase());};
  dialog.querySelector('[data-mobile-project]').onchange=ev=>{dialog.close();ctx.navigate('documents',{projectId:ev.target.value});};
  dialog.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.mobileTool){dialog.close();ctx.navigate(b.dataset.mobileTool);}
   else if(b.hasAttribute('data-mobile-preferences')){dialog.close();preferences();}else if(b.hasAttribute('data-mobile-profile')){dialog.close();ctx.dispatch('profile',b);}else if(b.hasAttribute('data-mobile-install')&&installEvent){const prompt=installEvent;installEvent=null;prompt.prompt().catch(error=>toast(error.message,'error'));dialog.close();}
  });return dialog;
 }
 function preferences(){return ctx.formDialog('Input & responsive layout',`<p class="subtitle">Mouse, keyboard, pen and touch remain available together. Touch mode enlarges controls without removing desktop commands.</p><div class="form-grid">${field('Control sizing','inputMode',P.inputMode||'auto',{options:[{value:'auto',label:'Automatic · follow primary pointer'},{value:'touch',label:'Touch · larger controls'},{value:'pointer',label:'Mouse · compact controls'}]})}${field('Phone document list','mobileList',P.mobileList||'cards',{options:[{value:'cards',label:'Touch cards · recommended on phones'},{value:'table',label:'Full register · horizontal scrolling'}]})}</div><p class="small muted mt16">The phone layout keeps Files, My work, Add, Updates and all workspace tools within reach. Full properties, preview, set actions and multi-select do not require hovering or a right click.</p>`,data=>{P.inputMode=data.get('inputMode');P.mobileList=data.get('mobileList');save();repaint();},{label:'Apply layout'});}
 function add(){const dialog=openDialog({title:'Add to this project',subtitle:S().projects.find(p=>p.id===U().projectId)?.name||'Choose a project first',body:`<div class="mobile-create-grid"><button data-mobile-create="upload">${icon('upload',26)}<strong>Upload files</strong><span>Choose documents from your device</span></button><button data-mobile-create="camera">${icon('camera',26)}<strong>Photo / camera</strong><span>Take or choose an image</span></button><button data-mobile-create="new-folder">${icon('folder',26)}<strong>New folder</strong><span>Organize this project</span></button><button data-mobile-create="new-set">${icon('layers',26)}<strong>Document set</strong><span>Collect controlled revisions</span></button></div><p class="small muted mt16">Photos enter the normal upload workflow. Original image metadata is retained; review sensitive location information before uploading. Camera support depends on the device and browser.</p>`});dialog.classList.add('mobile-add-dialog');dialog.addEventListener('click',ev=>{const b=ev.target.closest('[data-mobile-create]');if(b){dialog.close();if(b.dataset.mobileCreate==='camera'){try{camera();}catch(error){toast(error.message,'error');}}else ctx.dispatch(b.dataset.mobileCreate,b).catch(error=>toast(error.message,'error'));}});return dialog;}
 function camera(){if(!U().projectId)throw new Error('Create or select a project first.');const engine=E(),actor=engine.actorId,projectId=U().projectId,input=document.createElement('input');input.type='file';input.accept='image/*';input.setAttribute('capture','environment');input.hidden=true;document.body.append(input);input.addEventListener('cancel',()=>input.remove(),{once:true});input.onchange=()=>{const files=[...input.files];input.remove();if(!files.length)return;if(E()!==engine||E().actorId!==actor||U().projectId!==projectId){toast('Workspace, account or project changed. Choose the image again.','error');return;}ctx.uploadFiles(files);};input.click();}
 async function handleAction(action,button){if(action==='mobile-menu'||action==='mobile-more'){more();return true;}if(action==='mobile-add'){add();return true;}if(action==='mobile-preferences'){preferences();return true;}if(action==='mobile-camera'){camera();return true;}if(action==='mobile-route'){ctx.navigate(button.dataset.route);return true;}return false;}
 return {shell,handleAction,environment,preferences,get small(){return small();},get cards(){return small()&&P.mobileList!=='table';}};
}
