/** Durable single-node operations. Jobs use leases and restart recovery, not in-memory promises. */
import { DatabaseSync } from 'node:sqlite';
import { join } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
const encode=JSON.stringify,decode=JSON.parse,hash=value=>createHash('sha256').update(value).digest('hex');
export class OperationsStore {
  constructor(directory){this.db=new DatabaseSync(join(directory,'operations.sqlite'));this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000;
    CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY,kind TEXT NOT NULL,status TEXT NOT NULL,input TEXT NOT NULL,output TEXT,error TEXT,attempts INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,lease_until INTEGER NOT NULL DEFAULT 0,owner TEXT NOT NULL);
    CREATE INDEX IF NOT EXISTS jobs_queue ON jobs(status,lease_until,created_at);
    CREATE TABLE IF NOT EXISTS recipients(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,password TEXT,active INTEGER NOT NULL DEFAULT 1);
    CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY,transmittal_id TEXT NOT NULL,recipient_id TEXT NOT NULL,invite_hash TEXT UNIQUE,expires_at INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,enrolled_at TEXT,created_at TEXT NOT NULL,created_by TEXT NOT NULL,receipt TEXT);
    CREATE INDEX IF NOT EXISTS deliveries_recipient ON deliveries(recipient_id,expires_at);
    CREATE TABLE IF NOT EXISTS portal_sessions(token_hash TEXT PRIMARY KEY,recipient_id TEXT NOT NULL,expires_at INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS security_events(sequence INTEGER PRIMARY KEY,at TEXT NOT NULL,kind TEXT NOT NULL,actor TEXT NOT NULL,data TEXT NOT NULL,previous_hash TEXT NOT NULL,hash TEXT NOT NULL);
  `);}
  event(kind,actor,data={}){const text=encode(data),at=new Date().toISOString();this.db.exec('BEGIN IMMEDIATE');try{const last=this.db.prepare('SELECT sequence,hash FROM security_events ORDER BY sequence DESC LIMIT 1').get(),sequence=(last?.sequence||0)+1,previous=last?.hash||'0'.repeat(64),digest=hash(encode([sequence,at,kind,actor,text,previous]));this.db.prepare('INSERT INTO security_events VALUES(?,?,?,?,?,?,?)').run(sequence,at,kind,actor,text,previous,digest);this.db.exec('COMMIT');return digest;}catch(e){this.db.exec('ROLLBACK');throw e;}}
  verifyAudit(){let prev='0'.repeat(64),sequence=0;for(const row of this.db.prepare('SELECT * FROM security_events ORDER BY sequence').iterate()){sequence++;if(row.sequence!==sequence||row.previous_hash!==prev||hash(encode([row.sequence,row.at,row.kind,row.actor,row.data,prev]))!==row.hash)return{valid:false,at:sequence};prev=row.hash;}return{valid:true,events:sequence,head:prev};}
  events(after=0,limit=100){return this.db.prepare('SELECT * FROM security_events WHERE sequence>? ORDER BY sequence LIMIT ?').all(after,limit).map(x=>({...x,data:decode(x.data)}));}
  enqueue(kind,input,owner){const key=hash(encode([kind,input]));const existing=this.db.prepare("SELECT * FROM jobs WHERE id=? AND status IN ('queued','running','completed')").get(key);if(existing)return this.job(key);const now=new Date().toISOString();this.db.prepare("INSERT INTO jobs(id,kind,status,input,created_at,updated_at,owner) VALUES(?,?,'queued',?,?,?,?) ON CONFLICT(id) DO UPDATE SET status='queued',error=NULL,output=NULL,attempts=0,lease_until=0,updated_at=excluded.updated_at,owner=excluded.owner").run(key,kind,encode(input),now,now,owner);return this.job(key);}
  job(id){const row=this.db.prepare('SELECT * FROM jobs WHERE id=?').get(id);return row?{...row,input:decode(row.input),output:row.output?decode(row.output):null}:null;}
  jobs(limit=100){return this.db.prepare('SELECT id FROM jobs ORDER BY created_at DESC LIMIT ?').all(limit).map(x=>this.job(x.id));}
  claim(leaseMs=120000){this.db.exec('BEGIN IMMEDIATE');try{this.db.prepare("UPDATE jobs SET status='failed',error='Worker lease expired after the final attempt',lease_until=0,updated_at=? WHERE status='running' AND lease_until<? AND attempts>=3").run(new Date().toISOString(),Date.now());const row=this.db.prepare("SELECT id FROM jobs WHERE (status='queued' OR (status='running' AND lease_until<?)) AND attempts<3 ORDER BY created_at LIMIT 1").get(Date.now());if(!row){this.db.exec('COMMIT');return null;}this.db.prepare("UPDATE jobs SET status='running',attempts=attempts+1,lease_until=?,updated_at=? WHERE id=?").run(Date.now()+leaseMs,new Date().toISOString(),row.id);this.db.exec('COMMIT');return this.job(row.id);}catch(e){this.db.exec('ROLLBACK');throw e;}}
  finish(id,output){this.db.prepare("UPDATE jobs SET status='completed',output=?,lease_until=0,updated_at=? WHERE id=? AND status='running'").run(encode(output),new Date().toISOString(),id);}
  fail(id,error){this.db.prepare("UPDATE jobs SET status=CASE WHEN attempts<3 THEN 'queued' ELSE 'failed' END,error=?,lease_until=0,updated_at=? WHERE id=? AND status='running'").run(String(error).slice(0,1000),new Date().toISOString(),id);}
  cancel(id){return this.db.prepare("UPDATE jobs SET status='cancelled',updated_at=? WHERE id=? AND status IN ('queued','running','failed')").run(new Date().toISOString(),id).changes>0;}
  recipient(email,name=email){const existing=this.db.prepare('SELECT * FROM recipients WHERE email=?').get(email);if(existing)return existing;const id=randomUUID();this.db.prepare('INSERT INTO recipients(id,email,name) VALUES(?,?,?)').run(id,email,String(name).slice(0,200));return this.recipient(email);}
  invite(transmittalId,recipient,inviteHash,expiresAt,creator){const id=randomUUID(),at=new Date().toISOString();this.db.prepare('INSERT INTO deliveries(id,transmittal_id,recipient_id,invite_hash,expires_at,created_at,created_by) VALUES(?,?,?,?,?,?,?)').run(id,transmittalId,recipient.id,inviteHash,expiresAt,at,creator);return this.delivery(id);}
  delivery(id){return this.db.prepare('SELECT d.*,r.email,r.name,r.active FROM deliveries d JOIN recipients r ON r.id=d.recipient_id WHERE d.id=?').get(id);}
  deliveries(recipientId){const rows=recipientId?this.db.prepare('SELECT id FROM deliveries WHERE recipient_id=? ORDER BY created_at DESC').all(recipientId):this.db.prepare('SELECT id FROM deliveries ORDER BY created_at DESC LIMIT 1000').all();return rows.map(x=>this.delivery(x.id));}
  invitation(token){return this.db.prepare('SELECT d.*,r.email,r.name,r.password,r.active FROM deliveries d JOIN recipients r ON r.id=d.recipient_id WHERE d.invite_hash=? AND d.revoked=0 AND d.expires_at>? AND r.active=1').get(hash(token),Date.now());}
  enroll(invite,password){this.db.exec('BEGIN IMMEDIATE');try{const current=this.db.prepare('SELECT password FROM recipients WHERE id=? AND active=1').get(invite.recipient_id);if(!current||current.password!==invite.password)throw new Error('Recipient credentials changed. Open the invitation again and use the current password.');const change=this.db.prepare('UPDATE deliveries SET invite_hash=NULL,enrolled_at=? WHERE id=? AND invite_hash=? AND revoked=0 AND expires_at>?').run(new Date().toISOString(),invite.id,invite.invite_hash,Date.now());if(!change.changes)throw new Error('Invitation has expired or has already been used.');this.db.prepare('UPDATE recipients SET password=COALESCE(password,?) WHERE id=?').run(encode(password),invite.recipient_id);this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}}
  session(token,recipientId){this.db.prepare('DELETE FROM portal_sessions WHERE expires_at<=?').run(Date.now());this.db.prepare('INSERT INTO portal_sessions VALUES(?,?,?)').run(hash(token),recipientId,Date.now()+4*3600000);}
  identity(token){if(typeof token!=='string')return null;return this.db.prepare('SELECT r.id,r.email,r.name FROM portal_sessions s JOIN recipients r ON r.id=s.recipient_id WHERE s.token_hash=? AND s.expires_at>? AND r.active=1').get(hash(token),Date.now());}
  logout(token){if(token)this.db.prepare('DELETE FROM portal_sessions WHERE token_hash=?').run(hash(token));}
  revoke(id){this.db.prepare('UPDATE deliveries SET revoked=1,invite_hash=NULL WHERE id=?').run(id);}
  acknowledge(id,receipt){const existing=this.delivery(id);if(existing?.receipt)return decode(existing.receipt);this.db.prepare('UPDATE deliveries SET receipt=? WHERE id=? AND receipt IS NULL').run(encode(receipt),id);return decode(this.delivery(id).receipt);}
  counts(){return{jobs:this.db.prepare('SELECT status,COUNT(*) AS count FROM jobs GROUP BY status').all(),recipients:this.db.prepare('SELECT COUNT(*) AS count FROM recipients').get().count,deliveries:this.db.prepare('SELECT COUNT(*) AS count FROM deliveries WHERE revoked=0').get().count,audit:this.verifyAudit()};}
  close(){this.db.close();}
}
