import { randomBytes } from 'node:crypto';
import { createAccessContext } from '../packages/access/index.js';
const cookieName='civora_portal';
export function createPortal({ops,store,origin,passwordRecord,verifyPassword,json,readJSON,fault,rate}){
 const cookie=(token,maxAge=14400)=>`${cookieName}=${token}; HttpOnly; SameSite=Strict; Path=/api/portal; Max-Age=${maxAge}${origin.startsWith('https:')?'; Secure':''}`;
 const token=req=>(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(cookieName+'='))?.slice(cookieName.length+1);
 const issue=recipientId=>{const value=randomBytes(32).toString('base64url');ops.session(value,recipientId);return cookie(value);};
 function permitted(delivery,who){return delivery&&delivery.recipient_id===who.id&&!delivery.revoked&&delivery.active&&delivery.expires_at>Date.now()&&!!delivery.enrolled_at;}
 async function member(req,res,url,who){
   const access=createAccessContext(who.state,who.user.id);
   function check(transmittal){if(!transmittal||!access.can('share','project',transmittal.projectId)||!transmittal.documents.every(d=>access.can('share','document',d.documentId)&&access.can('download','document',d.documentId)))fault('Delivery not available.',404);}
   if(url.pathname==='/api/deliveries'&&req.method==='GET'){const rows=ops.deliveries().filter(d=>{const t=who.state.transmittals.find(t=>t.id===d.transmittal_id);try{check(t);return true;}catch{return false;}}).map(({invite_hash,...d})=>d);json(res,200,{deliveries:rows});return true;}
   if(url.pathname==='/api/deliveries'&&req.method==='POST'){const p=await readJSON(req,8192),t=who.state.transmittals.find(x=>x.id===p.transmittalId);check(t);if(!['Issued','Acknowledged'].includes(t.status))fault('Issue the pinned transmittal before creating recipient access.',400);const email=String(p.email||'').trim().toLowerCase();if(!t.recipients.some(r=>r.toLowerCase()===email))fault('Recipient must match the issued transmittal.',400);const days=Number(p.days||7);if(!Number.isInteger(days)||days<1||days>90)fault('Expiration must be 1 to 90 days.',400);const recipient=ops.recipient(email,p.name||email),secret=randomBytes(32).toString('base64url');const {createHash}=await import('node:crypto');const delivery=ops.invite(t.id,recipient,createHash('sha256').update(secret).digest('hex'),Date.now()+days*86400000,who.user.id);ops.event('portal.invited',who.user.id,{deliveryId:delivery.id,transmittalId:t.id,recipientId:recipient.id});const {invite_hash,...safe}=delivery;json(res,201,{delivery:safe,invitationUrl:`${origin}/portal.html#invite=${secret}`,notice:'Send this one-time invitation privately. No email has been dispatched.'});return true;}
   const match=url.pathname.match(/^\/api\/deliveries\/([a-f0-9-]+)\/revoke$/);if(match&&req.method==='POST'){const d=ops.delivery(match[1]),t=who.state.transmittals.find(t=>t.id===d?.transmittal_id);check(t);ops.revoke(d.id);ops.event('portal.revoked',who.user.id,{deliveryId:d.id});json(res,200,{ok:true});return true;}return false;
 }
 async function handle(req,res,url){
   const path=url.pathname;if(!path.startsWith('/api/portal/'))return false;
   if(path==='/api/portal/session'&&req.method==='GET'){json(res,200,{recipient:ops.identity(token(req))});return true;}
   if(path==='/api/portal/enroll'&&req.method==='POST'){rate(req);const p=await readJSON(req,8192);if(typeof p.token!=='string'||p.token.length>100)fault('Invalid or expired invitation.',401);const invite=ops.invitation(p.token);if(!invite)fault('Invalid or expired invitation.',401);let password;if(invite.password){password=JSON.parse(invite.password);if(!await verifyPassword(p.password,password))fault('Use the existing recipient password.',401);}else password=await passwordRecord(p.password);ops.enroll(invite,password);ops.event('portal.enrolled',invite.recipient_id,{deliveryId:invite.id});json(res,200,{ok:true},{'Set-Cookie':issue(invite.recipient_id)});return true;}
   if(path==='/api/portal/login'&&req.method==='POST'){rate(req);const p=await readJSON(req,8192),email=String(p.email||'').trim().toLowerCase(),r=ops.db.prepare('SELECT * FROM recipients WHERE email=?').get(email),valid=await verifyPassword(p.password,r?.password?JSON.parse(r.password):null);if(!r?.active||!r.password||!valid)fault('Invalid email or password.',401);json(res,200,{ok:true},{'Set-Cookie':issue(r.id)});return true;}
   if(path==='/api/portal/logout'&&req.method==='POST'){ops.logout(token(req));json(res,200,{ok:true},{'Set-Cookie':cookie('',0)});return true;}
   const who=ops.identity(token(req));if(!who)fault('Recipient sign-in is required.',401);
   const state=await store.read();
   if(path==='/api/portal/deliveries'&&req.method==='GET'){json(res,200,{recipient:who,deliveries:ops.deliveries(who.id).filter(d=>permitted(d,who)).map(d=>{const t=state.transmittals.find(t=>t.id===d.transmittal_id);return t?{id:d.id,expiresAt:d.expires_at,receipt:d.receipt?JSON.parse(d.receipt):null,number:t.number,title:t.title,message:t.message,purpose:t.purpose,documents:t.documents.map(v=>({documentId:v.documentId,name:v.name,revision:v.revision,size:v.size,hash:v.hash}))}:null;}).filter(Boolean)});return true;}
   const match=path.match(/^\/api\/portal\/deliveries\/([a-f0-9-]+)\/(files\/([^/]+)|acknowledge)$/);if(!match)fault('Unknown recipient endpoint.',404);const delivery=ops.delivery(match[1]);if(!permitted(delivery,who))fault('Delivery not available.',404);const t=state.transmittals.find(t=>t.id===delivery.transmittal_id);if(!t)fault('Delivery not available.',404);
   if(match[3]&&req.method==='GET'){const doc=t.documents.find(v=>v.documentId===decodeURIComponent(match[3]));if(!doc)fault('File not found in this delivery.',404);const blob=await store.blob(doc.blobId);if(!blob)fault('File content is missing.',404);ops.event('portal.download',who.id,{deliveryId:delivery.id,documentId:doc.documentId,versionId:doc.versionId,hash:doc.hash});res.writeHead(200,{'Content-Type':blob.type||'application/octet-stream','Content-Length':blob.size,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(doc.name).replaceAll("'",'%27')}`,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"});res.end(Buffer.from(await blob.arrayBuffer()));return true;}
   if(match[2]==='acknowledge'&&req.method==='POST'){const p=await readJSON(req,8192),receipt=ops.acknowledge(delivery.id,{at:new Date().toISOString(),recipientId:who.id,email:who.email,note:String(p.note||'Received').slice(0,2000),documents:t.documents.map(v=>({documentId:v.documentId,versionId:v.versionId,hash:v.hash}))});ops.event('portal.acknowledged',who.id,{deliveryId:delivery.id});json(res,200,{receipt});return true;}
   fault('Method is not allowed.',405);
 }
 return{handle,member};
}
