/** Dependency-free PDF/SVG renditions. No original file is overwritten. */
import { readDXF, drawingSVG, parseModel, modelStats, boundsOf } from '../engineering/index.js';
const ascii=s=>String(s).normalize('NFKD').replace(/[^\x20-\x7e\n]/g,'?');
const pdfString=s=>ascii(s).replace(/[\\()]/g,'\\$&');
function pdfDocument(streams,width=842,height=595){const enc=new TextEncoder(),objects=[],add=text=>{objects.push(text);return objects.length;};add('<< /Type /Catalog /Pages 2 0 R >>');add('');const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),pages=[];for(const content of streams){const stream=add(`<< /Length ${enc.encode(content).length} >>\nstream\n${content}\nendstream`);pages.push(add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${width} ${height}] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${stream} 0 R >>`));}objects[1]=`<< /Type /Pages /Count ${pages.length} /Kids [${pages.map(id=>`${id} 0 R`).join(' ')}] >>`;let out='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(enc.encode(out).length);out+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const start=enc.encode(out).length;out+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`;return new Blob([enc.encode(out)],{type:'application/pdf'});}
export function textPDF(text,{title='Civora rendition',revision='',hash=''}={}){if(text.length>1000000)throw new Error('Text rendition limit is 1,000,000 characters.');const lines=[];for(const line of ascii(text).split(/\r?\n/)){if(!line.length)lines.push('');for(let i=0;i<line.length;i+=104)lines.push(line.slice(i,i+104));}const streams=[];for(let start=0;start<Math.max(1,lines.length);start+=48){const page=lines.slice(start,start+48),header=`0.08 0.16 0.22 rg BT /F1 17 Tf 42 800 Td (${pdfString(String(title).slice(0,180))}) Tj ET\n0.4 0.45 0.5 rg BT /F1 9 Tf 42 779 Td (Revision ${pdfString(revision)} - generated derivative, source unchanged) Tj ET\n`,body=`0.1 0.15 0.2 rg BT /F1 9 Tf 13 TL 42 750 Td ${page.map((line,i)=>`${i?'T* ':''}(${pdfString(line)}) Tj`).join('\n')} ET\n`,footer=`0.4 0.45 0.5 rg BT /F1 8 Tf 42 34 Td (Civora | page ${streams.length+1} | SHA-256 ${pdfString(String(hash).slice(0,64))}) Tj ET`;streams.push(header+body+footer);}return pdfDocument(streams,842,842);}
export function drawingPDF(drawing,{title='Drawing',revision='',hash=''}={}){const points=drawing.entities.flatMap(e=>e.points||[e.position]),b=boundsOf(points.map(p=>[...p,0])),scale=Math.min(748/Math.max(b.max[0]-b.min[0],1),445/Math.max(b.max[1]-b.min[1],1)),pt=p=>[47+(p[0]-b.min[0])*scale,75+(p[1]-b.min[1])*scale],number=n=>Number(n.toFixed(4));let stream=`0.12 0.24 0.31 RG 0.65 w\n`;for(const e of drawing.entities){if(e.points?.length){stream+=e.points.map((p,i)=>`${pt(p).map(number).join(' ')} ${i?'l':'m'}`).join('\n')+'\nS\n';}else if(e.position){const[x,y]=pt(e.position),r=-e.rotation*Math.PI/180;stream+=`BT /F1 ${number(Math.max(3,Math.min(50,e.height*scale)))} Tf ${number(Math.cos(r))} ${number(-Math.sin(r))} ${number(Math.sin(r))} ${number(Math.cos(r))} ${number(x)} ${number(y)} Tm (${pdfString(e.text)}) Tj ET\n`;}}
 stream+=`0.1 0.17 0.22 rg BT /F1 16 Tf 42 553 Td (${pdfString(String(title).slice(0,120))}) Tj ET\nBT /F1 8 Tf 42 36 Td (Revision ${pdfString(revision)} | 2D DXF subset | ${drawing.warnings.length} importer notices | ${pdfString(String(hash).slice(0,16))}) Tj ET`;return pdfDocument([stream]);}
export async function renderRendition(blob,name,{format='pdf',revision='',hash=''}={}){const ext=name.split('.').at(-1).toLowerCase(),meta={title:name,revision,hash};if(ext==='dxf'){if(!['svg','pdf'].includes(format))throw new Error('DXF supports PDF or SVG renditions, not mesh output.');const drawing=readDXF(await blob.text());return{blob:format==='svg'?new Blob([drawingSVG(drawing)],{type:'image/svg+xml'}):drawingPDF(drawing,meta),extension:format==='svg'?'svg':'pdf',warnings:drawing.warnings};}
 if(ext==='pdf'&&format==='pdf')return{blob,extension:'pdf',warnings:['The input is already PDF; this is a checksummed pass-through, not a new interpretation.']};
 if(format==='mesh'){const model=await parseModel(blob,name);return{blob:new Blob([JSON.stringify(model)],{type:'application/json'}),extension:'json',warnings:model.warnings||[],stats:modelStats(model)};}
 if(['txt','md','csv','json','xml','log','yaml','yml','html','js','css'].includes(ext)&&format==='pdf')return{blob:textPDF(await blob.text(),meta),extension:'pdf',warnings:['Plain-text PDF. Markup, spreadsheet calculation, typesetting and non-ASCII font fidelity are not provided.']};throw new Error('No built-in renderer for this source/output. Configure a native converter or choose mesh output for supported model formats.');}
